//>>built
define("davinci/review/editor/Context","dojo/_base/declare dojo/_base/connect ../drawing/Surface ../drawing/tools/CreateTool ../drawing/tools/ExchangeTool ../drawing/tools/HighlightTool ../drawing/tools/SelectTool ../../Runtime davinci/XPathUtils davinci/maqetta/AppStates ../../UserActivityMonitor ../Review ../../ve/Context preview/silhouetteiframe".split(" "),function(p,f,q,r,s,t,u,k,n,v,w,m,x,y){var l=v.prototype;return p("davinci.review.editor.Context",[x],{setSource:function(){var a=this.containerNode,
d=this.resourceFile.parent;d.width||(a.style.overflowX="hidden");d.height||(a.style.overflowY="hidden");if(!this.frame){var b=this.baseURL;this.getPreference("zazl")&&(b+="?zazl\x3dtrue");this.frame=dojo.create("iframe",dojo.mixin(this.iframeattrs,{style:{border:"0",width:d.width&&d.height?d.width+"px":"100%",height:d.width&&d.height?d.height+"px":"100%"},src:b,onload:function(c){this._domIsReady=!0;var d=(c=c&&c.target&&c.target.contentDocument)&&c.defaultView&&c.defaultView.window;c=this.frame.contentDocument.body.getAttribute("data-maq-device");
var b=this.frame.contentDocument.body.getAttribute("data-maqetta-device");!c&&b&&(c=b);var a=null;c&&("none"!=c&&"desktop"!=c)&&(a="app/preview/images/"+c+".svg",d.require&&d.require("dojo/ready")(function(){d.require("dojox/mobile/deviceTheme").loadDeviceTheme(y.getMobileTheme(a))}));f.subscribe("/davinci/scene/selectionChanged",this,function(d,b){k.currentEditor&&"davinci.review.CommentReviewEditor"==k.currentEditor.editorID&&this._commentView&&this._commentView.updateStatesScenes()});d.require&&
d.require(["dojo/_base/connect"],function(b){b.subscribe("/maqetta/appstates/state/changed",this,function(b){if(b&&k.currentEditor&&"davinci.review.editor.ReviewEditor"==k.currentEditor.declaredClass){var c=d.davinci;c&&(c.states&&c.states.setState)&&(this._commentView&&this._commentView.updateStatesScenes(),b=dojo.clone(b),b.editorClass="davinci.review.editor.ReviewEditor",f.publish("/maqetta/appstates/state/changed",[b]))}})}.bind(this));this.rootNode=this.rootWidget=this.frame.contentDocument.body;
l.getFocus(this.rootNode)||(c=l.getAllStateContainers(this.rootNode),0<c.length&&(b=l.getInitial(c[0]),l.setState(b,c[0],{focus:!0,updateWhenCurrent:!0})));this._initDrawing();f.publish("/davinci/review/context/loaded",[this,this.fileName]);this._cxtConns=[].concat(this._cxtConns,w.addInActivityMonitor(this.frame.contentDocument));this.containerEditor.silhouetteiframe.setSVGFilename(a);this._statesLoaded=!0;f.publish("/davinci/ui/context/statesLoaded",[this]);this.surface&&this._refreshSurface(this.surface)}.bind(this)}),
a)}},getSelection:function(){return[]},select:function(){},_initDrawing:function(){var a=this.frame.contentDocument;this.surface?a=this.surface:(a=this.surface=new q(a.body,a,this),new r(a,["commentId"]),(new u(a,["commentId"])).activate(),new s(a,["commentId"]),(new t(a)).activate());this._cxtConns=[f.connect(a.highlightTool,"onShapeMouseDown",function(d){f.publish("/davinci/review/drawing/annotationSelected",[d.commentId])}),f.connect(this.getContainerNode(),"click",dojo.hitch(this,function(d){!this.containerEditor.isDirty&&
d.target===this.getContainerNode()&&f.publish("/davinci/review/view/canvasFocused",[this])}))];this._cxtSubs=[f.subscribe(this.fileName+"/davinci/review/drawing/addShape",function(d,b,c){this.surface.exchangeTool.importShapes(d,b,dojo.hitch(m,m.getColor))}.bind(this)),f.subscribe(this.fileName+"/davinci/review/drawing/enableEditing",this,function(d,b,c){var a=c.pageState,g=c.pageStateList,h=c.viewScene;c=c.viewSceneList;var e=this.surface;e.activate();e.cached=e.exchangeTool.exportShapesByAttribute();
e.currentReviewerEmail=d;e.commentId=b;e.filterState=a;e.filterStateList=g;e.filterScene=h;e.filterSceneList=c;e.filterComments=[b];this._refreshSurface(e)}),f.subscribe(this.fileName+"/davinci/review/drawing/getShapesInEditing",this,function(d,b){if(d._currentPage==this.fileName){var c=b.state,a=b.stateList,g=b.scene,h=b.sceneList,e=this.surface;e.selectTool.deselectShape();e.setValueByAttribute("commentId",e.commentId,"state",c);e.setValueByAttribute("commentId",e.commentId,"stateList",a);e.setValueByAttribute("commentId",
e.commentId,"scene",g);e.setValueByAttribute("commentId",e.commentId,"sceneList",h);d.drawingJson=e.exchangeTool.exportShapesByAttribute("commentId",[e.commentId]);e.deactivate();e.commentId=""}}),f.subscribe(this.fileName+"/davinci/review/drawing/cancelEditing",this,function(){var d=this.surface;d.exchangeTool.importShapes(d.cached,!0,dojo.hitch(m,m.getColor));d.deactivate();this._refreshSurface(d);d.commentId=""}),f.subscribe(this.fileName+"/davinci/review/drawing/filter",this,function(d,b){var c=
this.surface,a=l.getFocus(this.rootNode);c.filterState=a?a.state:void 0;c.filterStateList=this.getCurrentStates();c.filterScene=this.getCurrentScene();c.filterSceneList=this.getCurrentScenes();c.filterComments=b;this._refreshSurface(c)}),f.subscribe(this.fileName+"/davinci/review/drawing/setShownColorAliases",this,function(a){var b=this.surface;b.filterColorAliases=a;this._refreshSurface(b)}),f.subscribe("/davinci/review/view/openComment",this,function(){k.currentEditor===this.containerEditor&&(this.containerEditor.isDirty=
!0,this.containerEditor.editorContainer&&this.containerEditor.editorContainer.setDirty(!0))}),f.subscribe("/davinci/review/view/closeComment",this,function(){k.currentEditor===this.containerEditor&&(this.containerEditor.isDirty=!1,this.containerEditor.editorContainer&&this.containerEditor.editorContainer.setDirty(!1))}),f.subscribe("/davinci/ui/editorSelected",this,function(a){if(null!=a.oldEditor&&this===a.oldEditor.getContext&&this===a.oldEditor.getContext())try{this.getDocument()}catch(b){this._destroyDrawing()}})]},
_refreshSurface:function(a){var d=this;this._domIsReady&&dojo.forEach(a.shapes,function(b){var c="hidden";if(k.singleUserMode()||dojo.some(a.filterColorAliases,function(a){if(b.colorAlias==a)return!0;if(davinci&&davinci.review&&dojo.isArray(k.reviewers)){for(var c=k.reviewers,d=!1,e=0;e<c.length;e++)if(a==c[e].email){d=!0;break}return d&&b.colorAlias==c[e].email?!0:!1}}))a.filterComments&&0<a.filterComments.length?(dojo.some(a.filterComments,function(a){return b.commentId==a})?(c="visible",a.highlightTool&&
(a.highlightTool.shape=b)):c="partial",(!b||!a?0:!d.stateSceneCheck(b.stateList,b.sceneList,a.filterStateList,a.filterSceneList))&&(c="hidden")):c=(!b||!a?0:!d.stateSceneCheck(b.stateList,b.sceneList,a.filterStateList,a.filterSceneList))?"hidden":"visible";b.commentId==a.commentId&&(c="visible");b.setVisible(c)})},destroy:function(){this._destroyDrawing()},_destroyDrawing:function(){try{this.surface&&(this.surface.destroy(),delete this.surface)}catch(a){}this._cxtConns.forEach(f.disconnect);this._cxtSubs.forEach(f.unsubscribe)},
getCurrentStates:function(){return l.getAllCurrentStates(this.rootNode).map(function(a){var d=a.stateContainerNode,b=d?d.id:"",d=d?n.getXPath(d):"";return{id:b,xpath:d,state:a.state}})},getCurrentScenes:function(){var a=this.sceneManagers,d={},b;for(b in a){var c=a[b];c.getAllSceneContainers&&c.getCurrentScene&&(d[c.id]=c.getAllSceneContainers().map(function(a){var b=c.getCurrentScene(a),d=b&&b.id?b.id:"",b=b&&b.id?n.getXPath(b):"";return{scId:a.id,scXpath:n.getXPath(a),sceneId:d,sceneXpath:b}}))}return d},
getCurrentScene:function(){var a=this.sceneManagers,d;for(d in a){var b=a[d];if(b.getAllSceneContainers&&b.getCurrentScene)for(var c=b.getAllSceneContainers();0<c.length;)return(a=b.getCurrentScene(c[0]))&&a.id?a.id:""}},stateSceneCheck:function(a,d,b,c){var f,g,h;if(a&&b)for(f=0;f<b.length;f++){h=b[f];var e=!h.state?l.NORMAL:h.state;g=a[f];var k=!g.state?l.NORMAL:g.state;if(g&&h&&(g.id&&g.id===h.id||g.xpath&&g.xpath===h.xpath)&&k!==e)return!1}if(d&&c)for(var m in c)if(a=c[m],b=d[m],a&&b)for(f=0;f<
a.length;f++)if(h=a[f],(g=b[f])&&h&&(g&&g.scId&&h&&g.scId===h.scId||g&&g.scXpath&&h&&g.scXpath===h.scXpath)&&(g&&g.sceneId&&h&&g.sceneId!==h.sceneId||g&&g.sceneXpath&&h&&g.sceneXpath!==h.sceneXpath))return!1;return!0}})});
//# sourceMappingURL=Context.js.map