//>>built
define("davinci/ui/Dialog","dojo/_base/declare dijit/form/Button dijit/Dialog dojo/dom-geometry dojo/dom-style dojo/_base/connect dojo/window dojo/parser dojo/i18n!davinci/ve/nls/common dojox/layout/ResizeHandle".split(" "),function(s,t,x,l,y,f,z,A,v,B){var m=s(x,{contentStyle:null,buildRendering:function(){this.inherited(arguments);dojo.addClass(this.domNode,"resizableDialog");dojo.addClass(this.domNode,"ui-widget-content");this.submitOnEnter&&dojo.addClass(this.domNode,"submitOnEnter")},_setContent:function(a,
b){this.inherited(arguments);var c=dojo.doc.createElement("div");this.containerNode.appendChild(c);new B({targetId:this.id},c);(c=dojo.query(".dijitDialogPaneContentArea",this.containerNode)[0])?dojo.connect(c,"onkeydown",this,"_onKeyDown"):dojo.connect(this.domNode,"onkeydown",this,"_onKeyDown")},resize:function(a){if(a){var b=y.getComputedStyle(this.containerNode),b=l.getPadExtents(this.containerNode,b),c=a.w-b.w,e=a.h-b.h,e=e-l.getMarginBox(this.titleBar).h;a=dojo.query(".dijitDialogPaneContentArea",
this.containerNode)[0];b=dojo.query(".dijitDialogPaneActionBar",this.containerNode)[0];e-=l.getMarginBox(b).h;c&&dojo.style(a,"width",c+"px");e&&dojo.style(a,"height",e+"px");dojo.forEach(this.getChildren(),dojo.hitch(this,function(a){a.resize&&a.resize({w:c,h:e})}))}},show:function(){var a=this.inherited(arguments);if(this.contentStyle){if("object"==typeof this.contentStyle){var b={};this.contentStyle.width&&(b.w=parseInt(this.contentStyle.width));this.contentStyle.height&&(b.h=parseInt(this.contentStyle.height));
var c=z.getBox(this.ownerDocument);c.w*=this.maxRatio;c.h*=this.maxRatio;b.h>c.h&&(l.position(this.containerNode),Math.min(b.w,c.w),Math.min(b.h,c.h),b.h=c.h);this.resize(b)}this._size();this._position();dojo.style(this.containerNode,"width","auto");dojo.style(this.containerNode,"height","auto")}return a},_onKeyDown:function(a){var b=a.ctrlKey&&!dojo.isMac||dojo.isMac&&a.metaKey;if(a.which==dojo.keys.ENTER&&(b||this.submitOnEnter))a=dojo.query("input[type\x3dsubmit]",this.containerNode),0<a.length&&
(a=dijit.getEnclosingWidget(a[0]),b=document.createEvent("MouseEvents"),b.initMouseEvent("click",!0,!0,window,0,0,0,0,0,!1,!1,!1,!1,0,null),a._onClick(b))}});m._timedDestroy=function(a,b){b&&b.forEach(f.disconnect);var c=f.connect(a,"onHide",function(){f.disconnect(c);a.destroyRecursive()});a.hide()};m.showModal=function(a,b,c,e,C,d){var g=[];b={title:b,content:a,contentStyle:c,submitOnEnter:C};d&&(b.onShow=d);var h=new m(b);d=dojo.hitch(this,function(){var a=!1;e&&(a=e());a||this._timedDestroy(h,
g)});g.push(f.connect(h,"onExecute",a,d));a.onExecute&&g.push(f.connect(a,"onExecute",a,d));g.push(f.connect(a,"onClose",dojo.hitch(this,function(){this._timedDestroy(h,g)})));g.push(f.connect(h,"onCancel",dojo.hitch(this,function(){this._timedDestroy(h,g)})));h.show();return h};m.showMessage=function(a,b,c,e,f){return this.showDialog({title:a,content:b,style:c,okCallback:e,okLabel:null,hideCancel:!0})};m.showDialog=function(a){var b=a.title,c=a.content,e=a.style,l=a.okCallback,d=a.okLabel,g=a.hideCancel,
h=a.submitOnEnter,p=a.extendLabels,r=a.extendCallbacks,k,u=[];a=document.createElement("div");var n=document.createElement("div");dojo.addClass(n,"dijitDialogPaneContentArea");a.appendChild(n);var q=document.createElement("div");dojo.addClass(q,"dijitDialogPaneActionBar");d=new t({label:d?d:v.ok,type:"submit","class":"maqPrimaryButton"});q.appendChild(d.domNode);var w=dojo.hitch(this,function(){this._timedDestroy(k,u)});if(p&&r&&0<p.length&&p.length===r.length)for(d=0;d<p.length;d++){var s=function(a){if(r[a])r[a]();
k.onCancel()}.bind(this,d);q.appendChild((new t({label:p[d],onClick:s,"class":"maqSecondaryButton"})).domNode)}g||q.appendChild((new t({label:v.cancel,onClick:function(){k.onCancel()},"class":"maqSecondaryButton"})).domNode);a.appendChild(q);k=new m({title:b,content:a,contentStyle:e,submitOnEnter:h});dojo.isString(c)?(n.innerHTML=c,A.parse(n)):c.domNode?n.appendChild(c.domNode):n.appendChild(c);u.push(f.connect(k,"onExecute",dojo.hitch(this,function(){l&&l();w()})));u.push(f.connect(k,"onCancel",
dojo.hitch(this,function(){w()})));k.show();return k};return m});
//# sourceMappingURL=Dialog.js.map