//>>built
define("davinci/ui/Editor","../commands/CommandStack dojox/timing/doLater dojo/_base/declare ../actions/Action ./TextStyler orion/editor/editor orion/editor/editorFeatures orion/editor/htmlGrammar orion/editor/textMateStyler orion/editor/textView orion/editor/textModel orion/editor/projectionTextModel orion/editor/contentAssist orion/editor/jsContentAssist orion/editor/cssContentAssist ../UserActivityMonitor".split(" "),function(f,g,c,e,p,q,d,r,s,t,k,l,h,u,v,w){c("davinci.ui._EditorCutAction",e,{constructor:function(a){this._editor=
a},run:function(a){this._editor.getTextView()._doCut()},isEnabled:function(a){return!this._editor.getTextView()._getSelection().isEmpty()}});c("davinci.ui._EditorCopyAction",e,{constructor:function(a){this._editor=a},run:function(a){this._editor.getTextView()._doCopy()},isEnabled:function(a){return!this._editor.getTextView()._getSelection().isEmpty()}});c("davinci.ui._EditorPasteAction",e,{constructor:function(a){this._editor=a},run:function(a){this._editor.getTextView()._doPaste()}});var x=function(a){if(this._dontNotifyChange)delete this._dontNotifyChange;
else if(this.lastChangeStamp=Date.now(),this.handleChange&&!("waiter"in this))try{if(this.waiter=!0,!g(1E3<Date.now()-this.lastChangeStamp,this)){delete this.waiter;this.isTyping=!0;var b=this.editor.getTextView(),m=b.getSelection(),d=b.getHorizontalPixel(),c=b.getTopPixel();this.handleChange(this._textModel.getText());delete this.isTyping;b.setSelection(m.start,m.end,!1);b.setHorizontalPixel(d);b.setTopPixel(c)}}catch(e){console.error(e)}},n=function(a){this._progSelect||this.selectionChange({startOffset:a.newValue.start,
endOffset:a.newValue.end})};return c(null,{constructor:function(a,b,d){this.contentDiv=a;this.commandStack=new f;this._existWhenVisible=d;this._isVisible=!d},setContent:function(a,b){!this.editor&&(!this._existWhenVisible||this._isVisible)&&this._createEditor();this._textModel||(this._textModel=this.editor?this.editor.getModel():new l.ProjectionTextModel(new k.TextModel));this.fileName=a;this.setValue(b,!0);this._updateStyler();this._textModel&&(dojo.disconnect(this._textModelConnection),this._textModelConnection=
dojo.connect(this._textModel,"onChanged",this,x))},setVisible:function(a){a!=this._isVisible&&this._existWhenVisible&&(a&&this._existWhenVisible?(this._createEditor(),this._updateStyler()):(this.editor.getTextView().removeEventListener("Selection",dojo.hitch(this,n)),delete this.editor));this._isVisible=a},setValue:function(a,b){this._dontNotifyChange=b;this.editor?this.editor.setText(a):this._textModel.setText(a)},_createEditor:function(){var a,b=new v.CssContentAssistProvider,c=new u.JavaScriptContentAssistProvider,
e=this.contentDiv,f=this._textModel,g={statusReporter:function(a,b){b&&console.error("orion.editor: "+a)},textViewFactory:function(){return new t.TextView({parent:e,model:f||new l.ProjectionTextModel(new k.TextModel),tabSize:4})},undoStackFactory:new d.UndoFactory,annotationFactory:new d.AnnotationFactory,foldingRulerFactory:new d.FoldingRulerFactory,lineNumberRulerFactory:new d.LineNumberRulerFactory,contentAssistFactory:{createContentAssistMode:function(b){a=new h.ContentAssist(b.getTextView());
b=new h.ContentAssistWidget(a,"contentassist");return new h.ContentAssistMode(a,b)}},keyBindingFactory:function(a,b,c,e){var f=new d.TextActions(a,c);b.push(f);a=new d.SourceCodeActions(a,c,e);b.push(a)},domNode:e};this.editor=new q.Editor(g);this.editor.installTextView();/\.css$/.test(this.fileName)?a.setProviders([b]):/\.js$/.test(this.fileName)&&a.setProviders([c]);this._activityConnections=w.addInActivityMonitor(this.contentDiv.ownerDocument);this.editor.getTextView().focus();dojo.style(this.contentDiv,
"overflow","hidden");this.selectionChange&&this.editor.getTextView().addEventListener("Selection",dojo.hitch(this,n));this.cutAction=new davinci.ui._EditorCutAction(this.editor);this.copyAction=new davinci.ui._EditorCopyAction(this.editor);this.pasteAction=new davinci.ui._EditorPasteAction(this.editor)},_updateStyler:function(){if(this.editor){var a=this.fileName.substr(this.fileName.lastIndexOf(".")+1),b=this.editor.getTextView();this._styler&&(this._styler.destroy(),delete this._styler);"json"==
a&&(a="js");switch(a){case "js":case "java":case "css":this._styler=new p.TextStyler(b,a,this.editor.getAnnotationModel());this.editor.setFoldingRulerVisible(!0);break;case "html":this._styler=new s.TextMateStyler(b,new r.HtmlGrammar)}}},selectionChange:function(a){},destroy:function(){dojo.forEach(this._activityConnections,dojo.disconnect)},select:function(a){if(this.editor)try{this._progSelect=!0,this.editor.setSelection(a.endOffset,a.startOffset)}finally{delete this._progSelect}},getText:function(){return this._textModel.getText(0)},
getOnUnloadWarningMessage:function(){return null}})});
//# sourceMappingURL=Editor.js.map