//>>built
require({cache:{"url:davinci/ui/templates/ManageProjectTemplates.html":'\x3cdiv\x3e\n\t\x3cdiv class\x3d"dijitDialogPaneContentArea"\x3e\n\t\t\x3cdiv dojoAttachPoint\x3d"_templateTableDiv" class\x3d"ManageProjectTemplatesOuterDiv"\x3e\n\t\t\t\x3c!--  Filled in dynamically --\x3e\n\t\t\x3c/div\x3e\n\t\t\x3cdiv dojoAttachPoint\x3d"_ManageProjectTemplatesDuplicateNames" class\x3d"ManageProjectTemplatesDuplicateNames"\x3e\n\t\t\t${ManageProjectTemplatesDuplicateNames}\n\t\t\x3c/div\x3e\n\t\x3c/div\x3e\n\t\x3cdiv class\x3d"dijitDialogPaneActionBar"\x3e\n\t\t\x3cbutton dojoType\x3d\'dijit.form.Button\' dojoAttachPoint\x3d"_okButton" dojoAttachEvent\x3d\'onClick:okButton\' label\x3d\'${update}\' class\x3d"maqPrimaryButton" type\x3d"submit" disabled\x3e\x3c/button\x3e\n\t\t\x3cbutton dojoType\x3d\'dijit.form.Button\' dojoAttachPoint\x3d"_cancelButton" dojoAttachEvent\x3d\'onClick:cancelButton\' label\x3d\'${buttonCancel}\' class\x3d"maqSecondaryButton"\x3e\x3c/button\x3e\n\t\x3c/div\x3e\n\t\t\n\x3c/div\x3e\n'}});
define("davinci/ui/ManageProjectTemplates","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-class dojo/dom-construct dojo/on dojo/Deferred dojo/date/locale dijit/registry dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin davinci/library system/resource davinci/ui/ProjectTemplates davinci/workbench/Preferences davinci/Runtime davinci/Workbench dojo/i18n!davinci/ui/nls/ui dojo/i18n!dijit/nls/common dojo/text!./templates/ManageProjectTemplates.html dijit/InlineEditBox dijit/form/TextBox dijit/form/Button dijit/form/ComboBox dijit/form/CheckBox dojo/store/Memory".split(" "),
function(t,E,p,h,e,r,u,v,n,w,x,y,F,G,q,H,z,I,g,A,B,C,D,J,K,L,M){function s(d){var c;try{c=new Date(d)}catch(a){return g.unknown}d=432E5>Date.now()-c?"time":"date";return v.format(c,{selector:d,formatLength:"medium"})}return t("davinci.ui.ManageProjectTemplates",[w,x,y],{templateString:B,_okButton:null,postMixInProperties:function(){dojo.mixin(this,g);dojo.mixin(this,A);this.inherited(arguments)},postCreate:function(){this.inherited(arguments);q.getIncremental(1E3,function(d,c,a){a&&this._updateTable(d,
c);return!1}.bind(this));this._myProjectTemplates=[];this._templateTableDiv.innerHTML=g.ManageProjectTemplatesInitializing;this._showingDeferred=new u},_updateTable:function(d,c){this._showingDeferred.then(function(a){var d=z.getUserEmail(),f=this._templateTableDiv;f.innerHTML="";this._myProjectTemplates=p.filter(a,function(a){return a.authorEmail==d});var b,k,l;if(0<this._myProjectTemplates.length){f=e.create("table",{},f);c.enableProjectSharingAll||h.add(f,"mpt_col_sharing_hide");b=e.create("tr",
{"class":"mpt_row_head"},f);e.create("th",{innerHTML:g.ManageProjectTemplatesHeaderName},b);e.create("th",{innerHTML:g.ManageProjectTemplatesHeaderShared,"class":"mpt_col_sharing"},b);e.create("th",{innerHTML:g.ManageProjectTemplatesHeaderCreatedBy},b);e.create("th",{innerHTML:g.ManageProjectTemplatesHeaderCreatedOn},b);e.create("th",{innerHTML:g.ManageProjectTemplatesHeaderLastModified},b);e.create("th",{innerHTML:"\x26nbsp"},b);for(a=0;a<this._myProjectTemplates.length;a++){var m=this._myProjectTemplates[a];
b=e.create("tr",{id:"mpt_row"+a,"class":"mpt_row "+(0==a%2?"mpt_row_even":"mpt_row_odd")},f);l=m.name;k=e.create("td",{id:"mpt_name_cell"+a,"class":"mpt_name_cell"},b);e.create("div",{id:"mpt_name"+a,"class":"mpt_name",innerHTML:l},k);k=e.create("td",{id:"mpt_sharingSimple_cell"+a,"class":"mpt_sharingSimple_cell mpt_col_sharing"},b);l={type:"checkbox",id:"mpt_sharingSimple"+a,"class":"mpt_sharingSimple"};"all"==m.sharingSimple&&(l.checked="checked");k=e.create("input",l,k);r(k,"change",function(a,
c){var b=document.getElementById("mpt_sharingSimple"+a),d=document.getElementById("mpt_sharingSimple_cell"+a);b&&d&&((b.checked?"all":"none")==this._myProjectTemplates[a].sharingSimple?h.remove(d,"mpt_highlight"):h.add(d,"mpt_highlight"),this.updateUpdateButton())}.bind(this,a));e.create("td",{"class":"mpt_readonly",innerHTML:m.authorEmail},b);e.create("td",{"class":"mpt_readonly",innerHTML:s(m.creationTimestamp)},b);e.create("td",{"class":"mpt_readonly",innerHTML:s(m.lastModifyTimestamp)},b);k=e.create("td",
{id:"mpt_delete_cell"+a,"class":"mpt_delete_cell"},b);l={type:"button",id:"mpt_delete"+a,"class":"mpt_delete"};b=e.create("input",l,k);r(b,"click",function(a,c){this._myProjectTemplates[a].deleted=!this._myProjectTemplates[a].deleted;var b=document.getElementById("mpt_delete"+a),d=document.getElementById("mpt_row"+a);b&&d&&(this._myProjectTemplates[a].deleted?h.add(d,"mpt_delete_row"):h.remove(d,"mpt_delete_row"));this.updateDuplicateNameError();this.updateUpdateButton()}.bind(this,a))}for(a=0;a<
this._myProjectTemplates.length;a++)f="mpt_name"+a,new C({editor:D,autoSave:!0,onChange:function(a){var c="mpt_name_cell"+a,b=n.byId("mpt_name"+a),c=document.getElementById(c);b&&c&&(b.get("value")==this._myProjectTemplates[a].name?h.remove(c,"mpt_highlight"):h.add(c,"mpt_highlight"));this.updateDuplicateNameError();this.updateUpdateButton()}.bind(this,a)},f);setTimeout(function(){this._cancelButton.focus()}.bind(this),1E3)}else f.innerHTML=g.ManageProjectTemplatesNoTemplates}.bind(this,d))},checkForChanges:function(d){for(var c=
!1,a=0;a<this._myProjectTemplates.length;a++){var e=this._myProjectTemplates[a];if(e.deleted&&(c=d(a,"deleted")))break;if(c=n.byId("mpt_name"+a))if(c=c.get("value"),c!=e.name&&(c=d(a,"name",c)))break;if(e=document.getElementById("mpt_sharingSimple"+a))if(c=e.checked?"all":"none",c!=this._myProjectTemplates[a].sharingSimple&&(c=d(a,"sharingSimple",c)))break}},updateUpdateButton:function(){var d=!0;this._anyDuplicateNames||this.checkForChanges(function(c,a,e){d=!1;return!0});this._okButton.set("disabled",
d)},onShow:function(d){this._showingDeferred.resolve()},updateDuplicateNameError:function(){this._anyDuplicateNames=!1;for(var d=0;d<this._myProjectTemplates.length;d++)for(var c=n.byId("mpt_name"+d),c=c?c.get("value"):"",a=d+1;a<this._myProjectTemplates.length;a++){var e=n.byId("mpt_name"+a),e=e?e.get("value"):"";if(c&&c==e){this._anyDuplicateNames=!0;break}}this._anyDuplicateNames?h.add(this._ManageProjectTemplatesDuplicateNames,"ManageProjectTemplatesDuplicateNamesVisible"):h.remove(this._ManageProjectTemplatesDuplicateNames,
"ManageProjectTemplatesDuplicateNamesVisible")},okButton:function(){function d(a){for(var b=0;b<c.length;b++)if(a.name==c[b].name)return!1;return!0}var c=[],a=[],e=[];this.checkForChanges(function(b,d,f){"deleted"==d?c.push({name:this._myProjectTemplates[b].name}):"name"==d&&f?a.push({name:this._myProjectTemplates[b].name,newName:f}):"sharingSimple"==d&&f&&e.push({name:this._myProjectTemplates[b].name,sharingSimple:f})}.bind(this));var a=p.filter(a,d),e=p.filter(e,d),f=e.concat(a),b=!1;if(0<f.length||
0<c.length)b=g.ManageProjectTemplateAboutToOccur+"\n\n",0<c.length&&(b+=c.length+" "+g.ManageProjectTemplateDeletions+"\n"),0<f.length&&(b+=f.length+" "+g.ManageProjectTemplateModifications+"\n"),b+="\n"+g.NoteOperationNotUndoable+"\n",b+="\n"+g.ManageProjectTemplateOKToProceed,b=confirm(b);b&&(0<f.length&&q.modify(f),0<c.length&&q.deleteTemplates(c))},cancelButton:function(){this.cancel=!0;this.onClose()},onClose:function(){}})});
//# sourceMappingURL=ManageProjectTemplates.js.map