//>>built
define("davinci/ui/Resource","dojo/_base/declare system/resource ../model/Path ../Runtime ../Workbench ../workbench/Preferences ../ve/RebuildPage ./Rename ./widgets/NewHTMLFileOptions ./widgets/OpenFile ./widgets/NewFolder ./widgets/NewFile ./widgets/AddFiles ./widgets/AddFilesZip ./NewProject ./Dialog dojo/i18n!./nls/ui davinci/Theme dijit/form/Button dojox/form/uploader/plugins/HTML5".split(" "),function(E,k,r,s,e,t,v,w,F,x,y,z,A,B,C,G,c,D){var q=function(a,d,b,f,c,l,g,p){(g=g||m())?g="Folder"==
g.elementType?g:g.parent:(g=e.getProject(),g=t.getPreferences("davinci.ui.ProjectPrefs",g),null!=g.webContentFolder&&""!=g.webContentFolder?(g=(new r(e.getProject())).append(g.webContentFolder),g=k.findResource(g.toString())):g=k.findResource(e.getProject()));a={newFileName:l||h.getNewFileName("file",g,"."+b),fileFieldLabel:a,folderFieldLabel:"Where:",finishButtonLabel:d,value:g,checkFileName:u,dialogSpecificClass:f,dialogSpecificClassOptions:c,optionalMessage:p};return new z(a)},u=function(a){(a=
k.findResource(a))&&alert("File already exists!");return!a},m=function(){return(h.getSelectedResources()||[])[0]},h={newHTMLDialogSpecificClass:"davinci/ui/widgets/NewHTMLFileOptions",newHTMLMobile:function(){this.newHTML({comptype:"mobile",title:c.createMobileApplication,dialogSpecificClassOptions:{showDevices:!0,showThemeSetsButton:!0}})},newHTMLDesktop:function(){this.newHTML({comptype:"desktop",title:c.createDesktopApplication,dialogSpecificClassOptions:{showDevices:!1,showThemeSetsButton:!0},
device:"desktop"})},newHTMLSketchHiFi:function(){this.newHTML({comptype:"sketchhifi",title:c.createSketchHiFi,dialogSpecificClassOptions:{showDevices:!1,showThemeSetsButton:!0},layout:"absolute",theme:"claro"})},newHTMLSketchLoFi:function(){this.newHTML({comptype:"sketchlofi",title:c.createSketchLoFi,dialogSpecificClassOptions:{showDevices:!1,showThemeSetsButton:!1},layout:"absolute",theme:"Sketch"})},newHTML:function(a){var d=q(c.fileName,c.create,"html",this.newHTMLDialogSpecificClass,a?a.dialogSpecificClassOptions:
null);e.showModal(d,a.title,"",function(){var b,f;d.dialogSpecificWidget&&(b=d.dialogSpecificWidget,f=b.getOptions());b=d.get("value");k.createResource(b,!1,!1,function(b){b.isNew=!0;b.dirtyResource=!0;var c=k.createText("HTML",{resource:b});c&&b.setText(c);c="none";a&&(a.dialogSpecificClassOptions&&a.dialogSpecificClassOptions.showDevices)&&(c=f?f.device:"none");var g=a&&a.layout?a.layout:!0,p=a&&a.theme?a.theme:null,m=null;a&&(a.dialogSpecificClassOptions&&a.dialogSpecificClassOptions.showThemeSetsButton)&&
(p=f?f.theme:null,m=d.dialogSpecificWidget?d.dialogSpecificWidget._selectedThemeSet:null);h.openResource(b,{comptype:a.comptype,device:c,flowlayout:g+"",theme:p,themeSet:m});(b=e.workbenchStateCustomPropGet("nhfo"))||(b={});c=e.getActiveProject();b[c]=f;e.workbenchStateCustomPropSet("nhfo",b)})},!0)},newCSS:function(){var a=q(c.fileName,c.create,"css");e.showModal(a,c.createNewCSSFile,"",function(){var d=a.get("value");k.createResource(d,!1,!1,function(a){a.isNew=!0;var d=k.createText("CSS",{resource:a});
d&&a.setText(d);h.openResource(a)})},!0)},selectResource:function(a){for(var d=dijit.byId("resourceTree"),b=[];a.parent;a=a.parent)b.unshift(a);d.set("path",b)},newFolder:function(a,d){var b=a||m(),f;b?f="Folder"==b.elementType?b:b.parent:(b=e.getProject(),b=t.getPreferences("davinci.ui.ProjectPrefs",b),null!=b.webContentFolder&&""!=b.webContentFolder&&(f=(new r(e.getProject())).append(b.webContentFolder),f=k.findResource(f.toString())),f||(f=k.findResource(e.getProject())));f={newFileName:h.getNewFileName("folder",
f),fileFieldLabel:c.folderName,folderFieldLabel:c.parentFolder,root:f,finishButtonLabel:c.createFolder,checkFileName:u};var n=new y(f),l;e.showModal(n,c.createNewFolder,"",function(){var a=n.get("value");l=k.createResource(a,!0);d&&d(l);null!=l&&h.selectResource(l)},!0)},closeEditor:function(a,d){var b=e.getOpenEditor(a);null!=b&&(d&&b.save(),b.editorContainer.forceClose(b));return null!=b},save:function(){var a=e.getOpenEditor();a&&system.resource.findResourceAsync(a.fileName).then(dojo.hitch(this,
function(d){d.readOnly()?this.saveAs(d.getExtension(),c.savingReadonlyFile):a.save()}))},saveAs:function(a,d){var b=e.getOpenEditor(),f=b.fileName,h=(new r(f)).lastSegment(),l=k.findResource(f),g=q(c.fileName,c.save,a,null,null,h,l,d);e.showModal(g,c.saveFileAs,"",function(){var a=g.get("value");k.findResource(f);var d,c,h;d="davinci.html.CSSEditor"==b.editorID?b.getText():b.model&&b.model.getText?b.model.getText():b.getText();"davinci.ve.HTMLPageEditor"==b.editorID&&(c=D.getThemeSet(b.visualEditor.context),
h=b.visualEditor.context.theme);var l=k.findResource(a);b.editorContainer.forceClose(b);l&&(l.removeWorkingCopy(),l.deleteResource());b.isDirty=!1;var n=k.createResource(a);(new v).rebuildSource(d,n,h,c).then(function(a){n.setContents(a).then(function(){e.openEditor({fileName:n})})})})},newJS:function(){var a=q(c.fileName,c.create,"js");e.showModal(a,c.createNewJSFile,"",function(){var d=a.get("value");k.createResource(d,!1,!1,function(a){a.isNew=!0;var d=k.createText("CSS",{resource:a});d&&a.setText(d);
h.openResource(a)})})},openFile:function(){m()||k.findResource(e.getProject());var a=new x({finishButtonLabel:c.open});e.showModal(a,c.openFile,{width:350,height:250},function(){h.openResource(a.get("value"))},!0)},addFiles:function(){var a=new A({selectedResource:m()});e.showModal(a,c.addFiles,{width:350},null)},addFilesZip:function(){var a=new B({selectedResource:m()});e.showModal(a,c.addFiles,{width:350},null)},getNewFileName:function(a,d,b){var c,e,h=0;b||(b="");do h++,e="folder"===a?"folder"+
h:"file"+h+b,c=d.getPath()+"/"+e,c=k.findResource(c);while(c);return e},canModify:function(a){return!a.readOnly()},newProject:function(){var a=new C({});e.showModal(a,c.newProject,{"min-width":"330px"},null,!0)},renameAction:function(){var a=h.getSelectedResources();if(1==a.length){var d=a[0];d.parent.getChildren(function(a){a=a.map(function(a){return a.name});var f=new w({value:d.name,invalid:a});e.showModal(f,c.renameDialogTitle,"",function(){var a=f.attr("cancel"),b=f.attr("value");if(!a){var c=
h.closeEditor(d,!0);d.rename(b).then(function(){c&&h.openResource(d)})}return!0},!0)},!0)}},getResourceIcon:function(a,d){var b=a.readOnly();if("Folder"==a.elementType)return b?d?"dijitFolderOpened maqettaReadonlyFolderOpened":"dijitFolderClosed maqettaReadonlyFolderClosed":d?"dijitFolderOpened":"dijitFolderClosed";if("File"==a.elementType){var c;fileType=a.getExtension();if(extension=s.getExtension("davinci.fileType",function(a){return a.extension==fileType}))c=extension.iconClass,b&&(c+="ReadOnly");
c||(c="dijitLeaf",b&&(c+=" maqettaReadonlyFile"));return c}return this.prototype.getIconClass(a,d)},getResourceClass:function(a){if(a.readOnly())return"readOnlyResource"},deleteAction:function(){var a=h.getSelectedResources(),d=a.map(function(a){return a.getPath()}).join("\n\t"),d=dojo.string.substitute(c.areYouSureDelete,[d]),d=d+("\n\n"+c.NoteOperationNotUndoable+"\n");confirm(d)&&a.forEach(function(a){h.closeEditor(a);a.deleteResource()})},getSelectedResources:function(){var a=s.getSelection();
if(a[0]&&a[0].resource)return dojo.map(a,function(a){return a.resource})},alphabeticalSortFilter:{filterList:function(a){return a.sort(function(a,b){return a.name>b.name?1:a.name<b.name?-1:0})}},foldersFilter:{filterItem:function(a){if("File"==a.elementType)return!0}},openPath:function(a,c){var b={fileName:a};c&&(b.text=c);e.openEditor(b)},openResource:function(a,c){"File"==a.elementType&&a.getContent().then(function(b){e.openEditor({fileName:a,content:b},c)})}};return dojo.setObject("davinci.ui.Resource",
h)});
//# sourceMappingURL=Resource.js.map