//>>built
require({cache:{"url:davinci/ui/templates/UserLibraries.html":"\x3cdiv class\x3d'userLibDialog'\x3e\n\t\x3cdiv class\x3d\"dijitDialogPaneContentArea\"\x3e\n\t\t\x3cdiv dojoAttachPoint\x3d\"_tableDiv\"\x3e\x3c/div\x3e\n\t\x3c/div\x3e\n\n\t\x3cdiv class\x3d\"dijitDialogPaneActionBar\"\x3e\n\t\t\x3cbutton dojoType\x3d'dijit.form.Button' type\x3d'submit' dojoAttachEvent\x3d'onClick:okButton' label\x3d'${modify}' class\x3d\"maqPrimaryButton\"\x3e\x3c/button\x3e \n\t\t\x3cbutton dojoType\x3d'dijit.form.Button' dojoAttachEvent\x3d'onClick:cancelButton' label\x3d'${buttonCancel}' class\x3d\"maqSecondaryButton\"\x3e\x3c/button\x3e \n\t\x3c/div\x3e \n\x3c/div\x3e"}});
define("davinci/ui/UserLibraries","dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/promise/all ../Workbench dijit/form/Button dijit/form/TextBox dijit/form/RadioButton dijit/MenuItem dijit/Menu ../library dijit/form/ComboBox dojo/i18n!./nls/ui dojo/i18n!dijit/nls/common ../model/Path system/resource ../ve/RebuildPage dojo/text!./templates/UserLibraries.html ../Theme".split(" "),function(k,l,m,n,p,q,w,x,y,z,A,f,B,h,r,s,g,t,u,v){return k([l,m,n],{postMixInProperties:function(){dojo.mixin(this,
r);dojo.mixin(this,h);this.inherited(arguments)},_tableDiv:null,templateString:u,buildRendering:function(){this.inherited(arguments);this._handles=[];this._allLibs=f.getInstalledLibs();this._userLibs=f.getUserLibs(this.getResourceBase());var b=["\x3ctable cellspacing\x3d'0' cellpadding\x3d'0' width\x3d'100%'\x3e","\x3ctr\x3e\x3ctd class\x3d'header'\x3e\x3c/td\x3e\x3ctd class\x3d'header'\x3e{library}\x3c/td\x3e\x3ctd class\x3d'header'\x3e{version}\x3c/td\x3e\x3ctd class\x3d'header'\x3e{workspaceLocation}\x3c/td\x3e\x3c/tr\x3e",
"\x3ctr\x3e\x3c/tr\x3e"];this.libraries={};this._allLibs.forEach(function(a,c){a.initRoot=this._getLibRoot(a.id,a.version);var d=a.id;a.checked=!1;this._getUserLib(a.id,a.version)&&(a.checked=!0);var e=a.checked||a.required?"checked":"";a.required?b.push("\x3ctr style\x3d'display:none'\x3e"):b.push("\x3ctr\x3e");b.push("\x3ctd class\x3d'columna'\x3e\x3cinput type\x3d'checkbox' libItemCheck\x3d'"+c+"'"+e+"\x3e\x3c/input\x3e\x3c/td\x3e");b.push("\x3ctd class\x3d'columnb'\x3e"+d+"\x3c/td\x3e");b.push("\x3ctd class\x3d'columnc'\x3e"+
a.version+"\x3c/td\x3e");a.initRoot?b.push("\x3ctd class\x3d'columnd'\x3e\x3cinput type\x3d'text' value\x3d'"+a.initRoot+"' libItemPath\x3d'"+c+"'\x3e\x3c/input\x3e\x3c/td\x3e"):b.push("\x3ctd class\x3d'columnd'\x3e\x3c/td\x3e");b.push("\x3c/tr\x3e")},this);b.push("\x3c/table\x3e");var e=dojo.replace(b.join(""),h);dojo.place(e,this._tableDiv)},getResourceBase:function(){if(q.singleProjectMode())return g.getRoot().getName()},_destroy:function(){var b=this.domNode;for(dojo.forEach(dojo.query("[widgetId]",
b).map(dijit.byNode),function(b){b.destroy()});b.firstChild;)dojo._destroyElement(b.firstChild);this.topDiv=dojo.doc.createElement("div");this.container.appendChild(this.topDiv);dojo.forEach(this._handles,dojo.disconnect);this._handles=[]},_getLibRoot:function(b,e){var a;this._userLibs.some(function(c){if(c.id==b&&c.version==e)return a=c.root,!0})||this._allLibs.some(function(c){if(c.id==b&&c.version==e)return a=c.root,!0});return a},_getUserLib:function(b,e){return this._userLibs.some(function(a){return a.id==
b&&a.version==e})},_makeChange:function(b){if(b.length){f.modifyLib(b);for(var e=[],a=0;a<b.length;a++){var c=new s(b[a].base);e.some(function(a){return a.equals(c)})||e.push(c)}dojo.subscribe("/davinci/ui/libraryChanged",this,function(){g.findResourceAsync("*.html",!0,this.getResourceBase(),!0).then(function(a){var c=new t,b=[];a.forEach(function(a){v.isThemeHTML(a)||b.push(c.rebuildSource(a.getContentSync(),a).then(function(b){a.setContents(b,!1)}))});p(b).then(function(){this.onClose()})}.bind(this))});
e.forEach(function(a){a=a.toString();g.resourceChanged("reload",a);f.themesChanged(a)});dojo.publish("/davinci/ui/libraryChanged/start")}},_processChanges:function(){function b(a,b){for(var d=0;d<e.length;d++)if(e[d].id==a&&e[d].version==b)return e[d]}var e=[];dojo.query("[libItemCheck]",this.domNode).forEach(function(a){var c=parseInt(dojo.attr(a,"libItemCheck"));a=dojo.attr(a,"checked");c=this._allLibs[c];if(c.checked!=a){var d=b(c.id,c.version);d||(d={id:c.id,version:c.version},e.push(d));d.installed=
a;d.base=this.getResourceBase()}},this);dojo.query("[libItemPath]",this.domNode).forEach(function(a){var c=parseInt(dojo.attr(a,"libItemPath"));a=dojo.attr(a,"value");c=this._allLibs[c];if(c.initRoot!=a){var d=b(c.id,c.version);d||(d={id:c.id,version:c.version},e.push(d));d.path=a;d.oldPath=c.initRoot;d.base=this.getResourceBase()}},this);this._makeChange(e)},okButton:function(){this._processChanges()},cancelButton:function(){this.onClose()},_rewriteDojo:function(){var b=dojo.attr(this.__rewriteDojo,
"checked");dojo.attr(this.__rewriteDojoURL,"disabled",!b)}})});
//# sourceMappingURL=UserLibraries.js.map