//>>built
define("davinci/maqetta/AppStates","dojo/_base/connect dojo/dom-style dojo/dom dojo/_base/html dojo/_base/window dojo/_base/array dojo/parser require dojo/json dojo/_base/lang".split(" "),function(n,t,B,x,y,z,A,p,v,w){t=function(){};t.prototype={NORMAL:"Normal",DELTAS_ATTRIBUTE:"data-maq-deltas",DELTAS_ATTRIBUTE_P6:"dvStates",APPSTATES_ATTRIBUTE:"data-maq-appstates",APPSTATES_ATTRIBUTE_P6:"dvStates",reImportant:/^(.*)(!\ *important)(.*)/,isStateContainer:function(a){return!(!a||!a._maqAppStates)},
getStateContainersForNode:function(a){for(var b=[];a;){a._maqAppStates&&b.splice(0,0,a);if("BODY"==a.tagName)break;a=a.parentNode}return b},getAllStateContainers:function(a){function b(a){a._maqAppStates&&c.push(a);a=d._getChildrenOfNode(a);for(var f=0;f<a.length;f++)b(a[f])}var c=[],d=this;b(a);return c},getStatesArray:function(a,b,c,d){var e=[];if(a)for(a=a.parentNode;a;){if(a._maqAppStates)if(a==d)e.splice(0,0,{node:a,oldState:b,newState:c});else{var f=a._maqAppStates.states?a._maqAppStates.states.current:
void 0;e.splice(0,0,{node:a,oldState:f,newState:f})}if("BODY"==a.tagName)break;a=a.parentNode}return e},findStateContainer:function(a,b){if(a)for(var c=a.parentNode;c;){if(c._maqAppStates&&(!b||b==this.NORMAL||c._maqAppStates.states&&0<=c._maqAppStates.states.indexOf(b)))return c;if("BODY"==c.tagName)break;c=c.parentNode}},getAllStatesForNode:function(a){var b=[this.NORMAL];if(a)for(a=a.parentNode;a;){if(a._maqAppStates&&a._maqAppStates.states)for(var c=a._maqAppStates.states?a._maqAppStates.states:
[],d=0;d<c.length;d++)b.push(c[d]);if("BODY"==a.tagName)break;a=a.parentNode}return b},getStatesListCurrent:function(a){var b=[];if(a)for(a=a.parentNode;a;){a._maqAppStates&&b.splice(0,0,a._maqAppStates.current);if("BODY"==a.tagName)break;a=a.parentNode}return b},getAllCurrentStates:function(a){a=this.getAllStateContainers(a);for(var b=[],c=0;c<a.length;c++){var d=a[c],e=this.getState(d);b.push({stateContainerNode:d,state:e})}return b},getStates:function(a){var b=a&&a._maqAppStates;a=["Normal"];if(b)for(var b=
b.states?b.states:[],c=0;c<b.length;c++){var d=b[c];"Normal"!=d&&a.push(d)}return a},_getSCNodeFromElemOrEvent:function(a,b){var c;b&&b.tagName&&b.nodeName?c=b._maqAppStates?b:this.findStateContainer(b,a):b&&b.target&&b.currentTarget?(c=b.currentTarget,c._maqAppStates||(c=this.findStateContainer(c,a))):c=this.getContainer();return c},_updateSrcState:function(a){},hasState:function(a,b){return!(!a||!a._maqAppStates||!(a._maqAppStates.states&&0<=a._maqAppStates.states.indexOf(b)))},getState:function(a){return a&&
a._maqAppStates&&a._maqAppStates.current},setState:function(a,b,c){var d=c?c.updateWhenCurrent:!1,e=c?c.silent:!1,f=c?c.focus:!1;if((b=this._getSCNodeFromElemOrEvent(a,b))&&b._maqAppStates&&(d||b._maqAppStates.current!=a))d=b._maqAppStates.current,this.isNormalState(a)?(b._maqAppStates.hasOwnProperty("current")&&delete b._maqAppStates.current,a=void 0):b._maqAppStates.current=a,f&&this._setFocus(a,b),c&&c.hasOwnProperty("initial")&&(c.initial?b._maqAppStates.initial=a:b._maqAppStates.initial&&delete b._maqAppStates.initial),
e||n.publish("/maqetta/appstates/state/changed",[{node:b,newState:a,oldState:d,stateContainerNode:b}]),this._updateSrcState(b,!a)},getInitial:function(a){return a&&a._maqAppStates&&a._maqAppStates.initial},getFocus:function(a){if(!a)return null;a=this.getAllStateContainers(a);for(var b=0;b<a.length;b++){var c=a[b]._maqAppStates;if(c&&c.hasOwnProperty("focus"))return{stateContainerNode:a[b],state:c.focus}}return null},_setFocus:function(a,b){if(b&&b._maqAppStates){var c=b.ownerDocument&&b.ownerDocument.body;
if(c){var d=this.getFocus(c);if(!d||!(d.stateContainerNode==b&&d.state==a)){for(var d=this.getAllStateContainers(c),e=0;e<d.length;e++)(c=d[e]._maqAppStates)&&delete c.focus;b._maqAppStates.focus=a}}}},isNormalState:function(a){0==arguments.length&&(a=this.getState());return!a||a==this.NORMAL},_styleArrayMixin:function(a,b){if(b){for(var c=0;c<b.length;c++){var d=b[c],e;for(e in d)for(d=a.length-1;0<=d;d--)a[d].hasOwnProperty(e)&&a.splice(d,1)}for(c=0;c<b.length;c++)a.push(b[c])}},getStyle:function(a,
b,c){for(var d,e=[],f=0;f<b.length;f++)if(d=b[f],d=a&&a._maqDeltas&&a._maqDeltas[d]&&a._maqDeltas[d].style,this._styleArrayMixin(e,d),2<arguments.length&&e)for(d=e.length-1;0<=d;d--){var g=e[d],h;for(h in g)if(h!=c){e.splice(d,1);break}}return e},hasStyle:function(a,b,c){if(a&&c)if(a._maqDeltas&&a._maqDeltas[b]&&a._maqDeltas[b].style){a=a._maqDeltas[b].style;for(b=0;b<a[b];b++)if(a[b].hasProperty(c))return!0}else return!1},setStyle:function(a,b,c,d){if(a&&c){a._maqDeltas=a._maqDeltas||{};a._maqDeltas[b]=
a._maqDeltas[b]||{};a._maqDeltas[b].style=a._maqDeltas[b].style||[];var e=a._maqDeltas[b].style;if(c)for(var f=0;f<c.length;f++){var g=c[f],h;for(h in g)for(g=e.length-1;0<=g;g--){var l=e[g],m;for(m in l)if(h==m){e.splice(g,1);break}}}var k;if(c)for(g=0;g<c.length;g++)for(var u in c[g])f=c[g][u],"undefined"!=typeof f&&null!==f&&("undefined"==typeof k&&(k=[]),h={},h[u]=this._getFormattedValue(u,f),k.push(h));a._maqDeltas[b].style=e&&k?e.concat(k):e?e:k?k:void 0;d||n.publish("/davinci/states/state/style/changed",
[{node:a,state:b,style:c}]);this._updateSrcState(a)}},_convertStyleName:function(a){if(0<=a.indexOf("-")){var b=a.split("-");a=b[0];for(var c=1;c<b.length;c++){var d=b[c];a+=d.charAt(0).toUpperCase()+d.substring(1)}}return a},_DYNAMIC_PROPERTIES:{width:1,height:1,top:1,right:1,bottom:1,left:1},_getFormattedValue:function(a,b){if(a in this._DYNAMIC_PROPERTIES){if("string"!=typeof b)return b+"px";var c=p("dojo/_base/lang").trim(b);/^[-+]?[0-9]*\.?[0-9]+$/.test(c)&&(b=c+"px")}return b},_getStatesListUsingPropName:function(a,
b){var c=[];if(a)for(var d=0;d<a.length;d++)c.push(a[d][b]);return c},_resetAndCacheNormalStyle:function(a,b){if(a&&b)for(var c=0;c<b.length;c++){var d=this._getStatesListUsingPropName(b,"oldState"),e=this.getStyle(a,d),d=this._getStatesListUsingPropName(b),d=this.getStyle(a,d);if(e)for(var f=0;f<e.length;f++){var g=e[f],h;for(h in g)g=this._convertStyleName(h),a.style[g]=""}if(d)for(e=0;e<d.length;e++){var f=d[e],l;for(l in f){var g=this._convertStyleName(l),m=a.style,k=this._getFormattedValue(l,
f[l])+"",u=k?k.match(this.reImportant):null;u?(k=u[1]+u[3],k=w.trim(k),m.setProperty?m.setProperty(l,k,"important"):a.style[g]=k):a.style[g]=k}}}},_update:function(a,b){if(a&&a._maqDeltas){var c=this._getStatesListUsingPropName(b,"newState"),c=this.getStyle(a,c);this._resetAndCacheNormalStyle(a,b);if(c)for(var d=0;d<c.length;d++){var e=c[d],f;for(f in e){var g=this._convertStyleName(f),h=e[f]+"",l=h?h.match(this.reImportant):null;l?(h=l[1]+l[3],h=w.trim(h),e.setProperty?e.setProperty(f,h,"important"):
a.style[g]=h):a.style[g]=h}}var m,k;a.id&&a.ownerDocument&&(f=a.ownerDocument.defaultView.dijit.byId)&&(m=f&&f(a.id));m&&m.getParent&&(k=m.getParent());k&&k.resize?k.resize():m&&m.resize&&m.resize()}},isContainer:function(a){var b=!1;if(a){var c=this.getDocument();if(a===(c&&c.body)||"BODY"==a.tagName)b=!0}return b},getContainer:function(){return document.body},add:function(a,b,c){a&&!this.hasState(a,b)&&(c=c&&c.index,a._maqAppStates=a._maqAppStates||{},a._maqAppStates.states=a._maqAppStates.states||
[],"number"==typeof c&&0<=c?a._maqAppStates.states.splice(c,0,b):a._maqAppStates.states.push(b),n.publish("/davinci/states/state/added",[{node:a,state:b}]),this._updateSrcState(a))},remove:function(a,b){if(a&&a._maqAppStates&&a._maqAppStates.states&&this.hasState(a,b)){var c=a._maqAppStates.states.indexOf(b);if(!(0>c)){var d=this.getState(a),e=this.getFocus(a.ownerDocument.body);a._maqAppStates.states.splice(c,1);c={};e&&(e.stateContainerNode==a&&e.state==b)&&(c.focus=!0,c.updateWhenCurrent=!0);b==
d&&this.setState(void 0,a,c);n.publish("/davinci/states/state/removed",[{node:a,state:b}]);this._updateSrcState(a)}}},rename:function(a,b){if(!b)return!1;var c=b.oldName,d=b.newName;if(!a||!a._maqAppStates||!a._maqAppStates.states||!a._maqAppStates.states.length)return!1;var e=a._maqAppStates.states;if(0>e.indexOf(c)||0<=e.indexOf(d))return!1;e.splice(e.indexOf(c),1,d);a._maqAppStates.focus===c&&(a._maqAppStates.focus=d);a._maqAppStates.current===c&&(a._maqAppStates.current=d);e=[a];this.getState(a);
for(e=e.concat(this._getChildrenOfNode(a));e.length;){var f=e.shift();f._maqDeltas&&f._maqDeltas[c]&&(f._maqDeltas[d]=f._maqDeltas[c],delete f._maqDeltas[c]);var e=e.concat(this._getChildrenOfNode(f)),g=this.getStatesArray(f,null,d,a);this._update(f,g);this._updateSrcState(f)}n.publish("/davinci/states/state/renamed",[{node:f,oldName:c,newName:d,stateContainerNode:f}]);return!0},_isEmpty:function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},stringifyWithQuotes:function(a){str=v.stringify(a);
str=str.replace(/(\\)?'/g,function(a,c){return c?a:"\\'"});return str=str.replace(/"/g,"'")},serialize:function(a){var b=this,c=function(c){var d=null;a[c]&&(c=p("dojo/_base/lang").clone(a[c]),delete c.undefined,b._isEmpty(c)||(d=this.stringifyWithQuotes(c)));return d}.bind(this),d={};if(!a)return d;var e=c("_maqAppStates");"string"==typeof e&&(d.maqAppStates=e);c=c("_maqDeltas");"string"==typeof c&&(d.maqDeltas=c);return d},deserialize:function(a,b){"string"==typeof a&&(a=a.replace(/(\\)?'/g,function(a,
b){return b?"'":'"'}),a=v.parse(a),this._migrate_m4_m5(a),a=this._migrate_m6_m7(a,b&&b.isBody));return a},_migrate_m4_m5:function(a){for(var b in a){var c=a[b];if(c){var d=c.style;if(d&&!d.length){var e=[],f;for(f in d){var g={};g[f]=d[f];e.push(g)}c.style=e}}}},_migrate_m6_m7:function(a,b){if(!a||a.states)return a;if(b){var c=[],d;for(d in a)"current"!=d&&c.push(d);if(0<c.length)return{states:c}}else return delete a.current,a},store:function(a,b,c){if(a){this.clear(a);var d="BODY"==a.tagName;b&&
(a._maqAppStates=this.deserialize(b,{isBody:d}));c&&(a._maqDeltas=this.deserialize(c,{isBody:d}));n.publish("/davinci/states/stored",[])}},retrieve:function(a){if(a){var b=a.getAttribute(this.APPSTATES_ATTRIBUTE);!b&&"BODY"===a.tagName&&(b=a.getAttribute(this.APPSTATES_ATTRIBUTE_P6));var c=a.getAttribute(this.DELTAS_ATTRIBUTE);!c&&"BODY"!==a.tagName&&(c=a.getAttribute(this.DELTAS_ATTRIBUTE_P6));return{maqAppStates:b,maqDeltas:c}}},clear:function(a){a&&(a._maqAppStates&&delete a._maqAppStates,a._maqDeltas&&
delete a._maqDeltas)},_parseStyleValues:function(a){var b=[];a&&z.forEach(a.split(";"),function(a){var d=a.indexOf(":");if(0<d){var e=a.substring(0,d).trim();a=a.substring(d+1).trim();d={};d[e]=a;b.push(d)}});return b},transferElementStyle:function(a,b){if(a){var c=a._maqDeltas,d=this._parseStyleValues(b);c.undefined||(c.undefined={});c.undefined.style=d}},getDocument:function(){return document},shouldInitialize:function(){return!davinci.AppStatesDontInitialize},_getChildrenOfNode:function(a){for(var b=
[],c=0;c<a.childNodes.length;c++){var d=a.childNodes[c];1===d.nodeType&&b.push(d)}return b},initialize:function(){this.subscribed||(n.subscribe("/maqetta/appstates/state/changed",this,function(a){if(!a.editorClass)for(var b=davinci.states._getChildrenOfNode(a.node);b.length;){var c=b.shift();davinci.states.isContainer(c)||(b=b.concat(davinci.states._getChildrenOfNode(c)));var d=this.getStatesArray(c,a.oldState,a.newState,a.stateContainerNode);davinci.states._update(c,d)}}),this.subscribed=!0)}};"undefined"===
typeof davinci&&(davinci={});var q=davinci.states=new t;(function(){q.initialize();q.shouldInitialize()&&"undefined"!=typeof p&&p(["dojo/_base/lang","dojo/query","dojo/aspect"],function(a,b,c){var d=0,e=!1;a=function(a){e||(c.around(a,"parse",function(a){var b={};return function(c,d){var e;(e=!d&&c&&c.rootNode?c.rootNode:c)?x.byId(e):y.body();h(b);e=a.apply(this,arguments);var f=q.getDocument(),g,l,r,n,s;for(s in b){var p;if(p="body"==s?f.body:f.querySelectorAll("."+s)[0]){var t="BODY"==p.tagName;
l=r=n=null;t?g=b[s]:(g=b[s].maqAppStates,l=b[s].maqDeltas);g&&(r=q.deserialize(g,{isBody:t}));l&&(n=q.deserialize(l,{isBody:t}));r&&(r.initial?r.current=r.initial:(r.focus&&delete r.focus,delete r.current));q.store(p,r,n);l&&davinci.states.transferElementStyle(p,b[s].style)}}s=q.getAllStateContainers(f.body);for(f=0;f<s.length;f++)g=s[f],g._maqAppStates&&"string"==typeof g._maqAppStates.current&&q.setState(g._maqAppStates.current,g,{updateWhenCurrent:!0,focus:g._maqAppStates.focus});return e}}),dojo.parser.parse=
a.parse,e=!0)};try{var f=p("dojox/mobile/parser");a.apply(f)}catch(g){}f||a.call(null,A);var h=function(a){var c=q.getDocument();if(!c.body._maqAlreadyPreserved){var e=davinci.states.retrieve(c.body);e&&e.maqAppStates&&(a.body=e.maqAppStates);c.body._maqAlreadyPreserved=!0}b("*",c).forEach(function(b){var c=b.getAttribute("class");c||(c="");if(!b._maqAlreadyPreserved&&0>c.indexOf("maqTempClass")){b._maqAlreadyPreserved=!0;var e=q.retrieve(b);if("BODY"!=b.tagName&&e&&(e.maqAppStates||e.maqDeltas)){var f=
"maqTempClass"+d;b.setAttribute("class",c+" "+f);d++;a[f]={};e.maqAppStates&&(a[f].maqAppStates=e.maqAppStates);e.maqDeltas&&(a[f].maqDeltas=e.maqDeltas);b.style?a[f].style=b.style.cssText:console.error("States.js _preserveStates. No value for node.style.")}}})}})})();!davinci.Workbench&&"undefined"!=typeof dijit&&n.subscribe("/maqetta/appstates/state/changed",function(a){var b=a&&a.node&&a.node.ownerDocument&&a.node.ownerDocument.defaultView&&a.node.ownerDocument.defaultView.dijit.byId;b&&(a.newState&&
!a.newState.indexOf("_show:")?(a=b(a.newState.substring(6)))&&a.show&&a.show():a.oldState&&!a.oldState.indexOf("_show:")&&(a=b(a.oldState.substring(6)))&&a.hide&&a.hide())});return t});
//# sourceMappingURL=AppStates.js.map