//>>built
define("davinci/ve/widgets/Background","dojo/_base/declare dojo/Deferred davinci/workbench/WidgetLite davinci/ve/widgets/ColorPickerFlat davinci/ve/widgets/ColorStore davinci/ve/widgets/MutableStore dijit/form/ComboBox davinci/ve/widgets/BackgroundDialog davinci/Workbench davinci/ve/utils/URLRewrite davinci/model/Path dojo/i18n!davinci/ve/nls/ve dojo/i18n!dijit/nls/common davinci/ve/utils/CssUtils davinci/ve/widgets/ColorPicker".split(" "),function(q,n,r,s,t,u,v,w,x,m,y,z,B,A,C){var p=0;return q("davinci.ve.widgets.Background",
[r],{__id:0,data:null,buildRendering:function(){this.domNode=dojo.doc.createElement("div",{style:"width:100%"});this._textFieldId="davinci_ve_widgets_properties_border_generated"+p++;this._buttonId="davinci_ve_widgets_properties_border_generated"+p++;var a=dojo.create("div",{className:"bgPropButtonDiv",style:"float:right; width:28px;"});dojo.create("button",{innerHTML:"...",id:this._buttonId,className:"bgPropButton",style:"font-size:1em;"},a);var b=38,f=this._colorswatch="true"==this.colorswatch;
if(f){var b=56,h=dojo.doc.createElement("div");dojo.addClass(h,"colorPicker");this._selectedColor=dojo.doc.createElement("div");this._selectedColor.innerHTML="\x26nbsp;";dojo.addClass(this._selectedColor,"colorPickerSelected");dojo.addClass(this._selectedColor,"colorPickerSelectedSkinny");this._colorPickerFlat=new s({})}var b=dojo.create("div",{className:"bgPropComboDiv",style:"margin-right:"+b+"px;padding:1px 0;"}),g=dojo.isArray(this.data)?this.data:[""],c=this.langObjVE=z;if(f){this._statics=["",
davinci.ve.widgets.ColorPicker.divider,c.colorPicker,c.removeValue];this._run={};this.data?(this.data.push({value:davinci.ve.widgets.ColorPicker.divider}),this.data.push({value:langObj.removeValue,run:function(){this.set("value","")}})):(this.data=[{value:this._statics[0]}],this.data.push({value:this._statics[2],run:this._chooseColorValue}),this.data.push({value:this._statics[3],run:function(){this.set("value","")}}),this.data.push({value:this._statics[1]}),this.data.push({value:"transparent"}),this.data.push({value:"black"}),
this.data.push({value:"white"}),this.data.push({value:"red"}),this.data.push({value:"green"}),this.data.push({value:"blue"}));g=[];for(c=0;c<this.data.length;c++)g.push(this.data[c].value),this.data[c].run&&(this._run[this.data[c].value]=this.data[c].run);this._store=new t({values:g,noncolors:this._statics})}else this._store=new u({values:g});this._comboBox=new v({store:this._store,id:this._textFieldId,style:"width:100%;"});b.appendChild(this._comboBox.domNode);this.domNode.appendChild(a);f&&(this.domNode.appendChild(h),
dojo.connect(h,"onclick",dojo.hitch(this,function(a){dojo.stopEvent(a);this._chooseColorValue()})),h.appendChild(this._selectedColor),this._colorPickerFlat_comboBoxUpdateDueTo="colorSwatch");this.domNode.appendChild(b);"string"==typeof this.propname&&this._comboBox&&(davinci.ve._BackgroundWidgets||(davinci.ve._BackgroundWidgets={}),davinci.ve._BackgroundWidgets[this.propname]={propPaletteWidget:this,comboBox:this._comboBox});this.inherited(arguments)},startup:function(){this.inherited(arguments);
this._button=dojo.byId(this._buttonId);dojo.connect(this._button,"onclick",this,function(){var a=this._cascade&&this._cascade._widget&&this._cascade._widget.getContext?this._cascade._widget.getContext():null,b=new w({context:a}),f=dojo.hitch(this,function(b){a||(console.error("Background.js. no context"),a={});var d=a.cascadeBatch={},c=d.propList=[],f=d.actions={},h=d.deferreds={};d.askUserResponse=void 0;if(!b.cancel){var g=davinci.ve._BackgroundWidgets,e;for(e in g){var k=g[e];if(k.bgdWidget){var d=
k.bgdWidget.get("value"),l=k.propPaletteWidget.get("value");d!==l&&(c.push(e),f[e]=dojo.hitch(this,function(a,b){a.propPaletteWidget._comboBoxUpdateDueTo="backgroundDialog";a.propPaletteWidget.set("value",b)},k,d),h[e]=new n)}}e="background-image";k=g[e];b=A.buildBackgroundImage(b.bgddata);for(d=0;d<b.length;d++)l=b[d],m.containsUrl(l)&&!m.isAbsolute(l)&&((g=m.getUrl(l))&&(l="url('"+(new y(g)).toString()+"')"),b[d]=l);d=0==b.length?"":b[b.length-1];l=k.propPaletteWidget.get("value");d!==l&&(k.propPaletteWidget._cascade&&
(k.propPaletteWidget._cascade._valueArrayNew=b),c.push(e),f[e]=dojo.hitch(this,function(a,b){k.propPaletteWidget._comboBoxUpdateDueTo="backgroundDialog";k.propPaletteWidget.set("value",b)},k,d),h[e]=new n);for(d=0;d<c.length;d++)e=c[d],h[e].then(dojo.hitch(this,function(b){(b=c[b+1])?f[b].apply():delete a.cascadeBatch},d));0<c.length&&(e=c[0],f[e].apply())}return!0},b),h=davinci.ve._BackgroundWidgets,g;for(g in h){var c=h[g].propPaletteWidget._cascade;c&&(c._valueArrayNew=c._valueArray)}b.set("baseLocation",
this._baseLocation);x.showModal(b,"Background","",f)});this.connect(this._comboBox,"onChange",dojo.hitch(this,function(a){(a==davinci.ve.widgets.ColorPicker.divider||a==this.langObjVE.colorPicker)&&this._comboBox.set("value",this.value);var b=this._comboBoxUpdateDueTo;this._comboBoxUpdateDueTo=void 0;"setAttr"!=b&&this._onChange(a)}));this.connect(this._comboBox,"onFocus",dojo.hitch(this,function(a){a=davinci.ve._BackgroundWidgets;for(var b in a){var f=a[b].propPaletteWidget._cascade;f&&(f._valueArrayNew=
void 0)}(b=this._cascade&&this._cascade._widget&&this._cascade._widget.getContext?this._cascade._widget.getContext():null)&&delete b.cascadeBatch}));this._maqStartupComplete=!0},_setBaseLocationAttr:function(a){this._baseLocation=a},_setValueAttr:function(a){var b=this._comboBox.get("value");this._colorswatch&&dojo.style(this._selectedColor,"backgroundColor",a);a=dojo.isArray(a)?0<a.length?a[a.length-1]:"":a;b!==a&&("backgroundDialog"!==this._comboBoxUpdateDueTo&&"colorSwatch"!==this._comboBoxUpdateDueTo&&
(this._comboBoxUpdateDueTo="setAttr"),this._comboBox.set("value",a))},_onChange:function(a){this._colorswatch&&"string"==typeof a&&(a in this._run?dojo.hitch(this,this._run[a])():a==davinci.ve.widgets.ColorPicker.divider?this._comboBox.set("value",this._store.getItemNumber(0)):dojo.style(this._selectedColor,"backgroundColor",a));this.value=this._comboBox.get("value");this.onChange(a)},onChange:function(a){},_getValueAttr:function(){return this._comboBox.get("value")},_setReadOnlyAttr:function(a){this._maqStartupComplete&&
(this._isReadOnly=a,this._comboBox.set("disabled",a),this._button.disabled=a)},_chooseColorValue:function(){if(!this._isReadOnly){var a=this._comboBox.get("value"),b=this.isLeftToRight();davinci.ve.widgets.ColorPickerFlat.show(this._colorPickerFlat,a,this,b)}}})});
//# sourceMappingURL=Background.js.map