//>>built
define("davinci/ve/widgets/Cascade","dojo/_base/declare ../../workbench/WidgetLite ../../workbench/Preferences ../../Workbench ../../html/CSSModel ../../library ../../Theme ../../html/CSSRule ../States dojo/i18n!../nls/ve system/resource".split(" "),function(m,s,p,t,q,u,v,w,r,k,n){m=m("davinci.ve.widgets.Cascade",[s],{target:null,targetField:null,toggleClasses:null,_regex_combinators:/[\s\~\+\>]+/,_regex_not_pseudoclass:/(.*)\:not\((.*)\)(.*)/,_regex_pseudoelement:/(.*)(\:\:[^\:\.\#\[]*)(.*)/,_regex_id:/(.*)(\#[^\:\.\#\[]*)(.*)/,
_regex_class:/(.*)(\.[^\:\.\#\[]*)(.*)/,_regex_attribute:/(.*)(\[[^\]]*\])(.*)/,_regex_pseudoclass:/(.*)(\:[^\:\.\#\[]*)(.*)/,_regex_univeral:/(.*)(\*[^\:\.\#\[]*)(.*)/,delegate:null,constructor:function(a,b){this.subscriptions=[];this.publishing={};this._radioGroupName="davinci_ve_widgets_Cascade"+davinci.ve.widgets.Cascade.__id++;this._handles=[];this._values=[];this.inherited(arguments)},buildRendering:function(){this.domNode=dojo.doc.createElement("div");this.container=dojo.doc.createElement("div");
dojo.addClass(this.container,"showCascade");this.domNode.appendChild(this.container);this.topDiv=dojo.create("div",{"class":"cascadeTopDiv"},this.container);this.cascadeTableDiv=dojo.create("div",{"class":"cascadeTableDiv"},this.container);dojo.removeClass(this.container,"showAllValues");dojo.isArray(this.target)||(this.target=[this.target]);dojo.addClass(this.domNode,"CascadeTop");this.inherited(arguments)},startup:function(){var a=dijit.byId(this.targetField);if(a)a._cascade=this,this._getFieldValue=
function(){return a.get("value")},this._setFieldValue=function(b,d){a.set&&(this._value=b||"",this._loc=d,a._setBaseLocationAttr&&a.set("baseLocation",d&&d.getPath?d.getPath():null),a.set("value",this._value,!0))},dojo.connect(a,"onChange",this,"_onFieldChange"),dojo.connect(a,"onFocus",this,"_onFieldFocus"),dojo.connect(a,"onBlur",this,"_onFieldBlur");else{var b=dojo.byId(this.targetField);this._getFieldValue=function(){return dojo.attr(b,"value")};this._setFieldValue=function(a,d){this._value=a||
"";this._loc=d;dojo.attr(b,"value",this._value)};dojo.connect(b,"onchange",this,"_onFieldChange",!0);dojo.connect(b,"onfocus",this,"_onFieldFocus",!0);dojo.connect(b,"onblur",this,"_onFieldBlur",!0)}this._value=this._getFieldValue();this._started=!0},_canModifyRule:function(a){if(!a||!a.getCSSFile)return!0;a=a.getCSSFile();return!a?!0:!n.findResource(a.url).readOnly()},_onFieldChange:function(a){function b(){e&&(h&&h[e])&&h[e].resolve()}function c(a){a._value=a._getFieldValue();a._valueArray=a._valueArrayNew;
var b=a._valueArray&&dojo.isArray(a._valueArray)&&0<a._valueArray.length?a._valueArray:a._value;a._changeValue(a._targetValueIndex,b)}a=function(a,b){if(!a&&!b)return!0;if(!a&&b||a&&!b||a.length!=b.length)return!1;for(var c=0;c<a.length;c++)if(a[c]!==b[c])return!1;return!0};this.context&&this.context.blockChange(!1);if(!(this._value==this._getFieldValue()&&a(this._valueArray,this._valueArrayNew))&&!(1>this._values.length))if("(overrides)"==this._getFieldValue())this._setFieldValue&&this._setFieldValue("(overrides)",
null);else if("number"==typeof this._targetValueIndex){var d=p.getPreferences("davinci.ve.editorPrefs",t.getProject());if(this._widget&&this.target&&0<this.target.length){var e=this.target[0];a=this._widget.getContext();var f;a&&(f=a.cascadeBatch);if(f){var g=f.askUserResponse;if(f.deferreds)var h=f.deferreds}}!1===g?(this._setFieldValue(this._value,this._loc),b()):!0===g?(c(this),b()):(g=null,this._values[this._targetValueIndex].readOnly&&"davinci.themeEdit.ThemeEditor"!=this._editor.editorID?(g=
k.propChangeCannotComplete+"\x3cbr\x3e\x3cbr\x3e"+dojo.string.substitute(k.toChangeProperty,["\x3ca href\x3d'app/docs/index.html#CreatingStyleRulesWithAppCss' target\x3d'_blank'\x3e"+k.creatingStyleRules+"\x3c/a\x3e"])+"\x3cbr/\x3e\x3cbr/\x3e",davinci.Workbench.showMessage(k.errorModifyingValue,g,{width:350},dojo.hitch(this,function(){b();return!0})),f&&(f.askUserResponse=!1),this._setFieldValue(this._value,this._loc)):("theme"==this._values[this._targetValueIndex].type||"theme"==this._values[this._targetValueIndex].proposalTarget)&&
d.cssOverrideWarn&&this._editor.supports("MultiPropTarget")?require(["davinci/ve/widgets/ChangeWillModify"],dojo.hitch(this,function(a){var e=new a;a=davinci.Workbench.showDialog({title:"",content:e,style:{width:350},okCallback:dojo.hitch(this,function(){f&&(f.askUserResponse=!0);c(this);b();e.checkbox.get("checked")&&(d.cssOverrideWarn=!1,p.savePreferences("davinci.ve.editorPrefs",null,d))}),okLabel:null,hideCancel:null,submitOnEnter:!0});dojo.connect(a,"onCancel",dojo.hitch(this,function(){f&&(f.askUserResponse=
!1);this._setFieldValue(this._value,this._loc);b();e.checkbox.get("checked")&&(d.cssOverrideWarn=!1,p.savePreferences("davinci.ve.editorPrefs",null,d))}))})):(c(this),b()))}},_changeValue:function(a,b){var c=void 0;this._whichStateInputElement&&this._whichStateInputElement.checked&&(c=this._whichState);for(var d=this._values[a],e=[],f=0;f<this.target.length;f++)if(dojo.isArray(b))for(var g=0;g<b.length;g++){var h={};h[this.target[f]]=b[g];e.push(h)}else h={},h[this.target[f]]=b,e.push(h);this._dirtyCascadeList=
!0;"element.style"==d.type?("position"==this.target[0]&&1==e.length&&("absolute"==e[0].position?(d=this.context.getPreference("absoluteWidgetsZindex"),e.push({"z-index":d})):e.push({"z-index":""})),dojo.publish("/davinci/ui/styleValuesChange",[{values:e,appliesTo:"inline",applyToWhichStates:c,cascade:this}])):dojo.publish("/davinci/ui/styleValuesChange",[{values:e,appliesTo:d,applyToWhichStates:c}])},_getAttribStyleValue:function(){return this.context.getStyleAttributeValues(this._widget)},_getShortHands:function(){if(this._shorthands)return this._shorthands;
this._shorthands=[];for(var a=0;a<this.target.length;a++)this._buildShortHands(this.target[a]);return this._shorthands},_buildShortHands:function(a){for(var b=!1,c=0;c<q.shorthand.length;c++)if(a==q.shorthand[c][0]){b=!0;break}if(b){a=q.shorthand[c][1];for(b=0;b<a.length;b++){for(var d=!1,c=0;c<this._shorthands.length&&!d;c++)this._shorthands[c]==a[b]&&(d=!0);d||this._shorthands.push(a[b]);this._buildShortHands(a[b])}}return this._shorthands},_onChangeOverride:function(a){alert(k.valueIsOverriden);
return!1},_getSelector:function(a,b){var c=this.context.getThemeMeta();if(!c)return[];var d=c.loader.getType(a);if(c=c.metadata.getStyleSelectors(d,"Normal"))for(var e in c)for(d=0;d<c[e].length;d++)for(var f=0;f<b.length;f++)if(b[f]==c[e][d])return e},_getMetaTargets:function(a,b){var c=this._getSelector(a,b);return this.context.getModel().getRule(c).filter(function(a){return a.getSelectorText()==c})},_getSelectionCssRules:function(a){this.context._cssCache=this.context._cssCache||{};var b=this.context.getSelection();
if(!a&&!b.length)return{rules:null,matchLevels:null};var c=a||b[0].domNode||b[0],d=c.id+"_"+c.className;if(b.length){var e=this.context._cssCache[d]=this.context.model.getMatchingRules(c,!0);this.context.cssFiles&&this.context.cssFiles.forEach(function(a){a.getMatchingRules(c,e.rules,e.matchLevels)});e.rules.forEach(function(a){var b=dojo.hitch(a,"onChange",this,function(){delete this.context._cssCache[d];connect.unsubscribe(b)})},this);return e}return{rules:null,matchLevels:null}},_getAllRules:function(){function a(a){if(a&&
a.parent&&a.parent.url)return a=a.parent.url,/^themes\//.test(a)||/\/themes\//.test(a)?"theme":"queried"}var b=[];if("davinci.themeEdit.ThemeEditor"!=this._editor.editorID){var c=this._getDefaultSelection();if(this._editor.supports("inline-style")&&"element.style"==c){for(var c=this._getAttribStyleValue(),d=null,e=0;e<c.length;e++)for(var f=c[e],g=0;g<this.target.length;g++){var h=this.target[g];void 0!==f[h]&&(d=f[h])}b.push({rule:c,value:d,matchLevel:"element.style",type:"element.style"})}if((c=
this._getSelectionCssRules(this._topWidgetDom))&&c.rules)for(g=0;g<c.rules.length;g++){d="";e=c.rules[g];for(f=0;f<e.selectors.length;f++)0!=f&&(d+=", "),d+=e.selectors[f].getLabel();e=a(e);b.push({rule:c.rules[g],ruleString:d,matchLevel:c.matchLevels[g],type:e})}this._addDeltaRules(this._widget,b);for(var c=this._getClasses(this._widget),k=0,g=0;g<c.length;g++){var l=c[g];"string"==typeof l&&0<l.length&&this._getClassSelector(l).forEach(function(a){for(var c=!1,d=0;d<b.length;d++)if(this._compareSelectors(b[d].ruleString,
a)){b[d].className=l;c=!0;break}c||(c=this._computeMatchLevelSelector(a),b.splice(k,0,{rule:null,ruleString:a,targetFile:this.targetFile,className:l,value:null,matchLevel:c,type:"proposal"}),k++)}.bind(this))}}if("davinci.themeEdit.ThemeEditor"==this._editor.editorID){if(c=this._editor._getCssRules(this._widget,this._editor._selectedSubWidget,this._editor._currentState)){g=[];for(d=c.length-1;-1<d;--d)g.push(c[d]);c=g}}else c=this._widget?this._getMetaTargets(this._widget,this.target):[];for(g=0;g<
c.length;g++){d=!1;for(e=0;!d&&e<b.length;e++)b[e].rule==c[g]&&(d=!0,b[e].type="theme");d||b.push({rule:c[g],matchLevel:"theme",type:"theme"})}return b},_buildCssRuleset:function(){var a=this._getAllRules();this._values=[];this._hasOverride=!1;for(var b=this._getShortHands(),c=0;c<a.length;c++){var d=a[c].rule;if(d){for(var e=0;e<b.length;e++)if("element.style"!=a[c].type&&null!=a[c].rule.getProperty(b[e])){a[c].shorthand=b[e];var f=d.getProperty(b[e]);a[c].value=f&&f.value;this._hasOverride=!0}else"element.style"==
a[c].type&&-1<dojo.indexOf(a[c].rule,b[e])&&(a[c].shorthand=b[e],f=dojo.indexOf(a[c].rule,b[e]),a[c].value=d[f],this._hasOverride=!0);if(!a[c].shorthand&&"element.style"!=a[c].type)a[c].value=this._getRuleTargetValue(d);else if(!a[c].shorthand&&"element.style"==a[c].type)for(e=0;e<d.length;e++)d[e].hasOwnProperty(this.target[0])&&(a[c].value=d[e][this.target[0]])}}a=this._sortRules(a);this._addClasses(a);this._values=a},_sortRules:function(a){for(var b=[],c=0;c<a.length;c++){var d=!1;"element.style"==
a[c].type&&(b.splice(0,0,a[c]),d=!0);for(var e=0;!d&&e<b.length;e++)"element.style"!=b[e].matchLevel&&b[e].matchLevel<a[c].matchLevel&&(d=!0,b.splice(e,0,a[c]));d||b.push(a[c])}return b},_addClasses:function(a){for(var b=!1,c=0;c<a.length;c++)a[c].extraClass=[],b&&a[c].extraClass.push("cssShorthandOverRidden"),a[c].value||"element.style"!=a[c].type&&this._getRuleTargetValue(a[c].rule)?b=!0:!a[c].value&&"element.style"!=a[c].type&&a[c].extraClass.push("hiddenCascadeNode"),"element.style"==a[c].type&&
!a[c].value&&a[c].extraClass.push("elementStyleNode"),this._canModifyRule(a[c].rule)||(a[c].extraClass.push("readOnlyRule"),a[c].readOnly=!0)},_updateCascadeList:function(){function a(a){return function(){return this._onChange({target:a})}}function b(a){return function(){return this._onChangeRemove({target:a})}}this._setFieldValue&&this._setFieldValue("",null);if(!this._widget||!this._widget.domNode)dojo.addClass(this.container,"dijitHidden");else{dojo.removeClass(this.container,"dijitHidden");this._buildCssRuleset();
this._destroy();var c=dojo.doc.createElement("table");dojo.addClass(c,"cascadeTable");var d=null,e=null,d=dojo.doc.createElement("tr");d.className="propApplyToLabelRow";e=dojo.doc.createElement("td");e.colSpan="3";e.innerHTML=k.applyToWhich;e.className="propApplyToLabelCell";d.appendChild(e);c.appendChild(d);this._radio=[];for(var f=0;f<this._values.length;f++){var g=this._formatRuleString(this._values[f]);this._radio.push(dojo.create("input",{type:"radio",name:this._radioGroupName}));for(var d=dojo.doc.createElement("tr"),
h=0;h<this._values[f].extraClass.length;h++)dojo.addClass(d,this._values[f].extraClass[h]);e=dojo.doc.createElement("td");d.appendChild(e);dojo.addClass(e,"cascadeSpacer");e=dojo.doc.createElement("td");dojo.addClass(e,"cascadeButton");e.appendChild(this._radio[this._radio.length-1]);d.appendChild(e);e=dojo.doc.createElement("td");dojo.addClass(e,"cascadText");e.innerHTML="\x3cdiv class\x3d'cascadeRuleText'\x3e"+g+"\x3c/div\x3e";this._values[f].shorthand?this._handles.push(dojo.connect(this._radio[this._radio.length-
1],"onclick",this,"_onChangeOverride")):this._handles.push(dojo.connect(this._radio[this._radio.length-1],"onclick",this,a(f)));if(this._values[f].shorthand)e.innerHTML+="\x3cdiv\x3e"+this._values[f].shorthand+":"+this._values[f].value+";\x3c/div\x3e";else if(this._values[f].value){for(h=0;h<this.target.length;h++);e.innerHTML+="\x3cdiv class\x3d'ruleValue'\x3e"+this.target[0]+":"+this._values[f].value+";\x3c/div\x3e"}d.appendChild(e);e=dojo.doc.createElement("td");dojo.addClass(e,"cascadRemove");
g=dojo.doc.createElement("button");this._values[f].readOnly&&dojo.attr(g,"disabled","true");dojo.addClass(g,"cascadeRemoveButton");e.appendChild(g);this._handles.push(dojo.connect(g,"onclick",this,b(f)));d.appendChild(e);e=dojo.doc.createElement("td");e.className="cascadeSpacer";d.appendChild(e);c.appendChild(d)}this._widgetState=this._whichStateInputElement=void 0;d=r.getStatesListCurrent(this._widget.domNode);for(f=0;f<d.length;f++)if(d[f]){f=d[f];d=dojo.doc.createElement("tr");d.className="propWhichStateRow";
e=dojo.doc.createElement("td");e.colSpan="3";g=dojo.create("input",{type:"checkbox",checked:!1,className:"propWhichStateInput"});this._whichState=f;this._whichStateInputElement=g;e.appendChild(g);g=dojo.create("label",{className:"propWhichStateLabel"});g.innerHTML=dojo.string.substitute(k.onlyApplyToState,[f]);e.appendChild(g);e.className="propWhichStateCell";d.appendChild(e);c.appendChild(d);break}this.cascadeTableDiv.appendChild(c);this._updateFieldValue()}},selectRule:function(a){for(var b=0;b<
this._values.length;b++)if("element.style"!=a&&this._values[b].rule==a){dojo.removeClass(this._radio[b].parentNode.parentNode,"hiddenCascadeNode");dojo.attr(this._radio[b],"checked",!0);this._onChange({target:b});break}else if("element.style"==a&&"element.style"==this._values[b].type){dojo.removeClass(this._radio[b].parentNode.parentNode,"hiddenCascadeNode");dojo.attr(this._radio[b],"checked",!0);this._onChange({target:b});break}},selectRuleBySelector:function(a){if("element.style"==a)this._targetValueIndex=
0,0<this._values.length&&(dojo.attr(this._radio[0],"checked",!0),this._values[0].shorthand?dojo.addClass(this._radio[0].parentNode.parentNode,"cssShorthandOverRidden"):(a=this._getBaseLocation(),this._setFieldValue(this._values[0].value,a)));else for(var b=0;b<this._values.length;b++)if("element.style"!=this._values[b].type&&this._values[b].rule&&this._values[b].rule.hasSelector(a)){dojo.removeClass(this._radio[b].parentNode.parentNode,"hiddenCascadeNode");dojo.attr(this._radio[b],"checked",!0);this._onChange({target:b});
break}},_isTarget:function(a){if("$std_10"===a)return!0;for(var b=0;b<this.target.length;b++)if(this.target[b]==a)return!0;return!1},_targetIsRootProperty:function(){for(var a=["left","top","right","bottom"],b=0;b<this.target.length;b++)if(-1<a.indexOf(this.target[b]))return!0;return!1},_updateFieldValue:function(){null==this._widget&&this._setFieldValue("",this._getBaseLocation());var a=this._getDefaultSelection();this._targetValueIndex=0;for(var b=!1,c=!1,d=0;d<this._values.length;d++){var e="davinci.ve.HTMLPageEditor"==
this._editor.editorID,f="davinci.themeEdit.ThemeEditor"==this._editor.editorID;this._values[d].value&&!b&&f||this._values[d].value&&!b&&e&&!this._values[d].readOnly||!b&&!c&&"element.style"!=this._values[d].type&&this._values[d].rule&&this._values[d].rule.hasSelector(a)||"element.style"==a&&"element.style"==this._values[d].type?(this.selectRule("element.style"==this._values[d].type?"element.style":this._values[d].rule),this._values[d].value&&(b=!0),c=!0):b&&!c&&dojo.addClass(this._radio[d].parentNode.parentNode,
"cssOverRidden")}!b&&(!c&&e)&&this.selectRuleBySelector("element.style")},_getThemeMetaDataByWidget:function(a){var b=this.context.getThemeMeta();if(!b)return null;a=b.loader.getType(a);var b=b.loader.getMetaData(a),c=!1,d="string"==typeof a?a.split("."):null;d&&"html"==d[0]&&(c=!0);if(!b&&this.context.cssFiles&&!c)for(c=0;c<this.context.cssFiles.length;c++)if(d=v.getThemeByCssFile(this.context.cssFiles[c]))if(b=u.getThemeMetadata(d).loader.getMetaData(a))break;return b},_getDefaultSelection:function(){var a=
"Normal";"davinci.themeEdit.ThemeEditor"==this._editor.editorID&&(a=a||r.getState());var b=this._getThemeMetaDataByWidget(this._widget);if(!b||!b.states||this._targetIsRootProperty())return"element.style";if(b&&b.states[a]&&b.states[a].elements){var c=b.states[a].elements,d;for(d in c)for(var e=0;e<c[d].length;e++)if(this._isTarget(c[d][e]))return"$root"==d?"element.style":d}if(b&&b.states[a]&&(c=this.context.getThemeMeta()))if(e=c.loader.getType(this._widget),c=c.metadata.getStyleSelectors(e,a,null))for(d in c)for(a=
0;a<c[d].length;a++)if(this._isTarget(c[d][a])){if(b.rootSelectors)for(a=0;a<b.rootSelectors.length;a++)if(d==b.rootSelectors[a])return"element.style";return d}return null},_addDeltaRules:function(a,b){var c="Normal",d=-1,e=[],f=this.context._getCssFiles(),f=f&&0<f.length?f[0].url:null,g=!1;f&&(g=(g=n.findResource(f))?g._readOnly:!0);"davinci.themeEdit.ThemeEditor"==this._editor.editorID&&(c=c||r.getState());var h=this._getThemeMetaDataByWidget(a);if(h&&h.states[c]&&h.states[c].selectors){var c=h.states[c].selectors,
k;for(k in c){c=!1;for(h=0;h<b.length;h++){var l=b[h];"element.style"===l.type&&(d=h);if("theme"===l.type&&l.ruleString===k&&(l.rule.parent.relativeURL==this.context._themeUrl||l.rule.parent.url==f)){c=!0;break}}c||(c=this._computeMatchLevelSelector(k),f&&!g&&e.push({rule:null,ruleString:k,targetFile:f,className:null,value:null,matchLevel:c,type:"proposal"}),this.context._themeUrl&&!this.context.theme.getFile().readOnly()&&e.push({rule:null,ruleString:k,targetFile:this.context._themeUrl,className:null,
value:null,matchLevel:c,type:"proposal",proposalTarget:"theme"}))}}var m=d+1;e.forEach(function(a){b.splice(m++,0,a)});return b},_getRuleTargetValue:function(a){var b=null;if(a)for(var c=0;!b&&c<this.target.length;c++)b=a.getProperties(this.target[c]);if(null!=b){if(1<b.length){a=[];for(c=0;c<b.length;c++)a.push(b[c].value);return a}if(1==b.length)return b[0].value}return null},_onChangeRemove:function(a){this._changeValue(a.target,null);this._updateCascadeList()},_onChange:function(a){var b=null;
if("element.style"==this._values[a.target].type)b=this._getBaseLocation();else if("proposal"==this._values[a.target].type){var c=this.context.getModel().find({elementType:"CSSFile",relativeURL:this._values[a.target].targetFile},!0),d=this.context._getCssFiles();c?b=n.findResource(c.url):d[0].url==this._values[a.target].targetFile&&(b=n.findResource(d[0].url))}else b=n.findResource(this._values[a.target].rule.getCSSFile().url);this._setFieldValue(this._values[a.target].value||"",b);this._targetValueIndex=
a.target},_widgetValuesChanged:function(a){if(this._dirtyCascadeList)this._updateCascadeList(),this._dirtyCascadeList=!1;else{var b=this._getShortHands();a=a.values;for(var c in a)for(a=0;a<b.length;a++)if(b[a]==c){this._updateCascadeList();return}}},_formatRuleString:function(a){if("element.style"==a.type)return"element.style";var b="";if("proposal"==a.type)b=a.className?b+dojo.string.substitute(k.newRule,[a.className,a.targetFile]):b+dojo.string.substitute(k.newThemeRule,[a.targetFile]),b+=a.ruleString;
else{var c=a.rule;a.className?b+=dojo.string.substitute(k.existingRule,[a.className,this.targetFile]):"theme"==a.type&&(b+="["+a.type+"] ");if(a.ruleString)b+=a.ruleString;else for(var d=0;d<c.selectors.length;d++)0!=d&&(b+=", "),b+=c.selectors[d].getLabel();(d=c.searchUp("CSSFile"))&&(b+="  ("+d.url||d.relativeURL);b=a.property?b+dojo.string.substitute(k.line,[a.property.startLine]):b+dojo.string.substitute(k.line,[c.startLine||k.propUndefined])}return b},_getWidgetTopDom:function(a,b){var c=this._getSelector(a,
b),d=function(a,b){if(b.matches(a))return a;for(;0<a.children.length;)return d(a.children[0],b)};if(c){var e=new w;e.setText(c+"{}");return d(a.domNode||a,e)}return null},_widgetSelectionChanged:function(a){(this._widget=a=a[0])?(this.context=a.getContext(),this.targetFile=this.context.getAppCssRelativeFile(),this._editor=this.context.editor,this._topWidgetDom=this._getWidgetTopDom(this._widget,this.target)||this._widget.domNode||this._widget):this._topWidgetDom=null;this._updateCascadeList()},_getBaseLocation:function(){return{}},
_editorSelected:function(a){this._editor=a.editor;var b;this._editor&&this._editor.getContext&&(b=this._editor.getContext());b&&this._editor.supports("style")?(this.context=b,this.targetFile=b.getAppCssRelativeFile(),a=b.getSelection(),0<a.length?this._widgetSelectionChanged(a):this._widgetSelectionChanged([])):(this._widget=this.context=null,this._setFieldValue&&this._setFieldValue("",null));this._updateCascadeList()},_onFieldFocus:function(){this.context&&this.context.blockChange(!0)},_destroy:function(){var a=
this.cascadeTableDiv;for(dojo.forEach(dojo.query("[widgetId]",a).map(dijit.byNode),function(a){a.destroy()});a.firstChild;)dojo._destroyElement(a.firstChild);dojo.forEach(this._handles,dojo.disconnect);this._handles=[]},_onFieldBlur:function(){this.context&&this.context.blockChange(!1)},_getClasses:function(a){a=a.getClassNames("class")||"";a=a.split(" ");for(var b=0;b<a.length;b++)for(var c=b+1;c<a.length;c++)a[c]==a[b]&&a.splice(c,1);return a},_getRelativeMetaTargetSelector:function(a){var b=this.context.getThemeMeta();
if(!b)return[];var c=this.context.getSelection();if(!c.length)return[];c=c[0];c=b.loader.getType(c);return b.metadata.getRelativeStyleSelectorsText(c,"Normal",null,a,this.context.getTheme().className)},_getClassSelector:function(a){var b=this._getRelativeMetaTargetSelector(this.target),b=b.length?b[0]:"";bodyId=this.context.model.find({elementType:"HTMLElement",tag:"body"},!0).find({elementType:"HTMLAttribute",name:"id"},!0).value;var c=this.context.getTheme(),d=[];if(!c)return d;var e=c.className;
b.split(",").forEach(function(b){b=b.trim();d.push("#"+bodyId+"."+e+" ."+a+b)}.bind(this));return d},_computeMatchLevelSelector:function(a){a=a.split(this._regex_combinators);for(var b=0,c=0;c<a.length;c++){for(var d=a[c];;){var e=d.match(this._regex_not_pseudoclass);if(null!=e)b+=this._computeMatchLevelSimpleSelector(e[2]),d=e[1]+e[3];else break}b+=this._computeMatchLevelSimpleSelector(d)}return b},_computeMatchLevelSimpleSelector:function(a){var b=0;do{var c=!1,d=function(d,f){var g=a.match(d);
null!=g&&(c=!0,b+=f,a=g[1]+g[3])};d(this._regex_pseudoelement,1);c||(d(this._regex_id,100),d(this._regex_class,10),d(this._regex_attribute,10),d(this._regex_pseudoclass,10),d(this._regex_univeral,0))}while(c);0<a.length&&(b+=1);return b},_compareSelectors:function(a,b){if((!a||!b)&&a!=b)return!1;var c=a.split(this._regex_combinators),d=b.split(this._regex_combinators);if(c.length!=c.length)return!1;for(var e=0;e<c.length;e++)if(c[e]!=d[e])return!1;return!0},_compareSimpleSelectors:function(a,b){}});
return dojo.mixin(m,{__id:0})});
//# sourceMappingURL=Cascade.js.map