//>>built
define("davinci/ve/widgets/ColorPicker","dojo/_base/declare dijit/_WidgetBase dijit/form/ComboBox davinci/ve/widgets/ColorStore davinci/ve/widgets/ColorPickerFlat dijit/TooltipDialog dojo/i18n!davinci/ve/nls/ve dijit/popup".split(" "),function(c,e,h,k,l,m,d){c=c("davinci.ve.widgets.ColorPicker",[e],{numberDelta:1,insertPosition:9,data:null,postCreate:function(){this.inherited(arguments);this.domNode.removeAttribute("data-dojo-type");this.domNode.removeAttribute("dojoType");this._statics=["",davinci.ve.widgets.ColorPicker.divider,
d.colorPicker,d.removeValue];this._run={};this.data?(this.data.push({value:davinci.ve.widgets.ColorPicker.divider}),this.data.push({value:d.removeValue,run:function(){this.set("value","")}})):this.data=[{value:this._statics[0]},{value:this._statics[2],run:this._chooseColorValue},{value:this._statics[3],run:function(){this.set("value","")}},{value:this._statics[1]},{value:"transparent"},{value:"black"},{value:"white"},{value:"red"},{value:"green"},{value:"blue"}];for(var a=[],b=0;b<this.data.length;b++)a.push(this.data[b].value),
this.data[b].run&&(this._run[this.data[b].value]=this.data[b].run);this._store=new k({values:a,noncolors:this._statics});this._dropDown=new h({store:this._store,required:!1,autoComplete:!1,labelType:"html",labelAttr:"label",style:"width:100%"});dojo.connect(this._dropDown,"onChange",this,"_onChange");a=dojo.doc.createElement("div");dojo.addClass(a,"colorPicker");this._selectedColor=dojo.doc.createElement("div");this._selectedColor.innerHTML="\x26nbsp;";dojo.addClass(this._selectedColor,"colorPickerSelected");
dojo.connect(this._selectedColor,"onclick",dojo.hitch(this,function(a){this._chooseColorValue()}));a.appendChild(this._selectedColor);b=dojo.doc.createElement("div");dojo.addClass(b,"colorPickerComboContainer");b.appendChild(this._dropDown.domNode);a.appendChild(b);this._colorPickerFlat=new l({});this.domNode.appendChild(a)},_chooseColorValue:function(){this._dropDown.set("value",this._value,!0);var a=this._colorPickerFlat,b=new m({id:"maqetta_prop_tooltip_color_picker",title:d.selectColor,content:a});
dijit.popup.moveOffScreen(b.domNode);var f=!1,c=function(a){return function(){f&&(f=!1,dijit.popup.close(b))}}(this);b.connect(a,"onCancel",dojo.hitch(this,c));b.connect(a,"onClose",dojo.hitch(this,c));var g=dijit.byNode(dojo.query("[widgetId]",b.domNode)[0]);if(this._value in dojo.Color.named){var e=dojo.colorFromString(this._value);a.set("value",e.toHex())}else a.set("value",this._value||"",!0);(function(a){return function(){this._isReadOnly||(dijit.popup.open({parent:a._dropDown,popup:b,around:a._dropDown.domNode,
orient:a.isLeftToRight()?{BL:"TL",BR:"TR",TL:"BL",TR:"BR"}:{BR:"TR",BL:"TL",TR:"BR",TL:"BL"},onClose:function(){g.canceled||(a._dropDown.get("value"),a._dropDown.set("value",g.get("value")));c();b.destroy()}}),f=!0,dijit.focus(b.containerNode))}})(this)()},_setReadOnlyAttr:function(a){this._isReadOnly=a;this._dropDown.set("disabled",a)},onChange:function(a){},_getValueAttr:function(){return this._dropDown.get("value")},_setValueAttr:function(a,b){this._dropDown.set("value",a,!0);dojo.style(this._selectedColor,
"backgroundColor",a);if(a in dojo.Color.named){var c=dojo.colorFromString(a);this._colorPickerFlat.set("value",c.toHex(),b)}else this._colorPickerFlat.set("value",a,b);this._onChange(a,b)},_onChange:function(a,b){a in this._run?dojo.hitch(this,this._run[a])():a==davinci.ve.widgets.ColorPicker.divider?this._dropDown.set("value",this._store.getItemNumber(0)):(this._store.contains(a)||this._store.insert(this.insertPosition,a),dojo.style(this._selectedColor,"backgroundColor",a));if(this._value!=a&&!(a in
this._run)&&(this._value=a,!b))this.onChange(a)}});return dojo.mixin(c,{divider:"---"})});
//# sourceMappingURL=ColorPicker.js.map