//>>built
define("davinci/ve/widgets/EventSelection","dojo/_base/declare dojo/_base/connect dojo/dom-class system/resource davinci/Runtime davinci/Workbench davinci/model/Path ../../workbench/Preferences ../../workbench/ViewLite ../commands/EventCommand ./HTMLStringUtil ../States".split(" "),function(e,d,k,v,l,w,x,y,m,n,p,q){var r=/^State:.*/,s=/^\s*davinci\.states\.setState\s*\(\s*([\'"])((?:(?!\1).)*)\1\s*\)\s*$/,t=/^File:.*/,u=/^\s*location\.href\s*\=\s*([\'"])((?:(?!\1).)*)\1\s*$/,f=function(a){a&&q.getAllStateContainers(a);
return[""]},g=function(a){a&&a.match(r)&&(a=a.substring(6),a="davinci.states.setState('"+("Background"==a?"Normal":a)+"')");a&&a.match(t)&&(a="location.href\x3d'"+a.substring(5)+"'");return a},h=function(a){var b;a&&((b=a.match(s))&&(a="State:"+b[2]),(b=a.match(u))&&(a="File:"+b[2]));return a};e=e("davinci.ve.widgets.EventSelection",[m],{pageTemplate:[{display:"onclick",target:"onclick",type:"state",hideCascade:!0},{display:"ondblclick",target:"ondblclick",type:"state",hideCascade:!0},{display:"onmousedown",
target:"onmousedown",type:"state",hideCascade:!0},{display:"onmouseup",target:"onmouseup",type:"state",hideCascade:!0},{display:"onmouseover",target:"onmouseover",type:"state",hideCascade:!0},{display:"onmousemove",target:"onmousemove",type:"state",hideCascade:!0},{display:"onmouseout",target:"onmouseout",type:"state",hideCascade:!0},{display:"onkeypress",target:"onkeypress",type:"state",hideCascade:!0},{display:"onkeydown",target:"onkeydown",type:"state",hideCascade:!0},{display:"onkeyup",target:"onkeyup",
type:"state",hideCascade:!0},{display:"onfocus",target:"onfocus",type:"state",hideCascade:!0},{display:"onblur",target:"onblur",type:"state",hideCascade:!0},{display:"onchange",target:"onchange",type:"state",hideCascade:!0}],buildRendering:function(){this.domNode=dojo.doc.createElement("div");this.domNode.innerHTML=p.generateTable(this.pageTemplate,{zeroSpaceForIncrDecr:!0});k.add(this.domNode,"EventSelection");this.inherited(arguments)},setReadOnly:function(a){for(var b=0;b<this.pageTemplate.length;b++){var c=
this.pageTemplate[b].widget;c?c.set("readOnly",a):(c=this.pageTemplate[b].domNode)&&dojo.attr(c,"disabled",a)}},startup:function(){function a(a){return function(){return this._onChange({target:a})}}this.inherited(arguments);for(var b=0;b<this.pageTemplate.length;b++){var c=dijit.byId(this.pageTemplate[b].id);this.pageTemplate[b].widget=c;d.connect(c,"onChange",this,a(b))}this._buildSelectionValues();d.subscribe("/davinci/ui/context/loaded",dojo.hitch(this,this._buildSelectionValues));d.subscribe("/davinci/states/stored",
dojo.hitch(this,this._buildSelectionValues));d.subscribe("/davinci/states/state/added",dojo.hitch(this,this._buildSelectionValues));d.subscribe("/davinci/states/state/removed",dojo.hitch(this,this._updateValues));d.subscribe("/davinci/states/state/renamed",dojo.hitch(this,this._updateValues));d.subscribe("/davinci/ui/widgetPropertiesChanged",dojo.hitch(this,this._widgetPropertiesChanged));this.setReadOnly(!0)},onEditorSelected:function(){(!this._editor||!this._editor.supports("states"))&&delete this._editor;
this._buildSelectionValues()},_onChange:function(a){a=a.target;var b=dijit.byId(this.pageTemplate[a].id).get("value"),b=g(b),c={};c[this.pageTemplate[a].target]=b;a=new n(this._widget,c);dojo.publish("/davinci/ui/widgetPropertiesChanges",[{source:this._editor.editor_id,command:a}])},_getRoot:function(){var a=this._editor,b;a&&a.getContext&&(b=(a=a.getContext())&&a.rootNode);return b},_updateValues:function(a){if(a&&a.node&&a.node._dvWidget&&(a=(a=a.node._dvWidget.getContext())&&a.editor)&&a==l.currentEditor)this._buildSelectionValues(),
this._widget&&this._setValues()},onWidgetSelectionChange:function(){this._widget?(this._setValues(),this.setReadOnly(!1)):(this.setReadOnly(!0),this._clearValues())},_clearValues:function(){for(var a=0;a<this.pageTemplate.length;a++)dijit.byId(this.pageTemplate[a].id).set("value","",!1)},_buildSelectionValues:function(){for(var a=this._getRoot(),a=f(a),b=0;b<this.pageTemplate.length;b++){var c=dijit.byId(this.pageTemplate[b].id);c.store.clearValues();c.store.setValues(a)}},_setValues:function(){for(var a=
0;a<this.pageTemplate.length;a++){var b=this.pageTemplate[a].target,c=this._widget,d="",d=c.properties&&c.properties[b]?c.properties[b]:c._srcElement.getAttribute(b),d=h(d);(b=dijit.byId(this.pageTemplate[a].id))&&b.set("value",d,!1)}},_widgetPropertiesChanged:function(a){this._updateValues({widget:a[0]})}});e.getEventSelectionValues=f;e.getEventScriptFromValue=g;e.getValueFromEventScript=h;return e});
//# sourceMappingURL=EventSelection.js.map