//>>built
define("davinci/ve/widgets/HTMLStringUtil","davinci/Runtime ./FontDataStore ./FontComboBox ./MultiInputDropDown dijit/form/ComboBox dijit/form/DateTextBox dijit/form/TimeTextBox ./MetaDataStore ./ColorPicker ./Background".split(" "),function(r,q){var p=dojo.getObject("davinci.ve.widgets.HTMLStringUtil",!0);dojo.mixin(p,{__id:0,idPrefix:"davinci_ve_widgets_properties_generated",_currentPropSection:null,animSS:null,animRuleIndex:{},getCurrentPropSection:function(){return this._currentPropSection},getId:function(){return this.idPrefix+
this.__id++},injectId:function(a,e){var d=a.indexOf("\x3e");return!d?"\x3cspan id\x3d'"+e+"'\x3e"+a+"\x3c/span":a.substring(0,d)+" id\x3d'"+e+"'"+a.substring(d,a.length)},getEditor:function(a){function e(b){var a={};a.value="undefined"!=typeof b.value&&null!==b.value?b.value:b;a.title=b.title||a.value;return a}var d=a.type,c=this.getId();a.id=c;var b=a.disabled?" disabled\x3d'true' ":"";switch(d){case "multi":return d="",a.values&&(d="data\x3d'"+dojo.toJson(dojo.map(a.values,function(b){return{value:b}}))+
"'"),"\x3cdiv dojoType\x3d'davinci.ve.widgets.MultiInputDropDown' "+d+"  class\x3d'propertyPaneEditablevalue' style\x3d'display:inline-block; width:100%;' id\x3d'"+c+"'"+b+"\x3e\x3c/div\x3e";case "boolean":return"\x3cinput type\x3d'checkbox' class\x3d'propertyPaneEditablevalue' style\x3d'display:inline-block;margin-left:5px' id\x3d'"+c+"'\x3e\x3c/input\x3e";case "comboEdit":a=a.values;c="\x3cselect dojoType\x3d'dijit.form.ComboBox' autoComplete\x3d'false' style\x3d'display:inline-block; width:100%;' id\x3d'"+
c+"'"+b+"\x3e";for(b=0;b<a.length;b++)d=e(a[b]),c+="\x3coption value\x3d'"+d.value+"'\x3e"+d.title+"\x3c/option\x3e";return c+="\x3c/select\x3e";case "combo":a=a.values;c="\x3cselect style\x3d'display:inline-block; width:100%;' id\x3d'"+c+"'"+b+"\x3e";for(b=0;b<a.length;b++)d=e(a[b]),c+="\x3coption value\x3d'"+d.value+"'\x3e"+d.title+"\x3c/option\x3e";return c+="\x3c/select\x3e";case "font":return c="\x3cdiv dojoType\x3d'davinci.ve.widgets.FontDataStore' jsId\x3d'"+c+"_fontStore'\x3e"+("\x3cdiv dojoType\x3d'davinci.ve.widgets.FontComboBox' value\x3d'"+
q.fonts[0].value+"' store\x3d'"+c+"_fontStore'  id\x3d'"+c+"' class\x3d'propertyPaneEditablevalue' style\x3d'display:inline-block; width:100%;'\x3e\x3c/div\x3e");case "state":return c="\x3cdiv dojoType\x3d'davinci.ve.widgets.MetaDataStore' jsId\x3d'davinci.properties.event"+c+"_Store'\x3e"+("\x3cdiv dojoType\x3d'dijit.form.ComboBox' id\x3d'"+c+"'store\x3d'davinci.properties.event"+c+"_Store' class\x3d'propertyPaneEditablevalue' style\x3d'display:inline-block; width:100%;' autoComplete\x3d'false'\x3e\x3c/div\x3e");
case "color":return"\x3cdiv class\x3d'propertyPaneEditablevalue' dojoType\x3d'davinci.ve.widgets.ColorPicker' id\x3d'"+c+"' \x3e\x3c/div\x3e";case "background":return d=dojo.isArray(a.values)?" data\x3d'"+dojo.toJson(a.values)+"'":"",b=" propname\x3d'"+(dojo.isArray(a.target)?a.target[0]:a.target)+"'",c="\x3cdiv dojoType\x3d'davinci.ve.widgets.Background' id\x3d'"+c+"'"+d+b+(a.colorswatch?" colorswatch\x3d'true'":"")+"\x3e\x3c/div\x3e";case "border":case "number":case "object":case "text":case "array":case "string":if("date"==
a.format)return"\x3cdiv class\x3d'propertyPaneEditablevalue' dojoType\x3d'dijit.form.DateTextBox' id\x3d'"+c+"'\x3e\x3c/input\x3e";if("time"==a.format)return"\x3cdiv class\x3d'propertyPaneEditablevalue' dojoType\x3d'dijit.form.TimeTextBox' id\x3d'"+c+"'\x3e\x3c/input\x3e";default:return"\x3cinput type\x3d'text' class\x3d'propertyPaneEditablevalue' style\x3d'display:inline-block; width:100%;' id\x3d'"+c+"'\x3e\x3c/input\x3e"}},generateTable:function(a,e){var d=e?e.rowsOnly:!1,c=e&&e.zeroSpaceForIncrDecr?
"0px":"20px",b="";if(a.html)return a.id=this.getId(),this.injectId(a.html,a.id);var f;f="\x3ctable class\x3d'property_table_stretchable' border\x3d'0' width\x3d'100%' align\x3d'center' cellspacing\x3d'0' cellpadding\x3d'0'\x3e\x3ccolgroup\x3e\x3ccol style\x3d'width:6px;' /\x3e";f+="\x3ccol class\x3d'gap02' /\x3e";f+="\x3ccol class\x3d'gap03' /\x3e";f+="\x3ccol style\x3d'width:"+c+";' /\x3e";f+="\x3ccol style\x3d'width:6px;' /\x3e";f+="\x3c/colgroup\x3e";d||(b+=f);for(c=0;c<a.length;c++)if(a[c].widgetHtml)a[c].id=
this.getId(),a[c].rowId=this.getId(),b+="\x3ctr id\x3d'"+a[c].rowId+"'",a[c].rowClass&&(b+=" class\x3d'"+a[c].rowClass+"'"),b+="\x3e",b+="\x3ctd colspan\x3d'5' width\x3d'100%'\x3e",b+=this.injectId(a[c].widgetHtml,a[c].id),b+="\x3c/td\x3e",b+="\x3c/tr\x3e";else if(a[c].html)a[c].id=this.getId(),a[c].rowId=this.getId(),b+="\x3ctr id\x3d'"+a[c].rowId+"'",b+=" class\x3d'cssPropertySection",a[c].rowClass&&(b+=" "+a[c].rowClass),b+="'\x3e",b+="\x3ctd colspan\x3d'5' width\x3d'100%'\x3e",b+=a[c].html,b+=
"\x3c/td\x3e",b+="\x3c/tr\x3e";else if("toggleSection"==a[c].type){for(var b=b+("\x3ctr id\x3d'"+a[c].id+"'  class\x3d'cssPropertySection'\x3e\x3ctd colspan\x3d'5'\x3e"),g="",k=this.generateTable(a[c].pageTemplate,{rowsOnly:!0}),h=0;h<a[c].pageTemplate.length;h++)a[c].pageTemplate[h].rowId&&(g+="dojo.toggleClass('"+a[c].pageTemplate[h].rowId+"','propertiesSectionHidden');"),a[c].pageTemplate[h].cascadeSectionRowId&&(g+="if(this.checked){dojo.removeClass('"+a[c].pageTemplate[h].cascadeSectionRowId+
"','propertiesSectionHidden');}else{{dojo.addClass('"+a[c].pageTemplate[h].cascadeSectionRowId+"','propertiesSectionHidden');}}");b+="\x3cinput type\x3d'checkbox' onclick\x3d\""+g+'"\x3e\x3c/input\x3e';b+=a[c].display;b+="\x3c/td\x3e\x3c/tr\x3e";b+=k}else a[c].display?(a[c].toggleCascade=this.getId(),a[c].cascadeSection=this.getId(),a[c].rowId=this.getId(),a[c].cascadeSectionRowId=this.getId(),b+="\x3ctr id\x3d'"+a[c].rowId+"'",b+=" class\x3d'cssPropertySection",a[c].rowClass&&(b+=" "+a[c].rowClass),
b+="'",b+=" propName\x3d'"+a[c].display+"'",b+="\x3e",b+="\x3ctd/\x3e",b+="\x3ctd class\x3d'propertyDisplayName'\x3e"+a[c].display+":\x26nbsp;\x3c/td\x3e",b+="\x3ctd class\x3d'propertyInputField propertyInputField"+a[c].type+"' \x3e"+this.getEditor(a[c])+"\x3c/td\x3e",b+="\x3ctd class\x3d'propertyExtra' nowrap\x3d'true'\x3e",a[c].target&&!a[c].hideCascade&&(b+="\x3cdiv width\x3d'100%'\x3e\x3cbutton class\x3d'showCss propertyButton' id\x3d'"+a[c].toggleCascade+"'",b+=' onClick\x3d"davinci.ve.widgets.HTMLStringUtil.showProperty(',
b+="'"+a[c].rowId+"'",b+=')"\x3e\x26gt;\x3c/button\x3e',b+="\x3c/div\x3e"),b+="\x3ctd/\x3e",b+="\x3c/tr\x3e",a[c].target&&!a[c].hideCascade&&(g="{'cascadeSectionRowId':\""+a[c].cascadeSectionRowId+"\",'toggleCascade':\""+a[c].toggleCascade+'"}',b+="\x3ctr id\x3d'"+a[c].cascadeSectionRowId+"' class\x3d'cssCascadeSection cascadeRowHidden'\x3e",b+="\x3ctd colspan\x3d'5' width\x3d'100%' class\x3d'showCascadeDiv'\x3e\x3cdiv dojoType\x3d'davinci.ve.widgets.Cascade' toggleClasses\x3d"+g+" target\x3d'"+dojo.toJson(a[c].target)+
"' targetField\x3d'\""+a[c].id+"\"' id\x3d'"+a[c].cascadeSection+"'\x3e\x3c/div\x3e\x3c/td\x3e\x3c/tr\x3e")):(b+="\x3c/table\x3e",b+=this.getEditor(a[c]),b+=f);d||(b+="\x3c/table\x3e");return b},generateTemplate:function(a){var e="";a.pageTemplate?(a.key&&(a.id=this.getId(),e="\x3cdiv class\x3d'propGroup' id\x3d'"+a.id+"' propGroup\x3d'"+a.key+"'\x3e"),e+=this.generateTable(a.pageTemplate),e+="\x3c/div\x3e"):a.html?e+=a.html:a.widgetHtml&&(a.id=this.getId(),e+=this.injectId(a.widgetHtml,a.id));return e},
stylesheetHref:"propview.css",animShowSectionClass:"propRootDetailsContainer",animShowSectionClassSelector:".propRootDetailsContainer",animShowDetailsClass:"property_table_stretchable",animShowDetailsClassSelector:".property_table_stretchable",showPropAnimClasses:["propRowFadeIn","propRowFadeOut","propRowTransparent","propRowOpaque","propRowHidden"],showRoot:function(){this._hideSectionShowRoot();this._currentPropSection=null;return!1},showSection:function(a,e){this._initSection(a);return!1},showProperty:function(a){function e(a){dojo.disconnect(p);
dojo.disconnect(q);d();var e=b._findRule(b.animShowDetailsClassSelector);e?(a=e.ss,e=e.ruleIndex,a.deleteRule(e),a.insertRule(b.animShowDetailsClassSelector+" { margin-top:0px; }",e),c()):console.error("HTMLStringUtil showProperty: transEnd: rule not found")}var d=function(){for(var a=0;a<k.children.length;a++){var c=k.children[a];1==c.nodeType&&dojo.hasClass(c,"cssPropertySection")&&(c==g?b._addRemoveClasses(c,f,[]):b._addRemoveClasses(c,f,["propRowHidden"]))}},c=function(){n&&(dojo.removeClass(n,
"cascadeRowHidden"),dojo.addClass(n,"cascadeRowTransparent"),setTimeout(function(){dojo.removeClass(n,"cascadeRowTransparent");dojo.addClass(n,"cascadeRowFadeIn")},1))};dojo.addClass(dojo.byId("davinci_app"),"showingCascade");var b=this,f=this.showPropAnimClasses,g=dojo.byId(a),k=g.parentNode,h=b._searchSiblingsByTagClass(k.children[0],"TR","cssPropertySection"),n=b._searchSiblingsByTagClass(g.nextSibling,"TR","cssCascadeSection");a=b._searchUpByTagClass(k,"TABLE",b.animShowDetailsClass);var l=b._searchUpByTagClass(g,
"DIV","propGroup"),l=dojo.attr(l,"propGroup");dojo.attr(g,"propName");require("davinci/ve/views/SwitchingStyleView").prototype.sectionTitleFromKey(l);if(r.supportsCSS3Transitions){var h=dojo.marginBox(h),h=dojo.marginBox(g).t-h.t,m=b._findRule(b.animShowDetailsClassSelector);if(m){var l=m.ss,m=m.ruleIndex,p=dojo.connect(a,"webkitTransitionEnd",e),q=dojo.connect(a,"transitionend",e);l.deleteRule(m);l.insertRule(b.animShowDetailsClassSelector+" { margin-top:-"+h+"px; opacity:.99; -webkit-transition: all .6s ease; -moz-transition: all .6s ease; }",
m);a=!1;for(h=0;h<k.children.length;h++)l=k.children[h],1==l.nodeType&&dojo.hasClass(l,"cssPropertySection")&&(l==g?(b._addRemoveClasses(l,f,["propRowFadeIn"]),a=!0):a?b._addRemoveClasses(l,f,["propRowHidden"]):b._addRemoveClasses(l,f,["propRowTransparent"]))}else console.error("HTMLStringUtil showProperty: transEnd: rule not found")}else d(),c()},_initSection:function(a){for(var e=this.showPropAnimClasses,d=this._getRootTD(),c=dojo.query(".propGroup",d),b,d=0;d<c.length;d++){var f=c[d];dojo.attr(f,
"propGroup")==a?(dojo.removeClass(f,"dijitHidden"),b=f):dojo.addClass(f,"dijitHidden")}c=dojo.query(".cssPropertySection",b);for(d=0;d<c.length;d++)this._addRemoveClasses(c[d],e,[]);e=dojo.query(".cssCascadeSection",b);for(d=0;d<e.length;d++)dojo.addClass(e[d],"cascadeRowHidden");this._currentPropSection=a;dojo.removeClass(dojo.byId("davinci_app"),"showingCascade")},_hideSectionShowRoot:function(){var a=this._getRootTD();dojo.removeClass(a,"dijitHidden")},_findRule:function(a){function e(a,c){for(var d=
0;d<a.cssRules.length;d++){var k=a.cssRules[d];if(3===k.type){if(k=e(k.styleSheet,c))return k}else if(k.selectorText==c)return{ss:a,ruleIndex:d}}}if(this.animSS&&"number"==typeof this.animRuleIndex[a]){var d=this.animRuleIndex[a];if(this.animSS.cssRules[d].selectorText==a)return{ss:this.animSS,ruleIndex:d}}for(d=0;d<document.styleSheets.length;d++){var c=e(document.styleSheets[d],a);if(c)return this.animSS=c.ss,this.animRuleIndex[a]=c.ruleIndex,c}return null},_addRemoveClasses:function(a,e,d){for(var c=
[],b=0;b<e.length;b++){for(var f=!1,g=0;g<d.length;g++)if(e[b]==d[g]){f=!0;break}f||c.push(e[b])}for(b=0;b<c.length;b++)dojo.removeClass(a,c[b]);for(b=0;b<d.length;b++)dojo.addClass(a,d[b])},_searchUpByTagClass:function(a,e,d){for(;null!=a&&"BODY"!=a.nodeName;){if(a.nodeName==e&&(!d||dojo.hasClass(a,d)))return a;a=a.parentNode}return null},_searchSiblingsByTagClass:function(a,e,d){for(;null!=a;){if(a.nodeName==e&&(!d||dojo.hasClass(a,d)))return a;a=a.nextSibling}return null},_getRootDetailsContainer:function(){this._rootDetailsContainer||
(this._rootDetailsContainer=dojo.query(this.animShowSectionClassSelector)[0]);return this._rootDetailsContainer},_getRootTD:function(){var a=this._getRootDetailsContainer();this._rootTD||(this._rootTD=dojo.query(".propPaletteRoot",a)[0]);return this._rootTD}});return p});
//# sourceMappingURL=HTMLStringUtil.js.map