//>>built
define("davinci/ve/widgets/MultiInputDropDown","dojo/_base/declare dijit/_WidgetBase davinci/ve/widgets/MutableStore dijit/form/ComboBox dojo/i18n!davinci/ve/nls/ve dojo/i18n!dijit/nls/common".split(" "),function(h,k,l,m,n,p){var c=h("davinci.ve.widgets.MultiInputDropDown",[k],{numberDelta:1,insertPosition:1,data:null,postCreate:function(){this.domNode.removeAttribute("data-dojo-type");this.domNode.removeAttribute("dojoType");var a=dojo.doc.createElement("div");this._run={};this.data?(this.data.push({value:c.divider}),
this.data.push({value:"Remove Value",run:function(){this.set("value","")}})):this.data=[{value:""},{value:"auto"},{value:"0px"},{value:c.divider},{value:"Remove Value",run:function(){this.set("value","")}},{value:c.divider},{value:"Help",run:function(){alert("help!")}}];for(var b=[],d=0;d<this.data.length;d++)b.push(this.data[d].value),this.data[d].run&&(this._run[this.data[d].value]=this.data[d].run);this._store=new l({values:b,divider:c.divider});this._dropDown=new m({store:this._store,required:!1,
style:"width:100%"});b=dojo.doc.createElement("div");dojo.style(b,"float","right");this._plus=dojo.doc.createElement("button");dojo.addClass(this._plus,"incrementButton");dojo.addClass(this._plus,"propertyButton");b.appendChild(this._plus);this._minus=dojo.doc.createElement("button");dojo.addClass(this._minus,"decrementButton");dojo.addClass(this._minus,"propertyButton");b.appendChild(this._minus);a.appendChild(b);b=dojo.create("div",{"class":"propInputWithIncrDecrButtons"});b.appendChild(this._dropDown.domNode);
a.appendChild(b);b=dojo.doc.createElement("div");dojo.style(b,"clear","both");a.appendChild(b);this._currentValue=this._store.getItemNumber(0);dojo.connect(this._dropDown,"onKeyUp",this,"_updateSpinner");dojo.connect(this._dropDown,"onChange",this,"_onChange");dojo.connect(this._plus,"onclick",this,"_plusButton",!1);dojo.connect(this._minus,"onclick",this,"_minusButton",!1);this._updateSpinner();this.domNode.appendChild(a)},_setReadOnlyAttr:function(a){this._isReadOnly=a;this._dropDown.set("disabled",
a);dojo.attr(this._plus,"disabled",a);dojo.attr(this._minus,"disabled",a)},onChange:function(a){},_getValueAttr:function(){return this._dropDown.get("value")},_setValueAttr:function(a,b){this._dropDown.set("value",a,!0);this._currentValue=this._dropDown.get("value");this._onChange(this._currentValue);if(!b)this.onChange()},_changeValue:function(a,b){for(var d=a.split(" "),e="",c=0;c<d.length;c++){0<c&&(e+=" ");var f=d[c].match(/([-\d\.]+)([a-zA-Z%]*)/);if(f)if(1==f.length)e+=f[0];else for(var g=1;g<
f.length;g++)e=!isNaN(f[g])&&""!=f[g]?e+(parseFloat(f[g])+b):e+f[g];else e+=d[c]}return e},_plusButton:function(){var a=this._dropDown.get("value"),b=this._changeValue(a,this.numberDelta);this._store.modifyItem(a,b);this._dropDown.set("value",b)},_minusButton:function(){var a=this._dropDown.get("value"),b=this._changeValue(a,-1*this.numberDelta);this._store.modifyItem(a,b);this._dropDown.set("value",b)},_updateSpinner:function(){var a=this._dropDown.get("value"),a=/(-?)(\d+){1}/.exec(a);this._minus.disabled=
a&&a.length?this._plus.disabled=!1:this._plus.disabled=!0;return!0},_onChange:function(a){var b;a in this._run?(this._dropDown.get("value",this._store.getItemNumber(0)),dojo.hitch(this,this._run[a])()):a==c.divider?this._dropDown.get("value",this._store.getItemNumber(0)):(b=this._store.findSimilar(a))?this._store.modifyItem(b,a):this._store.contains(a)||this._store.insert(this.insertPosition,a);this._currentValue!=this._dropDown.get("value")&&(this._currentValue=this._dropDown.get("value"),this.onChange(a));
this._updateSpinner()}});return dojo.mixin(c,{divider:"---"})});
//# sourceMappingURL=MultiInputDropDown.js.map