//>>built
define("davinci/ve/widgets/WidgetProperties","dojo/_base/declare dojo/_base/connect davinci/workbench/ViewLite davinci/ve/metadata davinci/commands/CompoundCommand davinci/ve/commands/ModifyCommand ./HTMLStringUtil dijit/form/DateTextBox dijit/form/TimeTextBox xide/types xide/factory".split(" "),function(l,h,n,p,q,r,s,t,u,v,w){return l("davinci.ve.widgets.WidgetProperties",[n],{key:"widgetSpecific",_connects:null,buildRendering:function(){this.domNode=this.propDom=dojo.doc.createElement("div");dojo.addClass(this.domNode,
"propGroup");dojo.attr(this.domNode,"propGroup",this.key);this._connects=[];this.inherited(arguments)},onWidgetSelectionChange:function(){if(!this._widget||!this._editor||"davinci.ve.HTMLPageEditor"!=this._editor.editorID)this._disconnectAll(),this._destroyProperties();else{var b=davinci.ve.metadata.query(this._widget),c=this._widget.getParent();if(c&&c.isWidget&&(c=p.query(c))&&c.childProperties)if(b.$ownproperty)for(var a in c.childProperties)b.$ownproperty[a]=c.childProperties[a];else b.$ownproperty=
c.childProperties;if(b&&b.$ownproperty){this._disconnectAll();this._destroyProperties();c={};b.$ownproperty.title||(c.title={datatype:"string"});for(a in b.$ownproperty)c[a]=b.$ownproperty[a];b=this.propDom.innerHTML=this._createWidgetRows(c);(-1!==b.indexOf("data-dojo-type")||-1!==b.indexOf("dojoType"))&&dojo.parser.parse(this.propDom);this._setValues();this._connectAll()}}},onEditorSelected:function(b){if((this._editor=b)&&"davinci.ve.HTMLPageEditor"==b.editorID){if(this.context=b.getContext())this._widget=
this.context.getSelection()[0]}else this._widget=this.context=null;this.onWidgetSelectionChange()},_createWidgetRows:function(b){this._pageLayout=[];for(var c in b){var a=b[c];if(!a.hidden){var g={display:a.title||c,type:a.datatype,format:a.format,target:c,hideCascade:!0,data:a};if(a.dropdownQueryValues&&a.dropdownQueryAttribute){var f=[];dojo.forEach(a.dropdownQueryValues,dojo.hitch(this,function(b){b=dojo.query(b,this.context.rootNode);dojo.forEach(b,function(b){f.push(b.getAttribute(a.dropdownQueryAttribute))})}));
g.values=f;g.type="comboEdit"}if(dojo.isArray(a.mustHaveAncestor)){for(var e=!1,d=this._widget;!e&&d&&d.getParent()!=this.context.rootWidget;)(d=d.getParent())&&-1<dojo.indexOf(a.mustHaveAncestor,d.type)&&(e=!0);e||(g.disabled=!0)}this._pageLayout.push(g);a.option&&(this._pageLayout[this._pageLayout.length-1].values=dojo.map(a.option,function(a){return a}),this._pageLayout[this._pageLayout.length-1].type=a.unconstrained?"comboEdit":"combo")}}return s.generateTable(this._pageLayout)},_destroyProperties:function(){var b=
this.propDom;for(dojo.forEach(dojo.query("[widgetId]",b).map(dijit.byNode),function(b){b.destroy()});b.firstChild;)dojo._destroyElement(b.firstChild)},_connectAll:function(){function b(a){return function(){return this._onChange({target:a})}}for(var c=0,a=this._pageLayout.length;c<a;c++){var g=this._pageLayout[c],f=dijit.byId(g.id),e=f||dojo.byId(g.id),d=f?"onFocus":"focus",k=f?"onBlur":"blur";this._connect(e,f?"onChange":"change",this,b(c));this._connect(e,d,this,"_onFieldFocus");this._connect(e,
k,this,"_onFieldBlur");e.owner=this;e.row=c;w.publish(v.EVENTS.WIDGET_PROPERTY_RENDERED,{view:this,row:g,widget:f,node:e},this)}},_connect:function(b,c,a,g,f){this._connects.push(h.connect.apply(null,arguments))},_disconnectAll:function(){this._connects.forEach(h.disconnect);this._connects=[]},_onChange:function(b){b=this._pageLayout[b.target];var c=dijit.byId(b.id),a;this.context&&this.context.blockChange(!1);c?(a=c.get("value"))&&a instanceof Date&&(c instanceof t?a=a.toISOString().substring(0,
10):c instanceof u&&(a="T"+a.toTimeString().substring(0,8))):(a=dojo.byId(b.id),a=dojo.attr(a,"checkbox"===a.type?"checked":"value"));if(b.value!=a){b.value=a;c={};c[b.target]=a;b=new q;a=new r(this._widget,c,null);b.add(a);if((c=this._widget.getHelper())&&c.onWidgetPropertyChange)c.onWidgetPropertyChange({widget:this._widget,compoundCommand:b,modifyCommand:a});dojo.publish("/davinci/ui/widgetPropertiesChanges",[{source:this._editor.editor_id,compoundCommand:b,command:a}])}},_onFieldFocus:function(){this.context&&
this.context.blockChange(!0)},_onFieldBlur:function(){this.context&&this.context.blockChange(!1)},_setValues:function(){try{for(var b=0,c=this._pageLayout.length;b<c;b++){var a=this._pageLayout[b],g=dojo.byId(a.id);if(g){var f=this._widget,e=a.target,d;d="_children"===e?(d=f.getChildrenData())&&1===d.length?d[0]:f.getPropertyValue(e):f.getPropertyValue(e);if(d&&d.toISOString){var k=f.metadata.property[e].format;k&&("date"==k?d=d.toISOString().substring(0,10):"time"==k&&(d="T"+d.toTimeString().substring(0,
8)))}if(a.value!=d){a.value=d;var h="boolean"===a.type?"checked":"value",m=dijit.byId(a.id);m?m.attr(h,a.value):dojo.attr(g,h,a.value)}}}}catch(l){debugger}}})});
//# sourceMappingURL=WidgetProperties.js.map