//>>built
define("davinci/ve/themeEditor/metadata/CSSThemeProvider",["dojo/_base/declare","../../utils/pseudoClass"],function(r,q){return r("davinci.ve.themeEditor.metadata.CSSThemeProvider",null,{module:"davinci.lib",path:"theme/tundra.json",constructor:function(a,c){this._theme=c;this.url=encodeURI(a[0].getURL());this.getWidgets()},getWidgets:function(){if(!this._widgets){var a=void 0;dojo.xhrGet({url:""+this.url,handleAs:"json",sync:!0,load:function(c){a=c}});this._widgets=a;this._createDefaults()}return this._widgets},
_createDefaults:function(){for(var a in this._widgets){var c=this._widgets[a],b;for(b in c){var e=c[b],d;for(d in e.states)this.getStyleSelectors(a+"."+b,d);for(var f in e.subwidgets){var h=e.subwidgets[f];for(d in h.states)this.getStyleSelectors(a+"."+b,d,f)}}}},getRelativeStyleSelectorsText:function(a,c,b,e,d){var f=this.getStyleSelectors(a,c,b),h=[];for(s in f)e.forEach(function(a){for(var b=!1,c=0;!b&&c<f[s].length;c++)if(f[s][c]==a||"$std_10"==f[s][c])b=!0;if(b){var e=""+s;a=e.split(" ");e="";
a.forEach(function(a){a!="."+d&&(e+=" "+a)}.bind(this));h.push(e.replace(/^\s*/,"").replace(/\s*$/,""))}}.bind(this));return h},getStyleSelectors:function(a,c,b){if(a){c||(c="Normal");var e,d=a.split(/[\.\/]/);a=d[0];d=d[d.length-1];if(b&&a in this._widgets&&d in this._widgets[a]){b=b.id?b.id:b;if(!this._widgets[a][d].subwidgets[""+b].states[""+c])return null;e=this._widgets[a][d].subwidgets[""+b].states[""+c].selectors;if(!e||"$auto"==e)e=this._createDefaultSelectors(""+a+b,c),this._widgets[a][d].subwidgets[""+
b].states[""+c].selectors=e}else if(this._widgets&&(a in this._widgets&&d in this._widgets[a])&&this._widgets[a][d].states[""+c]&&(e=this._widgets[a][d].states[""+c].selectors,!e||"$auto"==e))e=this._createDefaultSelectors(""+a+d,c),this._widgets[a][d].states[""+c].selectors=e;return e}},getElementStyleProperties:function(a,c,b){if(a){c||(c="Normal");var e,d=a.split(/[\.\/]/);a=d[0];d=d[d.length-1];if(b&&a in this._widgets&&d in this._widgets[a]){b=b.id?b.id:b;if(!this._widgets[a][d].subwidgets[""+
b].states[""+c]||!this._widgets[a][d].subwidgets[""+b].states[""+c].element||!this._widgets[a][d].subwidgets[""+b].states[""+c].element.style)return null;e=this._widgets[a][d].subwidgets[""+b].states[""+c].element.style}else this._widgets&&(a in this._widgets&&d in this._widgets[a])&&(this._widgets[a][d].states[""+c]&&this._widgets[a][d].states[""+c].element&&this._widgets[a][d].states[""+c].element.style)&&(e=this._widgets[a][d].states[""+c].element.style);return e}},_createDefaultSelectors:function(a,
c){var b={};b["Normal"==c?"."+this._theme.className+" ."+a:"."+this._theme.className+" ."+a+c]=["$std_10"];return b},_createDefaultQuery:function(a,c){return"."+a},_simulateState:function(a,c,b,e){for(var d=a instanceof Array?a:[a],f=c instanceof Array?c:[c],h=0;h<f.length;h++){var g=f[h],k=d[h],m,l,n;if(-1<(m=g.indexOf(":")))l=g.substring(m+1),g=g.substring(0,m),m=l.indexOf("\x3d"),-1<m?(n=l.substring(m+1),l=l.substring(0,m)):n=l;k=dojo.query(k,e.domNode)[0];k||(k=e.domNode);try{"add"==b?(l&&k.setAttribute(l,
n),g&&dojo.addClass(k,g)):(l&&k.removeAttribute(l),g&&dojo.removeClass(k,g))}catch(p){console.error("CSSThemeProvider._simulateState invalid simulate in metadata for "+e.type+" "+a+": "+c)}}},_updateStyle:function(a,c,b,e){if("all"!==a.id){var d=!1;b||(b="Normal",d=!0);if(!this._widgets)return null;c||(c=a.type);var f=c.split(/[\.\/]/),h=f[0],g=f[f.length-1],f=this._widgets[h][g];"Normal"===b&&(!0==d&&"remove"===e&&this._widgets[h][g].startState)&&(b=this._widgets[h][g].startState);if(this._widgets[h][g].states[""+
b]){var k=this._widgets[h][g].states[""+b].query;if(!k||"$auto"==k)k=this._createDefaultQuery(h+g,b),f.states[""+b].query=k;g=this._widgets[h][g].states[""+b].simulate;if(!g){var g=" ",m=this.getStyleSelectors(c,b),l="",n;for(n in m)l=q.replace(n),l=l.replace(/\./g," "),l=l.replace(this._theme.className,""),g+=" "+l;"Normal"!=b&&(g=h+b+" "+g)}"Normal"!=b&&(g+=" "+q.MAQETTA_PSEUDO_CLASS+b,this._simulateState(k,g,e,a))}for(var p in f.subwidgets)if(m=f.subwidgets[p],"Normal"===b&&(!0==d&&"remove"===
e&&m.startState)&&(b=m.startState),m.states[""+b]){k=m.states[""+b].query;g=m.states[""+b].simulate;if(!k||"$auto"==k)k=this._createDefaultQuery(h+p,b),m.states[""+b].query=k;if(!g){m=this.getStyleSelectors(c,b,p);g=" ";for(n in m)l=q.replace(n).replace(/\./g," ").replace(this._theme.className,""),g+=" "+l;"Normal"!=b&&(g=h+b+" "+g)}"Normal"!=b&&this._simulateState(k,g,e,a)}}},setStyleValues:function(a,c,b,e){this._updateStyle(a,c,b,"add")},removeStyleValues:function(a,c,b,e){b&&"Normal"!=b&&this._updateStyle(a,
c,b,"remove")},setWidgetStyleValues:function(a,c){davinci.ve.widget.getWidget(a);this._updateStyle(a,null,c,"add")},removeWidgetStyleValues:function(a,c){this._updateStyle(a,null,c,"remove")},getDomNode:function(a,c,b,e){if(!this._widgets)return null;e||(e="Normal");var d=c.split(/[\.\/]/);c=d[0];var d=d[d.length-1],f;try{if(b){if(f=this._widgets[c][d].subwidgets[""+b].states[""+e].query,!f||"$auto"==f)f=this._createDefaultQuery(c+b,e),this._widgets[c][d].subwidgets[""+b].states[""+e].query=f}else if(f=
this._widgets[c][d].states[""+e].query,!f||"$auto"==f)f=this._createDefaultQuery(c+d,e),this._widgets[c][d].states[""+e].query=f}catch(h){return null}(d=dojo.query(f instanceof Array?f[0]:f,a)[0])||(d=a);return d},getMetadata:function(a){if(a){var c=a.split(/[\.\/]/);a=c[0];c=c[c.length-1];return this._widgets&&this._widgets[a]&&this._widgets[a][c]}},getWidgetType:function(a){var c;c=a.type;a=a.id;0===a.indexOf("all")&&(c=c+".$"+a);return c},isPropertyVaildForWidgetRule:function(a,c,b,e,d){b=this.getWidgetType(b);
b=this.getMetadata(b);e&&(b=b.subwidgets[e]);b=d?b.states[d]:b.states.Normal;a=a.getSelectorText();for(var f in b.selectors)if(e=b.selectors[f],a==f)for(d=0;d<e.length;d++){var h=e[d];if("$std_10"==h||h==c)return!0}return!1},isPropertyRuleValid:function(a,c,b){a=a.getSelectorText();for(var e in b.states){var d=b.states[e],f;for(f in d.selectors){var h=d.selectors[f];if(a==f)for(var g=0;g<h.length;g++){var k=h[g];if("$std_10"==k||k==c)return!0}}}for(var m in b.subwidgets){var l=b.subwidgets[m];for(e in l.states)for(f in d=
l.states[e],d.selectors)if(h=d.selectors[f],a==f)for(g=0;g<h.length;g++)if(k=h[g],"$std_10"==k||k==c)return!0}return!1},isPropertyValidForRule:function(a,c){a.getSelectorText();for(var b in this._widgets){var e=this._widgets[b],d;for(d in e)if(this.isPropertyRuleValid(a,c,e[d]))return!0}return!1},getStatesForAllWidgets:function(){if(!this._widgets)return null;states=[];for(var a in this._widgets){var c=this._widgets[a],b;for(b in c)if(0!=b.indexOf("$all")){var e=c[b],d;for(d in e.states)states[d]=
d;for(var f in e.subwidgets){var h=e.subwidgets[f];for(d in h.states)states[d]=d}}}retStates=[];for(var g in states)retStates.push(g);return retStates.sort()},isStateValid:function(a,c,b){if(!this._widgets||"all"===a.id&&"Normal"!=c)return!1;a=this.getMetadata(a.type);if(a.states[c]&&!b)return!0;if(b){if((b=a.subwidgets[b])&&b.states[c])return!0}else for(var e in a.subwidgets)if(b=a.subwidgets[e],b.states[c])return!0;return!1}})});
//# sourceMappingURL=CSSThemeProvider.js.map