//>>built
define("davinci/model/resource/Folder",["dojo/_base/declare","dojo/_base/xhr","davinci/Runtime","davinci/model/resource/Resource","davinci/model/resource/File"],function(k,n,l,m,h){var f=k(m,{serviceClass:"XIDE_Directory_Service",workspaceMount:"/ws/",constructor:function(b,d){this.elementType="Folder";this.name=b;this.parent=d},reload:function(){this._isLoaded=!1},createResource:function(b,d,a,e){var c;null!=b?c=d?new f(b,this):new h(b,this):(c=this,d="Folder"==this.elementType);var g=this;if(!a){a=
""+this.getPath();"."==a&&(a=""+this.workspaceMount);a=a.replace("./",this.workspaceMount);a=this.serviceClass;d=d?"mkDir":"mkFile";if(!this.serviceObject[a][d])return console.error("_createResource : server doesnt support :"+d),this;this.serviceObject[a][d](this.workspaceMount,c.getPath()).then(function(a){if(!0===a&&null!=b||"The file already exists"===a)return g.children.push(c),delete c.libraryId,delete c.libVersion,delete c._readOnly,dojo.publish("/davinci/resource/resourceChanged",["created",
c]),e&&e(c),c;if("OK"!=a)throw"Folder.createResource failed: name\x3d"+b+"response\x3d"+a;delete c.libraryId;delete c.libVersion;delete c._readOnly;e(g);if(!e)debugger})}},getChildren2:function(b,d){if(this._isLoaded)b(this.children);else if(this._loadingCallbacks)this._loadingCallbacks.push(b);else{this._loadingCallbacks=[];this._loadingCallbacks.push(b);var a=""+this.getPath();"."==a&&(a="/ws/");var e=this.serviceClass;if(!this.serviceObject)debugger;if(!this.serviceObject[e])debugger;this.serviceObject.sync=
!0;this.serviceObject[e].ls(this.workspaceMount,a).then(function(a){this.setChildrenSync(a);dojo.forEach(this._loadingCallbacks,function(a){a(this.children)},this);delete this._loadingCallbacks}.bind(this),d)}},getChildren:function(b,d){if(this._isLoaded)b.call(null,this.children);else if(this._loading)this._loading.then(function(){b.call(null,this.children)}.bind(this),d);else{console.error("list files : "+this.getPath());var a=""+this.getPath();"."==a&&(a="/ws/");a=a.replace("./",this.workspaceMount);
this.serviceObject[this.serviceClass].ls(a).then(function(a){this.setChildren(a);this._isLoaded=!0;b.call(null,this.children);delete this._loading}.bind(this),d)}},getChildrenSync:function(b,d){if(this._isLoaded)b(this.children);else if(this._loadingCallbacks)this._loadingCallbacks.push(b);else{this._loadingCallbacks=[];this._loadingCallbacks.push(b);console.error("list files : "+this.getPath());var a=this.getPath();"./project1"===a&&console.error("gotcha");a=""+a;"."==a&&(a="/ws/");a=a.replace("./",
"/ws/");l.serverJSONRequest({url:"cmd/listFiles.php",content:{path:this.getPath(),basePath:"./"},sync:d,load:dojo.hitch(this,function(a,b){this.setChildrenSync(a);dojo.forEach(this._loadingCallbacks,function(a){a(this.children)},this);delete this._loadingCallbacks})})}},setChildren:function(b){this.children=[];this._appendFiles(b)},setChildrenSync:function(b){this.children=[];this._appendFiles(b,!0)},_appendFiles:function(b,d){b.forEach(function(a){var b=d?this.getChildSync(a.name):this._getChild(a.name),
c=null!=b;a.isDir||a.isLib?(c||(b=new f(a.name,this)),a.isLib&&(b.isLibrary=!0)):c||(b=new h(a.name,this));b.link=a.link;b.isNew=a.isNew;b._readOnly=a.readOnly;b.setDirty(a.isDirty);a.libraryId&&(b.libraryId=a.libraryId,b.libVersion=a.libVersion);c||this.children.push(b)},this);this._isLoaded=!0},getMarkers:function(b,d){var a=[];this.visit({visit:function(e){if("File"==e.elementType)markers=e.getMarkers(b),a.concat(markers);else if(!d)return!0}},!0);return a},getChildSync:function(b){if(!this._isLoaded||
1>this.children.length)this._isLoaded=!1,this.getChildrenSync(function(b){this.children=b},!0);return this._getChild(b)},getChild:function(b){if(!this._isLoaded||1>this.children.length)this._isLoaded=!1,this.getChildren2(function(b){this.children=b},!0);return this._getChild(b)},_getChild:function(b){if(!this.__CASE_SENSITIVE){if(!b||null==b.toLowerCase)debugger;b=b.toLowerCase()}var d;this.children.some(function(a){var e=a.getName();this.__CASE_SENSITIVE||(e=e.toLowerCase());(e=e==b)&&(d=a);return e});
return d}});davinci.model.resource.root=new f(".",null,!0);return f});
//# sourceMappingURL=Folder.js.map