//>>built
define("davinci/ve/themeEditor/Context","dojo/_base/declare dojo/Deferred ../../commands/CommandStack ../widget ./SelectTool ../Context ../../library ../metadata".split(" "),function(f,g,h,n,k,l,m,p){return f("davinci.ve.ThemeEditor.Context",[l],{_bootstrapModules:"dijit/dijit,dijit/dijit-all",constructor:function(a){this._id="_edit_context_"+this._contextCount++;dojo.mixin(this,a);dojo.isString(this.containerNode)&&(this.containerNode=dijit.byId(this.containerNode));this._commandStack=h(this);this._defaultTool=
new k;this._widgetIds=[];this._objectIds=[];this._widgets=[];this._selectionCssRules=[]},_setSourceData:function(a){var c=[this.getDijit()._WidgetBase,this.getDijit()._TemplatedMixin];this.getDojo().declare("dijit.davinci.themeEditor.Dialog",c,{buttonCancel:"cancel",onCancel:function(){},title:"title",templateString:dojo.cache("dijit","templates/Dialog.html",'\x3cdiv class\x3d"dijitDialog" role\x3d"dialog" aria-labelledby\x3d"${id}_title"\x3e\n\t\x3cdiv data-dojo-attach-point\x3d"titleBar" class\x3d"dijitDialogTitleBar"\x3e\n\t\t\x3cspan data-dojo-attach-point\x3d"titleNode" class\x3d"dijitDialogTitle" id\x3d"${id}_title"\n\t\t\t\trole\x3d"heading" level\x3d"1"\x3e\x3c/span\x3e\n\t\t\x3cspan data-dojo-attach-point\x3d"closeButtonNode" class\x3d"dijitDialogCloseIcon" data-dojo-attach-event\x3d"ondijitclick: onCancel" title\x3d"${buttonCancel}" role\x3d"button" tabIndex\x3d"-1"\x3e\n\t\t\t\x3cspan data-dojo-attach-point\x3d"closeText" class\x3d"closeText" title\x3d"${buttonCancel}"\x3ex\x3c/span\x3e\n\t\t\x3c/span\x3e\n\t\x3c/div\x3e\n\t\x3cdiv data-dojo-attach-point\x3d"containerNode" class\x3d"dijitDialogPaneContent"\x3e\x3c/div\x3e\n\x3c/div\x3e\n'),
attributeMap:dojo.delegate(dijit._Widget.prototype.attributeMap,{title:[{node:"titleNode",type:"innerHTML"},{node:"titleBar",type:"attribute"}],"aria-describedby":""}),_setTitleAttr:[{node:"titleNode",type:"innerHTML"},{node:"titleBar",type:"attribute"}]});this.getDojo().declare("dijit.davinci.themeEditor.Tooltip",c,{templateString:dojo.cache("dijit","templates/Tooltip.html",'\x3cdiv class\x3d"dijitTooltip dijitTooltipLeft" id\x3d"dojoTooltip"\n\t\x3e\x3cdiv class\x3d"dijitTooltipContainer dijitTooltipContents" data-dojo-attach-point\x3d"containerNode" role\x3d\'alert\'\x3e\x3c/div\n\t\x3e\x3cdiv class\x3d"dijitTooltipConnector" data-dojo-attach-point\x3d"connectorNode"\x3e\x3c/div\n\x3e\x3c/div\x3e\n')});
this.setHeader({title:a.title,metas:a.metas,scripts:a.scripts,modules:a.modules,styleSheets:a.styleSheets,theme:a.theme,bodyClasses:a.bodyClasses,style:a.style});content=a.content||"";var b=this.getContainerNode();if(a=this.isActive())this.select(null),dojo.forEach(this.getTopWidgets(),this.detach,this);var d=new g;dojo.forEach(this.getTopWidgets(),function(a){a.getContext()&&a.destroyWidget()});b.innerHTML=content;dojo.forEach(dojo.query("*",b),function(a){a=(a=a.getAttribute("data-dojo-type")||
a.getAttribute("dojoType")||a.getAttribute("dvwidget"))&&a.replace(/\./g,"/");this.loadRequires(a,!1,!0)},this);this.getGlobal().require("dojo/ready")(function(){try{this.getGlobal().require("dojo/parser").parse(b),d.resolve()}catch(a){throw this.getDijit().registry.forEach(function(a){a.destroy()}),this._editorSelectConnection=dojo.subscribe("/davinci/ui/editorSelected",dojo.hitch(this,this._editorSelectionChange)),d.reject(),a;}}.bind(this));a&&dojo.query("\x3e *",this.rootNode).map(davinci.ve.widget.getWidget).forEach(this.attach,
this);dojo.query(".dvThemeWidget").forEach(this.theme.removeWidgetStyleValues);return d},attach:function(a){this.inherited(arguments);if(a&&!a.internal&&a._srcElement){var c=!1,b=a.getClassNames();b&&-1<b.indexOf("dvThemeWidget")&&(c=!0);a.dvAttributes={isThemeWidget:c};c&&-1===this._widgets.indexOf(a)&&this._widgets.push(a)}},getThemeMeta:function(){this._themeMetaCache||(this._themeMetaCache=m.getThemeMetadata(this.theme));return this._themeMetaCache},select:function(a,c){if(!a||a==this.rootWidget)this._selectedWidget=
null,c||this.deselect();else{this._selectedWidget=a;var b=void 0,d=void 0;c&&this._selection?(d=this._selection.length,b=this._selection,b.push(a)):b=[a];var e=!1;if(!this._selection||1<this._selection.length||1<b.length||b[0]!=this._selection[0])this._selection=b,e=!0;this.updateFocus(a,d);if(e)this.onSelectionChange(this.getSelection())}},onSelectionChange:function(a){this._forceSelectionChange||(this.visualEditor._themeEditor._selectedSubWidget=null);this.inherited(arguments)},getStyleAttributeValues:function(a){return[]},
_restoreStates:function(){},_configDojoxMobile:function(){try{var a=this.getGlobal().require,c=a("dojox/mobile"),b=a("dojox/mobile/deviceTheme"),d=this.getGlobal().dojo.config,e;e=RegExp("");b.themeMap=[[".*","",[]]];d.mblThemeFiles=[];d.mblLoadCompatPattern=e;c.loadCompatPattern=e;b.loadDeviceTheme("none")}catch(f){}},getPath:function(){var a=this.theme.getFile().getPath(),a=a.substring(0,a.lastIndexOf("/"));return a=a+"/"+this.theme.themeEditorHtmls[0]},getFullResourcePath:function(){return this.visualEditor.basePath},
widgetAddedOrDeleted:function(){}})});
//# sourceMappingURL=Context.js.map