//>>built
define("davinci/ve/themeEditor/ThemeEditor","dojo/_base/declare ../../ui/ModelEditor ./VisualThemeEditor ./metadata/query ./metadata/CSSThemeProvider ./commands/ThemeEditorCommand ./commands/SubwidgetChangeCommand ./commands/StateChangeCommand dijit/layout/ContentPane ../../commands/CompoundCommand ./ThemeColor system/resource ../../model/Path ../../Theme dojo/promise/all dojo/i18n!../nls/ve dojox/widget/Toaster".split(" "),function(t,u,w,x,y,r,z,A,B,s,C,D,E,F,G,H,I){return t("davinci.ve.themeEditor.ThemeEditor",
[u],{children:[],visualEditor:null,_currentState:"Normal",_dirtyResource:{},_subWidgetSelection:null,_theme:null,_tempRules:{},_subscriptions:[],__DEBUG_TO_CONSOLE:!1,_shortHands:"border padding margin background font list-style".split(" "),constructor:function(b){this.inherited(arguments);var c=this;this.editorContainer=dijit.getEnclosingWidget(b);this._cp=new B({},b);this.domNode=this._cp.domNode;this.domNode.className="ThemeEditor fullPane";this._loadedCSSConnects=[];this.subscribe("/davinci/ui/editorSelected",
this._editorSelected.bind(this));this.subscribe("/davinci/ui/context/loaded",this._contextLoaded.bind(this));this.editorContainer.connect(this.editorContainer,"resize",function(b){if((b=dojo.query("iframe",this.domNode)[0])&&b.contentDocument&&b.contentDocument.body)setTimeout(function(){var b=this.getContext();b.clearCachedWidgetBounds();b.updateFocusAll()}.bind(this),100),c._registerScrollHandler()}.bind(this))},_editorSelected:function(b){var c=this.getContext();this==b.oldEditor&&c.hideFocusAll();
b.editor&&b.editor.editorContainer&&("davinci.ve.PageEditor"==b.editor.declaredClass||"davinci.ve.themeEditor.ThemeEditor"==b.editor.declaredClass)&&this==b.editor&&this._registerScrollHandler()},onResize:function(){var b=this.getContext(),c=this.getSelectedWidget();b.select(c,!1)},getSelectionProperties:function(b){if(!this._selectedWidget)return[{editor:this,widget:null,subwidget:null,cssValues:null,computedCssValues:null,appliesTo:["theme"],context:this.context}];b=this._getSelectionStyleValues();
var c;c=this._getCssRules();this._rebaseCssRuleImagesForStylePalette(c,b);c=this._theme.getDomNode(this._selectedWidget.domNode,this._selectedWidget.type,this._selectedSubWidget);c=dojo.getComputedStyle(c);return{editor:this,widget:this._selectedWidget,subwidget:this._selectedSubWidget,cssValues:b,computedCssValues:c,appliesTo:["theme"],context:this.context}},_widgetStateChanged:function(b){if(this.isActiveEditor()&&b&&!(b.origin&&-1<b.origin.indexOf("davinci.ve.themeEditor.commands."))){var c=b.widget;
c&&c.processingUndoRedo?delete c.processingUndoRedo:this.getContext().getCommandStack().execute(new A({_themeEditor:this,_widget:c,_newState:b.newState,_oldState:b.oldState,_firstRun:!0}))}},selectSubwidget:function(b,c){if(b&&c&&"WidgetOuterContainer"!=c){var e=this._theme.getWidgetType(b),e=this._theme.getDomNode(b.domNode,e,c),d=this.getRelativeBox(e),f=this.getContext().getDocument().createElement("div");f.className="editSubwidgetFocusFrame";f.id="editSubwidgetFocusFrame";f.style.position="absolute";
f.style.width=e.offsetWidth+4+"px";f.style.height=e.offsetHeight+4+"px";f.style.top=d.t-2+"px";f.style.left=d.l-2+"px";f.style.padding="2px";f.style.display="block";this._selectedWidget.domNode.parentNode.appendChild(f);this._subWidgetFocusFrame=f}},deselectSubwidget:function(b,c){this._subWidgetFocusFrame&&(this._subWidgetFocusFrame.parentNode.removeChild(this._subWidgetFocusFrame),this._subWidgetFocusFrame=null)},_subwidgetSelectionChanged:function(b){if(!(b.origin&&-1<b.origin.indexOf("davinci.ve.themeEditor.commands."))&&
this.isActiveEditor()&&(this._selectedWidget||this._selectedSubWidget))"WidgetOuterContainer"==b.subwidget&&(b.subwidget=null),this.getContext().getCommandStack().execute(new z({_themeEditor:this,_subwidget:b.subwidget}))},_getSelectionStyleValues:function(){var b=this._getCssRules();if(0==b.length)return null;for(var c={},e=0;e<b.length;e++)for(var d=b[e],f=0;f<d.properties.length;f++)c[d.properties[f].name]=d.properties[f].value;return c=this.convertShortHandProps(c)},addShortHandProps:function(b){function c(b){return b.replace(/(\-[a-z])/g,
function(b){return b.toUpperCase().replace("-","")})}var e="";for(a in b)e=e+" "+a+": "+b[a]+";";var d=dojo.doc.createElement("div");d.style.cssText=e;for(v in b)e=c(v),d.style[e]&&(b[v]=d.style[e]);return b},convertShortHandProps:function(b){function c(b){return b.replace(/([A-Z])/g,function(b){return"-"+b.toLowerCase()})}for(var e=this._shortHands,d=0;d<e.length;d++){var f=e[d];if(b[f]){var g=dojo.doc.createElement("div");g.style.cssText=f+": "+b[f]+";";for(n in g.style)if(-1<n.indexOf(f)){var h=
c(n);g.style[n]&&(b[h]=g.style[n])}}}return b},_getCssRules:function(b,c,e){c||(c=null);b=this._loadCssSelectors(b,c,e);c=[];if(!b)return null;for(e=0;e<b.length;e++){var d=this.getContext()._getCssFiles();if(d)for(var f=0;f<d.length;f++)for(var g=d[f].getRules(b[e]),h=0;h<g.length;h++){var k=g[h];k&&(k=k.searchUp("CSSRule"))&&c.push(k)}}return c},focus:function(){this.onSelectionChange([this.getSelectedWidget()])},supports:function(b){return b.match(/^style|states|propsect_layout|propsect_paddingMargins|propsect_background|propsect_border|propsect_fontsAndText$/)?
!0:!1},onSelectionChange:function(b){this.isActiveEditor()&&(b&&b[0])&&(this._selectedWidget&&this._selectedWidget.id==b[0].id||this.getContext().getCommandStack().execute(new r({_themeEditor:this,_widget:b,_firstRun:!0})))},getSelectedWidget:function(){var b=this.getContext(),c=b.getSelection(),e=0<c.length?c[c.length-1]:void 0;1<c.length&&b.select(e);return e},getSelectedSubWidget:function(){if(this._selectedSubWidget)return this._selectedSubWidget},_loadCssSelectors:function(b,c,e){b||(b=this._selectedWidget,
c||(c=this.getSelectedSubWidget()));if(!b)return null;var d=this.metaDataLoader.getType(b);if(!d)return null;b=b.id;0===b.indexOf("all")&&(d=d+".$"+b);e||(e=this._currentState);e||(e="Normal");b=[];c=this._theme.getStyleSelectors(d,e,c);for(var f in c)b.push(f);return b},_addCommandsForValue:function(b,c,e,d,f,g){b||(b=new s);var h=[];c=this.getRules(c,e,d);for(var k=0;k<c.length;k++){var l=c[k];this._theme.isPropertyVaildForWidgetRule(l,g,this._selectedWidget,e,d)&&(l=this.getContext().getDeltaRule(l),
h[l.getSelectorText()]=l)}for(var m in h){var p=f.appliesTo.rule;f.appliesTo.rule=null;cValue=dojo.clone(f);cValue.appliesTo.rule=h[m];f.appliesTo.rule=p;cValue.values.forEach(function(b){if(b[g]&&0==b[g].indexOf("url('")){var c=b[g].split("'")[1];-1<c.indexOf("http://")||(c=p.parent.url.substring(0,p.parent.url.lastIndexOf("/"))+"/"+c,c=D.findResource(c),c=(new E(c.getPath())).relativeTo(cValue.appliesTo.rule.parent.url,!0),b[g]="url('"+c+"')")}}.bind(this));b.add(this.getContext().getCommandForStyleChange(cValue))}return b},
_propertiesChange:function(b){if(this.isActiveEditor()){var c=new s;if("all"===this._selectedWidget.id){var e=[];this._oldValues=[];for(var d=0;d<b.values.length;d++){var f=b.values[d],g;for(g in f)-1<g.indexOf("color")&&(e[g]=f[g])}var f=this._theme.getMetadata(this._theme.getWidgetType(this._selectedWidget)),h;for(h in f.states)if("Normal"!=h){g=dojo.clone(e);for(var k in g){var l,m;f.states.Normal.defaults&&f.states.Normal.defaults.cssPropery&&(l=f.states.Normal.defaults.cssPropery[k]);f.states[h].defaults&&
f.states[h].defaults.cssPropery&&(m=f.states[h].defaults.cssPropery[k]);d=g[k];if(l&&m&&d){d=(new C(d)).calculateHighlightColor(l,m);g[k]=d.toHex();for(d=0;d<b.values.length;d++){var p=b.values[d];for(name in p)g[name]&&(p[name]=g[name])}for(d=0;d<b.values.length;d++)for(var q in b.values[d])c=this._addCommandsForValue(c,this._selectedWidget,this._selectedSubWidget,h,b,q)}}}else for(d=0;d<b.values.length;d++)for(q in b.values[d])c=this._addCommandsForValue(c,this._selectedWidget,this._selectedSubWidget,
this._currentState,b,q)}else for(d=0;d<b.values.length;d++)for(q in b.values[d])c=this._addCommandsForValue(c,this._selectedWidget,this._selectedSubWidget,this._currentState,b,q);this._selectedWidget&&this.getContext().getCommandStack().execute(c);this.setDirty(!0)}},_rebaseCssRuleImagesForStylePalette:function(b,c){if(!b)return c;for(var e=0;e<b.length;e++){var d=b[e],f;for(f in c){var g=d.getProperty(f);g&&(g=g.getURL())&&(c[f]=g)}}return c},_markDirty:function(b){this._dirtyResource[b]=(new Date).getTime();
this._srcChanged()},_srcChanged:function(){this.isDirty||(this._themeFileContent?this.resourceFile.setContents(this._themeFileContent,!0):(console.error("ThemeEditor.theme file content empty"),this._themeFileContent=this.resourceFile.getContentSync()));this.isDirty=!0;this.lastModifiedTime=(new Date).getTime();this.editorContainer&&this.editorContainer.setDirty(!0)},setDirty:function(b){this.isDirty=b;this.editorContainer&&this.editorContainer.setDirty(b)},getContext:function(){return this.visualEditor?
this.visualEditor.context:null},getOutline:function(){return this.visualEditor.getOutline()},getPropertiesView:function(){return this.visualEditor.getPropertiesView()},getThemeFile:function(){return this.theme},setContent:function(b,c){try{this._themePath=new davinci.model.Path(b);var e=dojo.isString(c)?dojo.fromJson(c):c;this.theme=F.getTheme(e.name);this.themeCssFiles=[];for(e=0;e<this.theme.files.length;e++)-1<this.theme.files[e].indexOf(".css")&&this.themeCssFiles.push(this.theme.files[e]);for(var d=
[],f=0;f<this.theme.themeEditorHtmls.length;f++){var g=this._themePath.getParentPath().append(this.theme.themeEditorHtmls[f]).toString();d.push(system.resource.findResource(g))}this.visualEditor=new w(this,this._cp.domNode,b,this.themeCssFiles,d,this.theme);this.fileName=b;var g=[],h=this.getContext();h._themePath=this._themePath;h.themeCssFiles=this.themeCssFiles;for(e=0;e<this.theme.meta.length;e++)g.push(h._getThemeResource(this.theme.meta[e]));this.metaDataLoader=new x(g);this._theme=new y(g,
this.theme);for(var k=h._getCssFiles(),e=0;e<k.length;e++)this._loadedCSSConnects.push(dojo.connect(k[e],"onChange",h,"_themeChange"));this._themeFileContent=this.resourceFile.getContentSync();var l=this._subscriptions;l.push(dojo.subscribe("/davinci/ui/styleValuesChange",this,"_propertiesChange"));l.push(dojo.subscribe("/davinci/states/state/changed",this,"_widgetStateChanged"));l.push(dojo.subscribe("/davinci/ui/subwidgetSelectionChanged",this,"_subwidgetSelectionChanged"));dojo.connect(this.visualEditor,
"onSelectionChange",this,"onSelectionChange")}catch(m){alert("error loading:"+b+m)}},getDefaultContent:function(){},selectModel:function(b){},getFileEditors:function(){var b=[],c=this.getContext()._getCssFiles(),e=function(b,c,d){return{lookFor:b,urlResolver:c,result:d,_getObject:function(b,c,d){return{resourceFile:b,getText:function(){return c},lastModifiedTime:d}},visit:function(b){if("CSSFile"==b.elementType)for(var c in this.lookFor)if(c==b.url){var d=system.resource.findResource(c);this.result.push(this._getObject(d,
b.getText({noComments:!1}),this.lookFor[c]));break}return 0>=this.lookFor.length}}}(this._dirtyResource,this._URLResolver,b);if(c)for(var d=0;d<c.length;d++)c[d].visit(e);b.push({resourceFile:this.resourceFile,getText:function(){return this.resourceFile.getContentSync()},lastModifiedTime:Date.now()});return b},save:function(b){var c=this.getContext().saveDynamicCssFiles(this.getContext()._getCssFiles(),b);"undefined"==typeof hasToaster&&(new I({position:"br-left",duration:4E3,messageTopic:"/davinci/resource/saveError"}),
hasToaster=!0);G(c).then(function(c){for(var d=0;d<c.length;d++)if(c[d]instanceof Error){c=H.vteErrorSavingResourceMessage+c[d];dojo.publish("/davinci/resource/saveError",[{message:c,type:"error"}]);console.error(c);return}b||(this.isDirty=!1);this.editorContainer&&!b&&this.editorContainer.setDirty(!1)}.bind(this))},removeWorkingCopy:function(){},destroy:function(){this._scrollHandler&&(dojo.disconnect(this._scrollHandler),delete this._scrollHandler);this.inherited(arguments);this.getContext().destroy();
this.visualEditor&&this.visualEditor.destroy();this._subscriptions.forEach(dojo.unsubscribe);this._loadedCSSConnects&&(dojo.forEach(this._loadedCSSConnects,dojo.disconnect),delete this._loadedCSSConnects);delete this._tempRules},getText:function(){return dojo.toJson(this.theme,!0)},disableWidget:function(b){if(b){var c=this.getContext().getDocument().getElementById("enableWidgetFocusFrame_"+b.id);c&&c.parentNode.removeChild(c);this._createFrame(b,"disableWidgetFocusFrame_","disableWidgetFocusFrame")}},
_createFrame:function(b,c,e){if(b){var d=this.getContext().getDocument().getElementById(c+b.id);if(!d){var f=b;b.domNode&&(f=b.domNode);d=this.getContext().getDocument().createElement("div");dojo.connect(d,"onmousedown",this,"editFrameOnMouseDown");var g=this.getContext().getContainerNode();dojo.connect(g,"onmousedown",this,"canvasOnMouseDown");d.className=e;d.id=c+b.id;d.style.position="absolute";c=this.getRelativeBox(f);d.style.top=c.t+"px";d.style.left=c.l+"px";d.style.width=c.w+"px";d.style.height=
c.h+"px";d.style.display="block";d._widget=b;f.parentNode.appendChild(d)}}},getRelativeBox:function(b){var c=0,e=0,d=b;if(d.offsetParent){do{if(-1<d.className.indexOf("theming-widget")){e=b.offsetTop;c=b.offsetLeft;break}c+=d.offsetLeft;e+=d.offsetTop}while(d=d.offsetParent)}return{t:e,l:c,w:b.offsetWidth,h:b.offsetHeight}},canvasOnMouseDown:function(b){var c=davinci.ve.widget.getEnclosingWidget(b.target);-1<b.target.id.indexOf("enableWidgetFocusFrame_")&&(c=b.target._widget);for(;c;){if(c.dvAttributes&&
c.dvAttributes.isThemeWidget&&c.getContext())return;c=davinci.ve.widget.getEnclosingWidget(c.domNode.parentNode)}this._selectedWidget&&0>b.target.className.indexOf("editFeedback")&&(b.stopPropagation(),this.getContext().getCommandStack().execute(new r({_themeEditor:this,_widget:[null],_firstRun:!0})),this.getContext().select(null,!1))},editFrameOnMouseDown:function(b){b.stopPropagation();if(this.getContext()._activeTool&&this.getContext()._activeTool.onMouseDown)this.getContext()._activeTool.onMouseDown(b)},
enableWidget:function(b){if(b){var c=this.getContext().getDocument().getElementById("disableWidgetFocusFrame_"+b.id);c&&c.parentNode.removeChild(c);this._createFrame(b,"enableWidgetFocusFrame_","enableWidgetFocusFrame")}},getRules:function(b,c,e){b=this._loadCssSelectors(b,c,e);c=[];for(e=0;e<b.length;e++){var d=this.getContext()._getCssFiles();if(d)for(var f=0;f<d.length;f++)for(var g=d[f].getRules(b[e]),h=0;h<g.length;h++){var k=g[h];k&&(k=k.searchUp("CSSRule"))&&c.push(k)}}return c},_contextLoaded:function(b){b==
this.getContext()&&this._registerScrollHandler()},_registerScrollHandler:function(){var b=this.getContext();if(!this._scrollHandler){var c=dojo.query("iframe",this.editorContainer.domNode)[0];c&&(c.contentDocument&&c.contentDocument.body)&&(this._scrollHandler=dojo.connect(c.contentDocument,"onscroll",this,function(c){setTimeout(function(){b.clearCachedWidgetBounds();b.updateFocusAll()},100)}))}}})});
//# sourceMappingURL=ThemeEditor.js.map