//>>built
define("davinci/ve/themeEditor/VisualThemeEditor","dojo/_base/declare davinci/Workbench ./Context davinci/workbench/Preferences davinci/model/Path davinci/html/HTMLFile davinci/Theme dojo/i18n!../nls/ve dojo/cookie".split(" "),function(h,g,l,m,n,p,k,d,e){return h([],{constructor:function(b,q,d,f,e,a){this.THEME_EDITOR_SPEC=1;this._themeEditor=b;this.domNode=q;this.theme=a;b=e[0];this.basePath=new n(b.getPath());this.loadingDiv=dojo.create("div",{className:"loading",innerHTML:dojo.replace("\x3ctable\x3e\x3ctr\x3e\x3ctd\x3e\x3cspan\x3e\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;\x3c/span\x3e\x26nbsp;{0}\x3c/td\x3e\x3c/tr\x3e\x3c/table\x3e",
["Loading..."])},this.domNode.parentNode,"first");this._handles=[];this.context=new l({editor:this._themeEditor,visualEditor:this,containerNode:this.domNode,baseURL:encodeURI(b.getURL()),theme:a});dojo.connect(this.context,"onSelectionChange",this,"onSelectionChange");(a=m.getPreferences("davinci.ve.themeEditor.editorPrefs",g.getProject()))&&this.context.setPreferences(a);dojo.xhrGet({url:encodeURI(b.getURL()),handleAs:"text",content:{}}).then(dojo.hitch(this,function(a){this.setContent("DEFAULT_PAGE",
a,f)}))},onSelectionChange:function(){},destroy:function(){},getDefaultContent:function(){return""},getContent:function(){return this.context.getSource()},setContent:function(b,d,g){if(this.theme.specVersion<this.THEME_EDITOR_SPEC){var f="maqetta_"+this.theme.name+"_"+this.theme.specVersion;e(f)||(e(f,"true"),this.themeVersionWarn())}if(!(0<b.toLowerCase().indexOf(".css"))&&"DEFAULT_PAGE"==b){f=k.getThemeLocation();htmlFile=new p;htmlFile.fileName=b;htmlFile.setText(d,!0);var h=f.relativeTo(this.basePath,
!0);htmlFile.themeCssFiles=[];g.forEach(function(a){htmlFile.themeCssFiles.push(h.toString()+"/"+this.theme.name+"/"+a)}.bind(this));this.context.model=htmlFile;this.initialSet||(this.context.deactivate(),this.context._setSource(htmlFile,function(a){try{if(a instanceof Error)throw a;this.savePoint=0;var b=this.context.getDocument();dojo.some(b.head.children,function(a){if("LINK"==a.tagName&&-1<a.getAttribute("href").indexOf(this.theme.files[0]))return b.head.removeChild(a),b.head.appendChild(a),!0},
this);var c;this.theme&&this.theme.helper&&((c=k.getHelper(this.theme))&&c.preThemeConfig?c.preThemeConfig(this.context):c&&c.then&&c.then(function(a){a.helper&&a.helper.preThemeConfig&&(a.helper.preThemeConfig(this.context),this.theme.helper=a.helper)}.bind(this)));this.context.activate();setTimeout(dojo.hitch(this,function(){this.context.getTopWidgets().forEach(function(a){a.resize&&a.resize({})});dojo.publish("/davinci/states/state/changed",[{editorClass:"davinci.themeEditor.ThemeEditor",widget:"$all",
newState:"Normal",context:this.context}])}),1500);this.initialSet=!0;if(this.context.getDojo().version.major+"."+this.context.getDojo().version.minor!==this.theme.version){var d="maqetta_"+this.theme.name+"_"+this.theme.version;e(d)||(e(d,"true"),this.themeVersionWarn(!0))}}catch(f){a=f}finally{a.errorMessage?this.loadingDiv.innerHTML=a.errorMessage:a instanceof Error?(c="Uh oh! An error has occurred:\x3cbr\x3e\x3cb\x3e"+a.message+"\x3c/b\x3e",a.fileName&&(c+="\x3cbr\x3efile: "+a.fileName+"\x3cbr\x3eline: "+
a.lineNumber),a.stack&&(c+="\x3cbr\x3e\x3cpre\x3e"+a.stack+"\x3c/pre\x3e"),this.loadingDiv.innerHTML=c,dojo.addClass(this.loadingDiv,"error")):(this.loadingDiv.parentNode&&this.loadingDiv.parentNode.removeChild(this.loadingDiv),delete this.loadingDiv)}},this))}},themeVersionWarn:function(b){var e=d.vteWarningMessage;b&&(e=d.vteWarningToolkitMessage);g.showMessage(d.vteWarningTitle,e,{width:250})},themeVersionError:function(){g.showMessage(d.vteErrorTitle,d.vteErrorMessage,{width:250},dojo.hitch(this,
"themeVersionErrorOk"))},themeVersionErrorOk:function(){this.context.editor.editorContainer.save(!1);this.context.editor.editorContainer.forceClose(this,!0);return!0},hotModifyCssRule:function(){},getOutline:function(){return null}})});
//# sourceMappingURL=VisualThemeEditor.js.map