//>>built
define("dojo/nls/dojo_ROOT",{"dijit/_editor/nls/FontChoice":{noFormat:"None",1:"xx-small",2:"x-small",formatBlock:"Format",3:"small",4:"medium",5:"large",6:"x-large",7:"xx-large",fantasy:"fantasy",serif:"serif",p:"Paragraph",pre:"Pre-formatted","sans-serif":"sans-serif",fontName:"Font",h1:"Heading",h2:"Subheading",h3:"Sub-subheading",monospace:"monospace",fontSize:"Size",cursive:"cursive"},"dijit/nls/common":{buttonOk:"OK",buttonCancel:"Cancel",buttonSave:"Save",itemClose:"Close"},"xapp/widgets/nls/TemplatedWidgetBase":{create_venue:"Create Venue",
download_xcode_project:"Download XCode Project",titles:"Titles",learn_more:"Learn more",resolution_must_be:"Resolution must be",billed_monthly:"billed monthly",sci_fi:"Sci-Fi",lines:"Lines",discount:"dicount",my_uploads:"My Uploads",primary_application_platform:"Primary Application Platform",select:"Select",select_image:"Select Image",transparent:"Transparent",podcasts:"Podcasts",edit:"Edit",locations:"Locations",background:"Background",disabled:"Disabled",fonts:"Fonts",news:"News",refresh:"Refresh",
download:"Download",update_google_service:"Register Google Service",footer_text:"Footer Text",list_item_background:"List Item Background",done:"Done",colors:"Colors",detect:"Detect",monthly:"Monthly",one_year:"One Year",font:"Font",long_text:"Long Text",apple_launch_screen:"Apple Launch Screen",pictures:"Pictures",blog:"Blog",mono_white:"Mono White",until:"until",purchased:"Purchased",preview:"Preview",blue_buttons:"Blue Buttons",places:"Places",upload_file:"Upload File",update_joomla:"Register Joomla",
register_joomla:"Register Joomla",style:"Style",twitter:"Twitter",create_content:"Create Content",videos:"Videos",textures:"Textures",general:"General",remove:"Delete",register_wordpress:"Register Wordpress",articles:"Articles",content_background:"Content Background (Long)",platik:"Plastic",adjust_template:"Adjust Template",size:"Size",sub_titles:"Sub Titles",create_app:"Create App",web:"Web",music:"Music",application_template:"Application Template",my_title:"My Title",file:"File",content:"Content",
buy:"Buy",radio:"Radio",events:"Events",external_link:"External Link",update_wordpress:"Register Wordpress",new_application:"New Application",navigation_bar:"Navigation Bar",select_source:"Select a source",color:"Color",adjust_icons:"Adjust Icons",upload:"Upload",create:"Create",title:"Title",facebook:"Facebook",register_google_service:"Register Google Service",mono_dark:"Mono Dark",rss:"RSS",publish:"Publish",page_background:"Page Background",mono_colored:"Mono Colored",create_new_section_tab:"Create New Section Tab",
select_an_icon:"Select an Icon",delete_application:"Delete Application",create_category:"Create Category",previous:"Previous",select_icon:"Select Icon",picture:"Picture",xapp_cms:"Content",icon_labels:"Icon Labels",radio_stream:"Radio Stream",billed_annually:"billed annually",list_item_detail:"List Item Detail"},"dojo/cldr/nls/number":{scientificFormat:"#E0","currencySpacing-afterCurrency-currencyMatch":"[:^S:]",infinity:"\u221e",list:";",percentSign:"%",minusSign:"-","currencySpacing-beforeCurrency-surroundingMatch":"[:digit:]",
"decimalFormat-short":"000T","currencySpacing-afterCurrency-insertBetween":"\u00a0",nan:"NaN",plusSign:"+","currencySpacing-afterCurrency-surroundingMatch":"[:digit:]",currencyFormat:"\u00a4\u00a0#,##0.00","currencySpacing-beforeCurrency-currencyMatch":"[:^S:]",perMille:"\u2030",group:",",percentFormat:"#,##0%","decimalFormat-long":"000T",decimalFormat:"#,##0.###",decimal:".","currencySpacing-beforeCurrency-insertBetween":"\u00a0",exponential:"E"},"xas/widgets/nls/TemplatedWidgetBase":{create_venue:"Create Venue",
download_xcode_project:"Download XCode Project",titles:"Titles",learn_more:"Learn more",resolution_must_be:"Resolution must be",billed_monthly:"billed monthly",sci_fi:"Sci-Fi",lines:"Lines",discount:"dicount",my_uploads:"My Uploads",primary_application_platform:"Primary Application Platform",select:"Select",select_image:"Select Image",transparent:"Transparent",podcasts:"Podcasts",edit:"Edit",quick:"Quick",locations:"Locations",background:"Background",disabled:"Disabled",fonts:"Fonts",news:"News",
refresh:"Refresh",download:"Download",update_google_service:"Register Google Service",footer_text:"Footer Text",list_item_background:"List Item Background",done:"Done",colors:"Colors",detect:"Detect",monthly:"Monthly",one_year:"One Year",font:"Font",long_text:"Long Text",apple_launch_screen:"Apple Launch Screen",pictures:"Pictures",blog:"Blog",mono_white:"Mono White",until:"until",purchased:"Purchased",preview:"Preview",blue_buttons:"Blue Buttons",places:"Places",upload_file:"Upload File",update_joomla:"Register Joomla",
register_joomla:"Register Joomla",style:"Style",twitter:"Twitter",create_content:"Create Content",videos:"Videos",textures:"Textures",general:"General",remove:"Delete",register_wordpress:"Register Wordpress",articles:"Articles",advanced:"Advanced",content_background:"Content Background (Long)",platik:"Plastic",adjust_template:"Adjust Template",size:"Size",sub_titles:"Sub Titles",create_app:"Create App",web:"Web",music:"Music",application_template:"Application Template",my_title:"My Title",file:"File",
content:"Content",buy:"Buy",radio:"Radio",events:"Events",external_link:"External Link",update_wordpress:"Register Wordpress",new_application:"New Application",navigation_bar:"Navigation Bar",select_source:"Select a source",color:"Color",adjust_icons:"Adjust Icons",upload:"Upload",create:"Create",title:"Title",facebook:"Facebook",register_google_service:"Register Google Service",mono_dark:"Mono Dark",rss:"RSS",publish:"Publish",page_background:"Page Background",mono_colored:"Mono Colored",create_new_section_tab:"Create New Section Tab",
select_an_icon:"Select an Icon",delete_application:"Delete Application",create_category:"Create Category",previous:"Previous",select_icon:"Select Icon",picture:"Picture",xapp_cms:"Content",icon_labels:"Icon Labels",radio_stream:"Radio Stream",billed_annually:"billed annually",list_item_detail:"List Item Detail"},"dijit/form/nls/validate":{rangeMessage:"This value is out of range.",invalidMessage:"The value entered is not valid.",missingMessage:"This value is required."},"dijit/form/nls/ComboBox":{previousMessage:"Previous choices",
nextMessage:"More choices"},"dijit/nls/loading":{loadingState:"Loading...",errorState:"Sorry, an error occurred"}});
//@ sourceMappingURL=dojo_ROOT.js.map