//>>built
define("davinci/library_new","dojo/_base/xhr dojo/Deferred ./Runtime ./model/Path ./ve/themeEditor/metadata/CSSThemeProvider ./ve/themeEditor/metadata/query ./workbench/Preferences".split(" "),function(t,u,k,r,v,w,p){var g={_customWidgets:{}},f={},s={},l={},m={};dojo.subscribe("/davinci/ui/libraryChanged/start",this,function(){m={};l={}});dojo.subscribe("/davinci/resource/resourceChanged",this,function(a,c){var b=require("davinci/Workbench").getProject();if("deleted"==a||"renamed"==a){var d=p.getPreferences("davinci.ui.ProjectPrefs",
b),d=(new r(b)).append(d.themeFolder);(new r(c.getPath())).startsWith(d)&&delete f[b]}"File"==c.elementType&&"theme"==c.extension&&"modified"==a&&c.getContent().then(function(a){a=JSON.parse(a);a.path=[c.getPath()];a.getFile=function(){return system.resource.findResource(this.path[0])}.bind(a);for(var d=0;d<f[b].length;d++)if(f[b][d].name==a.name){f[b][d]=a;return}f[b].push(a)}.bind(this))});return g={themesChanged:function(a){f[a]=a?null:[]},getThemes:function(a,c,b){function d(){var b=[];f[a]&&
(b=c?f[a].filter(function(a){return!a.getFile().isVirtual()}):f[a]);return b}b&&delete f[a];if(f[a])return d();b=p.getPreferences("davinci.ui.ProjectPrefs",a);b=(new r(a)).append(b.themeFolder);b=k.serverJSONRequest({url:"cmd/getThemes",handleAs:"json",content:{path:"*.theme",ignoreCase:!0,workspaceOnly:!1,inFolder:b.toString()},sync:!0});b.forEach(function(a){a.getFile=function(){return system.resource.findResource(this.path[0])}.bind(a)}.bind(this));f[a]=b;return d()},getThemeMetadata:function(a){return s[a.name]?
s[a.name]:null},addCustomWidgets:function(a,c,b,d){var e=p.getPreferences("davinci.ui.ProjectPrefs",a);e.widgetFolder||(e.widgetFolder="./lib/custom",p.savePreferences("davinci.ui.ProjectPrefs",a,e));c=c.getParentFolder().getPath();c=new r(c);b=require("davinci/ve/metadata").parseMetaData(d.name,d,c,b);g._customWidgets[a].hasOwnProperty("name")||(g._customWidgets[a].name="custom",g._customWidgets[a].metaPath=e.widgetFolder,g._customWidgets[a].localPath=!0);g._customWidgets[a]=b;dojo.publish("/davinci/ui/addedCustomWidget",
[b]);return b},getCustomWidgets:function(a){if(!g._customWidgets||!g._customWidgets[a]){g._customWidgets||(g._customWidgets={});g._customWidgets[a]||(g._customWidgets[a]=[]);var c=p.getPreferences("davinci.ui.ProjectPrefs",a);c.widgetFolder||(c.widgetFolder="./lib/custom",p.savePreferences("davinci.ui.ProjectPrefs",a,c));var b=(new r(a)).append(c.widgetFolder).getSegments(),c=system.resource.findResource(b[0]);if(null==c)return console.error("getCustomWidgets : have no parent object for path "+b[0]),
null;for(var d=1;d<b.length;d++)if(null==c)console.error("getCustomWidgets : have no parent object for path "+b[0]);else var e=c._getChild(b[d]),c=e?e:c.createResource(b[d],!0);var f;c.getChildren(function(a){f=a},!0);this._customWidgetPackages=[];null==f&&(f=[]);b={};for(d=0;d<f.length;d++)if(e=f[d],"Folder"==e.elementType){b[e.name]=e.getPath();var k="maq-lib-custom-"+e.name,h=e.getURL();require({packages:[{name:k,location:h}]});this._customWidgetPackages.push({name:e.name,location:h})}e=system.resource.findResource("*_widgets.json",
!1,c);this._customWidgetDescriptors={};for(d=0;d<e.length;d++){var n=e[d],q=n.getParentFolder(),h=c.getURL(),k=q.getURL(),l=k.substr(h.length+1),h=null;try{h=dojo.fromJson(n.getContentSync())}catch(s){}if(h&&h.customWidgetSpec&&(l=l.split("/").shift(),h.__metadataModuleId="maq-lib-custom-"+l,g.addCustomWidgets(a,n,b[l],h),m[a]||(m[a]={}),m[a][q.name]||(m[a][q.name]={}),m[a][q.name][h.version]=k,h&&h.widgets))for(n=0;n<h.widgets.length;n++)(q=h.widgets[n].type)&&(this._customWidgetDescriptors[q]={name:l,
location:k,descriptor:h})}}return{custom:g._customWidgets[a]}},getCustomWidgetPackages:function(){return this._customWidgetPackages||[]},getCustomWidgetDescriptors:function(){return this._customWidgetDescriptors?this._customWidgetDescriptors:{}},getInstalledLibs:function(){g._serverLibs||(g._serverLibs=k.serverJSONRequest({url:"cmd/listLibs",handleAs:"json",content:{},sync:!0})[0].userLibs);return g._serverLibs},getUserLibs:function(a){if(l.base)return l.base;l.base=k.serverJSONRequest({url:"cmd/getUserLibs.json",
handleAs:"json",content:{base:a},sync:!0})[0].userLibs;return l.base},getLibRoot:function(a,c,b){var d=new u,e=m;if(e[b]&&e[b][a]&&void 0!==e[b][a][c])return d.resolve(e[b][a][c]||"");e[b]||(e[b]={});e[b][a]||(e[b][a]={});return t.get({url:"cmd/getLibRoots.php",handleAs:"json",content:{libId:a,version:c,base:b}}).then(function(f){f=f?f[0].libRoot.root:null;e[a]||(e[a]={});e[b][a][c]=f;return d.resolve(f||"")})},modifyLib:function(a){return k.serverJSONRequest({url:"cmd/modifyLib",handleAs:"text",
content:{libChanges:JSON.stringify(a)},sync:!0})},addLib:function(a,c){return k.serverJSONRequest({url:"cmd/getLibRoots",handleAs:"json",content:{libId:a,version:c},sync:!0})[0].libRoot.root},getLibraryId:function(a,c){return{sketch:"sketch",claro:"claro"}[a]+(c||"")},getLibraryName:function(a){var c,b;for(b in a)c=b;return c}}});
//# sourceMappingURL=library_new.js.map