//>>built
define("davinci/Theme","dojo/_base/declare dojo/promise/all ./Workbench ./Runtime ./library ./workbench/Preferences ./model/Path ./html/HTMLFile ./model/Factory system/resource".split(" "),function(u,t,k,r,m,n,l,v,w,p){var h={TEMP_CLONE_PRE:"clone_",desktop_default:"desktop_default",mobile_default:"custom_default",default_theme:"(device-specific)",none_themeset_name:"(none)",other_device:"other",none_theme:"none",dojoMobileDefault:[{theme:"android",device:"Android"},{theme:"blackberry",device:"BlackBerry"},
{theme:"ipad",device:"iPad"},{theme:"iphone",device:"iPhone"},{theme:"iphone",device:"other"}],dojoMobileCustom:[{theme:"custom",device:"Android"},{theme:"custom",device:"BlackBerry"},{theme:"custom",device:"iPad"},{theme:"custom",device:"iPhone"},{theme:"custom",device:"other"}],isThemeHTML:function(b){return-1<b.getName().indexOf("dojo-theme-editor.html")},CloneTheme:function(b,a,c,e,d,f){function g(a){var b=[];a.forEach(function(a){a=p.findResource(m+"/"+a);a=(new l(a.getPath())).relativeTo("./"+
k,!0);for(var d="..",c=0;c<a.segments.length;c++)d=d+"/"+a.segments[c];b.push(d)});return b}c=[];d.getFile();f=(new l(e)).removeLastSegments(0);f=p.findResource(f.toString());f.readOnly()&&f.createResource();p.createResource(e,!0);var h=p.findResource(e);d.getFile().getName();var q=(new l(h.getPath())).lastSegment();e=h.createResource(q+".theme");f=h.createResource(q+".css");var k=this.getThemeLocation(),m=d.getFile().parent.getPath(),n=g(d.themeEditorHtmls),r=g(d.meta),s=" ";g(d.files).forEach(function(a){s=
s+'@import url("'+a+'");'});b={className:d.className,name:b,version:a||d.version,specVersion:d.specVersion,files:[""+q+".css"],meta:r,themeEditorHtmls:n,useBodyFontBackgroundClass:d.useBodyFontBackgroundClass};d.helper&&(b.helper=d.helper.declaredClass?d.helper.declaredClass:d.helper);d.base&&(b.base=d.base);d.type&&(b.type=d.type);if(d.conditionalFiles){b.conditionalFiles=d.conditionalFiles;d=g(d.conditionalFiles);for(a=0;a<b.conditionalFiles.length;a++)q=h.createResource(b.conditionalFiles[a]),
c.push(q.setContents('@import url("'+d[a]+'");'))}d=e.setContents(JSON.stringify(b));d.themeFile=e;c.push(d);c.push(f.setContents(s));return{promise:t(c),themeFile:e}},getHelper:function(b){if(b){if(b.helper&&"string"!=typeof b.helper)return b.helper;var a=b.helper;if(a){var c=new dojo.Deferred;require([a],function(b){b.declaredClass=a;a=b;c.resolve({helper:a})});return c}}},getThemeSet:function(b){var a=h.getThemeSets(k.getProject()),c=dojo.clone(this.dojoMobileDefault),e;a||(a=this.dojoThemeSets);
a=dojo.clone(a);if(b){if(e=b._getDojoJsElem().getAttribute("data-dojo-config"))e=require.eval("({ "+e+" })","data-dojo-config"),e.themeMap&&(c=h.getDojoxMobileThemesFromThemeMap(b,e.themeMap));var d=b.getTheme();if(null==d)console.error("have no desktop theme, abort!");else for(var f=0,g=a.themeSets.length;f<g;f++)if(e=a.themeSets[f],e.desktopTheme===d.name&&this.themeSetEquals(c,e.mobileTheme))return e}d||(console.error("maq hack, restore desktop theme"),d={name:"claro"});e={name:this.none_themeset_name,
desktopTheme:b?d.name:"claro",mobileTheme:c};a.themeSets.push(e);return e},getBase:function(){if(k.singleProjectMode())return k.getProject()},getThemeLocation:function(){var b=this.getBase(),a=n.getPreferences("davinci.ui.ProjectPrefs",b);return(new l(b)).append(a.themeFolder)},getTheme:function(b,a){for(var c=m.getThemes(k.getProject(),this.workspaceOnly),e=0;e<c.length;e++)if(c[e]&&c[e].name===b)return c[e]},getThemeByCssFile:function(b){var a=m.getThemes(k.getProject(),this.workspaceOnly);b=p.findResource(b.url).getPath();
for(var c=0;c<a.length;c++)for(var e=a[c].getFile().getParentFolder().getPath(),d=0;d<a[c].files.length;d++)if(e+"/"+a[c].files[d]===b)return a[c];return null},getDojoxMobileThemeMap:function(b,a){for(var c=[],e=[".*","iphone",[]],d=0;d<a.length;d++)if(a[d].theme!=this.none_theme&&a[d].theme!=this.default_theme){var f=this.getTheme(a[d].theme);if(f){var g;f.path&&f.path[0]?(g=f.path[0].lastIndexOf("/"),g=new l(f.path[0].substring(0,g+1)+f.files[0])):g=(new l(f.getFile().parent.getPath())).append(f.files[0]);
var h=b.getFullResourcePath();g=g.relativeTo(h,!0).toString();a[d].device===this.other_device?e=[".*",f.base,[g]]:c.push([a[d].device,f.base,[g]])}}c.push(e);return c},getDojoxMobileThemesFromThemeMap:function(b,a){var c=m.getThemes(k.getProject(),this.workspaceOnly),e=[];a.forEach(function(a,f,g){for(g=0;g<c.length;g++){f=c[g];var h=(new l(f.getFile().parent.getPath())).append(f.files[0]),k=b.getFullResourcePath();if(h.relativeTo(k,!0).toString()==a[2][0]){g={};g.device=a[0];g.theme=f.name;".*"===
g.device&&(g.device="other");e.push(g);break}}},this);return e},themeSetEquals:function(b,a){function c(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}if(typeof b!==typeof a)return!1;if("function"===typeof b)return b.toString()===a.toString();if(b instanceof Object&&a instanceof Object){if(c(b)!==c(a))return!1;var e=!0,d;for(d in b)if(e=this.themeSetEquals(b[d],a[d]),!e)return!1;return!0}return b===a},themeMapsEqual:function(b,a){var c=JSON.stringify(b),e=JSON.stringify(a);return c===e},
singleMobileTheme:function(b){for(var a=b.mobileTheme[0].theme,c=1;c<b.mobileTheme.length;c++)if(b.mobileTheme[c].theme!=a)return!1;return!0},getThemeSets:function(b){var a=r.getDefaultThemeSet(),c=null;if(a){var e=!1;if(c=n.getPreferences("maqetta.dojo.themesets",b)){for(var d=!1,f=0;f<c.themeSets.length;f++)if(c.themeSets[f].name===a.name){d=!0;h.themeSetEquals(c.themeSets[f],a)||(c.themeSets[f]=a,e=!0);break}d||(c.themeSets.push(a),e=!0)}else c=h.dojoThemeSets,c.themeSets[0]=a,e=!0;e&&h.saveThemeSets(b,
c)}return c},saveThemeSets:function(b,a){n.savePreferences("maqetta.dojo.themesets",b,a)}};h.none_themeset={name:h.none_themeset_name,desktopTheme:"claro",mobileTheme:dojo.clone(h.dojoMobileDefault)};h.default_themeset={name:h.desktop_default,desktopTheme:"claro",mobileTheme:dojo.clone(h.dojoMobileDefault)};h.custom_themeset={name:h.mobile_default,desktopTheme:"claro",mobileTheme:h.dojoMobileCustom};h.dojoThemeSets={version:"1.7",specVersion:"0.8",helper:"maq-metadata-dojo/dojox/mobile/ThemeHelper",
themeSets:[h.custom_themeset]};return h});
//# sourceMappingURL=Theme.js.map