//>>built
/*

 Copyright (c) 2010, 2012 IBM Corporation and others.
 All rights reserved. This program and the accompanying materials are made 
 available under the terms of the Eclipse Public License v1.0 
 (http://www.eclipse.org/legal/epl-v10.html), and the Eclipse Distribution 
 License v1.0 (http://www.eclipse.org/org/documents/edl-v10.html). 

 Contributors: 
  Felipe Heidrich (IBM Corporation) - initial API and implementation
  Silenio Quarti (IBM Corporation) - initial API and implementation
*/
define("orion/editor/annotations",["i18n!orion/editor/nls/messages","orion/editor/eventTarget"],function(q,r){function l(a,b,c){this.start=a;this.end=b;this._projectionModel=c;this.html=this._expandedHTML;this.style=this._expandedStyle;this.expanded=!0}function d(){}function g(a,b){var c=a.lastIndexOf("."),c=a.substring(c+1),e={title:q[c],style:{styleClass:"annotation "+c},html:"\x3cdiv class\x3d'annotationHTML "+c+"'\x3e\x3c/div\x3e",overviewStyle:{styleClass:"annotationOverview "+c}};b?e.lineStyle=
{styleClass:"annotationLine "+c}:e.rangeStyle={styleClass:"annotationRange "+c};d.registerType(a,e)}function k(){}function m(a){this._annotations=[];var b=this;this._listener={onChanged:function(a){b._onChanged(a)}};this.setTextModel(a)}function n(a,b){this._view=a;this._annotationModel=b;var c=this;this._listener={onDestroy:function(a){c._onDestroy(a)},onLineStyle:function(a){c._onLineStyle(a)},onChanged:function(a){c._onAnnotationModelChanged(a)}};a.addEventListener("Destroy",this._listener.onDestroy);
a.addEventListener("postLineStyle",this._listener.onLineStyle);b.addEventListener("Changed",this._listener.onChanged)}l.prototype={_expandedHTML:"\x3cdiv class\x3d'annotationHTML expanded'\x3e\x3c/div\x3e",_expandedStyle:{styleClass:"annotation expanded"},_collapsedHTML:"\x3cdiv class\x3d'annotationHTML collapsed'\x3e\x3c/div\x3e",_collapsedStyle:{styleClass:"annotation collapsed"},collapse:function(){if(this.expanded){this.expanded=!1;this.html=this._collapsedHTML;this.style=this._collapsedStyle;
var a=this._projectionModel,b=a.getBaseModel();this._projection={start:b.getLineStart(b.getLineAtOffset(this.start)+1),end:b.getLineEnd(b.getLineAtOffset(this.end),!0)};a.addProjection(this._projection)}},expand:function(){this.expanded||(this.expanded=!0,this.html=this._expandedHTML,this.style=this._expandedStyle,this._projectionModel.removeProjection(this._projection))}};d.ANNOTATION_ERROR="orion.annotation.error";d.ANNOTATION_WARNING="orion.annotation.warning";d.ANNOTATION_TASK="orion.annotation.task";
d.ANNOTATION_BREAKPOINT="orion.annotation.breakpoint";d.ANNOTATION_BOOKMARK="orion.annotation.bookmark";d.ANNOTATION_FOLDING="orion.annotation.folding";d.ANNOTATION_CURRENT_BRACKET="orion.annotation.currentBracket";d.ANNOTATION_MATCHING_BRACKET="orion.annotation.matchingBracket";d.ANNOTATION_CURRENT_LINE="orion.annotation.currentLine";d.ANNOTATION_CURRENT_SEARCH="orion.annotation.currentSearch";d.ANNOTATION_MATCHING_SEARCH="orion.annotation.matchingSearch";d.ANNOTATION_READ_OCCURRENCE="orion.annotation.readOccurrence";
d.ANNOTATION_WRITE_OCCURRENCE="orion.annotation.writeOccurrence";var p={};d.registerType=function(a,b){var c=b;"function"!==typeof c&&(c=function(a,b,c){this.start=a;this.end=b;c&&(this.title=c)},c.prototype=b);c.prototype.type=a;p[a]=c;return a};d.createAnnotation=function(a,b,c,e){return new (this.getType(a))(b,c,e)};d.getType=function(a){return p[a]};g(d.ANNOTATION_ERROR);g(d.ANNOTATION_WARNING);g(d.ANNOTATION_TASK);g(d.ANNOTATION_BREAKPOINT);g(d.ANNOTATION_BOOKMARK);g(d.ANNOTATION_CURRENT_BRACKET);
g(d.ANNOTATION_MATCHING_BRACKET);g(d.ANNOTATION_CURRENT_SEARCH);g(d.ANNOTATION_MATCHING_SEARCH);g(d.ANNOTATION_READ_OCCURRENCE);g(d.ANNOTATION_WRITE_OCCURRENCE);g(d.ANNOTATION_CURRENT_LINE,!0);d.registerType(d.ANNOTATION_FOLDING,l);k.addMixin=function(a){var b=k.prototype,c;for(c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};k.prototype={addAnnotationType:function(a){this._annotationTypes||(this._annotationTypes=[]);this._annotationTypes.push(a)},getAnnotationTypePriority:function(a){if(this._annotationTypes)for(var b=
0;b<this._annotationTypes.length;b++)if(this._annotationTypes[b]===a)return b+1;return 0},getAnnotationsByType:function(a,b,c){a=a.getAnnotations(b,c);for(c=[];a.hasNext();)b=a.next(),0!==this.getAnnotationTypePriority(b.type)&&c.push(b);var e=this;c.sort(function(a,b){return e.getAnnotationTypePriority(a.type)-e.getAnnotationTypePriority(b.type)});return c},isAnnotationTypeVisible:function(a){return 0!==this.getAnnotationTypePriority(a)},removeAnnotationType:function(a){if(this._annotationTypes)for(var b=
0;b<this._annotationTypes.length;b++)if(this._annotationTypes[b]===a){this._annotationTypes.splice(b,1);break}}};m.prototype={addAnnotation:function(a){if(a){var b=this._annotations,c=this._binarySearch(b,a.start);b.splice(c,0,a);this.onChanged({type:"Changed",added:[a],removed:[],changed:[]})}},getTextModel:function(){return this._model},getAnnotations:function(a,b){var c=this._annotations,e,f=0,d=function(){for(;f<c.length;){var e=c[f++];if(a===e.start||(a>e.start?a<e.end:e.start<b))return e;if(e.start>=
b)break}return null};e=d();return{next:function(){var a=e;a&&(e=d());return a},hasNext:function(){return null!==e}}},modifyAnnotation:function(a){if(a&&!(0>this._getAnnotationIndex(a)))this.onChanged({type:"Changed",added:[],removed:[],changed:[a]})},onChanged:function(a){return this.dispatchEvent(a)},removeAnnotations:function(a){var b=this._annotations,c,e;if(a){c=[];for(e=b.length-1;0<=e;e--){var f=b[e];f.type===a&&b.splice(e,1);c.splice(0,0,f)}}else c=b;this.onChanged({type:"Changed",removed:c,
added:[],changed:[]})},removeAnnotation:function(a){a&&(a=this._getAnnotationIndex(a),0>a||(a={type:"Changed",removed:this._annotations.splice(a,1),added:[],changed:[]},this.onChanged(a)))},replaceAnnotations:function(a,b){var c=this._annotations,e,f,d,h=[];if(a)for(e=a.length-1;0<=e;e--)d=a[e],f=this._getAnnotationIndex(d),0>f||(c.splice(f,1),h.splice(0,0,d));b||(b=[]);for(e=0;e<b.length;e++)d=b[e],f=this._binarySearch(c,d.start),c.splice(f,0,d);this.onChanged({type:"Changed",removed:h,added:b,changed:[]})},
setTextModel:function(a){this._model&&this._model.removeEventListener("Changed",this._listener.onChanged);(this._model=a)&&this._model.addEventListener("Changed",this._listener.onChanged)},_binarySearch:function(a,b){for(var c=a.length,e=-1,f;1<c-e;)f=Math.floor((c+e)/2),b<=a[f].start?c=f:e=f;return c},_getAnnotationIndex:function(a){for(var b=this._annotations,c=this._binarySearch(b,a.start);c<b.length&&b[c].start===a.start;){if(b[c]===a)return c;c++}return-1},_onChanged:function(a){var b=a.start,
c=a.addedCharCount,e=a.removedCharCount,f=this._annotations,d=b+e;if(0<f.length){a={type:"Changed",added:[],removed:[],changed:[],textModelChangedEvent:a};c-=e;for(e=0;e<f.length;e++){var h=f[e];h.start>=d?(h.start+=c,h.end+=c,a.changed.push(h)):h.end<=b||(h.start<b&&d<h.end?(h.end+=c,a.changed.push(h)):(f.splice(e,1),a.removed.push(h),e--))}if(0<a.added.length||0<a.removed.length||0<a.changed.length)this.onChanged(a)}}};r.EventTarget.addMixin(m.prototype);n.prototype={destroy:function(){var a=this._view;
a&&(a.removeEventListener("Destroy",this._listener.onDestroy),a.removeEventListener("LineStyle",this._listener.onLineStyle),this.view=null);(a=this._annotationModel)&&a.removeEventListener("Changed",this._listener.onChanged)},_mergeStyle:function(a,b){if(b){a||(a={});a.styleClass=a.styleClass&&b.styleClass&&a.styleClass!==b.styleClass?a.styleClass+(" "+b.styleClass):b.styleClass;var c;if(b.style)for(c in a.style||(a.style={}),b.style)a.style[c]||(a.style[c]=b.style[c]);if(b.attributes)for(c in a.attributes||
(a.attributes={}),b.attributes)a.attributes[c]||(a.attributes[c]=b.attributes[c])}return a},_mergeStyleRanges:function(a,b){a||(a=[]);var c,e;for(e=0;e<a.length&&b;e++){var f=a[e];if(b.end<=f.start)break;if(!(b.start>=f.end)){c=this._mergeStyle({},f.style);c=this._mergeStyle(c,b.style);var d=[];d.push(e,1);b.start<f.start&&d.push({start:b.start,end:f.start,style:b.style});b.start>f.start&&d.push({start:f.start,end:b.start,style:f.style});d.push({start:Math.max(f.start,b.start),end:Math.min(f.end,
b.end),style:c});b.end<f.end&&d.push({start:b.end,end:f.end,style:f.style});b=b.end>f.end?{start:f.end,end:b.end,style:b.style}:null;Array.prototype.splice.apply(a,d)}}b&&(c=this._mergeStyle({},b.style),a.splice(e,0,{start:b.start,end:b.end,style:c}));return a},_onAnnotationModelChanged:function(a){function b(a){for(var b=0;b<a.length;b++)if(e.isAnnotationTypeVisible(a[b].type)){var d=a[b].start,g=a[b].end;f.getBaseModel&&(d=f.mapOffset(d,!0),g=f.mapOffset(g,!0));-1!==d&&-1!==g&&c.redrawRange(d,g)}}
if(!a.textModelChangedEvent){var c=this._view;if(c){var e=this,f=c.getModel();b(a.added);b(a.removed);b(a.changed)}}},_onDestroy:function(a){this.destroy()},_onLineStyle:function(a){var b=this._annotationModel,c=a.textView.getModel(),e=b.getTextModel(),d=a.lineStart,g=a.lineStart+a.lineText.length;e!==c&&(d=c.mapOffset(d),g=c.mapOffset(g));for(b=b.getAnnotations(d,g);b.hasNext();)if(d=b.next(),this.isAnnotationTypeVisible(d.type)){if(d.rangeStyle){var g=d.start,h=d.end;e!==c&&(g=c.mapOffset(g,!0),
h=c.mapOffset(h,!0));a.ranges=this._mergeStyleRanges(a.ranges,{start:g,end:h,style:d.rangeStyle})}d.lineStyle&&(a.style=this._mergeStyle({},a.style),a.style=this._mergeStyle(a.style,d.lineStyle))}}};k.addMixin(n.prototype);return{FoldingAnnotation:l,AnnotationType:d,AnnotationTypeList:k,AnnotationModel:m,AnnotationStyler:n}});
//# sourceMappingURL=annotations.js.map