//>>built
/*

 Copyright (c) 2011, 2012 IBM Corporation and others.
 All rights reserved. This program and the accompanying materials are made 
 available under the terms of the Eclipse Public License v1.0 
 (http://www.eclipse.org/legal/epl-v10.html), and the Eclipse Distribution 
 License v1.0 (http://www.eclipse.org/org/documents/edl-v10.html). 

 Contributors: IBM Corporation - initial API and implementation 
*/
define("orion/editor/AsyncStyler",["i18n!orion/editor/nls/messages","orion/editor/annotations"],function(r,n){function l(a){return-1!==a.getProperty("objectClass").indexOf(p)&&"highlighter"===a.getProperty("type")}function q(a,b,c){this.initialize(a,b,c);this.lineStyles=[]}var p="orion.edit.highlighter";n.AnnotationType.registerType("orion.annotation.highlightError",{title:r.syntaxError,html:"\x3cdiv class\x3d'annotationHTML error'\x3e\x3c/div\x3e",rangeStyle:{styleClass:"annotationRange error"}});
q.prototype={initialize:function(a,b,c){this.textView=a;this.serviceRegistry=b;this.annotationModel=c;this.services=[];var e=this;this.listener={onModelChanging:function(a){e.onModelChanging(a)},onModelChanged:function(a){e.onModelChanged(a)},onDestroy:function(a){e.onDestroy(a)},onLineStyle:function(a){e.onLineStyle(a)},onStyleReady:function(a){e.onStyleReady(a)},onServiceAdded:function(a){e.onServiceAdded(a.serviceReference,e.serviceRegistry.getService(a.serviceReference))},onServiceRemoved:function(a){e.onServiceRemoved(a.serviceReference,
e.serviceRegistry.getService(a.serviceReference))}};a.addEventListener("ModelChanging",this.listener.onModelChanging);a.addEventListener("ModelChanged",this.listener.onModelChanged);a.addEventListener("Destroy",this.listener.onDestroy);a.addEventListener("LineStyle",this.listener.onLineStyle);b.addEventListener("registered",this.listener.onServiceAdded);b.addEventListener("unregistering",this.listener.onServiceRemoved);a=b.getServiceReferences(p);for(c=0;c<a.length;c++){var d=a[c];l(d)&&this.addServiceListener(b.getService(d))}},
onDestroy:function(a){this.destroy()},destroy:function(){this.textView&&(this.textView.removeEventListener("ModelChanging",this.listener.onModelChanging),this.textView.removeEventListener("ModelChanged",this.listener.onModelChanged),this.textView.removeEventListener("Destroy",this.listener.onDestroy),this.textView.removeEventListener("LineStyle",this.listener.onLineStyle),this.textView=null);if(this.services){for(var a=0;a<this.services.length;a++)this.removeServiceListener(this.services[a]);this.services=
null}this.serviceRegistry&&(this.serviceRegistry.removeEventListener("registered",this.listener.onServiceAdded),this.serviceRegistry.removeEventListener("unregistering",this.listener.onServiceRemoved),this.serviceRegistry=null);this.lineStyles=this.listener=null},onModelChanging:function(a){this.startLine=this.textView.getModel().getLineAtOffset(a.start)},onModelChanged:function(a){var b=this.startLine;(a.addedLineCount||a.removedLineCount)&&Array.prototype.splice.apply(this.lineStyles,[b,a.removedLineCount].concat(this._getEmptyStyle(a.addedLineCount)))},
onStyleReady:function(a){var b=a.lineStyles||a.style;a=Number.MAX_VALUE;var c=-1,e=this.textView.getModel(),d;for(d in b)b.hasOwnProperty(d)&&(this.lineStyles[d]=b[d],a=Math.min(a,d),c=Math.max(c,d));a=Math.max(a,0);c=Math.min(c,e.getLineCount());if(b=this.annotationModel){for(var f=b.getAnnotations(e.getLineStart(a),e.getLineEnd(c)),g=[];f.hasNext();){var h=f.next();"orion.annotation.highlightError"===h.type&&g.push(h)}f=[];for(h=a;h<=c;h++){d=h;var k=this.lineStyles[d],k=k&&k.errors;d=e.getLineStart(d);
if(k)for(var m=0;m<k.length;m++){var l=k[m];f.push(n.AnnotationType.createAnnotation("orion.annotation.highlightError",l.start+d,l.end+d))}}b.replaceAnnotations(g,f)}this.textView.redrawLines(a,c+1)},onLineStyle:function(a){var b=this.lineStyles[a.lineIndex];if(b)if(b.ranges){for(var b=b.ranges,c=a.lineStart,e=b.length,d=[],f=0;f<e;f++){var g=b[f];d.push({start:g.start+c,end:g.end+c,style:g.style})}a.ranges=d}else b.style&&(a.style=b.style)},_getEmptyStyle:function(a){for(var b=[],c=0;c<a;c++)b.push(null);
return b},setContentType:function(a){this.contentType=a;if(this.services)for(a=0;a<this.services.length;a++){var b=this.services[a];if(b.setContentType){var c=this.serviceRegistry.getService("orion.page.progress");c?c.progress(b.setContentType(this.contentType),"Styling content type: "+this.contentType.id?this.contentType.id:this.contentType):b.setContentType(this.contentType)}}},onServiceAdded:function(a,b){l(a)&&this.addServiceListener(b)},onServiceRemoved:function(a,b){-1!==this.services.indexOf(b)&&
this.removeServiceListener(b)},addServiceListener:function(a){if("function"===typeof a.addEventListener&&(a.addEventListener("orion.edit.highlighter.styleReady",this.listener.onStyleReady),this.services.push(a),a.setContentType&&this.contentType)){var b=this.serviceRegistry.getService("orion.page.progress");b?b.progress(a.setContentType(this.contentType),"Styling content type: "+this.contentType.id?this.contentType.id:this.contentType):a.setContentType(this.contentType)}},removeServiceListener:function(a){"function"===
typeof a.removeEventListener&&(a.removeEventListener("orion.edit.highlighter.styleReady",this.listener.onStyleReady),a=this.services.indexOf(a),-1!==a&&this.services.splice(a,1))}};return q});
//# sourceMappingURL=AsyncStyler.js.map