//>>built
/*

 Copyright (c) 2011, 2012 IBM Corporation and others.
 All rights reserved. This program and the accompanying materials are made 
 available under the terms of the Eclipse Public License v1.0 
 (http://www.eclipse.org/legal/epl-v10.html), and the Eclipse Distribution 
 License v1.0 (http://www.eclipse.org/org/documents/edl-v10.html). 

 Contributors:
     IBM Corporation - initial API and implementation
*/
define("orion/editor/contentAssist",["i18n!orion/editor/nls/messages","orion/editor/keyBinding","orion/editor/eventTarget","orion/Deferred","orion/editor/util"],function(q,l,r,m,h){function k(a){this.textView=a;this.state=c.INACTIVE;this.providers=[];var b=this;this.contentAssistListener={onModelChanging:function(a){b.isDeactivatingChange(a)?b.setState(c.INACTIVE):b.state===c.ACTIVE&&b.setState(c.FILTERING)},onScroll:function(a){b.setState(c.INACTIVE)},onSelection:function(a){a=b.state;if(a===c.ACTIVE||
a===c.FILTERING)b.computeProposals(),b.setState(c.FILTERING)}};a.setKeyBinding(h.isMac?new l.KeyBinding(" ",!1,!1,!1,!0):new l.KeyBinding(" ",!0),"contentAssist");a.setAction("contentAssist",function(){b.activate();return!0},{name:q.contentAssist})}function n(a,b){this.contentAssist=a;this.widget=b;this.proposals=[];var d=this;this.contentAssist.addEventListener("ProposalsComputed",function(a){d.proposals=a.data.proposals;d.selectedIndex=d.proposals.length?0:-1})}function p(a,b){this.contentAssist=
a;this.textView=this.contentAssist.getTextView();this.isShowing=this.textViewListenerAdded=!1;var d=this.textView.getOptions("parent").ownerDocument;this.parentNode="string"===typeof b?d.getElementById(b):b;if(!this.parentNode){this.parentNode=h.createElement(d,"div");this.parentNode.className="contentassist";var f=d.getElementsByTagName("body")[0];if(f)f.appendChild(this.parentNode);else throw Error("parentNode is required");}var e=this;this.textViewListener={onMouseDown:function(a){a.event.target.parentElement!==
e.parentNode&&e.contentAssist.deactivate()}};this.contentAssist.addEventListener("ProposalsComputed",function(a){e.setProposals(a.data.proposals);e.show();e.textViewListenerAdded||(e.textView.addEventListener("MouseDown",e.textViewListener.onMouseDown),e.textViewListenerAdded=!0)});this.contentAssist.addEventListener("Deactivating",function(a){e.setProposals([]);e.hide();e.textViewListenerAdded&&(e.textView.removeEventListener("MouseDown",e.textViewListener.onMouseDown),e.textViewListenerAdded=!1);
e.textViewListenerAdded=!1});this.scrollListener=function(a){e.isShowing&&e.position()};d.addEventListener("scroll",this.scrollListener)}var c={INACTIVE:1,ACTIVE:2,FILTERING:3},g={selected:" selected",hr:"proposal-hr",emphasis:"proposal-emphasis",noemphasis:"proposal-noemphasis",dfault:"proposal-default"};k.prototype={apply:function(a){if(!a)return!1;var b=this.textView.getCaretOffset(),d={proposal:a,start:b,end:b};this.setState(c.INACTIVE);this.textView.setText(a.proposal||a,b,b);this.dispatchEvent({type:"ProposalApplied",
data:d});return!0},activate:function(){this.state===c.INACTIVE&&this.setState(c.ACTIVE)},deactivate:function(){this.setState(c.INACTIVE)},getTextView:function(){return this.textView},isActive:function(){return this.state===c.ACTIVE||this.state===c.FILTERING},isDeactivatingChange:function(a){var b=0<a.removedCharCount&&0===a.addedCharCount,d=this.textView,d=a.start+1<=d.getModel().getCharCount()&&/^\s*$/.test(d.getText(a.start,a.start+1));return 0<a.removedLineCount||0<a.addedLineCount||b&&d},setState:function(a){var b;
a===c.ACTIVE?b="Activating":a===c.INACTIVE&&(b="Deactivating");b&&this.dispatchEvent({type:b});this.state=a;this.onStateChange(a)},onStateChange:function(a){a===c.INACTIVE?this.listenerAdded&&(this.textView.removeEventListener("ModelChanging",this.contentAssistListener.onModelChanging),this.textView.removeEventListener("Scroll",this.contentAssistListener.onScroll),this.textView.removeEventListener("Selection",this.contentAssistListener.onSelection),this.listenerAdded=!1):a===c.ACTIVE&&(this.listenerAdded||
(this.textView.addEventListener("ModelChanging",this.contentAssistListener.onModelChanging),this.textView.addEventListener("Scroll",this.contentAssistListener.onScroll),this.textView.addEventListener("Selection",this.contentAssistListener.onSelection),this.listenerAdded=!0),this.computeProposals())},computeProposals:function(){var a=this,b=this.textView.getCaretOffset();this._computeProposals(b).then(function(b){a.dispatchEvent({type:"ProposalsComputed",data:{proposals:b}})})},getPrefixStart:function(a){for(;0<
a&&/[A-Za-z0-9_]/.test(this.textView.getText(a-1,a));)a--;return a},handleError:function(a){},_computeProposals:function(a){var b=this.providers,d=this.textView,f=d.getModel(),e=d.getText(),c={line:f.getLine(f.getLineAtOffset(a)),prefix:d.getText(this.getPrefixStart(a),a),selection:d.getSelection()},g=this,b=b.map(function(b){var d=b.computeProposals||b.getProposals,f;try{"function"===typeof d&&(f=g.progress?g.progress.progress(d.apply(b,[e,a,c]),"Generating content assist proposal"):d.apply(b,[e,
a,c]))}catch(h){g.handleError(h)}return m.when(f)});return m.all(b,this.handleError).then(function(a){return a.reduce(function(a,b){return b instanceof Array?a.concat(b):a},[])})},setProviders:function(a){this.providers=a.slice(0)},setProgress:function(a){this.progress=a}};r.EventTarget.addMixin(k.prototype);n.prototype={cancel:function(){this.getContentAssist().deactivate()},getContentAssist:function(){return this.contentAssist},isActive:function(){return this.getContentAssist().isActive()},lineUp:function(){for(var a=
0===this.selectedIndex?this.proposals.length-1:this.selectedIndex-1;this.proposals[a].unselectable&&0<a;)a--;this.selectedIndex=a;this.widget&&this.widget.setSelectedIndex(this.selectedIndex);return!0},lineDown:function(){for(var a=this.selectedIndex===this.proposals.length-1?0:this.selectedIndex+1;this.proposals[a].unselectable&&a<this.proposals.length-1;)a++;this.selectedIndex=a;this.widget&&this.widget.setSelectedIndex(this.selectedIndex);return!0},enter:function(){return this.contentAssist.apply(this.proposals[this.selectedIndex]||
null)},tab:function(){return this.widget?(this.widget.createAccessible(this),this.widget.parentNode.focus(),!0):!1}};p.prototype={onClick:function(a){this.contentAssist.apply(this.getProposal(a.target));this.textView.focus()},createDiv:function(a,b,d,f){var e=d.ownerDocument,c=h.createElement(e,"div");c.id="contentoption"+f;c.setAttribute("role","option");"hr"===a.style?a=h.createElement(e,"hr"):(c.className=this.calculateClasses(a.style,b),a=e.createTextNode(this.getDisplayString(a)),b&&this.parentNode.setAttribute("aria-activedescendant",
c.id));c.appendChild(a,c);d.appendChild(c)},createAccessible:function(a){this._isAccessible||this.parentNode.addEventListener("keydown",function(b){b.preventDefault();return 27===b.keyCode?a.cancel():38===b.keyCode?a.lineUp():40===b.keyCode?a.lineDown():13===b.keyCode?a.enter():!1});this._isAccessible=!0},calculateClasses:function(a,b){var d=g[a];d||(d=g.dfault);return b?d+g.selected:d},getDisplayString:function(a){return"string"===typeof a?a:a.description&&"string"===typeof a.description?a.description:
a.proposal},getProposal:function(a){for(var b=0,d=this.parentNode.firstChild;null!==d;d=d.nextSibling){if(d===a)return this.proposals[b]||null;b++}return null},setSelectedIndex:function(a){this.selectedIndex=a;this.selectNode(this.parentNode.childNodes[this.selectedIndex])},selectNode:function(a){for(var b=this.parentNode.childNodes,d=0;d<b.length;d++){var c=b[d],e=c.className.indexOf(g.selected);0<=e&&(c.className=c.className.substring(0,e)+c.className.substring(e+g.selected.length));c===a&&(c.className+=
g.selected,this.parentNode.setAttribute("aria-activedescendant",c.id),c.focus(),c.offsetTop<this.parentNode.scrollTop?c.scrollIntoView(!0):c.offsetTop+c.offsetHeight>this.parentNode.scrollTop+this.parentNode.clientHeight&&c.scrollIntoView(!1))}},setProposals:function(a){this.proposals=a},show:function(){if(0===this.proposals.length)this.hide();else{this.parentNode.innerHTML="";for(var a=0;a<this.proposals.length;a++)this.createDiv(this.proposals[a],0===a,this.parentNode,a);this.position();this.parentNode.onclick=
this.onClick.bind(this);this.isShowing=!0}},hide:function(){this.parentNode.ownerDocument.activeElement===this.parentNode&&this.textView.focus();this.parentNode.style.display="none";this.parentNode.onclick=null;this.isShowing=!1},position:function(){var a=this.textView.getLocationAtOffset(this.textView.getCaretOffset());a.y+=this.textView.getLineHeight();this.textView.convert(a,"document","page");this.parentNode.style.position="fixed";this.parentNode.style.left=a.x+"px";this.parentNode.style.top=
a.y+"px";this.parentNode.style.display="block";this.parentNode.scrollTop=0;var b=this.parentNode.ownerDocument,c=b.documentElement.clientWidth;a.y+this.parentNode.offsetHeight>b.documentElement.clientHeight&&(this.parentNode.style.top=a.y-this.parentNode.offsetHeight-this.textView.getLineHeight()+"px");a.x+this.parentNode.offsetWidth>c&&(this.parentNode.style.left=c-this.parentNode.offsetWidth+"px")}};return{ContentAssist:k,ContentAssistMode:n,ContentAssistWidget:p}});
//# sourceMappingURL=contentAssist.js.map