//>>built
/*

 Copyright (c) 2009, 2012 IBM Corporation and others.
 All rights reserved. This program and the accompanying materials are made 
 available under the terms of the Eclipse Public License v1.0 
 (http://www.eclipse.org/legal/epl-v10.html), and the Eclipse Distribution 
 License v1.0 (http://www.eclipse.org/org/documents/edl-v10.html). 

 Contributors: IBM Corporation - initial API and implementation
*/
define("orion/editor/editor","i18n!orion/editor/nls/messages orion/editor/keyBinding orion/editor/eventTarget orion/editor/tooltip orion/editor/annotations orion/editor/util".split(" "),function(r,v,w,s,g,x){function p(a){this._textViewFactory=a.textViewFactory;this._undoStackFactory=a.undoStackFactory;this._textDNDFactory=a.textDNDFactory;this._annotationFactory=a.annotationFactory;this._foldingRulerFactory=a.foldingRulerFactory;this._lineNumberRulerFactory=a.lineNumberRulerFactory;this._contentAssistFactory=
a.contentAssistFactory;this._keyBindingFactory=a.keyBindingFactory;this._statusReporter=a.statusReporter;this._domNode=a.domNode;this._foldingRuler=this._overviewRuler=this._lineNumberRuler=this._annotationRuler=this._annotationModel=this._annotationStyler=null;this._dirty=!1;this._title=this._contentAssist=null;this._keyModes=[]}function t(a){var b=this,c=Array.prototype.slice.call(arguments,1);return c.length?function(){return arguments.length?b.apply(a,c.concat(Array.prototype.slice.call(arguments))):
b.apply(a,c)}:function(){return arguments.length?b.apply(a,arguments):b.call(a)}}var u;p.prototype={destroy:function(){this.uninstallTextView();this._textViewFactory=this._undoStackFactory=this._textDNDFactory=this._annotationFactory=this._foldingRulerFactory=this._lineNumberRulerFactory=this._contentAssistFactory=this._keyBindingFactory=this._statusReporter=this._domNode=null},getAnnotationModel:function(){return this._annotationModel},getAnnotationRuler:function(){return this._annotationRuler},
getAnnotationStyler:function(){return this._annotationStyler},getFoldingRuler:function(){return this._foldingRuler},getLineNumberRuler:function(){return this._lineNumberRuler},getModel:function(){var a=this._textView.getModel();a.getBaseModel&&(a=a.getBaseModel());return a},getOverviewRuler:function(){return this._overviewRuler},getTextView:function(){return this._textView},getTitle:function(){return this._title},getKeyModes:function(){return this._keyModes},isDirty:function(){return this._dirty},
setAnnotationRulerVisible:function(a){if(this._annotationRulerVisible!==a&&(this._annotationRulerVisible=a,this._annotationRuler)){var b=this._textView;a?b.addRuler(this._annotationRuler,0):b.removeRuler(this._annotationRuler)}},setFoldingRulerVisible:function(a){if(this._foldingRulerVisible!==a&&(this._foldingRulerVisible=a,this._foldingRuler)){var b=this._textView;b.getModel().getBaseModel&&(a?b.addRuler(this._foldingRuler,100):b.removeRuler(this._foldingRuler))}},setDirty:function(a){this._dirty!==
a&&(this._dirty=a,this.onDirtyChanged({type:"DirtyChanged"}))},setLineNumberRulerVisible:function(a){if(this._lineNumberRulerVisible!==a&&(this._lineNumberRulerVisible=a,this._lineNumberRuler)){var b=this._textView;a?b.addRuler(this._lineNumberRuler,1):b.removeRuler(this._lineNumberRuler)}},setOverviewRulerVisible:function(a){if(this._overviewRulerVisible!==a&&(this._overviewRulerVisible=a,this._overviewRuler)){var b=this._textView;a?b.addRuler(this._overviewRuler):b.removeRuler(this._overviewRuler)}},
mapOffset:function(a,b){var c=this._textView.getModel();c.getBaseModel&&(a=c.mapOffset(a,b));return a},getCaretOffset:function(){return this.mapOffset(this._textView.getCaretOffset())},getSelection:function(){var a=this._textView,b=a.getSelection(),a=a.getModel();a.getBaseModel&&(b.start=a.mapOffset(b.start),b.end=a.mapOffset(b.end));return b},getText:function(a,b){var c=this._textView.getModel();c.getBaseModel&&(c=c.getBaseModel());return c.getText(a,b)},_expandOffset:function(a){var b=this._textView.getModel(),
c=this._annotationModel;if(c&&b.getBaseModel)for(a=c.getAnnotations(a,a+1);a.hasNext();)b=a.next(),b.type===g.AnnotationType.ANNOTATION_FOLDING&&b.expand&&(b.expand(),c.modifyAnnotation(b))},setCaretOffset:function(a){var b=this._textView,c=b.getModel();c.getBaseModel&&(this._expandOffset(a),a=c.mapOffset(a,!0));b.setCaretOffset(a)},setText:function(a,b,c){var f=this._textView,e=f.getModel();e.getBaseModel&&(void 0!==b&&(this._expandOffset(b),b=e.mapOffset(b,!0)),void 0!==c&&(this._expandOffset(c),
c=e.mapOffset(c,!0)));f.setText(a,b,c)},setFoldingEnabled:function(a){this.setFoldingRulerVisible(a)},setSelection:function(a,b,c){var f=this._textView,e=f.getModel();e.getBaseModel&&(this._expandOffset(a),this._expandOffset(b),a=e.mapOffset(a,!0),b=e.mapOffset(b,!0));f.setSelection(a,b,c)},moveSelection:function(a,b,c,f){var e=this._textView;this.setSelection(a,b||a,!1);b=e.getTopPixel();var d=e.getBottomPixel();a=this.getModel().getLineAtOffset(a);a=e.getLinePixel(a);a<b||a>d?(d=Math.max(0,a-Math.floor((a<
b?3:1)*(d-b)/4)),(new u({node:e,duration:300,curve:[b,d],onAnimate:function(a){e.setTopPixel(Math.floor(a))},onEnd:function(){e.showSelection();(void 0===f||f)&&e.focus();c&&c()}})).play()):(e.showSelection(),(void 0===f||f)&&e.focus(),c&&c())},checkDirty:function(){this.setDirty(!this._undoStack.isClean())},reportStatus:function(a,b,c){this._statusReporter&&this._statusReporter(a,b,c)},_getTooltipInfo:function(a,b){var c=this._textView,f=this.getAnnotationModel();if(!f)return null;var e=this._annotationStyler;
if(!e)return null;var d=c.getOffsetAtLocation(a,b);if(-1===d)return null;d=this.mapOffset(d);e=e.getAnnotationsByType(f,d,d+1);f=[];for(d=0;d<e.length;d++)e[d].rangeStyle&&f.push(e[d]);if(0===f.length)return null;c=c.convert({x:a,y:b},"document","page");return{contents:f,anchor:"left",x:c.x+10,y:c.y+20}},_highlightCurrentLine:function(a,b){var c=this._annotationModel;if(c){var f=this._textView.getModel(),e=b?f.getLineAtOffset(b.start):-1,d=f.getLineAtOffset(a.start),h=a.start===a.end,l=!b||b.start===
b.end,k=f.getLineStart(d),m=f.getLineEnd(d);f.getBaseModel&&(k=f.mapOffset(k),m=f.mapOffset(m));f=this._currentLineAnnotation;if(!(e===d&&l&&h&&f&&f.start===k&&f.end===m)){var e=f?[f]:null,n;h&&(f=g.AnnotationType.createAnnotation(g.AnnotationType.ANNOTATION_CURRENT_LINE,k,m),n=[f]);this._currentLineAnnotation=f;c.replaceAnnotations(e,n)}}},installTextView:function(){this._textView=this._textViewFactory();this._undoStackFactory&&(this._undoStack=this._undoStackFactory.createUndoStack(this));this._textDNDFactory&&
(this._textDND=this._textDNDFactory.createTextDND(this,this._undoStack));if(this._contentAssistFactory){var a=this._contentAssistFactory.createContentAssistMode(this);this._keyModes.push(a);this._contentAssist=a.getContentAssist()}var b=this,c=this._textView,f=this;this._listener={onModelChanged:function(a){f.checkDirty()},onMouseOver:function(a){f._listener.onMouseMove(a)},onMouseMove:function(a){var b=s.Tooltip.getTooltip(c);b&&b.setTarget({x:a.x,y:a.y,getTooltipInfo:function(){return f._getTooltipInfo(this.x,
this.y)}})},onMouseOut:function(a,b){var d=s.Tooltip.getTooltip(c);d&&d.setTarget(null)},onSelection:function(a){f._updateCursorStatus();f._highlightCurrentLine(a.newValue,a.oldValue)}};c.addEventListener("ModelChanged",this._listener.onModelChanged);c.addEventListener("Selection",this._listener.onSelection);c.addEventListener("MouseOver",this._listener.onMouseOver);c.addEventListener("MouseOut",this._listener.onMouseOut);c.addEventListener("MouseMove",this._listener.onMouseMove);this._keyBindingFactory&&
this._keyBindingFactory(this,this._keyModes,this._undoStack,this._contentAssist);c.setKeyBinding(new v.KeyBinding(27),"cancelMode");c.setAction("cancelMode",function(){for(var a=!1,b=0;b<this._keyModes.length;b++)this._keyModes[b].isActive()&&(a=this._keyModes[b].cancel()||a);return a}.bind(this),{name:r.cancelMode});c.setAction("lineUp",function(){for(var a=0;a<this._keyModes.length;a++)if(this._keyModes[a].isActive())return this._keyModes[a].lineUp();return!1}.bind(this));c.setAction("lineDown",
function(){for(var a=0;a<this._keyModes.length;a++)if(this._keyModes[a].isActive())return this._keyModes[a].lineDown();return!1}.bind(this));c.setAction("enter",function(){for(var a=0;a<this._keyModes.length;a++)if(this._keyModes[a].isActive())return this._keyModes[a].enter();return!1}.bind(this));a=function(a,c){if(void 0!==a&&-1!==a){for(var d=this.getView().getModel(),e=this.getAnnotationModel(),f=b.mapOffset(d.getLineStart(a)),d=b.mapOffset(d.getLineEnd(a)),p=e.getAnnotations(f,d),q=null;p.hasNext();){var r=
p.next();if(r.type===g.AnnotationType.ANNOTATION_BOOKMARK){q=r;break}}q?e.removeAnnotation(q):(q=g.AnnotationType.createAnnotation(g.AnnotationType.ANNOTATION_BOOKMARK,f,d),q.title=void 0,e.addAnnotation(q))}};if(this._annotationFactory){var e=c.getModel();e.getBaseModel&&(e=e.getBaseModel());if(this._annotationModel=this._annotationFactory.createAnnotationModel(e))if(e=this._annotationStyler=this._annotationFactory.createAnnotationStyler(c,this._annotationModel))e.addAnnotationType(g.AnnotationType.ANNOTATION_CURRENT_SEARCH),
e.addAnnotationType(g.AnnotationType.ANNOTATION_MATCHING_SEARCH),e.addAnnotationType(g.AnnotationType.ANNOTATION_ERROR),e.addAnnotationType(g.AnnotationType.ANNOTATION_WARNING),e.addAnnotationType(g.AnnotationType.ANNOTATION_MATCHING_BRACKET),e.addAnnotationType(g.AnnotationType.ANNOTATION_CURRENT_BRACKET),e.addAnnotationType(g.AnnotationType.ANNOTATION_CURRENT_LINE),e.addAnnotationType(g.AnnotationType.ANNOTATION_READ_OCCURRENCE),e.addAnnotationType(g.AnnotationType.ANNOTATION_WRITE_OCCURRENCE),
e.addAnnotationType("orion.annotation.highlightError");c.annotationModel=this._annotationModel;var e=this._annotationFactory.createAnnotationRulers(this._annotationModel),d=this._annotationRuler=e.annotationRuler;d&&(d.onClick=function(a,c){if(void 0!==a&&-1!==a)for(var d=this.getView().getModel(),e=this.getAnnotationModel(),f=b.mapOffset(d.getLineStart(a)),d=b.mapOffset(d.getLineEnd(a)),d=e.getAnnotations(f,d);d.hasNext();)if(e=d.next(),this.isAnnotationTypeVisible(e.type)){d=b.getModel();b.onGotoLine(d.getLineAtOffset(f),
e.start-f,e.end-f);break}},d.onDblClick=a,d.setMultiAnnotationOverlay({html:"\x3cdiv class\x3d'annotationHTML overlay'\x3e\x3c/div\x3e"}),d.addAnnotationType(g.AnnotationType.ANNOTATION_ERROR),d.addAnnotationType(g.AnnotationType.ANNOTATION_WARNING),d.addAnnotationType(g.AnnotationType.ANNOTATION_TASK),d.addAnnotationType(g.AnnotationType.ANNOTATION_BOOKMARK));this.setAnnotationRulerVisible(!0);if(d=this._overviewRuler=e.overviewRuler)d.onClick=function(a,d){if(void 0!==a){var e=c.getModel().getLineStart(a);
b.moveSelection(b.mapOffset(e))}},d.addAnnotationType(g.AnnotationType.ANNOTATION_CURRENT_SEARCH),d.addAnnotationType(g.AnnotationType.ANNOTATION_MATCHING_SEARCH),d.addAnnotationType(g.AnnotationType.ANNOTATION_ERROR),d.addAnnotationType(g.AnnotationType.ANNOTATION_WARNING),d.addAnnotationType(g.AnnotationType.ANNOTATION_TASK),d.addAnnotationType(g.AnnotationType.ANNOTATION_BOOKMARK),d.addAnnotationType(g.AnnotationType.ANNOTATION_MATCHING_BRACKET),d.addAnnotationType(g.AnnotationType.ANNOTATION_CURRENT_BRACKET),
d.addAnnotationType(g.AnnotationType.ANNOTATION_CURRENT_LINE),d.addAnnotationType(g.AnnotationType.ANNOTATION_READ_OCCURRENCE),d.addAnnotationType(g.AnnotationType.ANNOTATION_WRITE_OCCURRENCE);this.setOverviewRulerVisible(!0)}this._lineNumberRulerFactory&&(this._lineNumberRuler=this._lineNumberRulerFactory.createLineNumberRuler(this._annotationModel),this._lineNumberRuler.onDblClick=a,this.setLineNumberRulerVisible(!0));this._foldingRulerFactory&&(this._foldingRuler=this._foldingRulerFactory.createFoldingRuler(this._annotationModel),
this._foldingRuler.addAnnotationType(g.AnnotationType.ANNOTATION_FOLDING),this.setFoldingRulerVisible(!1));this.dispatchEvent({type:"TextViewInstalled",textView:c})},uninstallTextView:function(){var a=this._textView;a&&(a.destroy(),this._textView=this._undoStack=this._textDND=this._contentAssist=this._listener=this._annotationModel=this._annotationStyler=this._annotationRuler=this._overviewRuler=this._lineNumberRuler=this._foldingRuler=this._currentLineAnnotation=this._title=null,this._dirty=!1,this._keyModes=
[],this.dispatchEvent({type:"TextViewUninstalled",textView:a}))},_updateCursorStatus:function(){for(var a=this.getModel(),b=this.getCaretOffset(),c=a.getLineAtOffset(b),a=a.getLineStart(c),b=b-a,a=0;a<this._keyModes.length;a++){var f=this._keyModes[a];if(f.isActive()&&f.isStatusActive&&f.isStatusActive())return}this.reportStatus(x.formatMessage(r.lineColumn,c+1,b+1))},showProblems:function(a){var b=this._annotationModel;if(b){for(var c=[],f=[],e=b.getTextModel(),d=b.getAnnotations(0,e.getCharCount()),
h;d.hasNext();)h=d.next(),(h.type===g.AnnotationType.ANNOTATION_ERROR||h.type===g.AnnotationType.ANNOTATION_WARNING)&&c.push(h);if(a)for(d=0;d<a.length;d++)if(h=a[d]){var l=h.description.replace(/'/g,"\x26#39;").replace(/"/g,"\x26#34;"),k=e.getLineStart(h.line-1);h=g.AnnotationType.createAnnotation("error"===h.severity?g.AnnotationType.ANNOTATION_ERROR:g.AnnotationType.ANNOTATION_WARNING,k+h.start-1,k+h.end,l);f.push(h)}b.replaceAnnotations(c,f)}},showOccurrences:function(a){var b=this._annotationModel;
if(b){for(var c=[],f=[],e=b.getTextModel(),d=b.getAnnotations(0,e.getCharCount()),h;d.hasNext();)h=d.next(),(h.type===g.AnnotationType.ANNOTATION_READ_OCCURRENCE||h.type===g.AnnotationType.ANNOTATION_WRITE_OCCURRENCE)&&c.push(h);if(a)for(d=0;d<a.length;d++)if(h=a[d]){var l=e.getLineStart(h.line-1);h=g.AnnotationType.createAnnotation(!0===h.readAccess?g.AnnotationType.ANNOTATION_READ_OCCURRENCE:g.AnnotationType.ANNOTATION_WRITE_OCCURRENCE,l+h.start-1,l+h.end,h.description);f.push(h)}b.replaceAnnotations(c,
f)}},showSelection:function(a,b,c,f,e){"number"===typeof a?("number"!==typeof b&&(b=a),this.moveSelection(a,b)):"number"===typeof c&&(a=this.getModel().getLineStart(c-1),"number"===typeof f&&(a+=f),"number"!==typeof e&&(e=0),this.moveSelection(a,a+e))},setInput:function(a,b,c,f){this._title=a;this._textView&&(f?(this._undoStack.markClean(),this.checkDirty()):(b?this._textView.setText(b):null!==c&&void 0!==c&&(this._textView.setText(c),this._textView.getModel().setLineDelimiter("auto"),this._highlightCurrentLine(this._textView.getSelection())),
this._undoStack.reset(),this.checkDirty(),this._textView.focus()));this.onInputChanged({type:"InputChanged",title:a,message:b,contents:c,contentsSaved:f})},onInputChanged:function(a){return this.dispatchEvent(a)},onGotoLine:function(a,b,c){if(this._textView){var f=this.getModel(),e=f.getLineStart(a),d=0;void 0===c&&(c=0);"string"===typeof b?(a=f.getLine(a).indexOf(b),-1!==a&&(d=a,c=d+b.length)):(d=b,b=f.getLineEnd(a)-e,d=Math.min(d,b),c=Math.min(c,b));this.moveSelection(e+d,e+c)}},onDirtyChanged:function(a){return this.dispatchEvent(a)}};
w.EventTarget.addMixin(p.prototype);u=function(){function a(a){this.options=a}a.prototype.play=function(){var a="number"===typeof this.options.duration?this.options.duration:350,c=this.options.easing||this.defaultEasing,f=this.options.onAnimate||function(){},e=this.options.onEnd||function(){},d=this.options.curve[0],g=this.options.curve[1]-d,l,k,m=-1;k=setInterval(function(){m=-1===m?(new Date).getTime():m;var n=((new Date).getTime()-m)/a;1>n?(n=c(n),l=d+n*g,f(l)):(clearInterval(k),e())},"number"===
typeof this.options.rate?this.options.rate:20)};a.prototype.defaultEasing=function(a){return Math.sin(a*(Math.PI/2))};return a}();Function.prototype.bind||(Function.prototype.bind=t);return{Editor:p,util:{bind:t}}});
//# sourceMappingURL=editor.js.map