//>>built
/*

 Copyright (c) 2013 IBM Corporation and others.
 All rights reserved. This program and the accompanying materials are made 
 available under the terms of the Eclipse Public License v1.0 
 (http://www.eclipse.org/legal/epl-v10.html), and the Eclipse Distribution 
 License v1.0 (http://www.eclipse.org/org/documents/edl-v10.html). 

 Contributors:
     IBM Corporation - initial API and implementation
*/
define("orion/editor/edit","orion/editor/textView orion/editor/textModel orion/editor/projectionTextModel orion/editor/eventTarget orion/editor/keyBinding orion/editor/rulers orion/editor/annotations orion/editor/tooltip orion/editor/undoStack orion/editor/textDND orion/editor/editor orion/editor/editorFeatures orion/editor/contentAssist orion/editor/cssContentAssist orion/editor/htmlContentAssist orion/editor/jsTemplateContentAssist orion/editor/AsyncStyler orion/editor/mirror orion/editor/textMateStyler orion/editor/htmlGrammar davinci/ui/TextStyler".split(" "),
function(p,q,r,C,D,E,F,G,H,I,s,f,h,t,J,u,K,L,v,w,x){function y(a){var b=a.ownerDocument,c=b.defaultView||b.parentWindow;if(!c.getSelection)return a.innerText||a.textContent;b=b.createRange();b.selectNode(a);a=c.getSelection();var c=[],d;for(d=0;d<a.rangeCount;d++)c.push(a.getRangeAt(d));a.removeAllRanges();a.addRange(b);b=a.toString();a.removeAllRanges();for(d=0;d<c.length;d++)a.addRange(c[d]);return b}function z(a){if("data-editor-"===a.substring(0,12))return a=a.substring(12),a=a.replace(/-([a-z])/ig,
function(a,c){return c.toUpperCase()})}function k(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])}function A(a,b){var c={};k(c,b);for(var d,f=0,e=a.attributes,h=e.length;f<h;f++){d=e.item(f);var l=z(d.nodeName);if(l){d=d.nodeValue;if("true"===d||"false"===d)d="true"===d;c[l]=d}}return c}function B(a){var b=a.ownerDocument,b=b.defaultView||b.parentWindow,c;b.getComputedStyle?c=b.getComputedStyle(a,null).getPropertyValue("height"):a.currentStyle&&(c=a.currentStyle.height);return parseInt(c,10)||
0}function m(a){var b=a.parent;b||(b="editor");"string"===typeof b&&(b=(a.document||document).getElementById(b));if(!b&&a.className){var c=(a.document||document).getElementsByClassName(a.className);if(c){a.className=void 0;for(var d=[],g=0;g<c.length;g++)a.parent=c[g],d.push(m(a));return d}}if(!b)throw"no parent";a=A(b,a);var e;a.readonly||(d={createContentAssistMode:function(a){e=new h.ContentAssist(a.getTextView());a=new h.ContentAssistWidget(e);return new h.ContentAssistMode(e,a)}});c=new s.Editor({textViewFactory:function(){return new p.TextView({parent:b,
model:new r.ProjectionTextModel(new q.TextModel("")),tabSize:a.tabSize?a.tabSize:4,readonly:a.readonly,fullSelection:a.fullSelection,tabMode:a.tabMode,expandTab:a.expandTab,themeClass:a.themeClass,wrapMode:a.wrapMode})},undoStackFactory:new f.UndoFactory,annotationFactory:new f.AnnotationFactory,lineNumberRulerFactory:new f.LineNumberRulerFactory,foldingRulerFactory:new f.FoldingRulerFactory,textDNDFactory:new f.TextDNDFactory,contentAssistFactory:d,keyBindingFactory:function(a,b,c,d){var e=new f.TextActions(a,
c);b.push(e);a=new f.SourceCodeActions(a,c,d);b.push(a)},statusReporter:a.statusReporter,domNode:b});d=a.contents;void 0===d&&(d=y(b));d||(d="");c.installTextView();c.setLineNumberRulerVisible(void 0===a.showLinesRuler||a.showLinesRuler);c.setAnnotationRulerVisible(void 0===a.showAnnotationRuler||a.showFoldingRuler);c.setOverviewRulerVisible(void 0===a.showOverviewRuler||a.showOverviewRuler);c.setFoldingRulerVisible(void 0===a.showFoldingRuler||a.showFoldingRuler);c.setInput(a.title,null,d);({styler:null,
highlight:function(b,c){this.styler&&(this.styler.destroy(),this.styler=null);if(b){var d=c.getTextView(),e=c.getAnnotationModel();switch(b){case "js":case "java":case "css":this.styler=new x.TextStyler(d,b,e);c.setFoldingRulerVisible(void 0===a.showFoldingRuler||a.showFoldingRuler);break;case "html":this.styler=new v.TextMateStyler(d,new w.HtmlGrammar)}}}}).highlight(a.lang,c);if(e){var k=new t.CssContentAssistProvider,l=new u.JSTemplateContentAssistProvider;e.addEventListener("Activating",function(){/css$/.test(a.lang)?
e.setProviders([k]):/js$/.test(a.lang)&&e.setProviders([l])})}50>=B(b)&&(d=c.getTextView().computeSize().height,b.style.height=d+"px");return c}var n=this.orion?this.orion.editor:void 0;if(n)for(var g=0;g<arguments.length;g++)k(n,arguments[g]);return m});
//# sourceMappingURL=edit.js.map