//>>built
/*

 Copyright (c) 2011, 2012 IBM Corporation and others.
 All rights reserved. This program and the accompanying materials are made 
 available under the terms of the Eclipse Public License v1.0 
 (http://www.eclipse.org/legal/epl-v10.html), and the Eclipse Distribution 
 License v1.0 (http://www.eclipse.org/org/documents/edl-v10.html). 

 Contributors:
     IBM Corporation - initial API and implementation
*/
define("orion/editor/editorFeatures","i18n!orion/editor/nls/messages orion/editor/undoStack orion/editor/keyBinding orion/editor/rulers orion/editor/annotations orion/editor/tooltip orion/editor/textDND orion/editor/regex orion/editor/util".split(" "),function(g,A,k,q,m,r,B,C,l){function s(){}function t(){}function u(){}function v(){}function w(){}function x(d,a,b){this.editor=d;this.textView=d.getTextView();this.undoStack=a;this._incrementalFindActive=!1;this._incrementalFindSuccess=!0;this._incrementalFindIgnoreSelection=
!1;this._incrementalFindPrefix="";this._searcher=b;this._lastEditLocation=null;this.init()}function y(d,a,b,c){this.editor=d;this.textView=d.getTextView();this.undoStack=a;this.contentAssist=b;this.linkedMode=c;this.contentAssist&&this.contentAssist.addEventListener("ProposalApplied",this.contentAssistProposalApplied.bind(this));this.init()}function z(d){this.editor=d;this.textView=d.getTextView();this.linkedModeActive=!1;this.linkedModePositions=[];this.linkedModeEscapePosition=this.linkedModeCurrentPositionIndex=
0;this.linkedModeListener={onVerify:function(a){for(var b=!1,c=0,f=0;f<this.linkedModePositions.length;++f){var e=this.linkedModePositions[f];b?e.offset+=c:a.start>=e.offset&&a.end<=e.offset+e.length&&(b=e.length,e.length=a.start-e.offset+a.text.length+(e.offset+e.length-a.end),c=e.length-b,b=!0)}b?this.linkedModeEscapePosition+=c:this.cancel()}.bind(this)}}s.prototype={createUndoStack:function(d){d=d.getTextView();var a=new A.UndoStack(d,200);d.setAction("undo",function(){a.undo();return!0},{name:g.undo});
d.setAction("redo",function(){a.redo();return!0},{name:g.redo});return a}};t.prototype={createLineNumberRuler:function(d){return new q.LineNumberRuler(d,"left",{styleClass:"ruler lines"},{styleClass:"rulerLines odd"},{styleClass:"rulerLines even"})}};u.prototype={createFoldingRuler:function(d){return new q.FoldingRuler(d,"left",{styleClass:"ruler folding"})}};v.prototype={createAnnotationModel:function(d){return new m.AnnotationModel(d)},createAnnotationStyler:function(d,a){return new m.AnnotationStyler(d,
a)},createAnnotationRulers:function(d){var a=new q.AnnotationRuler(d,"left",{styleClass:"ruler annotations"});d=new q.OverviewRuler(d,"right",{styleClass:"ruler overview"});return{annotationRuler:a,overviewRuler:d}}};w.prototype={createTextDND:function(d,a){return new B.TextDND(d.getTextView(),a)}};x.prototype={init:function(){var d=this;this._incrementalFindListener={onVerify:function(a){var b=d.editor,c=b.getModel(),f=b.mapOffset(a.start),e=b.mapOffset(a.end),f=c.getText(f,e),c=d._incrementalFindPrefix;
if((c=c.match(RegExp("^"+C.escape(f),"i")))&&0<c.length)c=d._incrementalFindPrefix+=a.text,d.editor.reportStatus(l.formatMessage(g.incrementalFind,c)),f=b.getSelection().start,(f=b.getModel().find({string:c,start:f,caseInsensitive:c.toLowerCase()===c}).next())?(d._incrementalFindSuccess=!0,d._incrementalFindIgnoreSelection=!0,b.moveSelection(f.start,f.end),d._incrementalFindIgnoreSelection=!1):(b.reportStatus(l.formatMessage(g.incrementalFindNotFound,c),"error"),d._incrementalFindSuccess=!1),a.text=
null},onSelection:function(){d._incrementalFindIgnoreSelection||d.toggleIncrementalFind()}};this._lastEditListener={onModelChanged:function(a){d.editor.isDirty()&&(d._lastEditLocation=a.start+a.addedCharCount)}};this.textView.addEventListener("ModelChanged",this._lastEditListener.onModelChanged);this.textView.setKeyBinding(new k.KeyBinding("k",!0),"findNext");this.textView.setAction("findNext",function(){if(this._searcher){var a=this.textView.getSelection();a.start<a.end?this._searcher.findNext(!0,
this.textView.getText(a.start,a.end)):this._searcher.findNext(!0);return!0}return!1}.bind(this),{name:g.findNext});this.textView.setKeyBinding(new k.KeyBinding("k",!0,!0),"findPrevious");this.textView.setAction("findPrevious",function(){if(this._searcher){var a=this.textView.getSelection();a.start<a.end?this._searcher.findNext(!1,this.textView.getText(a.start,a.end)):this._searcher.findNext(!1);return!0}return!1}.bind(this),{name:g.findPrevious});this.textView.setKeyBinding(new k.KeyBinding("j",!0),
"incrementalFind");this.textView.setAction("incrementalFind",function(){if(this._searcher&&this._searcher.visible())return!0;var a=this.editor;if(this._incrementalFindActive){var b=this._incrementalFindPrefix;if(0!==b.length){var c;c=0;this._incrementalFindSuccess&&(c=a.getSelection().start+1);(c=a.getModel().find({string:b,start:c,caseInsensitive:b.toLowerCase()===b}).next())?(this._incrementalFindIgnoreSelection=this._incrementalFindSuccess=!0,a.moveSelection(c.start,c.end),this._incrementalFindIgnoreSelection=
!1,a.reportStatus(l.formatMessage(g.incrementalFind,b))):(a.reportStatus(l.formatMessage(g.incrementalFindNotFound,b),"error"),this._incrementalFindSuccess=!1)}}else a.setCaretOffset(a.getCaretOffset()),this.toggleIncrementalFind();return!0}.bind(this),{name:g.incrementalFindKey});this.textView.setAction("deletePrevious",function(){if(this._incrementalFindActive){var a=this.editor,b=this._incrementalFindPrefix,b=this._incrementalFindPrefix=b.substring(0,b.length-1);if(0===b.length)return this._incrementalFindIgnoreSelection=
this._incrementalFindSuccess=!0,a.setCaretOffset(a.getSelection().start),this._incrementalFindIgnoreSelection=!1,this.toggleIncrementalFind(),!0;a.reportStatus(l.formatMessage(g.incrementalFind,b));var c=a.getModel().find({string:b,start:a.getCaretOffset()-b.length-1,reverse:!0,caseInsensitive:b.toLowerCase()===b}).next();c?(this._incrementalFindIgnoreSelection=this._incrementalFindSuccess=!0,a.moveSelection(c.start,c.end),this._incrementalFindIgnoreSelection=!1):a.reportStatus(l.formatMessage(g.incrementalFindNotFound,
b),"error");return!0}return!1}.bind(this));this.textView.setAction("tab",function(){if(this.textView.getOptions("readonly"))return!1;if(this.textView.getOptions("tabMode")){var a=this.editor,b=a.getModel(),c=a.getSelection(),f=b.getLineAtOffset(c.start),e=b.getLineAtOffset(c.end>c.start?c.end-1:c.end);if(f!==e){var d=[];d.push("");for(var h=f;h<=e;h++)d.push(b.getLine(h,!0));var h=b.getLineStart(f),b=b.getLineEnd(e,!0),n=this.textView.getOptions("tabSize","expandTab"),n=n.expandTab?Array(n.tabSize+
1).join(" "):"\t";a.setText(d.join(n),h,b);a.setSelection(h===c.start?c.start:c.start+n.length,c.end+(e-f+1)*n.length);return!0}a=a.getKeyModes();for(c=0;c<a.length;c++)if(a[c].isActive())return a[c].tab();return!1}}.bind(this));this.textView.setAction("shiftTab",function(){if(this.textView.getOptions("readonly"))return!1;if(this.textView.getOptions("tabMode")){for(var a=this.editor,b=a.getModel(),c=a.getSelection(),f=b.getLineAtOffset(c.start),e=b.getLineAtOffset(c.end>c.start?c.end-1:c.end),d=this.textView.getOptions("tabSize"),
h=Array(d+1).join(" "),n=[],g=0,k=0,l=f;l<=e;l++){var m=b.getLine(l,!0);if(b.getLineStart(l)!==b.getLineEnd(l))if(0===m.indexOf("\t"))m=m.substring(1),g++;else if(0===m.indexOf(h))m=m.substring(d),g+=d;else return!0;l===f&&(k=g);n.push(m)}f=b.getLineStart(f);d=b.getLineEnd(e,!0);b=b.getLineStart(e);a.setText(n.join(""),f,d);n=f===c.start?c.start:c.start-k;c=Math.max(n,c.end-g+(c.end===b+1&&c.start!==c.end?1:0));a.setSelection(n,c);return!0}}.bind(this),{name:g.unindentLines});this.textView.setKeyBinding(new k.KeyBinding(38,
!1,!1,!0),"moveLinesUp");this.textView.setAction("moveLinesUp",function(){if(this.textView.getOptions("readonly"))return!1;var a=this.editor,b=a.getModel(),c=a.getSelection(),f=b.getLineAtOffset(c.start);if(0===f)return!0;var e=b.getLineAtOffset(c.end>c.start?c.end-1:c.end),d=b.getLineCount(),c=b.getLineStart(f-1),h=b.getLineStart(f),n=b.getLineEnd(e,!0),g=b.getText(h,n),k=0;e===d-1&&(e=b.getLineEnd(f-1),f=b.getLineEnd(f-1,!0),g+=b.getText(e,f),h=e,k=f-e);this.startUndo();a.setText("",h,n);a.setText(g,
c,c);a.setSelection(c,c+g.length-k);this.endUndo();return!0}.bind(this),{name:g.moveLinesUp});this.textView.setKeyBinding(new k.KeyBinding(40,!1,!1,!0),"moveLinesDown");this.textView.setAction("moveLinesDown",function(){if(this.textView.getOptions("readonly"))return!1;var a=this.editor,b=a.getModel(),c=a.getSelection(),f=b.getLineAtOffset(c.start),e=b.getLineAtOffset(c.end>c.start?c.end-1:c.end),d=b.getLineCount();if(e===d-1)return!0;var f=b.getLineStart(f),c=b.getLineEnd(e,!0),h=b.getLineEnd(e+1,
!0)-(c-f),g=0;e!==d-2?b=b.getText(f,c):(e=b.getLineEnd(e),b=b.getText(e,c)+b.getText(f,e),g+=c-e);this.startUndo();a.setText("",f,c);a.setText(b,h,h);a.setSelection(h+g,h+g+b.length);this.endUndo();return!0}.bind(this),{name:g.moveLinesDown});this.textView.setKeyBinding(new k.KeyBinding(38,!0,!1,!0),"copyLinesUp");this.textView.setAction("copyLinesUp",function(){if(this.textView.getOptions("readonly"))return!1;var a=this.editor,b=a.getModel(),c=a.getSelection(),f=b.getLineAtOffset(c.start),c=b.getLineAtOffset(c.end>
c.start?c.end-1:c.end),f=b.getLineStart(f),e=b.getLineEnd(c,!0),d=b.getLineCount(),h="",e=b.getText(f,e);c===d-1&&(e+=h=b.getLineDelimiter());a.setText(e,f,f);a.setSelection(f,f+e.length-h.length);return!0}.bind(this),{name:g.copyLinesUp});this.textView.setKeyBinding(new k.KeyBinding(40,!0,!1,!0),"copyLinesDown");this.textView.setAction("copyLinesDown",function(){if(this.textView.getOptions("readonly"))return!1;var a=this.editor,b=a.getModel(),c=a.getSelection(),f=b.getLineAtOffset(c.start),c=b.getLineAtOffset(c.end>
c.start?c.end-1:c.end),e=b.getLineStart(f),f=b.getLineEnd(c,!0),d=b.getLineCount(),h="",e=b.getText(e,f);c===d-1&&(e=(h=b.getLineDelimiter())+e);a.setText(e,f,f);a.setSelection(f+h.length,f+e.length);return!0}.bind(this),{name:g.copyLinesDown});this.textView.setKeyBinding(new k.KeyBinding("d",!0,!1,!1),"deleteLines");this.textView.setAction("deleteLines",function(){if(this.textView.getOptions("readonly"))return!1;var a=this.editor,b=a.getSelection(),c=a.getModel(),f=c.getLineAtOffset(b.start),b=c.getLineAtOffset(b.end>
b.start?b.end-1:b.end),f=c.getLineStart(f),c=c.getLineEnd(b,!0);a.setText("",f,c);return!0}.bind(this),{name:g.deleteLines});this.textView.setKeyBinding(new k.KeyBinding("l",!0),"gotoLine");this.textView.setAction("gotoLine",function(){var a=this.editor,b=a.getModel().getLineAtOffset(a.getCaretOffset());if(b=prompt(g.gotoLinePrompty,b+1))b=parseInt(b,10),a.onGotoLine(b-1,0);return!0}.bind(this),{name:g.gotoLine});this.textView.setKeyBinding(new k.KeyBinding(190,!0),"nextAnnotation");this.textView.setAction("nextAnnotation",
function(){var a=this.editor,b=a.getAnnotationModel();if(!b)return!0;for(var c=a.getModel(),f=a.getCaretOffset(),b=b.getAnnotations(f,c.getCharCount());b.hasNext();){var e=b.next();if(!(e.start<=f)&&!(e.type!==m.AnnotationType.ANNOTATION_ERROR&&e.type!==m.AnnotationType.ANNOTATION_WARNING&&e.type!==m.AnnotationType.ANNOTATION_TASK&&e.type!==m.AnnotationType.ANNOTATION_BOOKMARK)){var d=r.Tooltip.getTooltip(this.textView);if(!d){a.moveSelection(e.start);break}var h=c.getLineAtOffset(e.start),g=this.textView;
a.moveSelection(e.start,e.start,function(){setTimeout(function(){d.setTarget({getTooltipInfo:function(){var a=g.convert({x:g.getLocationAtOffset(e.start).x,y:g.getLocationAtOffset(c.getLineStart(h)).y},"document","page");return{contents:[e],x:a.x,y:a.y+Math.floor(1.33*g.getLineHeight(h))}}},0)},0)});break}}return!0}.bind(this),{name:g.nextAnnotation});this.textView.setKeyBinding(new k.KeyBinding(188,!0),"previousAnnotation");this.textView.setAction("previousAnnotation",function(){var a=this.editor,
b=a.getAnnotationModel();if(!b)return!0;for(var c=a.getModel(),f=a.getCaretOffset(),b=b.getAnnotations(0,f),e=null;b.hasNext();){var d=b.next();d.start>=f||d.type!==m.AnnotationType.ANNOTATION_ERROR&&d.type!==m.AnnotationType.ANNOTATION_WARNING&&d.type!==m.AnnotationType.ANNOTATION_TASK&&d.type!==m.AnnotationType.ANNOTATION_BOOKMARK||(e=d)}if(e){var h=c.getLineAtOffset(e.start),g=r.Tooltip.getTooltip(this.textView);if(!g)return a.moveSelection(e.start),!0;var k=this.textView;a.moveSelection(e.start,
e.start,function(){setTimeout(function(){g.setTarget({getTooltipInfo:function(){var a=k.convert({x:k.getLocationAtOffset(e.start).x,y:k.getLocationAtOffset(c.getLineStart(h)).y},"document","page");return{contents:[e],x:a.x,y:a.y+Math.floor(1.33*k.getLineHeight(h))}}},0)},0)})}return!0}.bind(this),{name:g.prevAnnotation});this.textView.setKeyBinding(new k.KeyBinding("e",!0,!1,!0,!1),"expand");this.textView.setAction("expand",function(){var a=this.editor,b=a.getAnnotationModel();if(!b)return!0;var c=
a.getModel(),a=a.getCaretOffset(),f=c.getLineAtOffset(a),a=c.getLineStart(f),f=c.getLineEnd(f,!0);c.getBaseModel&&(a=c.mapOffset(a),f=c.mapOffset(f),c.getBaseModel());for(var e,c=b.getAnnotations(a,f);!e&&c.hasNext();)a=c.next(),a.type===m.AnnotationType.ANNOTATION_FOLDING&&(a.expanded||(e=a));e&&!e.expanded&&(e.expand(),b.modifyAnnotation(e));return!0}.bind(this),{name:g.expand});this.textView.setKeyBinding(new k.KeyBinding("c",!0,!1,!0,!1),"collapse");this.textView.setAction("collapse",function(){var a=
this.editor,b=a.getAnnotationModel();if(!b)return!0;var c=a.getModel(),f=a.getCaretOffset(),e=c.getLineAtOffset(f),f=c.getLineStart(e),e=c.getLineEnd(e,!0);c.getBaseModel&&(f=c.mapOffset(f),e=c.mapOffset(e),c.getBaseModel());for(var d,c=b.getAnnotations(f,e);!d&&c.hasNext();)f=c.next(),f.type===m.AnnotationType.ANNOTATION_FOLDING&&(d=f);d&&d.expanded&&(a.setCaretOffset(d.start),d.collapse(),b.modifyAnnotation(d));return!0}.bind(this),{name:g.collapse});this.textView.setKeyBinding(new k.KeyBinding("e",
!0,!0,!0,!1),"expandAll");this.textView.setAction("expandAll",function(){var a=this.editor,b=a.getAnnotationModel();if(!b)return!0;var a=a.getModel(),c=b.getAnnotations(0,a.getCharCount());for(this.textView.setRedraw(!1);c.hasNext();)a=c.next(),a.type===m.AnnotationType.ANNOTATION_FOLDING&&!a.expanded&&(a.expand(),b.modifyAnnotation(a));this.textView.setRedraw(!0);return!0}.bind(this),{name:g.expandAll});this.textView.setKeyBinding(new k.KeyBinding("c",!0,!0,!0,!1),"collapseAll");this.textView.setAction("collapseAll",
function(){var a=this.editor,b=a.getAnnotationModel();if(!b)return!0;var a=a.getModel(),c=b.getAnnotations(0,a.getCharCount());for(this.textView.setRedraw(!1);c.hasNext();)a=c.next(),a.type===m.AnnotationType.ANNOTATION_FOLDING&&a.expanded&&(a.collapse(),b.modifyAnnotation(a));this.textView.setRedraw(!0);return!0}.bind(this),{name:g.collapseAll});this.textView.setKeyBinding(new k.KeyBinding("q",!l.isMac,!1,!1,l.isMac),"lastEdit");this.textView.setAction("lastEdit",function(){"number"===typeof this._lastEditLocation&&
this.editor.showSelection(this._lastEditLocation);return!0}.bind(this),{name:g.lastEdit})},toggleIncrementalFind:function(){(this._incrementalFindActive=!this._incrementalFindActive)?(this.editor.reportStatus(l.formatMessage(g.incrementalFind,this._incrementalFindPrefix)),this.textView.addEventListener("Verify",this._incrementalFindListener.onVerify),this.textView.addEventListener("Selection",this._incrementalFindListener.onSelection)):(this._incrementalFindPrefix="",this.editor.reportStatus(""),
this.textView.removeEventListener("Verify",this._incrementalFindListener.onVerify),this.textView.removeEventListener("Selection",this._incrementalFindListener.onSelection),this.textView.setCaretOffset(this.textView.getCaretOffset()))},startUndo:function(){this.undoStack&&this.undoStack.startCompoundChange()},endUndo:function(){this.undoStack&&this.undoStack.endCompoundChange()},cancel:function(){this.toggleIncrementalFind()},isActive:function(){return this._incrementalFindActive},isStatusActive:function(){return this._incrementalFindActive},
lineUp:function(){if(this._incrementalFindActive){var d=this._incrementalFindPrefix;if(0===d.length)return!1;var a=this.editor,b=a.getModel(),b=this._incrementalFindSuccess?a.getCaretOffset()-d.length-1:b.getCharCount()-1;(b=a.getModel().find({string:d,start:b,reverse:!0,caseInsensitive:d.toLowerCase()===d}).next())?(this._incrementalFindIgnoreSelection=this._incrementalFindSuccess=!0,a.moveSelection(b.start,b.end),this._incrementalFindIgnoreSelection=!1,a.reportStatus(l.formatMessage(g.incrementalFind,
d))):(a.reportStatus(l.formatMessage(g.incrementalFindNotFound,d),"error"),this._incrementalFindSuccess=!1);return!0}return!1},lineDown:function(){if(this._incrementalFindActive){var d=this._incrementalFindPrefix;if(0===d.length)return!1;var a=this.editor,b=0;this._incrementalFindSuccess&&(b=a.getSelection().start+1);(b=a.getModel().find({string:d,start:b,caseInsensitive:d.toLowerCase()===d}).next())?(this._incrementalFindIgnoreSelection=this._incrementalFindSuccess=!0,a.moveSelection(b.start,b.end),
this._incrementalFindIgnoreSelection=!1,a.reportStatus(l.formatMessage(g.incrementalFind,d))):(a.reportStatus(l.formatMessage(g.incrementalFindNotFound,d),"error"),this._incrementalFindSuccess=!1);return!0}return!1},enter:function(){return!1}};y.prototype={startUndo:function(){this.undoStack&&this.undoStack.startCompoundChange()},endUndo:function(){this.undoStack&&this.undoStack.endCompoundChange()},init:function(){function d(a,b,c){var f=a.getLineAtOffset(b),d=a.getLineAtOffset(c),g,h,k,l,m,p;for(g=
f;0<=g&&!(h=a.getLine(g),k=g===f?b-a.getLineStart(f):h.length,l=h.lastIndexOf("/*",k),h=h.lastIndexOf("*/",k),h>l);g--)if(-1!==l){m=a.getLineStart(g)+l;break}for(g=d;g<a.getLineCount()&&!(h=a.getLine(g),k=g===d?c-a.getLineStart(d):0,l=h.indexOf("/*",k),h=h.indexOf("*/",k),-1!==l&&l<h);g++)if(-1!==h){p=a.getLineStart(g)+h;break}return{commentStart:m,commentEnd:p}}this.textView.setAction("lineStart",function(){for(var a=this.editor,b=a.getModel(),c=a.getCaretOffset(),d=b.getLineAtOffset(c),e=b.getLineStart(d),
b=b.getLine(d),d=0;d<b.length;d++){var g=b.charCodeAt(d);if(!(32===g||9===g))break}d+=e;return c!==d?(a.setSelection(d,d),!0):!1}.bind(this));this.textView.setKeyBinding(new k.KeyBinding(191,!0),"toggleLineComment");this.textView.setAction("toggleLineComment",function(){if(this.textView.getOptions("readonly"))return!1;for(var a=this.editor,b=a.getModel(),c=a.getSelection(),d=b.getLineAtOffset(c.start),e=b.getLineAtOffset(c.end>c.start?c.end-1:c.end),g=!0,h=[],k,l,m=d;m<=e;m++)if(k=b.getLine(m,!0),
h.push(k),!g||-1===(l=k.indexOf("//")))g=!1;else if(0!==l){var p;for(p=0;p<l&&!(g=k.charCodeAt(p),!(32===g||9===g));p++);g=p===l}m=b.getLineStart(d);p=b.getLineEnd(e,!0);if(g){for(g=0;g<h.length;g++)k=h[g],l=k.indexOf("//"),h[g]=k.substring(0,l)+k.substring(l+2);h=h.join("");k=b.getLineStart(e);b=m===c.start?c.start:c.start-2;c=c.end-2*(e-d+1)+(c.end===k+1?2:0)}else h.splice(0,0,""),h=h.join("//"),b=m===c.start?c.start:c.start+2,c=c.end+2*(e-d+1);a.setText(h,m,p);a.setSelection(b,c);return!0}.bind(this),
{name:g.toggleLineComment});this.textView.setKeyBinding(new k.KeyBinding(191,!0,!l.isMac,!1,l.isMac),"addBlockComment");this.textView.setAction("addBlockComment",function(){if(this.textView.getOptions("readonly"))return!1;var a=this.editor,b=a.getModel(),c=a.getSelection(),f=RegExp("/\\*|\\*/","g"),e=d(b,c.start,c.end);if(void 0!==e.commentStart&&void 0!==e.commentEnd)return!0;b=b.getText(c.start,c.end);if(0===b.length)return!0;e=b.length;b=b.replace(f,"");f=b.length;a.setText("/*"+b+"*/",c.start,
c.end);a.setSelection(c.start+2,c.end+2+(f-e));return!0}.bind(this),{name:g.addBlockComment});this.textView.setKeyBinding(new k.KeyBinding(220,!0,!l.isMac,!1,l.isMac),"removeBlockComment");this.textView.setAction("removeBlockComment",function(){if(this.textView.getOptions("readonly"))return!1;var a=this.editor,b=a.getModel(),c=a.getSelection(),f=b.getText(c.start,c.end),e,g,h;for(h=0;h<f.length;h++)if("/*"===f.substring(h,h+2)){e=c.start+h;break}for(;h<f.length;h++)if("*/"===f.substring(h,h+2)){g=
c.start+h;break}if(void 0!==e&&void 0!==g)a.setText(b.getText(e+2,g),e,g+2),a.setSelection(e,g);else{f=d(b,c.start,c.end);if(void 0===f.commentStart||void 0===f.commentEnd)return!0;b=b.getText(f.commentStart+2,f.commentEnd);a.setText(b,f.commentStart,f.commentEnd+2);a.setSelection(c.start-2,c.end-2)}return!0}.bind(this),{name:g.removeBlockComment})},contentAssistProposalApplied:function(d){d=d.data.proposal;if(d.positions&&this.linkedMode){for(var a=[],b=0;b<d.positions.length;++b)a[b]={positions:[{offset:d.positions[b].offset,
length:d.positions[b].length}]};this.linkedMode.enterLinkedMode({groups:a,escapePosition:d.escapePosition})}else d.escapePosition&&this.textView.setCaretOffset(d.escapePosition);return!0},cancel:function(){return!1},isActive:function(){return!0},isStatusActive:function(){return!1},lineUp:function(){return!1},lineDown:function(){return!1},enter:function(){if(this.textView.getOptions("readonly"))return!1;var d=this.editor,a=d.getSelection();if(a.start===a.end){for(var b=d.getModel(),c=b.getLineAtOffset(a.start),
f=b.getLine(c,!0),e=b.getLineStart(c),c=0,e=a.start-e,g;c<e&&(32===(g=f.charCodeAt(c))||9===g);)c++;if(0<c){for(var h=f.substring(0,c),c=e;c<f.length&&(32===(g=f.charCodeAt(c++))||9===g);)a.end++;d.setText(b.getLineDelimiter()+h,a.start,a.end);return!0}}return!1},tab:function(){return!1}};z.prototype={enterLinkedMode:function(d){if(!this.linkedModeActive){this.linkedModeActive=!0;this.linkedModePositions=[];for(var a=0;a<d.groups.length;++a){var b=d.groups[a];this.linkedModePositions[a]={offset:b.positions[0].offset,
length:b.positions[0].length}}this.linkedModeEscapePosition=d.escapePosition;this.linkedModeCurrentPositionIndex=0;this.selectTextForLinkedModePosition(this.linkedModePositions[this.linkedModeCurrentPositionIndex]);this.textView.addEventListener("Verify",this.linkedModeListener.onVerify);this.textView.setKeyBinding(new k.KeyBinding(9),"nextLinkedModePosition");this.textView.setAction("nextLinkedModePosition",function(){this.linkedModeCurrentPositionIndex=++this.linkedModeCurrentPositionIndex%this.linkedModePositions.length;
this.selectTextForLinkedModePosition(this.linkedModePositions[this.linkedModeCurrentPositionIndex]);return!0}.bind(this));this.textView.setKeyBinding(new k.KeyBinding(9,!1,!0),"previousLinkedModePosition");this.textView.setAction("previousLinkedModePosition",function(){this.linkedModeCurrentPositionIndex=0<this.linkedModeCurrentPositionIndex?this.linkedModeCurrentPositionIndex-1:this.linkedModePositions.length-1;this.selectTextForLinkedModePosition(this.linkedModePositions[this.linkedModeCurrentPositionIndex]);
return!0}.bind(this));this.editor.reportStatus(g.linkedModeEntered,null,!0)}},isActive:function(){return this.linkedModeActive},isStatusActive:function(){return this.linkedModeActive},enter:function(){this.cancel();return!0},cancel:function(d){this.linkedModeActive&&(this.linkedModeActive=!1,this.textView.removeEventListener("Verify",this.linkedModeListener.onVerify),this.textView.setKeyBinding(new k.KeyBinding(9),"tab"),this.textView.setKeyBinding(new k.KeyBinding(9,!1,!0),"shiftTab"),d||this.textView.setCaretOffset(this.linkedModeEscapePosition,
!1),this.editor.reportStatus(g.linkedModeExited,null,!0))},lineUp:function(){this.cancel(!0);return!1},lineDown:function(){this.cancel(!0);return!1},selectTextForLinkedModePosition:function(d){this.textView.setSelection(d.offset,d.offset+d.length)}};return{UndoFactory:s,LineNumberRulerFactory:t,FoldingRulerFactory:u,AnnotationFactory:v,TextDNDFactory:w,TextActions:x,SourceCodeActions:y,LinkedMode:z}});
//# sourceMappingURL=editorFeatures.js.map