//>>built
/*

 Copyright (c) 2011 IBM Corporation and others.
 All rights reserved. This program and the accompanying materials are made 
 available under the terms of the Eclipse Public License v1.0 
 (http://www.eclipse.org/legal/epl-v10.html), and the Eclipse Distribution 
 License v1.0 (http://www.eclipse.org/org/documents/edl-v10.html). 

 Contributors:
     IBM Corporation - initial API and implementation
*/
define("orion/editor/jsContentAssist",[],function(){function k(c,a){return a.substring(c.length)}function q(c,a,b,d,e){for(var g,f,h,l,n=0;n<c.length;n++)if(l=c[n].name,0===l.indexOf(b))if(f=c[n].args,!f||0===f.length)g=l+(c[n].field?"":"()"),f=g+" - "+a,e.push({proposal:k(b,g),description:f});else{g=l+"(";h=[];l=d+l.length+1-b.length;for(var m=0;m<f.length;m++)h.push({offset:l,length:f[m].length}),l+=f[m].length+2,g+=f[m],m<f.length-1&&(g+=", ");g+=")";f=g+" - "+a;l--;e.push({proposal:k(b,g),description:f,
positions:h,escapePosition:l})}}function v(c,a,b){var d=b-c.length,e=[],g="";for(b-=1;0<b;){var f=a.charAt(b--);if("\n"===f||"\r"===f)break;g=/\s/.test(f)?f.concat(g):""}a=g;0==="if".indexOf(c)&&(g="if - if statement",b=[{offset:d+4,length:9}],f=d+a.length+18,e.push({proposal:k(c,"if (condition) {\n"+a+"\t\n"+a+"}"),description:g,positions:b,escapePosition:f}),g="if - if else statement",b=[{offset:d+4,length:9}],f=d+a.length+18,e.push({proposal:k(c,"if (condition) {\n"+a+"\t\n"+a+"} else {\n"+a+"\t\n"+
a+"}"),description:g,positions:b,escapePosition:f}));0==="for".indexOf(c)&&(g="for - iterate over array",b=[{offset:d+9,length:1},{offset:d+20,length:5}],f=d+a.length+42,e.push({proposal:k(c,"for (var i \x3d 0; i \x3c array.length; i++) {\n"+a+"\t\n"+a+"}"),description:g,positions:b,escapePosition:f}),g="for..in - iterate over properties of an object",b=[{offset:d+9,length:8},{offset:d+21,length:6}],f=d+2*a.length+73,e.push({proposal:k(c,"for (var property in object) {\n"+a+"\tif (object.hasOwnProperty(property)) {\n"+
a+"\t\t\n"+a+"\t}\n"+a+"}"),description:g,positions:b,escapePosition:f}));0==="while".indexOf(c)&&(g="while - while loop with condition",b=[{offset:d+7,length:9}],f=d+a.length+21,e.push({proposal:k(c,"while (condition) {\n"+a+"\t\n"+a+"}"),description:g,positions:b,escapePosition:f}));0==="do".indexOf(c)&&(g="do - do while loop with condition",b=[{offset:d+16,length:9}],f=d+a.length+6,e.push({proposal:k(c,"do {\n"+a+"\t\n"+a+"} while (condition);"),description:g,positions:b,escapePosition:f}));0===
"switch".indexOf(c)&&(g="switch - switch case statement",b=[{offset:d+8,length:10},{offset:d+28,length:6}],f=d+2*a.length+38,e.push({proposal:k(c,"switch (expression) {\n"+a+"\tcase value1:\n"+a+"\t\t\n"+a+"\t\tbreak;\n"+a+"\tdefault:\n"+a+"}"),description:g,positions:b,escapePosition:f}));0==="try".indexOf(c)&&(g="try - try..catch statement",f=d+a.length+7,e.push({proposal:k(c,"try {\n"+a+"\t\n"+a+"} catch (err) {\n"+a+"}"),description:g,escapePosition:f}),g="try - try..catch statement with finally block",
f=d+a.length+7,e.push({proposal:k(c,"try {\n"+a+"\t\n"+a+"} catch (err) {\n"+a+"} finally {\n"+a+"}"),description:g,escapePosition:f}));return e}function w(c,a,b){a="break case catch continue debugger default delete do else finally for function if in instanceof new return switch this throw try typeof var void while with".split(" ");b=[];for(var d=0;d<a.length;d++)0===a[d].indexOf(c)&&b.push({proposal:k(c,a[d]),description:a[d]});return b}function p(c,a){var b=c.charAt(a);switch(b){case "/":if("/"===
c.charAt(a+1)){if(a=c.indexOf("\n",a)+2,1===a)return c.length}else if("*"===c.charAt(a+1)){if(a=c.indexOf("*/",a+2)+2,1===a)return c.length}else{var d=c.indexOf("\n",a);0>d&&(d=c.length);for(b=c.indexOf("/",a+1);0<b&&b<d&&"\\"===c.charAt(b-1);)b=c.indexOf("/",b+1);a=0<b&&d>b?b:d;a++}break;case '"':case "'":d=c.indexOf("\n",a);0>d&&(d=c.length);for(var e=c.indexOf(b,a+1);0<e&&e<d&&"\\"===c.charAt(e-1);)e=c.indexOf(b,e+1);a=0<e&&d>e?e:d;a++}return a}function r(c,a){for(var b=a,d=0;b<c.length;){b=p(c,
b);switch(c.charAt(b)){case "{":d++;break;case "}":if(0===--d)return b}b++}return b}function s(c,a){var b=c.substring(0,a),d=b.lastIndexOf("function");return 0<=d?(b=b.indexOf("{",d),b=r(c,b),b<a?s(c,d):c.substring(d,b)):null}function t(c,a,b){var d=[],e,g=s(a,b);b=0;if(g){b=a.indexOf(g);e=g.indexOf("(");var f=g.indexOf(")");if(0<=e&&0<=f){f=g.substring(e+1,f).split(",");for(e=0;e<f.length;e++){var h=f[e].trim();0===h.indexOf(c)&&d.push({proposal:k(c,h),description:h})}}e=g.indexOf("{");0<e&&(g=g.substring(e+
1))}else g=a;e=g;g=[];for(f=0;(f=p(e,f))<e.length;)h=e.substring(f),h.match(/^var\s/)?(h=e.indexOf(";",f),0>h&&(h=e.length),(f=e.substring(f+3,h).match(/[\w]+/))&&g.push(f[0]),f=h+1):h.match(/^function[\s(]/)?f=r(e,f):(h=e.substring(f).match(/^\w[\w\s\()]+/))?f+=h[0].length:f++;for(e=0;e<g.length;e++)0===g[e].indexOf(c)&&d.push({proposal:k(c,g[e]),description:g[e]});0<b&&(d=d.concat(t(c,a,b)));return d}function x(c,a,b){a=a.substring(0,b);var d;d="";for(var e=0;e<a.length;)e=p(a,e),d+=a.charAt(e++);
return t(c,d,b-(a.length-d.length))}function u(){}var y=[{name:"toString"},{name:"toLocaleString"},{name:"valueOf"},{name:"hasOwnProperty",args:["property"]},{name:"isPrototypeOf",args:["object"]},{name:"propertyIsEnumerable",args:["property"]}],z=[{name:"charAt",args:["index"]},{name:"charCodeAt",args:["index"]},{name:"concat",args:["array"]},{name:"indexOf",args:["searchString","[position]"]},{name:"lastIndexOf",args:["searchString","[position]"]},{name:"length",field:!0},{name:"localeCompare",
args:["object"]},{name:"match",args:["regexp"]},{name:"replace",args:["searchValue","replaceValue"]},{name:"search",args:["regexp"]},{name:"slice",args:["start","end"]},{name:"split",args:["separator","[limit]"]},{name:"substring",args:["start","[end]"]},{name:"toLowerCase"},{name:"toLocaleLowerCase"},{name:"toUpperCase"},{name:"toLocaleUpperCase"},{name:"trim"}];u.prototype={computeProposals:function(c,a,b){b=b.prefix;var d=[];if(0<a&&"."===c.charAt(a-b.length-1)){for(var d=[],e=a-1;0<e;){var g=
c.charAt(e);if("\n"===g||"\r"===g)break;e--}c=c.substring(e+1,a-b.length);"String"===(1<c.length&&('"'===c.charAt(c.length-2)||"'"===c.charAt(c.length-2))?"String":null)&&q(z,"String",b,a,d);q(y,"Object",b,a,d);return d}d=d.concat(x(b,c,a-b.length));d=d.concat(v(b,c,a));return d=d.concat(w(b,c,a))}};return{JavaScriptContentAssistProvider:u}});
//# sourceMappingURL=jsContentAssist.js.map