//>>built
/*

 Copyright (c) 2011, 2012 IBM Corporation and others.
 All rights reserved. This program and the accompanying materials are made 
 available under the terms of the Eclipse Public License v1.0 
 (http://www.eclipse.org/legal/epl-v10.html), and the Eclipse Distribution 
 License v1.0 (http://www.eclipse.org/org/documents/edl-v10.html). 

 Contributors:
     IBM Corporation - initial API and implementation
*/
define("orion/editor/mirror",["i18n!orion/editor/nls/messages","orion/editor/eventTarget","orion/editor/annotations"],function(s,t,n){function m(a){this.string=a;this.tokenStart=this.pos=0}function p(a){this._modes={};this.mimeModes={};this.options={};this.StringStream=m}function q(a){var b=[],d;for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&b.push(d);return b}function l(a,b,d){d=d||{};this.model=a;this.codeMirror=b;this.isWhitespaceVisible="undefined"===typeof d.whitespacesVisible?!1:d.whitespacesVisible;
this.mode=null;this.isModeLoaded=!1;this.lines=[];this.dirtyLines=[];this.startLine=Number.MAX_VALUE;this.endLine=-1;this.timer=null;this.initialize(a)}function r(a,b,d){this.init(a,b,d)}m.prototype={eol:function(){return this.pos>=this.string.length},sol:function(){return 0===this.pos},peek:function(){return this.string[this.pos]},next:function(){return this.string[this.pos++]},eat:function(a){var b=this.string[this.pos];return"string"===typeof b&&(b===a||a.test&&a.test(b)||"function"===typeof a&&
a(b))?this.string[this.pos++]:void 0},eatWhile:function(a){for(var b=!1;void 0!==this.eat(a);)b=!0;return b},eatSpace:function(){return this.eatWhile(/\s/)},skipToEnd:function(){this.pos=this.string.length},skipTo:function(a){a=this.string.indexOf(a,this.pos);return-1!==a?(this.pos=a,!0):!1},match:function(a,b,d){b=!0===b||"undefined"===typeof b;if("string"===typeof a){var c=d?this.string.toLowerCase():this.string;a=d?a.toLowerCase():a;d=c.indexOf(a,this.pos);-1!==d&&b&&(this.pos=d+a.length);return-1!==
d}if((a=this.string.substring(this.pos).match(a))&&b&&"string"===typeof a[0])this.pos+=a.index+a[0].length;return a},backUp:function(a){this.pos-=a},column:function(){for(var a=0,b=0;b<this.tokenStart;)a+="\t"===this.string[b++]?4:1;return a},indentation:function(){for(var a=this.string.search(/\S/),b=0,d=0;d<a;)b+="\t"===this.string[d++]?4:1;return b},current:function(){return this.string.substring(this.tokenStart,this.pos)},advance:function(){this.tokenStart=this.pos}};p.prototype={options:{},setOption:function(a,
b){this.options[a]=b},getOption:function(a){return this.options[a]},copyState:function(a,b){if("function"===typeof a.copyState)return a.copyState(b);var d={},c;for(c in b){var e=b[c];d[c]=e instanceof Array?e.slice():e}return d},defineMode:function(a,b){this._modes[a]=b},defineMIME:function(a,b){this.mimeModes[a]=b},getMode:function(a,b){var d={},c;"string"===typeof b&&this.mimeModes[b]&&(b=this.mimeModes[b]);"object"===typeof b&&(d=b,c=this._modes[b.name]);c=c||this._modes[b];if("function"!==typeof c)throw"Mode not found "+
b;return c(a,d)},listModes:function(){return q(this._modes)},listMIMEs:function(){return q(this.mimeModes)},_getModeName:function(a){a=this.mimeModes[a];"object"===typeof a&&(a=a.name);return a}};l.prototype={initialize:function(a){var b=this;this.listener={onModelChanging:function(a){b._onModelChanging(a)},onModelChanged:function(a){b._onModelChanged(a)},onDestroy:function(a){b._onDestroy(a)}};this.model.addEventListener("Changing",this.listener.onModelChanging);this.model.addEventListener("Changed",
this.listener.onModelChanged);this.model.addEventListener("Destroy",this.listener.onDestroy)},destroy:function(){this.model&&(this.model.removeEventListener("Changing",this.listener.onModelChanging),this.model.removeEventListener("Changed",this.listener.onModelChanged),this.model.removeEventListener("Destroy",this.listener.onDestroy));this.dirtyLines=this.lines=this.mode=this.codeMirror=this.model=null;clearTimeout(this.timer);this.timer=null},_onModelChanging:function(a){this.startLine=this.model.getLineAtOffset(a.start)},
_onModelChanged:function(a){this._dbgEvent(a);var b=this.startLine;(a.removedLineCount||a.addedLineCount)&&Array.prototype.splice.apply(this.lines,[b+1,a.removedLineCount].concat(this._newLines(a.addedLineCount)));this.mode&&(a=Math.max(a.addedLineCount,a.removedLineCount),a=b+Math.min(a,500),this.highlight(b,a),this.highlightLater(a+1))},_onDestroy:function(a){this.destroy()},setViewportIndex:function(a){this.viewportIndex=a},_dbgEvent:function(a){},_dbgStyle:function(){},_newLines:function(a,b){for(var d=
[],c=0;c<a;c++)d.push({style:null,eolState:null});return d},setMode:function(a,b){a&&(this.mode=this.codeMirror.getMode(this.codeMirror.options,a),this.lines=this._newLines(this.model.getLineCount()),b&&this.highlight())},highlight:function(a,b,d){if(this.mode){var c=this.model.getLineCount();a="undefined"===typeof a?0:a;b="undefined"===typeof b?c-1:Math.min(b,c-1);for(var c=this.mode,e=this.getState(a),f=a;f<=b;f++){var h=this.lines[f];this.highlightLine(f,h,e);h.eolState=this.codeMirror.copyState(c,
e)}this._expandRange(a,b);if(!d)this.onHighlightDone()}},highlightLater:function(a){this.dirtyLines.push(a);var b=this;this.timer=setTimeout(function(){b._highlightJob()},50)},_highlightJob:function(){for(var a=+new Date+30,b=this.mode.compareStates,d=this.model.getLineCount();this.dirtyLines.length;){var c=this.viewportIndex,e=this.lines[c],c=e&&!e.eolState?c:this.dirtyLines.pop();if(c>=d)break;this._expandRange(c,c);for(var e=this._getResumeLineIndex(c),c=e+1,e=(e=0<=e&&this.lines[e].eolState)?
this.codeMirror.copyState(this.mode,e):this.mode.startState(),f=0,h=c;h<d;h++){var g=this.lines[h],k=g.eolState,l=this.highlightLine(h,g,e);g.eolState=this.codeMirror.copyState(this.mode,e);l&&this._expandRange(c,h+1);var g=b&&k&&b(k,g.eolState),m=!b&&!l&&3<f++;if(g||m)break;else if(!k||l)f=0;k=h<d||this.dirtyLines.length;if(+new Date>a&&k){this.highlightLater(h+1);this.onHighlightDone();return}}}this.onHighlightDone()},onHighlightDone:function(){this.startLine!==Number.MAX_VALUE&&-1!==this.endLine&&
this.dispatchEvent({type:"Highlight",start:this.startLine,end:this.endLine});this.startLine=Number.MAX_VALUE;this.endLine=-1},_getResumeLineIndex:function(a){for(var b=this.lines,d=a-1;0<=d;d--)if(b[d].eolState||40<a-d)return d;return-1},getState:function(a){var b=this.mode,d=this.lines,c,e;for(c=a-1;0<=c&&!(e=d[c],e.eolState||40<a-c);c--);var f=0<=c&&d[c].eolState;if(f){f=this.codeMirror.copyState(b,f);for(c=Math.max(0,c);c<a-1;c++)e=d[c],this.highlightLine(c,e,f),e.eolState=this.codeMirror.copyState(b,
f);return f}return b.startState()},highlightLine:function(a,b,d){if(this.mode){var c=this.model;c.getLineStart(a)===c.getLineEnd(a)&&this.mode.blankLine&&this.mode.blankLine(d);var e=b.style||[];a=c.getLine(a);a=new m(a);for(var c=!b.style,f=[],h=0;!a.eol();h++){var g=this.mode.token(a,d)||null,k=a.current();this._whitespaceStyle(g,k,a.tokenStart);g=[a.tokenStart,a.pos,g];k=e[h];f.push(g);c=c||!k||k[0]!==g[0]||k[1]!==g[1]||k[2]!==g[2];a.advance()}if(c=c||f.length!==e.length)b.style=f.length?f:null;
return c}},_whitespaceStyle:function(a,b,d){if(!a&&this.isWhitespaceVisible&&/\s+/.test(b)){a=[];for(var c,e,f=0;f<b.length;f++){var h=b[f];h!==e&&(e&&a.push([d+c,d+f,"\t"===e?"token_tab":"token_space"]),c=f,e=h)}a.push([d+c,d+f,"\t"===e?"token_tab":"token_space"]);return a}return null},_expandRange:function(a,b){this.startLine=Math.min(this.startLine,a);this.endLine=Math.max(this.endLine,b)},toStyleRangesAndErrors:function(a,b){var d=a.style;if(!d)return null;for(var c=[],e=[],f="undefined"===typeof b?
0:this.model.getLineStart(b),h=0;h<d.length;h++){var g=d[h],k;k=(k=g[2])?"token_tab"===k||"token_space"===k?k:"cm-"+k:null;k&&(g={start:f+g[0],end:f+g[1],style:{styleClass:k}},c.push(g),"cm-error"===k&&e.push(g))}return[c,e]},getLineStyle:function(a){return this.lines[a]},getLineStyles:function(){return this.lines}};t.EventTarget.addMixin(l.prototype);n.AnnotationType.registerType("orion.annotation.highlightError",{title:s.syntaxError,html:"\x3cdiv class\x3d'annotationHTML error'\x3e\x3c/div\x3e",
rangeStyle:{styleClass:"annotationRange error"}});r.prototype={init:function(a,b,d){this.textView=a;this.annotationModel=d;this.modeApplier=new l(a.getModel(),b);var c=this;this.listener={onLineStyle:function(a){c.onLineStyle(a)},onDestroy:function(a){c.onDestroy(a)},onHighlight:function(a){c.onHighlight(a)}};a.addEventListener("LineStyle",this.listener.onLineStyle);a.addEventListener("Destroy",this.listener.onDestroy);this.modeApplier.addEventListener("Highlight",this.listener.onHighlight)},destroy:function(){this.modeApplier&&
(this.modeApplier.removeEventListener("Highlight",this.listener.onHighlight),this.modeApplier.destroy());this.textView&&(this.textView.removeEventListener("LineStyle",this.listener.onLineStyle),this.textView.removeEventListener("Destroy",this.listener.onDestroy));this.listener=this.modeApplier=this.annotationModel=this.textView=null},setMode:function(a){this.modeApplier.setMode(a)},onLineStyle:function(a){var b=a.lineIndex,d=this.modeApplier,c=d.getLineStyle(b);if(!c||!c.eolState){var e=this.textView.getModel().getLineCount();
d.highlight(b,Math.min(b+20,e-1),!0);c=d.getLineStyle(b)}e=this.textView.getModel();if(c){var f=d.toStyleRangesAndErrors(c,b);if(f&&(a.ranges=f[0],a=this.annotationModel)){d=[];c=[];if(f=f[1])for(var h=0;h<f.length;h++){var g=f[h];"cm-error"===g.style.styleClass&&c.push(n.AnnotationType.createAnnotation("orion.annotation.highlightError",g.start,g.end))}for(b=a.getAnnotations(e.getLineStart(b),e.getLineEnd(b));b.hasNext();)e=b.next(),"orion.annotation.highlightError"===e.type&&d.push(e);a.replaceAnnotations(d,
c)}}},onHighlight:function(a){this.textView.redrawLines(a.start,a.end)},onDestroy:function(a){this.destroy()}};return{Mirror:p,ModeApplier:l,CodeMirrorStyler:r}});
//# sourceMappingURL=mirror.js.map