//>>built
/*

 Copyright (c) 2010, 2012 IBM Corporation and others.
 All rights reserved. This program and the accompanying materials are made 
 available under the terms of the Eclipse Public License v1.0 
 (http://www.eclipse.org/legal/epl-v10.html), and the Eclipse Distribution 
 License v1.0 (http://www.eclipse.org/org/documents/edl-v10.html). 

 Contributors: 
  Felipe Heidrich (IBM Corporation) - initial API and implementation
  Silenio Quarti (IBM Corporation) - initial API and implementation
*/
define("orion/editor/projectionTextModel",["orion/editor/textModel","orion/editor/eventTarget"],function(u,v){function q(a){this._model=a;this._projections=[]}q.prototype={addProjection:function(a){if(a){var g=this._model,c=this._projections;a._lineIndex=g.getLineAtOffset(a.start);a._lineCount=g.getLineAtOffset(a.end)-a._lineIndex;var d=a.text;d||(d="");a._model="string"===typeof d?new u.TextModel(d,g.getLineDelimiter()):d;var g=this.mapOffset(a.start,!0),d=a.end-a.start,e=a._lineCount,k=a._model.getCharCount(),
h=a._model.getLineCount()-1,b={type:"Changing",text:a._model.getText(),start:g,removedCharCount:d,addedCharCount:k,removedLineCount:e,addedLineCount:h};this.onChanging(b);b=this._binarySearch(c,a.start);c.splice(b,0,a);this.onChanged({type:"Changed",start:g,removedCharCount:d,addedCharCount:k,removedLineCount:e,addedLineCount:h})}},getProjections:function(){return this._projections.slice(0)},getBaseModel:function(){return this._model},mapOffset:function(a,g){var c=this._projections,d=0,e,k;if(g){for(e=
0;e<c.length;e++){k=c[e];if(k.start>a)break;if(k.end>a)return-1;d+=k._model.getCharCount()-(k.end-k.start)}return a+d}for(e=0;e<c.length;e++){k=c[e];if(k.start>a-d)break;var h=k._model.getCharCount();if(k.start+h>a-d)return-1;d+=h-(k.end-k.start)}return a-d},removeProjection:function(a){var g,c=0;for(g=0;g<this._projections.length;g++){var d=this._projections[g];if(d===a){a=d;break}c+=d._model.getCharCount()-(d.end-d.start)}if(g<this._projections.length){var d=this._model,c=a.start+c,e=a.end-a.start,
k=a._lineCount,h=a._model.getCharCount(),b=a._model.getLineCount()-1;a={type:"Changing",text:d.getText(a.start,a.end),start:c,removedCharCount:h,addedCharCount:e,removedLineCount:b,addedLineCount:k};this.onChanging(a);this._projections.splice(g,1);this.onChanged({type:"Changed",start:c,removedCharCount:h,addedCharCount:e,removedLineCount:b,addedLineCount:k})}},_binarySearch:function(a,g){for(var c=a.length,d=-1,e;1<c-d;)e=Math.floor((c+d)/2),g<=a[e].start?c=e:d=e;return c},getCharCount:function(){for(var a=
this._model.getCharCount(),g=this._projections,c=0;c<g.length;c++)var d=g[c],a=a+(d._model.getCharCount()-(d.end-d.start));return a},getLine:function(a,g){if(0>a)return null;var c=this._model,d=this._projections,e=0,k=[],h=0,b,m,l;for(b=0;b<d.length;b++){l=d[b];if(l._lineIndex>=a-e)break;m=l._model.getLineCount()-1;if(l._lineIndex+m>=a-e){h=a-(l._lineIndex+e);if(h<m)return l._model.getLine(h,g);k.push(l._model.getLine(m))}h=l.end;e+=m-l._lineCount}for(h=Math.max(h,c.getLineStart(a-e));b<d.length;b++){l=
d[b];if(l._lineIndex>a-e)break;k.push(c.getText(h,l.start));m=l._model.getLineCount()-1;if(l._lineIndex+m>a-e)return k.push(l._model.getLine(0,g)),k.join("");k.push(l._model.getText());h=l.end;e+=m-l._lineCount}d=c.getLineEnd(a-e,g);h<d&&k.push(c.getText(h,d));return k.join("")},getLineAtOffset:function(a){for(var g=this._model,c=this._projections,d=0,e=0,k=0;k<c.length;k++){var h=c[k];if(h.start>a-d)break;var b=h._model.getCharCount();if(h.start+b>a-d){c=a-(h.start+d);e+=h._model.getLineAtOffset(c);
d+=c;break}e+=h._model.getLineCount()-1-h._lineCount;d+=b-(h.end-h.start)}return g.getLineAtOffset(a-d)+e},getLineCount:function(){for(var a=this._projections,g=this._model.getLineCount(),c=0;c<a.length;c++)var d=a[c],g=g+(d._model.getLineCount()-1-d._lineCount);return g},getLineDelimiter:function(){return this._model.getLineDelimiter()},getLineEnd:function(a,g){if(0>a)return-1;for(var c=this._model,d=this._projections,e=0,k=0,h=0;h<d.length;h++){var b=d[h];if(b._lineIndex>a-e)break;var m=b._model.getLineCount()-
1;if(b._lineIndex+m>a-e)return b._model.getLineEnd(a-(b._lineIndex+e),g)+b.start+k;k+=b._model.getCharCount()-(b.end-b.start);e+=m-b._lineCount}return c.getLineEnd(a-e,g)+k},getLineStart:function(a){if(0>a)return-1;for(var g=this._model,c=this._projections,d=0,e=0,k=0;k<c.length;k++){var h=c[k];if(h._lineIndex>=a-d)break;var b=h._model.getLineCount()-1;if(h._lineIndex+b>=a-d)return h._model.getLineStart(a-(h._lineIndex+d))+h.start+e;e+=h._model.getCharCount()-(h.end-h.start);d+=b-h._lineCount}return g.getLineStart(a-
d)+e},getText:function(a,g){void 0===a&&(a=0);var c=this._model,d=this._projections,e=0,k=[],h,b,m;for(h=0;h<d.length;h++){b=d[h];if(b.start>a-e)break;m=b._model.getCharCount();if(b.start+m>a-e){if(void 0!==g&&b.start+m>g-e)return b._model.getText(a-(b.start+e),g-(b.start+e));k.push(b._model.getText(a-(b.start+e)));a=b.end+e+m-(b.end-b.start)}e+=m-(b.end-b.start)}var l=a-e;if(void 0!==g){for(;h<d.length;h++){b=d[h];if(b.start>g-e)break;k.push(c.getText(l,b.start));m=b._model.getCharCount();if(b.start+
m>g-e)return k.push(b._model.getText(0,g-(b.start+e))),k.join("");k.push(b._model.getText());l=b.end;e+=m-(b.end-b.start)}k.push(c.getText(l,g-e))}else{for(;h<d.length;h++)b=d[h],k.push(c.getText(l,b.start)),k.push(b._model.getText()),l=b.end;k.push(c.getText(l))}return k.join("")},_onChanging:function(a,g,c,d,e,k){for(var h=this._model,b=this._projections,m,l=0,f,n=g+c;m<b.length;m++){c=b[m];if(c.start>g)break;l+=c._model.getCharCount()-(c.end-c.start)}g+=l;for(var r=m;m<b.length;m++){c=b[m];if(c.start>
n)break;l+=c._model.getCharCount()-(c.end-c.start);f+=c._model.getLineCount()-1-c._lineCount}c=n+l;l=m;this.onChanging(g,c-g,d,e+f,k);b.splice(b,l-r);for(a=a.length-(c-g);m<b.length;m++)c=b[m],c.start+=a,c.end+=a,c._lineIndex=h.getLineAtOffset(c.start)},onChanging:function(a){return this.dispatchEvent(a)},onChanged:function(a){return this.dispatchEvent(a)},setLineDelimiter:function(a){this._model.setLineDelimiter(a)},setText:function(a,g,c){void 0===a&&(a="");void 0===g&&(g=0);var d=g,e=c,k=this._model,
h=this._projections,b=0,m=0,l,f,n,r,t,p=0;for(l=0;l<h.length;l++){f=h[l];if(f.start>g-b)break;n=f._model.getCharCount();if(f.start+n>g-b){if(void 0!==c&&f.start+n>c-b){f._model.setText(a,g-(f.start+b),c-(f.start+b));return}p=f._model.getLineCount()-1-f._model.getLineAtOffset(g-(f.start+b));r={projection:f,start:g-(f.start+b)};g=f.end+b+n-(f.end-f.start)}m+=f._model.getLineCount()-1-f._lineCount;b+=n-(f.end-f.start)}g-=b;var q=l,p=k.getLineAtOffset(g)+m-p;if(void 0!==c)for(;l<h.length;l++){f=h[l];
if(f.start>c-b)break;n=f._model.getCharCount();if(f.start+n>c-b){m+=f._model.getLineAtOffset(c-(f.start+b));n=c-(f.start+b);c=f.end+b;t={projection:f,end:n};break}m+=f._model.getLineCount()-1-f._lineCount;b+=n-(f.end-f.start)}else{for(;l<h.length;l++)f=h[l],m+=f._model.getLineCount()-1-f._lineCount,b+=f._model.getCharCount()-(f.end-f.start);c=e=k.getCharCount()+b}c-=b;f=k.getLineAtOffset(c)+m;for(var e=e-d,m=f-p,p=a.length,s=n=f=b=0;;){-1!==f&&f<=s&&(f=a.indexOf("\r",s));-1!==n&&n<=s&&(n=a.indexOf("\n",
s));if(-1===n&&-1===f)break;s=-1!==f&&-1!==n?f+1===n?n+1:(f<n?f:n)+1:-1!==f?f+1:n+1;b++}this.onChanging({type:"Changing",text:a,start:d,removedCharCount:e,addedCharCount:p,removedLineCount:m,addedLineCount:b});k.setText(a,g,c);r&&(f=r.projection,f._model.setText("",r.start));t&&(f=t.projection,f._model.setText("",0,t.end),f.start=f.end,f._lineCount=0);h.splice(q,l-q);for(a=a.length-(c-g);l<h.length;l++)f=h[l],f.start+=a,f.end+=a,f._lineIndex=k.getLineAtOffset(f.start);this.onChanged({type:"Changed",
start:d,removedCharCount:e,addedCharCount:p,removedLineCount:m,addedLineCount:b})}};v.EventTarget.addMixin(q.prototype);return{ProjectionTextModel:q}});
//# sourceMappingURL=projectionTextModel.js.map