//>>built
/*

 Copyright (c) 2010, 2012 IBM Corporation and others.
 All rights reserved. This program and the accompanying materials are made 
 available under the terms of the Eclipse Public License v1.0 
 (http://www.eclipse.org/legal/epl-v10.html), and the Eclipse Distribution 
 License v1.0 (http://www.eclipse.org/org/documents/edl-v10.html). 

 Contributors: IBM Corporation - initial API and implementation
*/
define("orion/editor/rulers",["i18n!orion/editor/nls/messages","orion/editor/annotations","orion/editor/tooltip","orion/editor/util"],function(u,v,r,w){function h(a,b,c,d){this._location=b||"left";this._overview=c||"page";this._rulerStyle=d;this._view=null;var f=this;this._listener={onTextModelChanged:function(a){f._onTextModelChanged(a)},onAnnotationModelChanged:function(a){f._onAnnotationModelChanged(a)}};this.setAnnotationModel(a)}function p(a,b,c,d,f){h.call(this,a,b,"page",c);this._oddStyle=
d||{style:{backgroundColor:"white"}};this._evenStyle=f||{style:{backgroundColor:"white"}};this._numOfDigits=0}function m(a,b,c){h.call(this,a,b,"page",c)}function k(a,b,c){h.call(this,a,b,"document",c)}function q(a,b,c){m.call(this,a,b,c)}h.prototype={getAnnotations:function(a,b){var c=this._annotationModel;if(!c)return[];var d=this._view.getModel(),f=d.getLineStart(a),e=d.getLineEnd(b-1),g=d;d.getBaseModel&&(g=d.getBaseModel(),f=d.mapOffset(f),e=d.mapOffset(e));for(var n=[],c=this.getAnnotationsByType(c,
f,e),f=0;f<c.length;f++)for(var e=c[f],s=g.getLineAtOffset(e.start),t=g.getLineAtOffset(Math.max(e.start,e.end-1)),h=s;h<=t;h++){var l=h;if(d!==g){l=g.getLineStart(h);l=d.mapOffset(l,!0);if(-1===l)continue;l=d.getLineAtOffset(l)}if(a<=l&&l<b){var m=this._mergeAnnotation(n[l],e,h-s,t-s+1);m&&(n[l]=m)}}if(!this._multiAnnotation&&this._multiAnnotationOverlay)for(var k in n)n[k]._multiple&&(n[k].html+=this._multiAnnotationOverlay.html);return n},getAnnotationModel:function(){return this._annotationModel},
getLocation:function(){return this._location},getOverview:function(){return this._overview},getRulerStyle:function(){return this._rulerStyle},getView:function(){return this._view},getWidestAnnotation:function(){return null},setAnnotationModel:function(a){this._annotationModel&&this._annotationModel.removEventListener("Changed",this._listener.onAnnotationModelChanged);(this._annotationModel=a)&&this._annotationModel.addEventListener("Changed",this._listener.onAnnotationModelChanged)},setMultiAnnotation:function(a){this._multiAnnotation=
a},setMultiAnnotationOverlay:function(a){this._multiAnnotationOverlay=a},setView:function(a){this._onTextModelChanged&&this._view&&this._view.removeEventListener("ModelChanged",this._listener.onTextModelChanged);this._view=a;this._onTextModelChanged&&this._view&&this._view.addEventListener("ModelChanged",this._listener.onTextModelChanged)},onClick:function(a,b){},onDblClick:function(a,b){},onMouseMove:function(a,b){var c=r.Tooltip.getTooltip(this._view);if(c&&!(c.isVisible()&&this._tooltipLineIndex===
a)){this._tooltipLineIndex=a;var d=this;c.setTarget({y:b.clientY,getTooltipInfo:function(){return d._getTooltipInfo(d._tooltipLineIndex,this.y)}})}},onMouseOver:function(a,b){this.onMouseMove(a,b)},onMouseOut:function(a,b){var c=r.Tooltip.getTooltip(this._view);c&&c.setTarget(null)},_getTooltipInfo:function(a,b){if(void 0!==a){var c=this._view,d=c.getModel(),f=this._annotationModel,e=[];if(f){var e=d.getLineStart(a),g=d.getLineEnd(a);d.getBaseModel&&(e=d.mapOffset(e),g=d.mapOffset(g));e=this.getAnnotationsByType(f,
e,g)}f=this._getTooltipContents(a,e);if(!f)return null;f={contents:f,anchor:this.getLocation()};e=c.getClientArea();"document"===this.getOverview()?e.y=c.convert({y:b},"view","document").y:e.y=c.getLocationAtOffset(d.getLineStart(a)).y;c.convert(e,"document","page");f.x=e.x;f.y=e.y;"right"===f.anchor&&(f.x+=e.width);return f}},_getTooltipContents:function(a,b){return b},_onAnnotationModelChanged:function(a){function b(a){for(var b=0;b<a.length;b++)if(f.isAnnotationTypeVisible(a[b].type)){var e=a[b].start,
h=a[b].end;d.getBaseModel&&(e=d.mapOffset(e,!0),h=d.mapOffset(h,!0));-1!==e&&-1!==h&&c.redrawLines(d.getLineAtOffset(e),d.getLineAtOffset(Math.max(e,h-1))+1,f)}}var c=this._view;if(c){var d=c.getModel(),f=this,e=d.getLineCount();a.textModelChangedEvent?(a=a.textModelChangedEvent.start,d.getBaseModel&&(a=d.mapOffset(a,!0)),a=d.getLineAtOffset(a),c.redrawLines(a,e,f)):(b(a.added),b(a.removed),b(a.changed))}},_mergeAnnotation:function(a,b,c,d){a||(a={});0===c&&(a.html&&b.html?(b.html!==a.html&&(!a._multiple&&
this._multiAnnotation)&&(a.html=this._multiAnnotation.html),a._multiple=!0):a.html=b.html);a.style=this._mergeStyle(a.style,b.style);return a},_mergeStyle:function(a,b){if(b){a||(a={});a.styleClass=a.styleClass&&b.styleClass&&a.styleClass!==b.styleClass?a.styleClass+(" "+b.styleClass):b.styleClass;var c;if(b.style)for(c in a.style||(a.style={}),b.style)a.style[c]||(a.style[c]=b.style[c]);if(b.attributes)for(c in a.attributes||(a.attributes={}),b.attributes)a.attributes[c]||(a.attributes[c]=b.attributes[c])}return a}};
v.AnnotationTypeList.addMixin(h.prototype);p.prototype=new h;p.prototype.getAnnotations=function(a,b){for(var c=h.prototype.getAnnotations.call(this,a,b),d=this._view.getModel(),f=a;f<b;f++){var e=f&1?this._oddStyle:this._evenStyle,g=f;d.getBaseModel&&(g=d.getLineStart(g),g=d.getBaseModel().getLineAtOffset(d.mapOffset(g)));c[f]||(c[f]={});c[f].html=g+1+"";c[f].style||(c[f].style=e)}return c};p.prototype.getWidestAnnotation=function(){var a=this._view.getModel().getLineCount();return this.getAnnotations(a-
1,a)[a-1]};p.prototype._onTextModelChanged=function(a){var b=a.start;a=this._view.getModel();var c=((a.getBaseModel?a.getBaseModel().getLineCount():a.getLineCount())+"").length;this._numOfDigits!==c&&(this._numOfDigits=c,b=a.getLineAtOffset(b),this._view.redrawLines(b,a.getLineCount(),this))};m.prototype=new h;k.prototype=new h;k.prototype.getRulerStyle=function(){var a={style:{lineHeight:"1px",fontSize:"1px"}};return a=this._mergeStyle(a,this._rulerStyle)};k.prototype.onClick=function(a,b){void 0!==
a&&this._view.setTopIndex(a)};k.prototype._getTooltipContents=function(a,b){if(0===b.length){var c=this._view.getModel(),d=a;c.getBaseModel&&(d=c.getLineStart(d),d=c.getBaseModel().getLineAtOffset(c.mapOffset(d)));return w.formatMessage(u.line,d+1)}return h.prototype._getTooltipContents.call(this,a,b)};k.prototype._mergeAnnotation=function(a,b,c,d){if(0===c)return a||(a={html:"\x26nbsp;",style:{style:{height:3*d+"px"}}},a.style=this._mergeStyle(a.style,b.overviewStyle)),a};q.prototype=new m;q.prototype.onClick=
function(a,b){if(void 0!==a){var c=this._annotationModel;if(c){var d=this._view.getModel(),f=d.getLineStart(a),e=d.getLineEnd(a,!0);d.getBaseModel&&(f=d.mapOffset(f),e=d.mapOffset(e),d=d.getBaseModel());for(var g,c=c.getAnnotations(f,e);!g&&c.hasNext();)e=c.next(),this.isAnnotationTypeVisible(e.type)&&(g=e);g&&d.getLineAtOffset(g.start)===d.getLineAtOffset(f)&&((d=r.Tooltip.getTooltip(this._view))&&d.setTarget(null),g.expanded?g.collapse():g.expand(),this._annotationModel.modifyAnnotation(g))}}};
q.prototype._getTooltipContents=function(a,b){return 1===b.length&&b[0].expanded?null:m.prototype._getTooltipContents.call(this,a,b)};q.prototype._onAnnotationModelChanged=function(a){function b(a){for(e=0;e<a.length;e++)if(f.isAnnotationTypeVisible(a[e].type)){var b=a[e].start;d.getBaseModel&&(b=d.mapOffset(b,!0));-1!==b&&(h=Math.min(h,d.getLineAtOffset(b)))}}if(a.textModelChangedEvent)m.prototype._onAnnotationModelChanged.call(this,a);else{var c=this._view;if(c){var d=c.getModel(),f=this,e,g=d.getLineCount(),
h=g;b(a.added);b(a.removed);b(a.changed);a=c.getRulers();for(e=0;e<a.length;e++)c.redrawLines(h,g,a[e])}}};return{Ruler:h,AnnotationRuler:m,LineNumberRuler:p,OverviewRuler:k,FoldingRuler:q}});
//# sourceMappingURL=rulers.js.map