//>>built
/*

 Copyright (c) 2010, 2012 IBM Corporation and others.
 All rights reserved. This program and the accompanying materials are made 
 available under the terms of the Eclipse Public License v1.0 
 (http://www.eclipse.org/legal/epl-v10.html), and the Eclipse Distribution 
 License v1.0 (http://www.eclipse.org/org/documents/edl-v10.html). 

 Contributors: 
  Felipe Heidrich (IBM Corporation) - initial API and implementation
  Silenio Quarti (IBM Corporation) - initial API and implementation
*/
define("orion/editor/textModel",["orion/editor/eventTarget","orion/editor/util"],function(u,v){function t(a,e){this._lastLineIndex=-1;this._text=[""];this._lineOffsets=[0];this.setText(a);this.setLineDelimiter(e)}t.prototype={find:function(a){1<this._text.length&&(this._text=[this._text.join("")]);var e=a.string,b=e;!a.regex&&e&&(b=e.replace(/([\\$\^*\/+?\.\(\)|{}\[\]])/g,"\\$\x26"));var c=null,d;if(b){var e=a.reverse,g=a.wrap,l=a.wholeWord,p=a.caseInsensitive,q=a.start||0,s=a.end;a=void 0!==a.end;
var m="";-1===m.indexOf("g")&&(m+="g");p&&-1===m.indexOf("i")&&(m+="i");l&&(b="\\b"+b+"\\b");var f=this._text[0],h,n,k=0;a&&(f=f.substring(q,s),k=q);var r=RegExp(b,m);e?d=function(){var a=null;for(r.lastIndex=0;;){n=r.lastIndex;h=r.exec(f);if(n===r.lastIndex)return null;if(h){if(!(h.index<q)){if(!g||a)break;q=f.length}a={start:h.index+k,end:r.lastIndex+k}}else break}a&&(q=a.start);return a}:(a||(r.lastIndex=q),d=function(){for(;;){n=r.lastIndex;h=r.exec(f);if(n===r.lastIndex)break;if(h)return{start:h.index+
k,end:r.lastIndex+k};if(!(0!==n&&g))break}return null});c=d()}return{next:function(){var a=c;a&&(c=d());return a},hasNext:function(){return null!==c}}},getCharCount:function(){for(var a=0,e=0;e<this._text.length;e++)a+=this._text[e].length;return a},getLine:function(a,e){var b=this.getLineCount();if(!(0<=a&&a<b))return null;var c=this._lineOffsets[a];if(a+1<b){b=this.getText(c,this._lineOffsets[a+1]);if(e)return b;for(var c=b.length,d;10===(d=b.charCodeAt(c-1))||13===d;)c--;return b.substring(0,c)}return this.getText(c)},
getLineAtOffset:function(a){var e=this.getCharCount();if(!(0<=a&&a<=e))return-1;var b=this.getLineCount();if(a===e)return b-1;var c,d,g=this._lastLineIndex;if(0<=g&&g<b&&(c=this._lineOffsets[g],d=g+1<b?this._lineOffsets[g+1]:e,c<=a&&a<d))return g;for(var l=b,p=-1;1<l-p;)if(g=Math.floor((l+p)/2),c=this._lineOffsets[g],d=g+1<b?this._lineOffsets[g+1]:e,a<=c)l=g;else if(a<d){l=g;break}else p=g;return this._lastLineIndex=l},getLineCount:function(){return this._lineOffsets.length},getLineDelimiter:function(){return this._lineDelimiter},
getLineEnd:function(a,e){var b=this.getLineCount();if(!(0<=a&&a<b))return-1;if(a+1<b){b=this._lineOffsets[a+1];if(e)return b;for(var c=this.getText(Math.max(this._lineOffsets[a],b-2),b),d=c.length,g;10===(g=c.charCodeAt(d-1))||13===g;)d--;return b-(c.length-d)}return this.getCharCount()},getLineStart:function(a){return!(0<=a&&a<this.getLineCount())?-1:this._lineOffsets[a]},getText:function(a,e){void 0===a&&(a=0);void 0===e&&(e=this.getCharCount());if(a===e)return"";for(var b=0,c=0,d;c<this._text.length;){d=
this._text[c].length;if(a<=b+d)break;b+=d;c++}for(var g=b,l=c;c<this._text.length;){d=this._text[c].length;if(e<=b+d)break;b+=d;c++}if(l===c)return this._text[l].substring(a-g,e-b);g=this._text[l].substring(a-g);b=this._text[c].substring(0,e-b);return g+this._text.slice(l+1,c).join("")+b},onChanging:function(a){return this.dispatchEvent(a)},onChanged:function(a){return this.dispatchEvent(a)},setLineDelimiter:function(a,e){"auto"===a&&(a=void 0,1<this.getLineCount()&&(a=this.getText(this.getLineEnd(0),
this.getLineEnd(0,!0))));this._lineDelimiter=a?a:v.platformDelimiter;if(e){var b=this.getLineCount();if(1<b){for(var c=Array(b),d=0;d<b;d++)c[d]=this.getLine(d);this.setText(c.join(this._lineDelimiter))}}},setText:function(a,e,b){void 0===a&&(a="");void 0===e&&(e=0);void 0===b&&(b=this.getCharCount());if(!(e===b&&""===a)){for(var c=this.getLineAtOffset(e),d=this.getLineAtOffset(b),g=e,l=b-e,p=d-c,q=a.length,s=0,m=this.getLineCount(),f=0,h=0,n=0,k=[];;){-1!==f&&f<=n&&(f=a.indexOf("\r",n));-1!==h&&
h<=n&&(h=a.indexOf("\n",n));if(-1===h&&-1===f)break;n=-1!==f&&-1!==h?f+1===h?h+1:(f<h?f:h)+1:-1!==f?f+1:h+1;k.push(e+n);s++}this.onChanging({type:"Changing",text:a,start:g,removedCharCount:l,addedCharCount:q,removedLineCount:p,addedLineCount:s});0===k.length&&(f=this.getLineStart(c),d=d+1<m?this.getLineStart(d+1):this.getCharCount(),e!==f&&(a=this.getText(f,e)+a,e=f),b!==d&&(a+=this.getText(b,d),b=d));d=q-l;for(f=c+p+1;f<m;f++)this._lineOffsets[f]+=d;c=[c+1,p].concat(k);Array.prototype.splice.apply(this._lineOffsets,
c);for(d=k=0;d<this._text.length;){f=this._text[d].length;if(e<=k+f)break;k+=f;d++}m=k;for(c=d;d<this._text.length;){f=this._text[d].length;if(b<=k+f)break;k+=f;d++}f=this._text[d];e=this._text[c].substring(0,e-m);b=f.substring(b-k);c=[c,d-c+1];e&&c.push(e);a&&c.push(a);b&&c.push(b);Array.prototype.splice.apply(this._text,c);0===this._text.length&&(this._text=[""]);this.onChanged({type:"Changed",start:g,removedCharCount:l,addedCharCount:q,removedLineCount:p,addedLineCount:s})}}};u.EventTarget.addMixin(t.prototype);
return{TextModel:t}});
//# sourceMappingURL=textModel.js.map