//>>built
/*

 Copyright (c) 2011, 2012 IBM Corporation and others.
 All rights reserved. This program and the accompanying materials are made 
 available under the terms of the Eclipse Public License v1.0 
 (http://www.eclipse.org/legal/epl-v10.html), and the Eclipse Distribution 
 License v1.0 (http://www.eclipse.org/org/documents/edl-v10.html). 

 Contributors: IBM Corporation - initial API and implementation 
*/
define("orion/editor/textMateStyler",["orion/editor/regex"],function(z){function A(a,d,c){c=d.textView._parent.ownerDocument;var b=d._stylesheet=d.util.createElement(c,"style");b.appendChild(c.createTextNode(d._styleSheet(a,"",d.util)));(c.getElementsByTagName("head")[0]||c.documentElement).appendChild(b);d.textView.update(!0)}function B(a,d){var c,b=this;a.getPreferences("/settings",2).then(function(a){if(void 0!==a.get("JavaScript Editor")&&(c=JSON.parse(a.get("JavaScript Editor"))))b._stylesheet&&
(b._stylesheet.parentNode.removeChild(b._stylesheet),b._stylesheet=null),b._update(c,b,d)})}function C(a,d){for(var c=[],b=0;b<a.length;b++)c[a[b].element]=a[b].value;b=[];b.push("");var e=c.fontFamily,e="sans serif"===e?'"Menlo", "Consolas", "Vera Mono", "monospace"':"monospace";b.push(d+" .textviewContainer {");b.push("\background-color:"+c.background+";");b.push("\tfont-family: "+e+";");b.push("\tfont-size: "+c.fontSize+";");b.push("\tmin-width: 50px;");b.push("\tmin-height: 50px;");b.push("\tcolor: "+
c.text+";");b.push("}");b.push(d+" {");b.push("\tfont-family: "+e+";");b.push("\tfont-size: "+c.fontSize+";");b.push("\tcolor: "+c.text+";");b.push("}");b.push(d+" .textview {");b.push("\tbackground-color: "+c.background+";");b.push("}");b.push(d+".ruler.annotations{");b.push("\tbackground-color: white;");b.push("}");b.push(d+" .ruler {");b.push("\tbackground-color: "+c.annotationRuler+";");b.push("}");b.push(d+" .rulerLines {");b.push("\tcolor: "+c.lineNumber+";");b.push("\tbackground-color: "+c.annotationRuler+
";");b.push("}");b.push(d+" .rulerLines.even {");b.push("\tcolor: "+c.lineNumber+";");b.push("\tbackground-color: "+c.annotationRuler+";");b.push("}");b.push(d+" .rulerLines.odd {");b.push("\tcolor: "+c.lineNumber+";");b.push("\tbackground-color: "+c.annotationRuler+";");b.push("}");b.push(d+" .annotationLine.currentLine {");b.push("\tbackground-color: "+c.currentLine+";");b.push("}");b.push(d+" .entity-name-tag {");b.push("color: "+c.keyword+";");b.push("}");return b.join("\n")}function v(a){var d;
if(a instanceof Array){d=Array(a.length);for(var c=0;c<a.length;c++)d[c]=v(a[c])}else for(c in d={},a)if(Object.prototype.hasOwnProperty.call(a,c)){var b=a[c];d[c]="object"===typeof b&&null!==b?v(b):b}return d}function y(a,d,c,b,e){this.initialize(a,b);this.grammar=v(d);this.externalGrammars=c?v(c):[];this._styles={};this._tree=null;this._allGrammars={};this.preprocess(this.grammar);this._updateStylesheet=B;this._update=A;this._styleSheet=C;this.util=e}var x,s={unsupported:[{regex:/\(\?[ims\-]:/,
func:function(a){return"option on/off for subexp"}},{regex:/\(\?<([=!])/,func:function(a){return"\x3d"===a[1]?"lookbehind":"negative lookbehind"}},{regex:/\(\?>/,func:function(a){return"atomic group"}}],toRegExp:function(a){function d(d,a){throw Error('Unsupported regex feature "'+d+'": "'+a[0]+'" at index: '+a.index+" in "+a.input);}var c="",b;a=s.processGlobalFlag("x",a,function(d){for(var a="",b=!1,c=d.length,e=0;e<c;){var l=d.charAt(e);if(!b&&"#"===l)for(;e<c&&"\r"!==l&&"\n"!==l;)l=d.charAt(++e);
else if(!b&&/\s/.test(l))for(;e<c&&/\s/.test(l);)l=d.charAt(++e);else"\\"===l?(a+=l,/\s/.test(d.charAt(e+1))||(a+=d.charAt(e+1),e+=1)):("["===l?b=!0:"]"===l&&(b=!1),a+=l),e+=1}return a});a=s.processGlobalFlag("i",a,function(a){c+="i";return a});for(b=0;b<this.unsupported.length;b++){var e;(e=this.unsupported[b].regex.exec(a))&&d(this.unsupported[b].func(e),e)}return RegExp(a,c)},processGlobalFlag:function(a,d,c){var b="(?"+a+")";a="(?"+a+":";if(d.substring(0,b.length)===b)return c(d.substring(b.length));
if(d.substring(0,a.length)===a){for(var b=0,e=d.length,g=-1,f=0;f<e&&-1===g;f++)switch(d.charAt(f)){case "\\":f++;break;case "(":b++;break;case ")":b--,0===b&&(g=f)}b=g;if(b<d.length-1)throw Error("Only a "+a+") group that encloses the entire regex is supported in: "+d);return c(d.substring(a.length,b))}return d},hasBackReference:function(a){return/\\\d+/.test(a.source)},getSubstitutedRegex:function(a,d,c){c="undefined"===typeof c?!0:!1;a=a.source.split(/(\\\d+)/g);for(var b=[],e=0;e<a.length;e++){var g=
a[e],f=/\\(\d+)/.exec(g);f?(g=d[f[1]]||"",b.push(c?z.escape(g):g)):b.push(g)}return RegExp(b.join(""))},groupify:function(a,d){for(var c=a.source,b=c.length,e=[],g=0,f=[],q=1,h=1,k=[],l={},n={},r=0;r<b;r++){var m=e[e.length-1],u=c.charAt(r);switch(u){case "(":4===m&&(e.pop(),k.push(")"),f[f.length-1].end=r);var t=r+2<b?c.charAt(r+1)+""+c.charAt(r+2):null;if("?:"===t||"?\x3d"===t||"?!"===t){var p;"?:"===t?p=1:(p=3,g++);e.push(p);f.push({start:r,end:-1,type:p});k.push(u);k.push(t);r+=t.length}else e.push(2),
f.push({start:r,end:-1,type:2,oldNum:q,num:h}),k.push(u),0===g&&(n[h]=null),l[q]=h,q++,h++;break;case ")":m=e.pop();3===m&&g--;f[f.length-1].end=r;k.push(u);break;case "*":case "+":case "?":case "}":var s=u,w=c.charAt(r-1),t=r-1;if("}"===u){for(p=r-1;"{"!==c.charAt(p)&&0<=p;p--);w=c.charAt(p-1);t=p-1;s=c.substring(p,r+1)}p=f[f.length-1];if(")"===w&&(2===p.type||4===p.type)){k.splice(p.start,0,"(");k.push(s);k.push(")");u={start:p.start,end:k.length-1,type:4,num:p.num};for(w=0;w<f.length;w++)if(m=
f[w],(2===m.type||4===m.type)&&m.start>=p.start&&m.end<=t)m.start+=1,m.end+=1,m.num+=1,2===m.type&&(l[m.oldNum]=m.num);f.push(u);h++;break}default:"|"!==u&&(2!==m&&4!==m)&&0===g&&(e.push(4),f.push({start:r,end:-1,type:4,num:h}),k.push("("),n[h]=null,h++),k.push(u),"\\"===u&&(u=c.charAt(r+1),k.push(u),r+=1)}}for(;e.length;)e.pop(),k.push(")");c=RegExp(k.join(""));b={};d=d||l;for(var v in d)d.hasOwnProperty(v)&&(b[v]="\\"+d[v]);c=this.getSubstitutedRegex(c,b,!1);return[c,l,n]},complexCaptures:function(a){if(!a)return!1;
for(var d in a)if(a.hasOwnProperty(d)&&"0"!==d)return!0;return!1}};y.prototype={initialize:function(a,d,c){this.textView=a;this.textView.stylerOptions=this;var b=this;this.textView&&d&&d.startup().then(function(a){x=a.preferences;b.preferences=x;b._updateStylesheet(x,c);b.storageKey=x.listenForChangedSettings(b._listener.onStorage)});this._listener={onModelChanged:function(a){b.onModelChanged(a)},onDestroy:function(a){b.onDestroy(a)},onLineStyle:function(a){b.onLineStyle(a)},onStorage:function(a){b.onStorage(a)}};
a.addEventListener("ModelChanged",this._listener.onModelChanged);a.addEventListener("Destroy",this._listener.onDestroy);a.addEventListener("LineStyle",this._listener.onLineStyle);a.redrawLines()},onDestroy:function(a){this.destroy()},onStorage:function(a){a.key===this.storageKey&&this._updateStylesheet(this.preferences)},destroy:function(){this.textView&&(this.textView.removeEventListener("ModelChanged",this._listener.onModelChanged),this.textView.removeEventListener("Destroy",this._listener.onDestroy),
this.textView.removeEventListener("LineStyle",this._listener.onLineStyle),this.textView=null);this._listener=this._tree=this._styles=this.grammar=null},preprocess:function(a){for(a=[a];0!==a.length;){var d=a.pop();if(!d._resolvedRule||!d._typedRule)if(d._resolvedRule=this._resolve(d),d._typedRule=this._createTypedRule(d),this.addStyles(d.name),this.addStyles(d.contentName),this.addStylesForCaptures(d.captures),this.addStylesForCaptures(d.beginCaptures),this.addStylesForCaptures(d.endCaptures),d._resolvedRule!==
d&&a.push(d._resolvedRule),d.patterns)for(var c=0;c<d.patterns.length;c++)a.push(d.patterns[c])}},addStyles:function(a){if(a&&!this._styles[a]){this._styles[a]=[];for(var d=a.split("."),c=0;c<d.length;c++)this._styles[a].push(d.slice(0,c+1).join("-"))}},addStylesForCaptures:function(a){for(var d in a)a.hasOwnProperty(d)&&this.addStyles(a[d].name)},ContainerRule:function(){function a(a){this.rule=a;this.subrules=a.patterns}a.prototype.valueOf=function(){return"aa"};return a}(),BeginEndRule:function(){function a(a){this.rule=
a;this.beginRegex=s.toRegExp(a.begin);this.endRegex=s.toRegExp(a.end);this.subrules=a.patterns||[];this.endRegexHasBackRef=s.hasBackReference(this.endRegex);var c=s.complexCaptures(a.captures);a=s.complexCaptures(a.beginCaptures)||s.complexCaptures(a.endCaptures);if(this.isComplex=c||a)c=s.groupify(this.beginRegex),this.beginRegex=c[0],this.beginOld2New=c[1],this.beginConsuming=c[2],c=s.groupify(this.endRegex,this.beginOld2New),this.endRegex=c[0],this.endOld2New=c[1],this.endConsuming=c[2]}a.prototype.valueOf=
function(){return this.beginRegex};return a}(),MatchRule:function(){function a(a){this.rule=a;this.matchRegex=s.toRegExp(a.match);if(this.isComplex=s.complexCaptures(a.captures))a=s.groupify(this.matchRegex),this.matchRegex=a[0],this.matchOld2New=a[1],this.matchConsuming=a[2]}a.prototype.valueOf=function(){return this.matchRegex};return a}(),_createTypedRule:function(a){return a.match?new this.MatchRule(a):a.begin?new this.BeginEndRule(a):new this.ContainerRule(a)},_resolve:function(a){var d=a;if(a.include){if(a.begin||
a.end||a.match)throw Error('Unexpected regex pattern in "include" rule '+a.include);a=a.include;if("#"===a.charAt(0)){if(d=this.grammar.repository&&this.grammar.repository[a.substring(1)],!d)throw Error("Couldn't find included rule "+a+" in grammar repository");}else if("$self"===a)d=this.grammar;else{if("$base"===a)throw Error('Include "$base" is not supported');d=this._allGrammars[a];if(!d)for(var c=0;c<this.externalGrammars.length;c++){var b=this.externalGrammars[c];if(b.scopeName===a){this.preprocess(b);
d=this._allGrammars[a]=b;break}}}}return d},ContainerNode:function(){function a(a,c){this.parent=a;this.rule=c;this.children=[];this.end=this.start=null}a.prototype.addChild=function(a){this.children.push(a)};a.prototype.valueOf=function(){var a=this.rule;return"ContainerNode { "+(a.include||"")+" "+(a.name||"")+(a.comment||"")+"}"};return a}(),BeginEndNode:function(){function a(a,c,b){this.parent=a;this.rule=c;this.children=[];this.setStart(b);this.endMatch=this.end=null;this.endRegexSubstituted=
c.endRegexHasBackRef?s.getSubstitutedRegex(c.endRegex,b):null}a.prototype.addChild=function(a){this.children.push(a)};a.prototype.getIndexInParent=function(a){return this.parent?this.parent.children.indexOf(this):-1};a.prototype.setStart=function(a){this.start=a.index;this.beginMatch=a};a.prototype.setEnd=function(a){a&&"object"===typeof a?(this.endMatch=a,this.end=a.index+a[0].length):(this.endMatch=null,this.end=a)};a.prototype.shiftStart=function(a){this.start+=a;this.beginMatch.index+=a};a.prototype.shiftEnd=
function(a){this.end+=a;this.endMatch&&(this.endMatch.index+=a)};a.prototype.valueOf=function(){return"{"+this.rule.beginRegex+" range\x3d"+this.start+".."+this.end+"}"};return a}(),push:function(a,d){if(d)for(var c=d.length;0<c;)a.push(d[--c])},exec:function(a,d,c){if(d=a.exec(d))d.index+=c;a.lastIndex=0;return d},afterMatch:function(a){return a.index+a[0].length},getEndMatch:function(a,d,c){if(a instanceof this.BeginEndNode){var b=a.rule;a=a.endRegexSubstituted||b.endRegex;return!a?null:this.exec(a,
d,c)}return null},initialParse:function(){this.textView.getModel().getCharCount();this._tree=new this.ContainerNode(null,this.grammar._typedRule);this.parse(this._tree,!1,0)},onModelChanged:function(a){var d=a.addedCharCount,c=a.removedCharCount;a=a.start;if(this._tree){var b=this.textView.getModel(),e=b.getCharCount(),b=b.getLineEnd(b.getLineAtOffset(a)-1),g=this.getFirstDamaged(b,b),b=-1===b?0:b,d=g?this.parse(g,!0,b,a,d,c):e;this.textView.redrawRange(b,d)}else this.initialParse()},getFirstDamaged:function(a,
d){if(0>a)return this._tree;for(var c=[this._tree],b=null;c.length;){var e=c.pop();if(!e.parent||this.isDamaged(e,a,d)){e instanceof this.BeginEndNode&&(b=e);for(var g=0;g<e.children.length;g++)c.push(e.children[g])}}return b||this._tree},isDamaged:function(a,d,c){return a.start<=c&&a.end>d},parse:function(a,d,c,b,e,g){var f=this.textView.getModel(),q=f.getLineStart(f.getLineCount()-1),h=f.getCharCount(),k=this.getInitialExpected(a,c),l=-1;d&&(a.repaired=!0,a.endNeedsUpdate=!0,l=(l=a.children[a.children.length-
1])?f.getLineEnd(f.getLineAtOffset(l.end+(e-g))):-1,b=f.getLineEnd(f.getLineAtOffset(b+g)),l=Math.max(l,b));l=-1===l?h:l;b=k;for(var n=a,r=!1,m=c,s=-1;n&&(!d||m<l);){var t=this.getNextMatch(f,n,m);t||(m=m>=q?h:f.getLineStart(f.getLineAtOffset(m)+1));var p=t&&t.match,v=t&&t.rule,w=t&&t.isEnd;if(t&&t.isSub)m=this.afterMatch(p),v instanceof this.BeginEndRule&&(r=!0,d&&v===b.rule&&n===b.parent?(n=b,n.setStart(p),n.repaired=!0,n.endNeedsUpdate=!0,b=this.getNextExpected(b,"begin")):(d&&(this.prune(n,b),
d=!1),p=new this.BeginEndNode(n,v,p),n.addChild(p),n=p));else if(w||m===h)n instanceof this.BeginEndNode&&(p?(r=!0,s=Math.max(s,n.end),n.setEnd(p),m=this.afterMatch(p),d&&n===b&&n.parent===b.parent?(n.repaired=!0,delete n.endNeedsUpdate,b=this.getNextExpected(b,"end")):d&&(this.prune(n,b),d=!1)):(n.setEnd(h),delete n.endNeedsUpdate)),n=n.parent;d&&(m>=l&&!r)&&(this.prune(a,k),d=!1)}this.removeUnrepairedChildren(a,d,c);this.cleanup(d,a,c,l,h,e,g);return d?Math.max(s,m):m},removeUnrepairedChildren:function(a,
d,c){if(d){d=a.children;for(var b=-1,e=0;e<d.length;e++){var g=d[e];if(!g.repaired&&this.isDamaged(g,c,Number.MAX_VALUE)){b=e;break}}-1!==b&&(a.children.length=b)}},cleanup:function(a,d,c,b,e,g,f){if(a){a=g-f;e=this.getIntersecting(b-a+1,e);d=this.getIntersecting(c,b);for(c=0;c<e.length;c++)b=e[c],!b.repaired&&b instanceof this.BeginEndNode&&(b.shiftEnd(a),b.shiftStart(a));for(c=0;c<d.length;c++)b=d[c],b.repaired&&b.endNeedsUpdate&&b.shiftEnd(a),delete b.endNeedsUpdate,delete b.repaired}else{d=this.getIntersecting(c,
b);for(c=0;c<d.length;c++)delete d[c].repaired}},getNextMatch:function(a,d,c,b){var e=a.getLineAtOffset(c),e=a.getLineEnd(e),g=a.getText(c,e),f=[],q=[];a=[];e=[];for(this.push(f,d.rule.subrules);f.length;){var h=f.length?f.pop():null,h=h&&h._resolvedRule._typedRule;if(h instanceof this.ContainerRule&&-1===q.indexOf(h))q.push(h),this.push(f,h.subrules);else if(!h||!b||h.matchRegex){var k=h&&this.exec(h.matchRegex||h.beginRegex,g,c);k&&(a.push(k),e.push(h))}}f=Number.MAX_VALUE;q=-1;for(h=0;h<a.length;h++)k=
a[h],k.index<f&&(f=k.index,q=h);if(!b&&(c=this.getEndMatch(d,g,c)))if(b=d.rule.applyEndPatternLast,-1===q||c.index<f||!b&&c.index===f)return{isEnd:!0,rule:d.rule,match:c};return-1===q?null:{isSub:!0,rule:e[q],match:a[q]}},getInitialExpected:function(a,d){var c,b;if(a===this._tree)for(c=0;c<a.children.length;c++){if(b=a.children[c],b.start>=d)return b}else if(a instanceof this.BeginEndNode&&a.endMatch){var e=a.endMatch.index;for(c=0;c<a.children.length&&!(b=a.children[c],b.start>=d);c++);if(b&&b.start<
e)return b}return a},getNextExpected:function(a,d){if("begin"===d){var c=a.children[0];return c?c:a}if("end"===d&&(c=a.parent)){var b=c.children[c.children.indexOf(a)+1];return b?b:c}return null},prune:function(a,d){d.parent===a?a.children.length=d.getIndexInParent():a instanceof this.BeginEndNode&&(a.endMatch=null,a.end=null);a.parent&&(a.parent.children.length=a.getIndexInParent()+1)},onLineStyle:function(a){this._tree||this.initialParse();var d=a.lineStart,c=this.textView.getModel(),b=c.getLineEnd(a.lineIndex),
e=c.getLineEnd(c.getLineAtOffset(d)-1),e=this.getFirstDamaged(e,e),d=this.getLineScope(c,e,d,b);a.ranges=this.toStyleRanges(d);a.ranges.sort(function(a,b){return a.start-b.start})},getLineScope:function(a,d,c,b){for(var e=c,g=this.getInitialExpected(d,c),f=[],q=[];d&&e<b;){var h=this.getNextMatch(a,d,e);if(!h)break;var k=h&&h.match,l=h&&h.rule,n=h&&h.isSub,h=h&&h.isEnd;k.index!==e&&q.push({start:e,end:k.index,node:d});n?(e=this.afterMatch(k),l instanceof this.BeginEndRule?(this.addBeginScope(f,k,
l),d=g,g=this.getNextExpected(g,"begin")):this.addMatchScope(f,k,l)):h&&(e=this.afterMatch(k),this.addEndScope(f,k,l),g=this.getNextExpected(g,"end"),d=d.parent)}e<b&&q.push({start:e,end:b,node:d});a=this.getInheritedLineScope(q,c,b);return f.concat(a)},getInheritedLineScope:function(a,d,c){d=[];for(c=0;c<a.length;c++)for(var b=a[c],e=b.node;e;){var g=e.rule.rule,f=g.name;if(g=g.contentName||f){this.addScopeRange(d,b.start,b.end,g);break}e=e.parent}return d},addBeginScope:function(a,d,c){var b=c.rule;
this.addCapturesScope(a,d,b.beginCaptures||b.captures,c.isComplex,c.beginOld2New,c.beginConsuming)},addEndScope:function(a,d,c){var b=c.rule;this.addCapturesScope(a,d,b.endCaptures||b.captures,c.isComplex,c.endOld2New,c.endConsuming)},addMatchScope:function(a,d,c){var b=c.rule,e=b.name;(b=b.captures)?this.addCapturesScope(a,d,b,c.isComplex,c.matchOld2New,c.matchConsuming):this.addScope(a,d,e)},addScope:function(a,d,c){c&&a.push({start:d.index,end:this.afterMatch(d),scope:c})},addScopeRange:function(a,
d,c,b){b&&a.push({start:d,end:c,scope:b})},addCapturesScope:function(a,d,c,b,e,g){if(c)if(b){b={1:0};for(var f=0,q=1;void 0!==d[q];q++)void 0!==g[q]&&(f+=d[q].length),void 0!==d[q+1]&&(b[q+1]=f);g=d.index;for(f=1;c[f];f++){var q=c[f].name,h=e[f],k=g+b[h];"undefined"!==typeof d[h]&&this.addScopeRange(a,k,k+d[h].length,q)}}else this.addScope(a,d,c[0]&&c[0].name)},getIntersecting:function(a,d){for(var c=[],b=this._tree?[this._tree]:[];b.length;){var e=b.pop(),g=!1;e instanceof this.ContainerNode?g=!0:
this.isDamaged(e,a,d)&&(g=!0,c.push(e));if(g)for(var g=e.children.length,f=0;f<g;f++)b.push(e.children[f])}return c.reverse()},toStyleRanges:function(a){for(var d=[],c=0;c<a.length;c++){var b=a[c],e=this._styles[b.scope];if(!e)throw Error("styles not found for "+b.scope);e=e.join(" ");d.push({start:b.start,end:b.end,style:{styleClass:e}})}return d}};return{RegexUtil:s,TextMateStyler:y}});
//# sourceMappingURL=textMateStyler.js.map