//>>built
/*

 Copyright (c) 2010, 2012 IBM Corporation and others.
 All rights reserved. This program and the accompanying materials are made 
 available under the terms of the Eclipse Public License v1.0 
 (http://www.eclipse.org/legal/epl-v10.html), and the Eclipse Distribution 
 License v1.0 (http://www.eclipse.org/org/documents/edl-v10.html). 

 Contributors: IBM Corporation - initial API and implementation
*/
define("orion/editor/tooltip",["i18n!orion/editor/nls/messages","orion/editor/textView","orion/editor/textModel","orion/editor/projectionTextModel","orion/editor/util"],function(p,q,r,m,n){function k(a){this._view=a;this._create(a.getOptions("parent").ownerDocument);a.addEventListener("Destroy",this,this.destroy)}k.getTooltip=function(a){a._tooltip||(a._tooltip=new k(a));return a._tooltip};k.prototype={_create:function(a){if(!this._tooltipDiv){var e=this._tooltipDiv=n.createElement(a,"div");e.className=
"textviewTooltip";e.setAttribute("aria-live","assertive");e.setAttribute("aria-atomic","true");var b=this._tooltipContents=n.createElement(a,"div");e.appendChild(b);a.body.appendChild(e);this.hide()}},_getWindow:function(){var a=this._tooltipDiv.ownerDocument;return a.defaultView||a.parentWindow},destroy:function(){if(this._tooltipDiv){this.hide();var a=this._tooltipDiv.parentNode;a&&a.removeChild(this._tooltipDiv);this._tooltipDiv=null}},hide:function(){this._contentsView&&(this._contentsView.destroy(),
this._contentsView=null);this._tooltipContents&&(this._tooltipContents.innerHTML="");this._tooltipDiv&&(this._tooltipDiv.style.visibility="hidden");var a=this._getWindow();this._showTimeout&&(a.clearTimeout(this._showTimeout),this._showTimeout=null);this._hideTimeout&&(a.clearTimeout(this._hideTimeout),this._hideTimeout=null);this._fadeTimeout&&(a.clearInterval(this._fadeTimeout),this._fadeTimeout=null)},isVisible:function(){return this._tooltipDiv&&"visible"===this._tooltipDiv.style.visibility},
setTarget:function(a,e){if(this.target!==a&&(this._target=a,this.hide(),a)){var b=this;if(0===e)b.show(!0);else{var d=this._getWindow();b._showTimeout=d.setTimeout(function(){b.show(!0)},e?e:500)}}},show:function(a){if(this._target){var e=this._target.getTooltipInfo();if(e){var b=this._tooltipDiv,d=this._tooltipContents;b.style.left=b.style.right=b.style.width=b.style.height=d.style.width=d.style.height="auto";var c=e.contents;c instanceof Array&&(c=this._getAnnotationContents(c));if("string"===typeof c)d.innerHTML=
c;else if(this._isNode(c))d.appendChild(c);else if(c instanceof m.ProjectionTextModel){var g=this._view,f=g.getOptions();f.wrapMode=!1;f.parent=d;var h=f.themeClass;h?((h=h.replace("tooltip",""))&&(h=" "+h),h="tooltip"+h):h="tooltip";f.themeClass=h;f=this._contentsView=new q.TextView(f);f._clientDiv.contentEditable=!1;f.addEventListener("LineStyle",function(a){g.onLineStyle(a)});f.setModel(c);c=f.computeSize();d.style.width=c.width+20+"px";d.style.height=c.height+"px";f.resize()}else return;d=b.ownerDocument.documentElement;
"right"===e.anchor?(c=d.clientWidth-e.x,b.style.right=c+"px"):(c=parseInt(this._getNodeStyle(b,"padding-left","0"),10),c+=parseInt(this._getNodeStyle(b,"border-left-width","0"),10),c=e.x-c,b.style.left=c+"px");b.style.maxWidth=d.clientWidth-c-10+"px";c=parseInt(this._getNodeStyle(b,"padding-top","0"),10);c+=parseInt(this._getNodeStyle(b,"border-top-width","0"),10);c=e.y-c;b.style.top=c+"px";b.style.maxHeight=d.clientHeight-c-10+"px";b.style.opacity="1";b.style.visibility="visible";if(a){var l=this,
k=this._getWindow();l._hideTimeout=k.setTimeout(function(){var a=parseFloat(l._getNodeStyle(b,"opacity","1"));l._fadeTimeout=k.setInterval(function(){"visible"===b.style.visibility&&0<a?(a-=0.1,b.style.opacity=a):l.hide()},50)},5E3)}}}},_getAnnotationContents:function(a){function e(a){var b=a.title;if(""===b)return null;var c="\x3cdiv\x3e";a.html&&(c+=a.html+"\x26nbsp;");b||(b=a.end,a=d.getLineStart(d.getLineAtOffset(a.start)),b=d.getLineEnd(d.getLineAtOffset(b),!0),b=d.getText(a,b));b=b.replace(/</g,
"\x26lt;").replace(/>/g,"\x26gt;");return c+("\x3cspan style\x3d'vertical-align:middle;'\x3e"+b+"\x3c/span\x3e\x3cdiv\x3e")}if(0===a.length)return null;var b=this._view.getModel(),d=b.getBaseModel?b.getBaseModel():b;if(1===a.length){b=a[0];if(void 0!==b.title)return e(b);a=new m.ProjectionTextModel(d);var c=d.getLineStart(d.getLineAtOffset(b.start)),g=d.getCharCount();b.end!==g&&a.addProjection({start:b.end,end:g});0<c&&a.addProjection({start:0,end:c});return a}c="\x3cdiv\x3e\x3cem\x3e"+p.multipleAnnotations+
"\x3c/em\x3e\x3c/div\x3e";for(g=0;g<a.length;g++)b=a[g],(b=e(b))&&(c+=b);return c},_getNodeStyle:function(a,e,b){var d;if(a&&(d=a.style[e],!d))if(a.currentStyle){for(d=0;-1!==(d=e.indexOf("-",d));)e=e.substring(0,d)+e.substring(d+1,d+2).toUpperCase()+e.substring(d+2);d=a.currentStyle[e]}else d=(a=a.ownerDocument.defaultView.getComputedStyle(a,null))?a.getPropertyValue(e):null;return d||b},_isNode:function(a){return"object"===typeof Node?a instanceof Node:a&&"object"===typeof a&&"number"===typeof a.nodeType&&
"string"===typeof a.nodeName}};return{Tooltip:k}});
//# sourceMappingURL=tooltip.js.map