//>>built
/*

 Copyright (c) 2010, 2012 IBM Corporation and others.
 All rights reserved. This program and the accompanying materials are made 
 available under the terms of the Eclipse Public License v1.0 
 (http://www.eclipse.org/legal/epl-v10.html), and the Eclipse Distribution 
 License v1.0 (http://www.eclipse.org/org/documents/edl-v10.html). 

 Contributors: IBM Corporation - initial API and implementation
*/
define("orion/editor/undoStack",[],function(){function e(a,c,b){this.offset=a;this.text=c;this.previousText=b}function f(){this.changes=[]}function g(a,c){this.view=a;this.size=void 0!==c?c:100;this.reset();var b=a.getModel();b.getBaseModel&&(b=b.getBaseModel());this.model=b;var d=this;this._listener={onChanging:function(a){d._onChanging(a)},onDestroy:function(a){d._onDestroy(a)}};b.addEventListener("Changing",this._listener.onChanging);a.addEventListener("Destroy",this._listener.onDestroy)}e.prototype=
{undo:function(a,c){this._doUndoRedo(this.offset,this.previousText,this.text,a,c)},redo:function(a,c){this._doUndoRedo(this.offset,this.text,this.previousText,a,c)},_doUndoRedo:function(a,c,b,d,e){var k=d.getModel();if(k.mapOffset&&d.annotationModel){var h=k.mapOffset(a,!0);if(0>h)for(var f=d.annotationModel.getAnnotations(a,a+1);f.hasNext();){var g=f.next();if("orion.annotation.folding"===g.type){g.expand();h=k.mapOffset(a,!0);break}}if(0>h)return;a=h}d.setText(c,a,a+b.length);e&&d.setSelection(a,
a+c.length)}};f.prototype={add:function(a){this.changes.push(a)},end:function(a){this.endSelection=a.getSelection();this.endCaret=a.getCaretOffset()},undo:function(a,c){for(var b=this.changes.length-1;0<=b;b--)this.changes[b].undo(a,!1);if(c){var b=this.startSelection.start,d=this.startSelection.end;a.setSelection(this.startCaret?b:d,this.startCaret?d:b)}},redo:function(a,c){for(var b=0;b<this.changes.length;b++)this.changes[b].redo(a,!1);if(c){var b=this.endSelection.start,d=this.endSelection.end;
a.setSelection(this.endCaret?b:d,this.endCaret?d:b)}},start:function(a){this.startSelection=a.getSelection();this.startCaret=a.getCaretOffset()}};g.prototype={add:function(a){this.compoundChange?this.compoundChange.add(a):(this.stack.splice(this.index,this.stack.length-this.index,a),this.index++,this.stack.length>this.size&&(this.stack.shift(),this.index--,this.cleanIndex--))},markClean:function(){this.endCompoundChange();this._commitUndo();this.cleanIndex=this.index},isClean:function(){return this.cleanIndex===
this.getSize().undo},canUndo:function(){return 0<this.getSize().undo},canRedo:function(){return 0<this.getSize().redo},endCompoundChange:function(){this.compoundChange&&this.compoundChange.end(this.view);this.compoundChange=void 0},getSize:function(){var a=this.index,c=this.stack.length;void 0!==this._undoStart&&a++;return{undo:a,redo:c-a}},undo:function(){this._commitUndo();if(0>=this.index)return!1;var a=this.stack[--this.index];this._ignoreUndo=!0;a.undo(this.view,!0);this._ignoreUndo=!1;return!0},
redo:function(){this._commitUndo();if(this.index>=this.stack.length)return!1;var a=this.stack[this.index++];this._ignoreUndo=!0;a.redo(this.view,!0);this._ignoreUndo=!1;return!0},reset:function(){this.index=this.cleanIndex=0;this.stack=[];this._undoStart=void 0;this._undoText="";this._undoType=0;this._ignoreUndo=!1;this._compoundChange=void 0},startCompoundChange:function(){this._commitUndo();var a=new f;this.add(a);this.compoundChange=a;this.compoundChange.start(this.view)},_commitUndo:function(){void 0!==
this._undoStart&&(-1===this._undoType?this.add(new e(this._undoStart,"",this._undoText)):this.add(new e(this._undoStart,this._undoText,"")),this._undoStart=void 0,this._undoText="",this._undoType=0)},_onDestroy:function(a){this.model.removeEventListener("Changing",this._listener.onChanging);this.view.removeEventListener("Destroy",this._listener.onDestroy)},_onChanging:function(a){var c=a.text,b=a.start,d=a.removedCharCount;a=a.addedCharCount;if(!this._ignoreUndo){void 0!==this._undoStart&&!(1===a&&
0===d&&1===this._undoType&&b===this._undoStart+this._undoText.length||0===a&&1===d&&-1===this._undoType&&(b+1===this._undoStart||b===this._undoStart))&&this._commitUndo();if(!this.compoundChange){if(1===a&&0===d){void 0===this._undoStart&&(this._undoStart=b);this._undoText+=c;this._undoType=1;return}if(0===a&&1===d){c=0<this._undoText.length&&this._undoStart===b;this._undoStart=b;this._undoType=-1;this._undoText=c?this._undoText+this.model.getText(b,b+d):this.model.getText(b,b+d)+this._undoText;return}}this.add(new e(b,
c,this.model.getText(b,b+d)))}}};return{UndoStack:g}});
//# sourceMappingURL=undoStack.js.map