//>>built
define("davinci/ui/nls/ui",{root:{dontShowAgain:"Don't show again",selectFile:"Select a file",openFile:"Open File",aboutMaqetta:"About Maqetta",productVersion:"Version: ${0}",productDate:"Date: ${0}",build:"Build: ${0}",library:"Library",version:"Version",include:"Include",source:"Source",baseLocation:"Base Location",invalidDownloadFileName:"File name may only contain letters, numbers, \x26#8216;_\x26#8216;, and \x26#8216;.\x26#8216;.",selectedFiles:"Selected Files",noFilesSelected:"No files selected!",
downloadButtonLabel:"Download",themeAlreadyExists:"Theme already Exists!",invalidThemeName:"Invalid theme name",errorCreatingTheme:"Error creating theme: ",creatingTheme:"Creating theme",noUserThemes:"No user themes found in workspace. Please create a new theme before editing.",themeSetsDialog:"Manage theme sets",renameThemeSet:"Rename theme set",themeSets:"Theme sets:",currentlySelectedThemeSet:"Currently selected theme set:",themeSetName:"Name:",desktopTheme:"Dojo desktop 1.7 theme:",mobileTheme:"Dojo mobile 1.7 theme:",
android:"Android:",blackberry:"Blackberry:",ipad:"iPad:",iphone:"iPhone:",other:"Other:",selectTheme:"Select theme",themeSet:"Theme set:",themeVersionMessage:"Theme version does not match workspace version this could produce unexpected results. We suggest recreating the custom theme using the current version of Maqetta and deleting the existing theme.",addThemeSet:"Add theme set",deleteThemeSet:"Delete theme set",workspaceLocation:"Workspace Location",savingReadonlyFile:"This file is a read-only file. Please save it to a writeable location.",
create:"Create",open:"Open",save:"Save",select:"Select",update:"Update",unknown:"unknown",fileName:"File name",folderName:"Folder name",parentFolder:"Parent folder: ",newFolderLabel:"New folder",cancelButtonLabel:"Cancel",newFolderName:"Name:",createFolder:"Create Folder",createNewFile:"Create New File",createMobileApplication:"Create a Mobile Application",createDesktopApplication:"Create a Desktop Application",createSketchHiFi:"Create a Sketch (high-fidelity)",createSketchLoFi:"Create a Sketch (low-fidelity)",
createNewCSSFile:"Create New CSS File",createNewJSFile:"Create New JavaScript File",createNewFolder:"Create New Folder",saveFileAs:"Save File As",downloadFile:"Download",selectFiles:"Select Files...",selectZip:"Select ZIP file...",upload:"Upload",addFiles:"Upload",uploading:"Uploading...",completed:"completed: ${0} \n",done:"Done",explodeZipWarning:"Warning: Contents of .zip files will overwrite any conflicting files in your workspace",mustEnterFileName:"You must enter a file name.",cannotSelect:"Cannot select ${0}. It is a folder.",
fileAlreadyExistsOverwrite:"File ${0} already exists. OK to overwrite?",cannotCreate:"Cannot create ${0}. It already Exists.",fileNameSlashCharacter:"File names cannot contain a slash character (/). Your file name is: ${0}",doesNotHaveExtension:"The name ${0} does not have an extension (e.g., .html, .css or .js) and will be treated as a plain text file. OK to proceed?",areYouSureDelete:"Are you sure you want to delete ${0}?",areYouSureDeleteProject:"Are you sure you want to delete project ${0}?",
noResourcesSelected:"No resources are currently selected.",optimizeOption:"Use Dojo Web Builder (experimental)",downloadFullSource:"Download uncompressed source for selected libraries (if available)",selectAll:"All",selectNone:"None",themeToClone:"Theme to clone",newName:"New Name",selectTheme:"Select a Theme",newProject:"New Project",renameProjectDialogTitle:"Rename Project To...",deleteProjectButtonTitle:"Delete Project",renameProjectButtonTitle:"Rename Project...",deleteOnlyProjectError:"You can't delete the only project in your workspace!",
newFileShowFiles:"Show file picker",newFileHideFiles:"Hide file picker",root:"(root)",nhfoDevice:"Device:",nhfoDeviceTooltip:"Select an initial mobile device",nhfoThemeButtonLabel:"Theme...",nhfoThemeButtonTitle:"Select themes or theme set for new HTML file",renameNewLabel:"Name:",renameButtonLabel:"Rename",renameDialogTitle:"Rename To...",createProject:"New project",createProjectMenuItem:"New project...",deleteProjectMenuItem:"Delete this project...",renameProjectMenuItem:"Rename this project...",
saveAsProjectTemplateMenuItem:"Save as project template...",manageProjectTemplatesMenuItem:"Manage project templates...",modifyLibrariesMenuItem:"Modify libraries...",modifyLibraries:"Modify libraries",projectColon:"Project:",ProjectMenu:"Project menu",newProjectName:"Name:",newProjectTemplate:"Template:",newProjectUseProjectTemplate:"Use project template",newProjectCloneExistingProject:"Copy files from current project into new project",newProjectEclipseSupport:"New project should be Eclipse-compatible",
newProjectNameExists:"A project with this name already exists",saveAsProjectTemplate:"Save as project template",newProjectTemplateName:"Project template name:",newProjectTemplateShareLabel:"Share with everyone",newProjectTemplateOverwrite:"Project template {0} already exists. OK to overwrite?",newProjectTemplateCreationSuccess:"Project template {0} has been saved",newProjectTemplateCreationFailure:"Error: Project template {0} save operation failed",newProjectTemplateCancelled:"Operation cancelled",
manageProjectTemplates:"Manage project templates",ManageProjectTemplatesHeaderName:"Project template name",ManageProjectTemplatesHeaderShared:"Share with everyone?",ManageProjectTemplatesHeaderCreatedBy:"Created by",ManageProjectTemplatesHeaderCreatedOn:"Created on",ManageProjectTemplatesHeaderLastModified:"Last updated",ManageProjectTemplatesNoTemplates:"You have no project templates.",ManageProjectTemplatesDuplicateNames:"Invalid entries - two project templates have the same name",ManageProjectTemplateAboutToOccur:"The following actions are about to occur:",
ManageProjectTemplateDeletions:"project template deletions",ManageProjectTemplateModifications:"project template modifications",ManageProjectTemplateOKToProceed:"OK to proceed?",ManageProjectTemplatesInitializing:"Initializing...",modify:"Modify",User:"Account",currentProject:"Current Project:",selectProject:"Select a Project:",NoteOperationNotUndoable:"Note: this operation is not undoable."}});
//# sourceMappingURL=ui.js.map