//>>built
define("davinci/ve/views/StatesView","dojo/_base/declare dojo/query dojo/dom-class dojo/_base/connect dojo/aspect dojo/i18n!../nls/ve davinci/workbench/ViewPart dijit/layout/BorderContainer dijit/layout/ContentPane davinci/XPathUtils davinci/ve/States davinci/ve/widget davinci/ve/_Widget davinci/ve/commands/AppStateCommand dojo/data/ItemFileWriteStore dijit/tree/ForestStoreModel dijit/Tree dojo/_base/window".split(" "),function(E,I,m,H,J,B,K,L,M,F,r,C,N,O,P,Q,G,R){E(G._TreeNode,{});var S=E(G._TreeNode,
{_setLabelAttr:{node:"labelNode",type:"innerHTML"}}),D="sceneId category node sceneContainerNode isCurrent isFocus isInitial".split(" ");return E("davinci.ve.views.StatesView",[K],{nextId:0,_lastSelectedId:null,postCreate:function(){this.inherited(arguments);this._themeState=null;this.container=new L({design:"headline",gutters:!1,liveSplitters:!1});this.centerPane=new M({region:"center"});this.container.addChild(this.centerPane);this.container.layout();this.container.startup();this.setContent(this.container);
this.subscribe("/davinci/ui/editorSelected",this._editorSelected.bind(this));this.subscribe("/davinci/ui/context/loaded",this._contextLoaded.bind(this));this.subscribe("/davinci/ui/context/statesLoaded",this._statesLoaded.bind(this));this.subscribe("/davinci/ui/context/pagebuilt",this._pagebuilt.bind(this));this.subscribe("/davinci/ui/context/pagerebuilt",this._pagerebuilt.bind(this));this.subscribe("/davinci/states/statesReordered",this._statesReordered.bind(this));this.subscribe("/davinci/ui/deviceChanged",
this._deviceChanged.bind(this));this.subscribe("/davinci/states/state/added",this._addState.bind(this));this.subscribe("/davinci/states/state/removed",this._removeState.bind(this));this.subscribe("/davinci/states/state/renamed",this._renameState.bind(this));this.subscribe("/davinci/states/state/changed",this._changeState.bind(this));this.subscribe("/maqetta/appstates/state/changed",this._changeState.bind(this));this.subscribe("/maqetta/appstates/state/containerChange",this._containerChange.bind(this));
this.subscribe("/davinci/ui/context/registerSceneManager",this._registerSceneManager.bind(this));this.subscribe("/davinci/scene/scenesLoaded",this._scenesLoaded.bind(this));this.subscribe("/davinci/scene/added",this._addScene.bind(this));this.subscribe("/davinci/scene/removed",this._removeScene.bind(this));this.subscribe("/davinci/scene/renamed",this._renameScene.bind(this));this.subscribe("/davinci/scene/selectionChanged",this._sceneSelectionChanged.bind(this));dojo.subscribe("/davinci/ui/widgetPropertiesChanged",
dojo.hitch(this,this._widgetPropertiesChanged));this.subscribe("/davinci/ui/widgetSelected",dojo.hitch(this,this._widgetSelectionChanged));this.attachToolbar();dojo.style(this.toolbarDiv,"display","none")},_contextLoaded:function(){},_pagebuilt:function(){this._statesLoaded.apply(this,arguments)},_pagerebuilt:function(){this._destroyTree();this._statesLoaded.apply(this,arguments)},_statesReordered:function(){this._destroyTree();this._statesLoaded.apply(this,arguments)},_statesLoaded:function(){this._editor&&
"davinci.ve.themeEditor.ThemeEditor"!=this._editor.declaredClass&&this._updateView();this._hideShowToolBar()},_deviceChanged:function(){this._updateView()},_addState:function(){this._updateView()},_removeState:function(){this._updateView()},_renameState:function(){this._updateView()},_changeState:function(a){this.isThemeEditor()?this._updateThemeSelection(a.newState):this._updateView()},_containerChange:function(){this._updateView()},_registerSceneManager:function(a){},_scenesLoaded:function(a){this._updateView()},
_addScene:function(a,b,c){this._updateView()},_removeScene:function(a,b,c){this._updateView()},_renameScene:function(a,b,c){this._updateView()},_widgetPropertiesChanged:function(){this._updateView()},_widgetSelectionChanged:function(){if(this._editor&&this._editor.getContext&&this._tree&&this._sceneStore){var a=this._editor.getContext().getSelection();1==a.length&&(a=a[0].domNode)&&a._maqAppStates&&this._sceneStore.fetch({query:{node:a},queryOptions:{deep:!0},onComplete:dojo.hitch(this,function(a,
c){if(0<a.length){var e=this._getTreeSelectionPath(a[0]);this._tree.set("path",e)}})})}},_sceneSelectionChanged:function(a,b){a&&(a.category&&b)&&this._updateView()},_editorSelected:function(a){a=a.editor;this._destroyTree();this._unregisterForContextEvents();a&&a.supports("states")?(this._editor=a,dojo.style(this.container.domNode,"display","block"),"davinci.ve.themeEditor.ThemeEditor"===a.declaredClass?(this.set("title",B.States),this._updateViewForThemeEditor(),this._themeState?this._updateThemeSelection(this._themeState):
this._updateThemeSelection("Normal")):(this.set("title",B.Scenes),this._registerForContextEvents(),this._updateView()),this.container.layout()):(delete this._editor,dojo.style(this.container.domNode,"display","none"));this._hideShowToolBar()},_getRootNode:function(){var a=this._editor,b;a&&a.getContext&&(b=(a=a.getContext())&&a.rootNode);return b},_updateView:function(){if(this._editor&&this._editor.getContext&&!this.isThemeEditor()){var a=this._editor.getContext();a&&a._statesLoaded&&R.withDoc(document,
function(){this._updateList();this._updateSelection()},this)}},isThemeEditor:function(){return this._editor&&"davinci.ve.themeEditor.ThemeEditor"===this._editor.declaredClass},_updateViewForThemeEditor:function(){var a=this._editor._theme.getStatesForAllWidgets(),b={Normal:"Normal"};if(a)for(var c=0;c<a.length;c++){var e=a[c];"Normal"!=e&&(b[e]=e)}latestStates=b;var a=this._getScenes(),b={name:this._editor&&this._editor.getFileNameToDisplay?this._editor.getFileNameToDisplay():this._editor&&this._editor.fileName?
this._editor.fileName:"file",type:"file",category:"file",children:[]},c=[],e=[b],f;for(f in latestStates)c.push({name:f,sceneId:f,type:"AppState"});b.children=b.children.concat(c);this._compareStructures(e,a)||(this._destroyTree(),this._createTree(e))},_updateList:function(){function a(g,b){var c,h=g.declaredClass&&g.isInstanceOf&&g.isInstanceOf(N);h?(c=g,node=c.domNode):(c=null,node=g);var z=r.isStateContainer(node),w=!1,m;for(m in e){var k=e[m];if(k.getSceneChildren&&(k.name&&k.category)&&(w=k.isSceneContainer(node)))break}if("BODY"==
node.tagName||z||w){for(var t=null,p=0;p<f.length;p++)if(k=f[p],k.node==node){t=k;break}var u=null;if(!t){pn=node.parentNode;a:for(;pn;){for(p=0;p<f.length;p++)if(k=f[p],k.node==pn){u=k;break a}if("BODY"==pn.tagName)break;pn=pn.parentNode}}if(t)b=t;else{var n=h?C.getLabel(c):C.getLabelForNode(node),p=F.getXPath(node),n={name:n,type:"file",category:"file",node:node,children:[]};u?(n.maqid=u.maqid+"$"+p,u.children.push(n)):(n.maqid=b.maqid+"$"+p,b.children.push(n));f.push(n);b=n}if(z){p=r.getStates(node);
k=r.getState(node);k||(k=r.NORMAL);var A=r.getInitial(node);A||(A=r.NORMAL);for(var x={maqid:b.maqid+"$AppStates",name:"Application States",type:"SceneManagerRoot",category:"AppStates",sceneContainerNode:node,parentItem:b,children:[]},v=0;v<p.length;v++){var s=p[v],n=l._treeNodeContent("Normal"==s?"Background":s),z=d&&d.stateContainerNode==node&&d.state==k,u=s===k,t=s===A,n={maqid:x.maqid+"$"+s,name:n,sceneId:s,type:"AppState",isFocus:z,isCurrent:u,isInitial:t,sceneContainerNode:node,parentItem:x};
x.children.push(n);f.push(n)}b.children.push(x);f.push(x)}if(w)for(m in e)if(k=e[m],k.getSceneChildren&&(k.getCurrentScene&&k.getInitialScenes&&k.name&&k.category)&&(w=k.getSceneChildren(node),0<w.length)){A=k.getCurrentScene(node);x=k.getInitialScenes(node);p=F.getXPath(node);v={maqid:b.maqid+"$"+p,name:k.name,type:"SceneManagerRoot",category:k.category,parentItem:b,children:[]};for(s=0;s<w.length;s++){var y=w[s],n=h?C.getLabel(y._dvWidget):C.getLabelForNode(y),n=l._treeNodeContent(n),z=!1,u=y===
A,t=0<=x.indexOf(y),p=F.getXPath(y),n={maqid:v.maqid+"$"+p,name:n,sceneId:y.id,type:k.category,isFocus:z,isCurrent:u,isInitial:t,sceneContainerNode:node,parentItem:v,node:y,children:[]};v.children.push(n);f.push(n)}b.children.push(v);f.push(n)}}c=h?c.getChildren():r._getChildrenOfNode(node);for(h=0;h<c.length;h++)a(c[h],b)}var b=this._getScenes();if(this._editor&&b){var c=this._editor.getContext();if(c&&c.rootWidget&&c.rootNode&&c._statesLoaded){var e=c.sceneManagers,f=[],l=this,d=r.getFocus(c.rootNode);
d&&!d.state&&(d.state=r.NORMAL);var g={maqid:"root",children:[]};a(c.rootWidget,g);c=[g.children[0]];if(!this._compareStructures(c,b)){var h=null;this._tree&&this._sceneStore&&(b=this._tree.get("path"),0<b.length&&(h=b[b.length-1].maqid[0]));this._destroyTree();this._createTree(c);h&&this._tree.onLoadDeferred.then(function(){this._sceneStore.fetch({query:{maqid:h},queryOptions:{deep:!0},onComplete:dojo.hitch(this,function(g,a){if(1===g.length){var b=this._getTreeSelectionPath(g[0]);0<b.length&&this._tree.set("path",
b)}})})}.bind(this))}this._hideShowToolBar()}}},_getTreeSelectionPath:function(a){var b=[];b.splice(0,0,a.id[0]);for(a=a.parentItem&&a.parentItem[0];a;)b.splice(0,0,a.id[0]),a=a.parentItem&&a.parentItem[0];b.splice(0,0,"StoryRoot");return b},_updateSelection:function(){if(this._editor&&this._tree){var a=this._editor.getContext();a&&a._statesLoaded&&this._tree.onLoadDeferred.then(function(){var b=this._tree.get("path"),b=0<b.length?b[b.length-1].maqid[0]:null,c=a.sceneManagers,e;for(e in c){var f=
c[e];if(f.getAllSceneContainers&&f.getSceneChildren&&f.getCurrentScene){f.getAllSceneContainers();var l;this._sceneStore.fetch({query:{type:f.category},queryOptions:{deep:!0},onComplete:dojo.hitch(this,function(g,a){l=g})});for(f=0;f<l.length;f++){var d=l[f],g=this._findTreeNodeSpanByClass(d,"ScenesPaletteCurrent"),h=this._findTreeNodeSpanByClass(d,"ScenesPaletteInitial");d.isCurrent&&d.isCurrent[0]?g&&m.remove(g,"ScenesPaletteCurrentHidden"):g&&m.add(g,"ScenesPaletteCurrentHidden");d.isInitial&&
d.isInitial[0]?h&&m.remove(h,"ScenesPaletteInitialHidden"):h&&m.add(h,"ScenesPaletteInitialHidden");if(d.maqId&&d.maqId[0]==b&&(g=d.node&&d.node[0])&&g._maqAppStates)h=r.getState(g),r.setState(h,g,{focus:!0,updateWhenCurrent:!0})}}}var q=[];this._sceneStore.fetch({query:{type:"AppState"},queryOptions:{deep:!0},onComplete:dojo.hitch(this,function(g,a){q=g})});for(f=0;f<q.length;f++)e=q[f],g=this._findTreeNodeSpanByClass(e,"ScenesPaletteCurrent"),h=this._findTreeNodeSpanByClass(e,"ScenesPaletteInitial"),
e.isCurrent&&e.isCurrent[0]?g&&m.remove(g,"ScenesPaletteCurrentHidden"):g&&m.add(g,"ScenesPaletteCurrentHidden"),e.isInitial&&e.isInitial[0]?h&&m.remove(h,"ScenesPaletteInitialHidden"):h&&m.add(h,"ScenesPaletteInitialHidden")}.bind(this))}},_updateThemeSelection:function(a){if(this._sceneStore){var b;a||(a="Normal");this._sceneStore.fetch({query:{type:"AppState",sceneId:a},queryOptions:{deep:!0},onComplete:dojo.hitch(this,function(a,e){1===a.length&&(b=a[0].sceneId[0])})});b&&this._updateSelectedScene("AppState",
b)}},_getScenes:function(){var a=[];this._sceneStore&&this._sceneStore.fetch({query:{},queryOptions:{},onComplete:dojo.hitch(this,function(b,c){function e(a,b){for(var c={name:a.name[0],type:a.type[0]},g=0;g<D.length;g++){var h=D[g];a[h]&&(c[h]=a[h][0])}b.push(c);a.children&&0<a.children.length&&(c.children=[],a.children.forEach(function(a){e(a,c.children)}))}b.forEach(function(b){e(b,a)})})});return a},_compareStructures:function(a,b){function c(a,b){if(a.length!=b.length)return!1;for(var l=0;l<
a.length;l++){var d;a:{d=a[l];for(var g=b[l],h=0;h<D.length;h++){var q=D[h];q=d[q]&&!g[q]||!d[q]&&g[q]?!1:d[q]&&d[q]!==g[q]?!1:!0;if(!q){d=!1;break a}}h=d.children&&d.children.length;q=g.children&&g.children.length;d=h&&!q||!h&&q||h&&!c(d.children,g.children)?!1:!0}if(!d)return!1}return!0}return c(a,b)},_destroyTree:function(){this._tree&&(this._tree.destroyRecursive(),this._forest.destroy(),this._tree=this._forest=this._sceneStore=null)},_createTree:function(a){require(["dijit/tree/dndSource"],function(b){b=
function(a,b,c){if(a&&b){var d,e,f;b.forInSelectedItems(function(a){if(d=a.data&&a.data.item)e=d.parentItem&&d.parentItem[0],f=e.children&&e.children.indexOf(d)});var l,m;if(a=dijit.getEnclosingWidget(a).item)(l=a.parentItem&&a.parentItem[0])&&(m=l.children&&l.children.indexOf(a));return"over"!=c&&d&&a&&e&&l&&"AppState"==d.type[0]&&"AppState"==a.type[0]&&e==l&&0!==f&&!("before"==c&&0===m)&&!("before"==c&&f+1==m)&&!("after"==c&&f==m+1)}}.bind(this);var c=function(a,b,c){if(a.tree==this._tree){var d,
f;a.forInSelectedItems(function(a){(d=a.data&&a.data.item)&&(f=d.parentItem&&d.parentItem[0])});if((a=f.sceneContainerNode&&f.sceneContainerNode[0])&&a._maqAppStates&&a._maqAppStates.states){b=[];for(c=1;c<f.children.length;c++)b.push(f.children[c].sceneId[0]);a=new O({action:"reorder",newStatesList:b,stateContainerNode:a,context:e});e.getCommandStack().execute(a)}}}.bind(this);if(this._editor){var e=this._editor.getContext(),f=e.sceneManagers;this._sceneStore=new P({data:{identifier:"id",label:"name",
items:[]},clearOnClose:!0});this._forest=new Q({store:this._sceneStore,query:{type:"file"},rootId:"StoryRoot",rootLabel:"All",childrenAttrs:["children"]});this._tree=new G({model:this._forest,persist:!1,showRoot:!1,autoExpand:!0,dndController:"dijit.tree.dndSource",dragThreshold:8,betweenThreshold:5,checkItemAcceptance:b,className:"StatesViewTree",style:"height:150px; overflow-x:hidden; overflow-y:auto;",_createTreeNode:function(a){return new S(a)},getIconClass:function(a,b){return"dijitLeaf"}});
this._tree.tree&&this._tree.tree.dndController&&J.after(this._tree.tree.dndController,"onDndDrop",c,!0);this.centerPane.domNode.appendChild(this._tree.domNode);dojo.connect(this._tree,"onClick",this,function(a){var b=this._editor,c=b?b.getContext():null,d=null,e=null,l=null;a&&a.type&&(e=a.type[0],l=a.category&&a.category[0],"AppState"==e||"SceneManagerRoot"==e&&"AppStates"==l?d=a.sceneContainerNode?a.sceneContainerNode[0]:null:a.node&&a.node[0]._maqAppStates&&(d=a.node[0]));if(this.isThemeEditor())this.publish("/davinci/states/state/changed",
[{editorClass:b.declaredClass,widget:"$all",newState:a.sceneId[0],oldState:this._themeState,context:this._editor.context}]),this._themeState=a.sceneId[0];else{c&&d&&(l="AppState"==e?a.sceneId?a.sceneId[0]:null:r.getState(d),r.setState(l,d,{focus:!0,updateWhenCurrent:!0}),"davinci.ve.PageEditor"===this._editor.declaredClass&&(c.deselectInvisible(),c.clearCachedWidgetBounds(),c.updateFocusAll()));if(a.sceneId)for(var m in f){if(b=f[m],b.selectScene&&b.selectScene({sceneId:a.sceneId[0]}))break}else a.type&&
("file"==a.type[0]&&a.node&&a.node[0]._dvWidget)&&c.select(a.node[0]._dvWidget);this._updateSelection()}});var l=function(a,b){var c=dojo.mixin({},a),d=this.nextId+"";this.nextId++;c.id=d;c.parentItem=b;delete c.children;var e;e=b?this._sceneStore.newItem(c,{parent:b,attribute:"children"}):this._sceneStore.newItem(c);a.children&&a.children.forEach(function(a){l(a,e)})}.bind(this);a.forEach(function(a){l(a)});this._sceneStore.save();if(this._tree.getParent){var d=this._tree.getParent();d.resize&&window.setTimeout(function(){d.resize()},
0)}}}.bind(this))},_updateSelectedScene:function(a,b){if(this._sceneStore){for(var c=b,e=[];c;)this._sceneStore.fetch({query:{type:a,sceneId:c},queryOptions:{deep:!0},onComplete:dojo.hitch(this,function(a,b){if(1!==a.length)console.error("_sceneSelectionChanged error. currentSceneId\x3d"+c+",items.length\x3d"+a.length),c=null;else{var d=a[0];e.splice(0,0,d.id[0]);c=d.parentSceneId?d.parentSceneId[0]:null;for(d=d.parentItem&&d.parentItem[0];d;)e.splice(0,0,d.id[0]),d=d.parentItem&&d.parentItem[0]}})});
e.splice(0,0,"StoryRoot");this._tree.set("paths",[e])}},_hideShowToolBar:function(){function a(a,b){var c=a+"Disabled",e=I("."+a);e.length&&(b?m.remove(e[0],c):m.add(e[0],c))}if(this._editor){var b=this._editor.getContext&&this._editor.getContext();dojo.style(this.toolbarDiv,"display","davinci.ve.PageEditor"===this._editor.declaredClass?"block":"none");var c,e,f;c=e=f=!1;b&&b.rootNode&&((b=r.getFocus(b.rootNode))&&b.stateContainerNode&&(c=f=!0),b&&(b.state&&b.state!==r.NORMAL)&&(e=f=!0));a("addStateIcon",
c);a("removeStateIcon",e);a("modifyStateIcon",f)}},_treeNodeContent:function(a){var b;b=""+('\x3cspan title\x3d"'+B.InitialScene+'" class\x3d"ScenesPaletteAppStateIcon ScenesPaletteInitial"\x3e\x26#x2713;\x3c/span\x3e');b+='\x3cspan title\x3d"'+B.ActiveScene+'" class\x3d"ScenesPaletteAppStateIcon ScenesPaletteCurrent"\x3e\x3c/span\x3e';return b+("\x3cspan\x3e"+a+"\x3c/span\x3e")},_findTreeNodeSpanByClass:function(a,b){var c=this._tree.getNodesByItem(a),e=(c=c&&0<c.length?c[0]:null)?c.domNode:null;
return(c=c?dojo.query("."+b,e):[])&&0<c.length?c[0]:null},_contextEventHandler:function(){this._updateView()},_unregisterForContextEvents:function(){this._contextConnects&&(this._contextConnects.forEach(H.disconnect),this._contextConnects=null)},_registerForContextEvents:function(){var a=["widgetChanged","widgetAddedOrDeleted"];this._unregisterForContextEvents();var b=this._editor&&this._editor.getContext&&this._editor.getContext();b&&(this._contextConnects=[],a.forEach(function(a){b[a]&&this._contextConnects.push(H.connect(b,
a,this,"_contextEventHandler"))}.bind(this)))}})});
//# sourceMappingURL=StatesView.js.map