//>>built
define("davinci/ve/views/SwitchingStyleView","dojo/_base/declare dojo/i18n!davinci/ve/nls/ve dojo/i18n!dijit/nls/common dijit/layout/TabContainer dijit/layout/ContentPane davinci/Runtime davinci/workbench/WidgetLite davinci/ve/widgets/HTMLStringUtil davinci/ve/widgets/WidgetToolBar davinci/ve/widgets/Cascade davinci/ve/widgets/CommonProperties davinci/ve/widgets/WidgetProperties davinci/ve/widgets/EventSelection".split(" "),function(k,g,q,r,l,m,n,h,s,t,u,v,w){return k("davinci.ve.views.SwitchingStyleView",
[n],{_editor:null,_widget:null,_subWidget:null,_titleBarDiv:"\x3cdiv class\x3d'palette_titleBarDiv'\x3e\x3cspan class\x3d'paletteCloseBox'\x3e\x3c/span\x3e\x3cspan class\x3d'titleBarDivTitle'\x3e\x3c/span\x3e\x3c/div\x3e",constructor:function(a,b){dojo.subscribe("/davinci/ui/editorSelected",dojo.hitch(this,this._editorSelected));dojo.subscribe("/davinci/ui/widgetSelected",dojo.hitch(this,this._widgetSelectionChanged));dojo.subscribe("/davinci/states/state/changed",dojo.hitch(this,this._stateChanged));
dojo.subscribe("/maqetta/appstates/state/changed",dojo.hitch(this,this._stateChanged));dojo.subscribe("/davinci/ui/initialPerspectiveReady",dojo.hitch(this,this._initialPerspectiveReady));dojo.subscribe("/davinci/workbench/ready",dojo.hitch(this,this._workbenchReady))},pageTemplate:[{key:"widgetSpecific",className:"maqPropertySection page_editor_only",addCommonPropertiesAtTop:!1,html:"\x3cdiv dojoType\x3d'davinci.ve.widgets.WidgetProperties'\x3e\x3c/div\x3e"},{key:"events",className:"maqPropertySection page_editor_only",
addCommonPropertiesAtTop:!1,pageTemplate:{html:"\x3cdiv dojoType\x3d'davinci.ve.widgets.EventSelection'\x3e\x3c/div\x3e"}},{key:"layout",className:"maqPropertySection",addCommonPropertiesAtTop:!0,pageTemplate:[{display:"width",type:"multi",target:["width"],values:["","auto","100%","200px","10em"]},{display:"height",type:"multi",target:["height"],values:["","auto","100%","200px","10em"]},{html:"\x26nbsp;"},{key:"showMinMax",display:"\x26nbsp;\x26nbsp;\x26nbsp;",type:"toggleSection",pageTemplate:[{display:"min-height",
type:"multi",target:["min-height"],rowClass:"propertiesSectionHidden"},{display:"max-height",type:"multi",target:["max-height"],rowClass:"propertiesSectionHidden"},{display:"min-width",type:"multi",target:["min-width"],rowClass:"propertiesSectionHidden"},{display:"max-width",type:"multi",target:["max-width"],rowClass:"propertiesSectionHidden"},{html:"\x26nbsp;",rowClass:"propertiesSectionHidden"}]},{display:"position",type:"combo",target:["position"],values:["","absolute","fixed","relative","static"]},
{display:"left",type:"multi",target:["left"],values:["","0px","1em"]},{display:"top",type:"multi",target:["top"],values:["","0px","1em"]},{display:"right",type:"multi",target:["right"],values:["","0px","1em"]},{display:"bottom",type:"multi",target:["bottom"],values:["","0px","1em"]},{display:"display",type:"combo",target:["display"],values:["","none","block","inline","inline-block"]},{display:"opacity",type:"multi",target:["opacity"],values:["0","0.5","1.0"]},{display:"box-shadow",type:"text",target:["box-shadow"],
value:["","none","1px 1px rgba(0,0,0,.5)"]},{display:"float",type:"combo",target:["float"],values:["","none","left","right"]},{display:"clear",type:"combo",target:["clear"],values:["","none","left","right","both"]},{display:"overflow",type:"combo",target:["overflow"],values:["","visible","hidden","scroll","auto"]},{display:"z-index",type:"multi",target:["z-index"],values:" auto 0 1 100 -1 -100".split(" ")},{display:"box-sizing",type:"combo",target:["box-sizing","-webkit-box-sizing","-ms-box-sizing",
"-moz-box-sizing"],values:["","content-box","border-box"]}]},{key:"padding",className:"maqPropertySection",addCommonPropertiesAtTop:!0,pageTemplate:[{display:"\x3cb\x3e(padding)\x3c/b\x3e",type:"multi",target:["padding"],values:["","0px","1em"]},{key:"showtrbl",display:"\x26nbsp;\x26nbsp;\x26nbsp;",type:"toggleSection",pageTemplate:[{display:"padding-top",type:"multi",target:["padding-top"],values:["","0px","1em"],rowClass:"propertiesSectionHidden"},{display:"padding-right",type:"multi",target:["padding-right"],
values:["","0px","1em"],rowClass:"propertiesSectionHidden"},{display:"padding-bottom",type:"multi",target:["padding-bottom"],values:["","0px","1em"],rowClass:"propertiesSectionHidden"},{display:"padding-left",type:"multi",target:["padding-left"],values:["","0px","1em"],rowClass:"propertiesSectionHidden"}]}]},{key:"margins",className:"maqPropertySection",addCommonPropertiesAtTop:!0,pageTemplate:[{display:"\x3cb\x3e(margin)\x3c/b\x3e",type:"multi",target:["margin"],values:["","0px","1em"]},{key:"showtrbl",
display:"\x26nbsp;\x26nbsp;\x26nbsp;",type:"toggleSection",pageTemplate:[{display:"margin-top",type:"multi",target:["margin-top"],values:["","0px","1em"],rowClass:"propertiesSectionHidden"},{display:"margin-right",type:"multi",target:["margin-right"],values:["","0px","1em"],rowClass:"propertiesSectionHidden"},{display:"margin-bottom",type:"multi",target:["margin-bottom"],values:["","0px","1em"],rowClass:"propertiesSectionHidden"},{display:"margin-left",type:"multi",target:["margin-left"],values:["",
"0px","1em"],rowClass:"propertiesSectionHidden"}]}]},{key:"background",className:"maqPropertySection",addCommonPropertiesAtTop:!0,pageTemplate:[{display:"background-color",type:"background",target:["background-color"],colorswatch:!0},{display:"background-image",type:"background",target:["background-image"],values:["","none"]},{display:"background-repeat",type:"background",values:["","repeat","repeat-x","repeat-y","no-repeat"],target:["background-repeat"]},{display:"background-position",type:"background",
target:["background-position"],values:";0px 0px;0% 0%;left top;center center;right bottom".split(";")},{display:"background-size",type:"background",target:["background-size"],values:["","auto","contain","cover","100%"]},{display:"background-origin",type:"background",target:["background-origin"],values:["","border-box","padding-box","content-box"]},{display:"background-clip",type:"background",target:["background-clip"],values:["","border-box","padding-box","content-box"]}]},{key:"border",className:"maqPropertySection",
addCommonPropertiesAtTop:!0,pageTemplate:[{display:"\x3cb\x3e(border)\x3c/b\x3e",type:"multi",target:["border"],values:["","none","1px solid black"]},{display:"show",type:"combo",values:["none","props","sides","all"],id:"properties_show_select",onchange:function(a){if("number"==typeof a){var b=function(a,b,c,p,g){for(;b<=c;b++){var h=dojo.byId(a[b].rowId);b>=p&&b<=g?dojo.removeClass(h,"propertiesSectionHidden"):dojo.addClass(h,"propertiesSectionHidden")}};if(this.pageTemplate){a=this.pageTemplate[a];
var c;a&&a.id&&(c=dojo.byId(a.id).value);dojo.isString(c)&&("none"===c?b(this.pageTemplate,2,20,-1,-1):"sides"===c?b(this.pageTemplate,2,20,2,5):"props"===c?b(this.pageTemplate,2,20,6,8):"all"===c&&b(this.pageTemplate,2,20,9,20))}}}},{display:"border-top",type:"multi",target:["border-top"],values:["","none","1px solid black"],rowClass:"propertiesSectionHidden"},{display:"border-right",type:"multi",target:["border-right"],values:["","none","1px solid black"],rowClass:"propertiesSectionHidden"},{display:"border-bottom",
type:"multi",target:["border-bottom"],values:["","none","1px solid black"],rowClass:"propertiesSectionHidden"},{display:"border-left",type:"multi",target:["border-left"],values:["","none","1px solid black"],rowClass:"propertiesSectionHidden"},{display:"border-width",type:"multi",target:["border-width"],values:["","1px","1em"],rowClass:"propertiesSectionHidden"},{display:"border-style",type:"multi",target:["border-style"],values:["","none","solid","dotted","dashed"],rowClass:"propertiesSectionHidden"},
{display:"border-color",type:"color",target:["border-color"],rowClass:"propertiesSectionHidden"},{display:"border-top-width",type:"multi",target:["border-top-width"],values:["","1px","1em"],rowClass:"propertiesSectionHidden"},{display:"border-top-style",type:"multi",target:["border-top-style"],values:["","none","solid","dotted","dashed"],rowClass:"propertiesSectionHidden"},{display:"border-top-color",type:"color",target:["border-top-color"],rowClass:"propertiesSectionHidden"},{display:"border-right-width",
type:"multi",target:["border-right-width"],values:["","1px","1em"],rowClass:"propertiesSectionHidden"},{display:"border-right-style",type:"multi",target:["border-right-style"],values:["","none","solid","dotted","dashed"],rowClass:"propertiesSectionHidden"},{display:"border-right-color",type:"color",target:["border-right-color"],rowClass:"propertiesSectionHidden"},{display:"border-bottom-width",type:"multi",target:["border-bottom-width"],values:["","1px","1em"],rowClass:"propertiesSectionHidden"},
{display:"border-bottom-style",type:"multi",target:["border-bottom-style"],values:["","none","solid","dotted","dashed"],rowClass:"propertiesSectionHidden"},{display:"border-bottom-color",type:"color",target:["border-bottom-color"],rowClass:"propertiesSectionHidden"},{display:"border-left-width",type:"multi",target:["border-left-width"],values:["","1px","1em"],rowClass:"propertiesSectionHidden"},{display:"border-left-style",type:"multi",target:["border-left-style"],values:["","none","solid","dotted",
"dashed"],rowClass:"propertiesSectionHidden"},{display:"border-left-color",type:"color",target:["border-left-color"],rowClass:"propertiesSectionHidden"},{display:"border-collapse",type:"combo",target:["border-collapse"],values:["","separate","collapse"]},{display:"\x3cb\x3e(border-radius)\x3c/b\x3e",type:"multi",target:["border-radius","-moz-border-radius"],values:["","0px","6px"]},{key:"showDetails",display:"",type:"toggleSection",pageTemplate:[{display:"border-top-left-radius",type:"multi",target:["border-top-left-radius",
"-moz-border-radius-topleft"],values:["","0px","6px"],rowClass:"propertiesSectionHidden"},{display:"border-top-right-radius",type:"multi",target:["border-top-right-radius","-moz-border-radius-topright"],values:["","0px","6px"],rowClass:"propertiesSectionHidden"},{display:"border-bottom-right-radius",type:"multi",target:["border-bottom-right-radius","-moz-border-radius-bottomright"],values:["","0px","6px"],rowClass:"propertiesSectionHidden"},{display:"border-bottom-left-radius",type:"multi",target:["border-bottom-left-radius",
"-moz-border-radius-bottomleft"],values:["","0px","6px"],rowClass:"propertiesSectionHidden"}]}]},{key:"fontsAndText",className:"maqPropertySection",addCommonPropertiesAtTop:!0,pageTemplate:[{display:"font",type:"text",target:["font"]},{display:"font-family",type:"font",target:["font-family"]},{display:"size",type:"multi",target:["font-size"],values:["","100%","1em","10px","10pt"]},{display:"color",type:"color",target:["color"]},{display:"font-weight",type:"combo",target:["font-weight"],values:["",
"normal","bold"]},{display:"font-style",type:"combo",target:["font-style"],values:["","normal","italic"]},{display:"text-decoration",type:"combo",target:["text-decoration"],values:["","none","underline","line-through"]},{display:"text-align",type:"combo",target:["text-align"],values:["","left","center","right","justify"]},{display:"vertical-align",type:"combo",target:["vertical-align"],values:["","baseline","top","middle","bottom"]},{display:"white-space",type:"combo",target:["white-space"],values:" normal nowrap pre pre-line pre-wrap".split(" ")},
{display:"text-indent",type:"multi",target:["text-indent"],values:["","0","1em","10px"]},{display:"line-height",type:"multi",target:["line-height"],values:["","normal","1.2","120%"]}]}],buildRendering:function(){this.domNode=dojo.doc.createElement("div");dojo.addClass(this.domNode,"propertiesContent");var a;a=""+this._titleBarDiv;a+="\x3cdiv class\x3d'propertiesToolBar' dojoType\x3d'davinci.ve.widgets.WidgetToolBar'\x3e\x3c/div\x3e\x3cdiv dojoType\x3d'davinci.ve.widgets.WidgetProperties'\x3e\x3c/div\x3e";
a+="\x3cdiv class\x3d'propScrollableArea'\x3e";a+="\x3ctable class\x3d'propRootDetailsContainer'\x3e";a+="\x3ctr\x3e";a+="\x3ctd class\x3d'propPaletteRoot'\x3e";for(var b=0;b<this.pageTemplate.length;b++)if(this.pageTemplate[b].title=g[this.pageTemplate[b].key]?g[this.pageTemplate[b].key]:"Key not found",this.pageTemplate[b].pageTemplate)for(var c=0;c<this.pageTemplate[b].pageTemplate.length;c++)this.pageTemplate[b].pageTemplate[c].key&&(this.pageTemplate[b].pageTemplate[c].display+=g[this.pageTemplate[b].pageTemplate[c].key]?
g[this.pageTemplate[b].pageTemplate[c].key]:"Key not found");this.domNode.innerHTML=a;this.inherited(arguments)},_widgetValuesChanged:function(a){var b=this._currentPropSection;if(b){for(var c=!1,d=0;d<this.pageTemplate.length;d++)if(this.pageTemplate[d].key==b){c=!0;break}if(c){b=this._getVisibleCascade(d);for(c=0;c<b.length;c++)b[c]._widgetValuesChanged(a)}}},_getVisibleCascade:function(a){if(a)return this.pageTemplate[a].cascade;a=[];var b=this._currentPropSection;if(b)for(var c=0;c<this.pageTemplate.length;c++)if(this.pageTemplate[c].key==
b){a=a.concat(this.pageTemplate[c].cascade);break}return a},_updatePaletteValues:function(a){if(this._editor){var b=a[0];this._subwidget=(this._widget=b)&&b.subwidget;this.setReadOnly(!(this._widget||this._subwidget));for(var b=this._getVisibleCascade(),c=0;c<b.length;c++)b[c]._widgetSelectionChanged(a)}},_widgetSelectionChanged:function(a){this._updatePaletteValues(a)},_stateChanged:function(){this._updatePaletteValues(this._widget?[this._widget]:[])},_widgetPropertiesChanged:function(a){(!this._widget||
this._widget.type===a[0].type)&&this._updatePaletteValues(a)},_titlePaneOpen:function(a){a=this._getVisibleCascade(a);for(var b=0;b<a.length;b++)a[b]._editorSelected({editor:this._editor})},startup:function(){this.domNode.style.height="100%";this._editor=m.currentEditor;this.inherited(arguments);for(var a=0;a<this.pageTemplate.length;a++){var b=this.pageTemplate[a];if(b.pageTemplate)for(var c=0;c<b.pageTemplate.length;c++){var d=b.pageTemplate[c];d.onchange&&d.id&&dojo.connect(dojo.byId(d.id),"onchange",
dojo.hitch(b,d.onchange,c))}}for(a=0;a<this.pageTemplate.length;a++)this.pageTemplate[a].cascade=[];this.setReadOnly(!0);this.onEditorSelected();dojo.subscribe("/davinci/ui/widgetValuesChanged",dojo.hitch(this,this._widgetValuesChanged));dojo.subscribe("/davinci/ui/widgetPropertiesChanged",dojo.hitch(this,this._widgetPropertiesChanged))},setReadOnly:function(a){for(var b=0;b<this.pageTemplate.length;b++){var c=this.pageTemplate[b].pageTemplate;if(c)for(var d=0;d<c.length;d++){var f=c[d].widget;f?
f.set("readOnly",a):(f=c[d].domNode)&&dojo.attr(f,"disabled",a)}}},_modelEntryById:function(a){for(var b=0;b<this.pageTemplate.length;b++){var c=this.pageTemplate[b].pageTemplate;if(c)for(var d=0;d<c.length;d++)if(a==c[d].id)return c[d]}},_editorSelected:function(a){this._editor=a.editor;this.onEditorSelected(this._editor);a=this.getParent();var b=a.selectedChildWidget,c=!1,d=dojo.query(".maqPropertySection",a.domNode);this._editor?"davinci.ve.PageEditor"!=this._editor.declaredClass&&"davinci.ve.themeEditor.ThemeEditor"!=
this._editor.declaredClass?d.forEach(function(a){a=dijit.byNode(a);a.controlButton&&(a.controlButton.domNode.style.display="none");a==b&&(c=!0)}):(d.forEach(function(a){a=dijit.byNode(a);a.controlButton&&(a.controlButton.domNode.style.display="")}),"davinci.ve.themeEditor.ThemeEditor"==this._editor.declaredClass&&dojo.query(".page_editor_only",a.domNode).forEach(function(a){a=dijit.byNode(a);a.controlButton&&(a.controlButton.domNode.style.display="none");a==b&&(c=!0)})):(d.forEach(function(a){dijit.byNode(a).controlButton.domNode.style.display=
""}),c=!0);c&&this._selectFirstVisibleTab()},onEditorSelected:function(){this._subWidget=this._widget=null;this._oldClassName&&(this.domNode?dojo.removeClass(this.domNode.parentNode.parentNode,this._oldClassName):console.error("have no dom node !"));if(this._editor)if(this._editor&&this._editor.editorID&&(this._oldClassName=this._editor.editorID.replace(/\./g,"_"),this.domNode?dojo.addClass(this.domNode.parentNode.parentNode,this._oldClassName):console.error("have no dom node !")),this.domNode){for(var a=
this._currentPropSection,b=dojo.query(".propSectionButton",this.domNode),c=0;c<b.length;c++){var d=b[c];this._editor&&this._editor.supports&&this._editor.supports("propsect_"+this.pageTemplate[c].key)?dojo.removeClass(d,"dijitHidden"):(dojo.addClass(d,"dijitHidden"),a==this.pageTemplate[c].key&&h.showRoot())}a=[];for(c=0;c<this.pageTemplate.length;c++)(b=this.pageTemplate[c].cascade)&&(a=a.concat(b));for(c=0;c<a.length;c++)b=a[c],b._editorSelected&&b._editorSelected({editor:this._editor})}else console.error("have no dom node !")},
_destroyContent:function(){var a=this.containerNode||this.domNode;for(dojo.forEach(dojo.query("[widgetId]",a).map(dijit.byNode),function(a){a.destroy()});a.firstChild;)dojo._destroyElement(a.firstChild);dojo.forEach(this._tooltips,function(a){a.destroy()});this._tooltips=void 0},sectionTitleFromKey:function(a){for(var b=0;b<this.pageTemplate.length;b++)if(this.pageTemplate[b].key==a)return this.pageTemplate[b].title},_initialPerspectiveReady:function(){console.error("_initialPerspectiveReady");if(!this._alreadySplitIntoMultipleTabs){var a=
this.getParent();dojo.addClass(a.domNode,"propRootDetailsContainer");dojo.addClass(a.domNode,"propertiesContent");for(var b=0;b<this.pageTemplate.length;b++){var c=this.pageTemplate[b].key,d=this.pageTemplate[b].title,f=this.pageTemplate[b].className;f||(f="");var e=this._titleBarDiv,e=e+"\x3cdiv class\x3d'propertiesToolBar' dojoType\x3d'davinci.ve.widgets.WidgetToolBar'\x3e\x3c/div\x3e",e=e+("\x3cdiv class\x3d'cascadeBackButtonDiv'\x3e\x3cbutton onclick\x3d'davinci.ve.widgets.HTMLStringUtil.showSection(\""+
c+'","'+d+"\")'\x3e"+d+" "+g.properties+"\x3c/button\x3e\x3c/div\x3e"),c=h.generateTemplate(this.pageTemplate[b]),e=e+c;0==b?(e=this,e.set("title",d),dojo.addClass(e.domNode,f)):(e=new l({title:d,content:e,"class":f}),a.addChild(e));e._maqPropGroup=this.pageTemplate[b].key;d=dojo.query(".paletteCloseBox",e.domNode);0<d.length&&dojo.connect(d[0],"click",this,function(a){davinci.Workbench.collapsePaletteContainer(a.currentTarget)})}for(d=0;d<this.pageTemplate.length;d++)if(this.pageTemplate[d].cascade=
[],f=this.pageTemplate[d].pageTemplate){for(b=0;b<f.length;b++)e=f[b].id,(c=dijit.byId(e))?f[b].widget=c:(c=dojo.byId(e))&&(f[b].domNode=c);dojo.query("#"+this.pageTemplate[d].id+" .CascadeTop").forEach(function(a){return function(b){b=dijit.byId(b.id);a.cascade.push(b)}}(this.pageTemplate[d]))}dojo.connect(a,"selectChild",this,function(a){"none"==a.controlButton.domNode.style.display&&!this._recursiveSelectChildInProcess?(this._recursiveSelectChildInProcess=!0,this._selectFirstVisibleTab(),delete this._recursiveSelectChildInProcess):
a._maqPropGroup&&(this._currentPropSection=a._maqPropGroup,a=(a=this._editor&&this._editor.getContext?this._editor.getContext():null)&&a.getSelection?a.getSelection():[],this._updatePaletteValues(a),h._initSection(this._currentPropSection))});this._alreadySplitIntoMultipleTabs=!0}},_workbenchReady:function(){this._updateToolBars()},_updateToolBars:function(){dojo.query(".propertiesToolBar").forEach(function(a){this._editor&&"davinci.ve.PageEditor"==this._editor.declaredClass?(dojo.removeClass(a,"dijitHidden"),
a.style.display=""):dojo.addClass(a,"dijitHidden")}.bind(this))},_selectFirstVisibleTab:function(){for(var a=this.getParent(),b=a.getChildren(),c=0;c<b.length;c++){var d=b[c];if("none"!=d.controlButton.domNode.style.display){a._maqDontExpandCollapse=!0;a.selectChild(d);delete a._maqDontExpandCollapse;break}}}})});
//# sourceMappingURL=SwitchingStyleView.js.map