//>>built
define("davinci/ve/tools/CreateTool","dojo/_base/declare dojo/dom-style ../tools/_Tool davinci/Workbench davinci/workbench/Preferences ../metadata ../widget dojo/Deferred dojo/promise/all davinci/ve/States davinci/commands/CompoundCommand ../commands/AddCommand ../commands/MoveCommand ../commands/ResizeCommand ../commands/StyleCommand".split(" "),function(D,E,F,z,u,n,p,G,x,v,H,I,J,K,r){return D("davinci.ve.tools.CreateTool",F,{constructor:function(a){if((this._data=a)&&a.type){var c=n.queryDescriptor(a.type,
"resizableOnCreate")||n.queryDescriptor(a.type,"resizable");"none"!==c&&(this._resizable=c);this._dropCursor=n.queryDescriptor(a.type,"dropCursor")}this._requireHelpers(a)},activate:function(a){if((this._context=a)&&a.rootNode)this._oldCursor=a.rootNode.style.cursor;a.rootNode.style.cursor="crosshair"},deactivate:function(){this._context&&this._context.rootNode&&(this._context.rootNode.style.cursor=this._oldCursor);this._setTarget(null);delete this._mdPosition;this._context.dragMoveCleanup()},_getContentPosition:function(a){if(a)return a.target&&
(a={x:a.pageX,y:a.pageY}),a},onMouseDown:function(a){this._target=p.getEnclosingWidget(a.target);this._mdPosition=this._getContentPosition(a);this._dragRect=null},onMouseMove:function(a){var c=this._context,b=c._chooseParent;a.target!=this._lastEventTarget&&b.setProposedParentWidget(null);this._lastEventTarget=a.target;if(this._mdPosition){if(this._resizable){c.deselect();var d=this._getContentPosition(a),e,f,h=!0,g=!0;d.x>=this._mdPosition.x?(b=this._mdPosition.x,f=d.x-this._mdPosition.x):(b=d.x,
f=this._mdPosition.x-d.x,h=!1);d.y>=this._mdPosition.y?(e=this._mdPosition.y,d=d.y-this._mdPosition.y):(e=d.y,d=this._mdPosition.y-d.y,g=!1);a.shiftKey&&(f>=d?(d=f,g||(e=this._mdPosition.y-d)):(f=d,h||(b=this._mdPosition.x-f)));this._dragSizeRect||(a=c.getDocument().body,this._dragSizeRect=dojo.create("div",{style:"border:1px dashed black;z-index:1000001;position:absolute;"},a));a=this._dragSizeRect.style;a.left=b+"px";a.top=e+"px";a.width=f+"px";a.height=d+"px"}}else b=!this.createWithFlowLayout(),
this._setTarget(a.target,a),e=c.getPreference("showPossibleParents"),e=!e&&this._spaceKeyDown||e&&!this._spaceKeyDown,f={x:a.pageX,y:a.pageY},d={l:a.pageX,t:a.pageY,w:0,h:0},h=u.getPreferences("davinci.ve.editorPrefs",z.getProject()).snap&&b,g=!b,"object"==typeof this._dropCursor&&!1===this._dropCursor.show&&(g=!1),c.dragMoveUpdate({data:this._data,position:f,absolute:b,currentParent:null,eventTarget:a.target,rect:d,doSnapLinesX:h,doSnapLinesY:h,doFindParentsXY:e,doCursor:g,beforeAfter:this._dropCursor&&
this._dropCursor.beforeAfter})},onMouseUp:function(a){var c=this._context,b=c._chooseParent,d=!this.createWithFlowLayout();this._dragSizeRect&&(this._dragSizeRect.parentNode.removeChild(this._dragSizeRect),this._dragSizeRect=null);var e=c.getActiveDragDiv();e&&(e=dojo.query(".maqCandidateParents",e),1==e.length&&(e[0].innerHTML=""));this._lastEventTarget=null;var f,h,g,k,e=this._getContentPosition(a);if(this._mdPosition){var r=!0,u=!0;this._position=dojo.mixin({},this._mdPosition);e.x<this._mdPosition.x&&
(this._position.x=e.x);"height"==this._resizable?g=0:0<=e.x-this._mdPosition.x?g=e.x-this._mdPosition.x:(g=this._mdPosition.x-e.x,r=!1);e.y<this._mdPosition.y&&(this._position.y=e.y);"width"==this._resizable?k=0:0<=e.y-this._mdPosition.y?k=e.y-this._mdPosition.y:(k=this._mdPosition.y-e.y,u=!1);a.shiftKey&&(g>=k?(k=g,u||(t=this._mdPosition.y-k)):(g=k,r||(l=this._mdPosition.x-g)))}else this._position=e;if(this._resizable&&this._position&&(4<g||4<k))f={w:0<g?g:void 0,h:0<k?k:void 0};if(g=b.getProposedParentWidget()){if(h=
g.parent,g.refChild){var y=g.parent.getChildren().indexOf(g.refChild);0<=y?g.refAfter&&y++:y=null}}else{a=this._getTarget()||p.getEnclosingWidget(a.target);var m=this._data;g=b.getAllowedTargetWidget(a,m,!0,{absolute:d});var q=dojo.isArray(m)?m[0].type:m.type,s=p.getWidgetHelper(q);1<g.length&&s&&s.chooseParent?h=s.chooseParent(g):0<g.length&&(h=0<=g.indexOf(a)?a:g[0])}b.setProposedParentWidget(null);b=function(a){this.prototype=Error.prototype;this.name="InvalidTargetWidgetError";this.message=a?
a:"The selected target is not a valid parent for the given widget."};try{m=this._data instanceof Array?this._data:[this._data];if(!h){var x=m.map(function(a){return a.type}).join(", "),w=m.map(function(a){var b=n.getAllowedParent(a.type);a=a.type;var c=n.queryDescriptor(a,"class");a=c?c.split(/\s+/).push(a):[a];return{allowedParent:b,classList:a}});f="The selected target is not a valid parent for the given widget.";1===w.length&&w[0].allowedParent&&(f+=['The widget \x3cspan style\x3d"font-family: monospace"\x3e',
x,"\x3c/span\x3e requires ",1<w[0].allowedParent.length?"one of the following parent types":"the parent type",' \x3cspan style\x3d"font-family: monospace"\x3e',w[0].allowedParent.join(", "),"\x3c/span\x3e."].join(""),q=m[0].type,(s=p.getWidgetHelper(q))&&s.isAllowedError&&(f=s.isAllowedError({errorMsg:f,type:q,allowedParent:w[0].allowedParent,absolute:d})));throw new b(f);}for(d=0;d<m.length;d++){var v=m[d].type,A=n.getLibraryForType(v),B=A.name,q=[v,c];c._widgets.hasOwnProperty(B)||(c._widgets[B]=
0);1==++c._widgets[B]&&n.invokeCallback(A,"onFirstAdd",q);n.invokeCallback(A,"onAdd",q)}this.create({target:h,index:y,directTarget:this._getTarget(),size:f})}catch(C){C instanceof b?(m=C.message,f="Invalid Target"):(m="The action was interrupted by an internal error.",f="Error",console.error(C)),z.showMessage(f,m)}finally{this.exitCreateToolOnMouseUp()&&c.setActiveTool(null),this._cleanupActions()}},_cleanupActions:function(){var a=this._context;a.dragMoveCleanup();a.inlineEditActive()||this._context.getDocument().defaultView.focus()},
onKeyDown:function(a){dojo.stopEvent(a);var c=this._context;if(a.keyCode==dojo.keys.ESCAPE)c.setActiveTool(null),this._cleanupActions();else{var b=this._context.getPreference("showPossibleParents");a.keyCode==dojo.keys.SPACE?this._spaceKeyDown=!0:this._processKeyDown(a.keyCode);a=!b&&this._spaceKeyDown||b&&!this._spaceKeyDown;var b=this._data,b=dojo.isArray(b)?b[0].type:b.type,c=c._chooseParent,d=!this.createWithFlowLayout(),e=!d;"object"==typeof this._dropCursor&&!1===this._dropCursor.show&&(e=!1);
c.dragUpdateCandidateParents({widgetType:b,showCandidateParents:a,absolute:d,doCursor:e,beforeAfter:this._dropCursor&&this._dropCursor.beforeAfter,currentParent:null})}},_processKeyDown:function(a){if(49<=a&&57>=a){var c=this._context._chooseParent,b=c.getProposedParentsList();b&&1<b.length&&(a=b.length-(a-48),0<=a&&c.setProposedParentWidget(b[a]))}},onKeyUp:function(a){a.keyCode==dojo.keys.SPACE&&(this._spaceKeyDown=!1);dojo.stopEvent(a);a=this._context.getPreference("showPossibleParents");a=!a&&
this._spaceKeyDown||a&&!this._spaceKeyDown;var c=this._data,c=dojo.isArray(c)?c[0].type:c.type,b=this._context._chooseParent,d=!this.createWithFlowLayout(),e=!d;"object"==typeof this._dropCursor&&!1===this._dropCursor.show&&(e=!1);b.dragUpdateCandidateParents({widgetType:c,showCandidateParents:a,absolute:d,doCursor:e,beforeAfter:this._dropCursor&&this._dropCursor.beforeAfter,currentParent:null})},_requireHelpers:function(a){var c=[];if(!a||!a.type)return a instanceof Array&&a.forEach(function(a){c.concat(this._requireHelpers(a))},
this),c;c.push(p.requireWidgetHelper(a.type));a.children&&!dojo.isString(a.children)&&dojo.every(a.children,function(a){return c.concat(this._requireHelpers(a))},this);return c},create:function(a){if(a&&this._data){for(var c=a.target,b,d;c&&!(b=c.getContainerNode());)d=c,c=c.getParent();var e=a.index,f;b=!1;this._data.properties&&(this._data.properties.style&&0<this._data.properties.style.indexOf("absolute"))&&(b=!0);!b&&this.createWithFlowLayout()?d&&(e=c.indexOf(d)):a.position?f=a.position:this._position&&
(f=this._position);this._data.context=this._context;x(this._requireHelpers(this._data)).then(function(){this._create({parent:c,index:e,position:f,size:a.size})}.bind(this))}},_create:function(a){var c=this._context,b=[],d=new G;if(!this._loadType(this._data,b))return d.reject(),d;x(b).then(function(){var b;this.createNewWidget()?dojo.withDoc(this._context.getDocument(),function(){b=p.createWidget(this._data)},this):b=this._widget;b||d.reject(Error("Failed to create widget"));var f=new H;if(this.createNewWidget()){a.size=
this._getInitialSize(b,a);f.add(new I(b,a.parent||this._context.getContainerNode(),a.index));if(a.position){var h=c.getPreference("absoluteWidgetsZindex");f.add(new r(b,[{position:"absolute"},{"z-index":h}]));f.add(new J(b,a.position.x,a.position.y))}if(a.size){var h=a.size.w,g=a.size.h;f.add(new K(b,h,g));var k=p.getWidgetHelper(b.type);if(k&&k.onCreateResize)k.onCreateResize(f,b,h,g)}this.checkAddToCurrentState(f,b)}h=b.id;this.addToCommandStack&&this.addToCommandStack(f,{widget:b});f.isEmpty()||
this._context.getCommandStack().execute(f);b.isLayoutContainer&&b.resize();b=p.byId(h);this._select(b);this._widget=b;d.resolve(b);this.mouseUpProcessingCompleted()}.bind(this));return d},_loadType:function(a,c){if(!a||!a.type)return!1;c.push(this._context.loadRequires(a.type,!0));a.children&&!dojo.isString(a.children)&&dojo.forEach(a.children,function(a){this._loadType(a,c)}.bind(this));return!0},_getInitialSize:function(a,c){var b=c.size,d=a.getHelper();d&&d.initialSize&&(d=d.initialSize(c))&&(b=
d);if(!b&&(d=n.queryDescriptor(a.type,"initialSize")))c&&!c.position?(b=c.parent,"html.body"==b.type?b="auto"==d||"auto"==d.flow?{w:"100%",h:"auto"}:this._getExplicitFlowSizeFromMetadata(d):this._isTypeContainer(b.type)?"auto"==d||"auto"==d.flow?(b=b.getData().children,b={w:"100%",h:b&&b.length?"auto":"100%"}):b=this._getExplicitFlowSizeFromMetadata(d):b=this._getExplicitFlowSizeFromMetadata(d)):b="auto"==d||"auto"==d.absolute?{w:"300px",h:"300px"}:this._getExplicitAbsoluteSizeFromMetadata(d);return b},
_getExplicitFlowSizeFromMetadata:function(a){var c=null;return c=a.flow?{w:a.flow.width?a.flow.width:"100%",h:a.flow.height?a.flow.height:"auto"}:{w:a.width?a.width:"100%",h:a.height?a.height:"auto"}},_getExplicitAbsoluteSizeFromMetadata:function(a){var c=null;return c=a.absolute?{w:a.absolute.width?a.absolute.width:"300px",h:a.absolute.height?a.absolute.height:"300px"}:{w:a.width?a.width:"300px",h:a.height?a.height:"300px"}},_isTypeContainer:function(a){return a&&("dijit/layout/ContentPane"==a||
"html.div"==a||"html.form"==a||"html.fieldset"==a)},_select:function(a){n.getSmartInput(a.type).then(function(c){!this._data.fileDragCreate&&c&&c.displayOnCreate?(a.inLineEdit_displayOnCreate=c.displayOnCreate,this._context.select(a,null,!0)):this._context.select(a)}.bind(this))},createWithFlowLayout:function(){return n.queryDescriptor(this._data.type,"forceAbsolute")?!1:this._context.getFlowLayout()},createNewWidget:function(){return!0},exitCreateToolOnMouseUp:function(){return!0},mouseUpProcessingCompleted:function(){},
checkAddToCurrentState:function(a,c){var b=v.getFocus(c._edit_context.rootNode);if(b&&b.stateContainerNode){var b=v.getState(b.stateContainerNode),d=u.getPreferences("davinci.ve.editorPrefs",z.getProject());b&&d.newWidgetsCurrentState&&(d=E.get(c.domNode,"display"),a.add(new r(c,[{display:"none"}])),a.add(new r(c,[{display:d}],b)))}}})});
//# sourceMappingURL=CreateTool.js.map