//>>built
define("davinci/ve/tools/SelectTool","dojo/_base/declare dojo/dom-geometry ../../Workbench ../../workbench/Preferences ./_Tool ../widget ../metadata dojo/dnd/Mover ../../XPathUtils ../../html/HtmlFileXPathAdapter ../Snap ../../commands/CompoundCommand ../commands/AddCommand ../commands/ReparentCommand ../commands/MoveCommand ../commands/ResizeCommand ../commands/ModifyCommand ../tools/CreateTool ../States ../utils/GeomUtils".split(" "),function(C,D,E,M,N,x,F,O,u,P,Q,A,G,B,v,R,S,J,z,p){return C("davinci.ve.tools.SelectTool",
N,{CONSTRAIN_MIN_DIST:3,activate:function(a){this._context=a},deactivate:function(){this._setTarget(null)},onMouseDown:function(a){var c=this._context;if(!c.isFocusNode(a.target)){this._shiftKey=a.shiftKey;this._sKey=this._spaceKey=!1;this._areaSelectClear();var b=this._checkFocusXY(a.pageX,a.pageY);b&&"NONE"!==F.getAllowedChild(b.type)[0]&&(b=null);var e=this._getTarget()||x.getEnclosingWidget(a.target);for(b||(b=e);b&&!b.getContext();)b=x.getEnclosingWidget(b.domNode.parentNode);if(b)if(dojo.isMac&&
a.ctrlKey||2==a.button)c.select(b);else{for(var f=c.getSelection(),d=null,g=0;g<f.length;g++){for(var h=f[g],k=b;k&&k!=c.rootWidget;){if(k==h){d=h;break}k=k.getParent()}if(d)break}k=null;g=dojo.isMac?a.metaKey:a.ctrlKey;this._mouseDownInfo=null;if(0<=dojo.indexOf(f,b))g?c.deselect(b):(k=b,this._mouseDownInfo={widget:b,eventTargetWidget:e,pageX:a.pageX,pageY:a.pageY,dateValue:Date.now()});else if(g){if(b==c.rootWidget)return;c.select(b,g)}else if(d)k=d,this._mouseDownInfo={widget:b,eventTargetWidget:e,
pageX:a.pageX,pageY:a.pageY,dateValue:Date.now()};else{if(b==c.rootWidget){c.deselect();this._areaSelectInit(a.pageX,a.pageY);return}"NONE"===F.getAllowedChild(b.type)[0]?(c.select(b,g),k=b):(this._mouseDownInfo={widget:b,eventTargetWidget:e,pageX:a.pageX,pageY:a.pageY,dateValue:Date.now()},this._areaSelectInit(a.pageX,a.pageY))}if(k&&(b=c.getDocument(),f=b.defaultView&&b.defaultView.dojo))if(f=f.style(k.domNode,"position"),this._moverAbsolute="absolute"==f,f=k.getParent(),e=k.getHelper(),(!e||!e.disableDragging||
!e.disableDragging(k))&&(!f||!f.isLayout||!f.isLayout())){this._moverWidget=k;this._moverWidgets=[k];this._moverLastEventTarget=null;c._chooseParent.setProposedParentWidget(null);f=c.getSelection();this._moverStartLocations=[];this._moverStartLocationsRel=[];for(g=0;g<f.length;g++){f[g]!=k&&this._moverWidgets.push(f[g]);d=null;d=(d=f[g].getHelper())&&d.getMarginBoxPageCoords?d.getMarginBoxPageCoords(f[g]):p.getMarginBoxPageCoordsCached(f[g].domNode);this._moverStartLocations.push(d);if((h=f[g].domNode.offsetParent)&&
"BODY"!=h.tagName)var m=p.getBorderBoxPageCoordsCached(h),q=D.getBorderExtents(h),h=d.l-(m.l+q.l),d=d.t-(m.t+q.t);else h=d.l,d=d.t;this._moverStartLocationsRel.push({l:h,t:d})}g=k.domNode;d=g.offsetWidth;f=g.offsetHeight;h=null;e&&e.getMarginBoxPageCoords?(h=e.getMarginBoxPageCoords(k),d=h.w,f=h.h):h=p.getMarginBoxPageCoordsCached(g);g=h.l;e=h.t;k=h.w;h=h.h;this._moverAbsolute?this._moverDragDiv=dojo.create("div",{className:"selectToolDragDiv",style:"left:"+g+"px;top:"+e+"px;width:"+k+"px;height:"+
h+"px"},c.rootNode):(k=d+10,f+=10,d=k-8,h=f-8,this._moverDragDiv=dojo.create("div",{className:"flowDragOuter",style:"left:"+(g-5)+"px;top:"+(e-5)+"px;width:"+k+"px;height:"+f+"px"},c.rootNode),dojo.create("div",{className:"flowDragInner",style:"width:"+d+"px;height:"+h+"px"},this._moverDragDiv));this._mover=new O(this._moverDragDiv,a,this);this._altKey=a.altKey;this._updateMoveCursor();(a=document.getElementById("maqetta_project_select"))&&a.focus();b.defaultView.focus()}}}},onMouseUp:function(a){if(!this._context.isFocusNode(a.target)){var c=
1===a.which,b=Date.now();this._mouseDownInfo&&(10>=Math.abs(a.pageX-this._mouseDownInfo.pageX)&&(10>=Math.abs(a.pageY-this._mouseDownInfo.pageY)&&750>=b-this._mouseDownInfo.dateValue)&&(this._context.select(this._mouseDownInfo.eventTargetWidget?this._mouseDownInfo.eventTargetWidget:this._mouseDownInfo.widget),c=!1),this._mouseDownInfo=null);if(this._lastMouseUp&&10>=Math.abs(a.pageX-this._lastMouseUp.pageX)&&10>=Math.abs(a.pageY-this._lastMouseUp.pageY)&&750>=b-this._lastMouseUp.dateValue)this.onDblClick(a);
this._lastMouseUp={pageX:a.pageX,pageY:a.pageY,dateValue:b};this._areaSelect&&c&&this._areaSelectSelectWidgets(a.pageX,a.pageY);this._areaSelectClear()}},onDblClick:function(a){if(!this._context.isFocusNode(a.target)){for(var c="selectToolDragDiv"===a.target.getAttribute("class")?this._context.getSelection()[0]:this._getTarget()||x.getEnclosingWidget(a.target);c&&!c.getContext();)c=x.getEnclosingWidget(c.domNode.parentNode);if(c){var b=this._context.getSelection(),e=dojo.isMac?a.ctrlKey:a.metaKey;
0<=dojo.indexOf(b,c)?e&&2!==a.button?this._context.deselect(c):2!==a.button&&this._context.select(c,null,!0):this._context.select(c,e,!0)}}},onMouseMove:function(a){this._context.isFocusNode(a.target)||(this._setTarget(a.target,a),this._areaSelect&&(1===a.which?this._areaSelectUpdate(a.pageX,a.pageY):this._areaSelectClear()))},onMouseOver:function(a){try{!dojo.hasClass(a.target,"editFeedback")&&!dojo.hasClass(a.target,"selectToolDragDiv")&&(this._onMouseOverEventTargetXPath=u.getXPath(a.target)),
this._setTarget(a.target,a)}catch(c){}},onMouseOut:function(a){try{this._setTarget(a.relatedTarget,a)}catch(c){}},onExtentChange:function(a){var c=a.index,b=a.newBox,e=a.copy,f=a.oldBoxes,d=a.applyToWhichStates,g,h=this._context,k=h._chooseParent,m=h.getSelection(),q=[];if(!(m.length<=c)){var n=m[c],l=void 0;if("w"in b||"h"in b){var c=F.queryDescriptor(n.type,"resizable"),r,y;a=n.domNode;var u=a.ownerDocument.defaultView.getComputedStyle(a),k=p.getMarginExtents(a,u),z=D.getBorderExtents(a,u);a=D.getPadExtents(a,
u);"number"==typeof b.w&&(b.w-=k.w+z.w+a.w);"number"==typeof b.h&&(b.h-=k.h+z.h+a.h);switch(c){case "width":r=b.w;break;case "height":y=b.h;case "both":r=b.w,y=b.h}c=new R(n,r,y,d);l||(l=new A);l.add(c);c=dojo.style(n.domNode,"position");"l"in b&&("t"in b&&"absolute"==c)&&(r=b.l,b=b.t,b=new v(n,r,b,null,null,d),l.add(b))}else if(a=n.getStyleNode(),"absolute"!=dojo.style(a,"position")){var s=k.getProposedParentWidget();if(s){l||(l=new A);var H=null;a=h.reorderPreserveSiblingOrder(m);dojo.forEach(a,
function(a){s.refChild&&(null!==H?g=H+1:(g=s.parent.getChildren().indexOf(s.refChild),0<=g?s.refAfter&&g++:g=null),H=g);if(e){var b,c=a.getData({identify:!1});c.context=h;dojo.withDoc(h.getDocument(),function(){b=x.createWidget(c)},this);b&&(l.add(new G(b,s.parent,g)),J.prototype.checkAddToCurrentState(l,b),q.push(b))}else l.add(new B(a,s.parent,g)),q.push(a)},this);h.select(null)}else console.error("SelectTool: ppw is null")}else{var I=[],K=[];dojo.forEach(m,function(a,b){I[b]=m[b].getParent();K[b]=
I[b].indexOf(a)});r=b.l;b=b.t;l||(l=new A);var t=(s=k.getProposedParentWidget())?s.parent:null;a=n.getParent();y=void 0;t&&t!=a&&(y=t);var C=r-f[0].l,E=b-f[0].t;e&&(a=h.reorderPreserveSiblingOrder(m),dojo.forEach(a,function(a){var b=a.getParent();if(b){for(var c=b.getChildren(),d=0;d<c.length&&c[d]!=a;d++);var e,f=a.getData({identify:!1});f.context=h;dojo.withDoc(h.getDocument(),function(){e=x.createWidget(f)},this);e&&(t?l.add(new G(e,t,-1)):l.add(new G(e,b,d)),J.prototype.checkAddToCurrentState(l,
e),q.push(e))}},this),newWidget=q[c]);var w=e?newWidget:n,L=new v(w,r,b,null,f[c],d);l.add(L);y&&(l.add(new B(w,t,"last")),l.add(new v(w,r,b,null,null,d)));dojo.forEach(m,dojo.hitch(this,function(a,b){w=e?q[b]:a;if(a!=n){var c=f[b].l+C,g=f[b].t+E;if("absolute"==a.getStyleNode().style.position){var h=new v(w,c,g,L,f[b],d,!0);l.add(h)}h=a.getParent();t&&t!=h&&(l.add(new B(w,t,"last")),l.add(new v(w,c,g,null,null,d,!0)))}}));e&&dojo.forEach(m,dojo.hitch(this,function(a,b){l.add(new B(m[b],I[b],K[b]));
l.add(new v(m[b],f[b].l,f[b].t,null,f[b],d,!0))}))}l?(h.getCommandStack().execute(l),dojo.forEach(q,function(a,b){h.select(a,0<b)},this)):h.select(n)}},_updateMoveCursor:function(){var a=this._context.getDocument().body;this._moverDragDiv?this._altKey?(dojo.removeClass(a,"selectToolDragMove"),dojo.addClass(a,"selectToolDragCopy")):(dojo.removeClass(a,"selectToolDragCopy"),dojo.addClass(a,"selectToolDragMove")):(dojo.removeClass(a,"selectToolDragMove"),dojo.removeClass(a,"selectToolDragCopy"))},onKeyDown:function(a){if(a)switch(dojo.stopEvent(a),
a.keyCode){case dojo.keys.SHIFT:this._shiftKey=!0;Q.clearSnapLines(this._context);break;case dojo.keys.ALT:this._altKey=!0;this._updateMoveCursor();break;case dojo.keys.SPACE:this._spaceKey=!0;break;case 83:this._sKey=!0;break;case dojo.keys.TAB:this._moveFocus(a)&&dojo.stopEvent(a);break;case dojo.keys.RIGHT_ARROW:case dojo.keys.LEFT_ARROW:case dojo.keys.DOWN_ARROW:case dojo.keys.UP_ARROW:this._move(a)}},onKeyUp:function(a){if(a&&this._moverWidget)switch(dojo.stopEvent(a),a.keyCode){case dojo.keys.SHIFT:this._shiftKey=
!1;break;case dojo.keys.ALT:this._altKey=!1;this._updateMoveCursor();break;case dojo.keys.SPACE:this._spaceKey=!1;break;case 83:this._sKey=!1}},_move:function(a){var c=this._context.getSelection();if(0!==c.length){var b=0,e=0,f=a.shiftKey?10:1;switch(a.keyCode){case dojo.keys.RIGHT_ARROW:b=f;break;case dojo.keys.LEFT_ARROW:b=-f;break;case dojo.keys.DOWN_ARROW:e=f;break;case dojo.keys.UP_ARROW:e=-f}var d=new A;dojo.forEach(c,function(a){var c=null,c=(c=a.getHelper())&&c.getMarginBoxPageCoords?c.getMarginBoxPageCoords(a):
p.getMarginBoxPageCoords(a.domNode);d.add(new v(a,c.l+b,c.t+e))},this);d.isEmpty()||(this._context.getCommandStack().execute(d),this._updateTargetOverlays())}},_moveFocus:function(a){a=a.shiftKey?-1:1;for(var c=this._context.getSelection()[0],b=this._context.getTopWidgets(),c=c?dojo.indexOf(b,c)+a:0<a?0:b.length-1,e=b[c];e&&!e.getContext();)c+=a,e=b[c];e&&this._context.select(e);return e},onMove:function(a,c,b){this._mouseDownInfo=null;a=this._context;var e=a._chooseParent,f=a.getSelection(),d=f.indexOf(this._moverWidget);
if(0>d)console.error("SelectTool.js onMove error. move widget is not selected");else{this._selectionHideFocus();var g=!1,h=e.getProposedParentWidget();if(h&&h.parent&&h.parent.domNode){var k=h.parent.domNode;if("BODY"==h.parent.domNode.tagName)g=!0;else for(h=b.target;h&&"BODY"!=h.tagName;){if(h==k){g=!0;break}h=h.parentNode}}(!g||b.target!=this._moverLastEventTarget)&&e.setProposedParentWidget(null);this._moverLastEventTarget=b.target;this._moverBox=c;this._moverDragDiv.style.left=c.l+"px";this._moverDragDiv.style.top=
c.t+"px";if(this._moverAbsolute){g=c.l-this._moverStartLocations[d].l;c=c.t-this._moverStartLocations[d].t;d=Math.abs(g);k=Math.abs(c);if(this._shiftKey&&(d>=this.CONSTRAIN_MIN_DIST||k>=this.CONSTRAIN_MIN_DIST))d>k?c=0:g=0;for(d=0;d<f.length;d++)k=f[d],h=this._moverStartLocationsRel[d].t,k.domNode.style.left=this._moverStartLocationsRel[d].l+g+"px",k.domNode.style.top=h+c+"px"}g=this._moverWidget.type;f=this._moverWidget.getParent();(c=e.parentListDivGet())||(c=e.parentListDivCreate({widgetType:g,
absolute:this._moverAbsolute,doCursor:!this._moverAbsolute,beforeAfter:null,currentParent:f}));if(d=a.getParentIframe()){offsetTop=offsetLeft=0;for(offsetNode=d;offsetNode&&"BODY"!=offsetNode.tagName;)offsetLeft+=offsetNode.offsetLeft,offsetTop+=offsetNode.offsetTop,offsetNode=offsetNode.offsetParent;d=p.getScrollLeft(a.rootNode);k=p.getScrollTop(a.rootNode);c.style.left=offsetLeft+b.pageX-d+"px";c.style.top=offsetTop+b.pageY-k+"px"}c=M.getPreferences("davinci.ve.editorPrefs",E.getProject());c=!this._shiftKey&&
c.snap&&this._moverAbsolute;d=a.getPreference("showPossibleParents");d=!0;e=e.isSpaceKeyDown()||this._spaceKey;e=!d&&e||d&&!e;g={type:g};d={x:b.pageX,y:b.pageY};k=null;k=(k=this._moverWidget.getHelper())&&k.getMarginBoxPageCoords?k.getMarginBoxPageCoords(this._moverWidget):p.getMarginBoxPageCoords(this._moverWidget.domNode);a.dragMoveUpdate({widgets:this._moverWidgets,data:g,eventTarget:b.target,position:d,absolute:this._moverAbsolute,currentParent:f,rect:k,doSnapLinesX:c,doSnapLinesY:c,doFindParentsXY:e,
doCursor:!this._moverAbsolute})}},onFirstMove:function(a){},onMoveStart:function(a){},onMoveStop:function(a){a=this._context;var c=this._context._chooseParent;this._moverWidget&&this._moverWidget._srcElement&&u.getXPath(this._moverWidget._srcElement,P);var b=!0,e,f;!this._moverBox||!this._moverWidget||!this._moverWidget.domNode?b=!1:(f={l:this._moverBox.l,t:this._moverBox.t},e=a.getSelection().indexOf(this._moverWidget),0>e&&(b=!1));if(b){b=void 0;if(this._sKey)for(var d=z.getStatesListCurrent(this._moverWidget.domNode),
g=0;g<d.length;g++){if(d[g]){b=d[g];break}}else b=z.propertyDefinedForAnyCurrentState(this._moverWidget.domNode,["left","top","right","bottom"]);g=this._getPageLeftTop(this._moverWidget.domNode.offsetParent);d=f.t-g.t-this._moverStartLocations[e].t;g=Math.abs(f.l-g.l-this._moverStartLocations[e].l);d=Math.abs(d);if(this._shiftKey&&(g>=this.CONSTRAIN_MIN_DIST||d>=this.CONSTRAIN_MIN_DIST))g>d?f.t=this._moverStartLocations[e].t:f.l=this._moverStartLocations[e].l;this.onExtentChange({index:e,newBox:f,
oldBoxes:this._moverStartLocations,copy:this._altKey,applyToWhichStates:b})}this._moverDragDiv&&((e=this._moverDragDiv.parentNode)&&e.removeChild(this._moverDragDiv),this._moverDragDiv=null);this._mover=this._moverBox=this._moverWidget=this._moverWidgets=this._moverLastEventTarget=null;this._updateMoveCursor();a.dragMoveCleanup();c.parentListDivDelete();this._selectionShowFocus();c=u.toCssPath(this._onMouseOverEventTargetXPath);a=a.getDocument();(a=c?a.querySelector(c):null)&&this._setTarget(a)},
_getPageLeftTop:function(a){var c=a.offsetLeft,b=a.offsetTop;for(a=a.offsetParent;a&&"BODY"!=a.tagName;)c+=a.offsetLeft,b+=a.offsetTop,a=a.offsetParent;return{l:c,t:b}},_areaSelectInit:function(a,c){this._areaSelect={x:a,y:c,attached:!1};this._areaSelectDiv=dojo.create("div",{className:"areaSelectDiv",style:"display:none"})},_areaSelectUpdate:function(a,c){if(this._areaSelect&&this._areaSelectDiv){var b=this._getBounds(this._areaSelect.x,this._areaSelect.y,a,c),e=this._areaSelectDiv.style;e.display=
"block";e.left=b.l+"px";e.top=b.t+"px";e.width=b.w+"px";e.height=b.h+"px";this._areaSelect.attached||(this._context.rootNode.appendChild(this._areaSelectDiv),this._areaSelect.attached=!0)}},_areaSelectClear:function(){this._areaSelect=null;if(this._areaSelectDiv){var a=this._areaSelectDiv.parentNode;a&&a.removeChild(this._areaSelectDiv);this._areaSelectDiv=null}},_areaSelectSelectWidgets:function(a,c){if(this._areaSelect){var b=this._getBounds(this._areaSelect.x,this._areaSelect.y,a,c),e=b.l,f=b.t,
d=b.w,b=b.h,g=this._context;g.deselect();for(var g=g.getTopWidgets(),h=0;h<g.length;h++)this._areaSelectRecursive(g[h],e,f,d,b)}},_areaSelectRecursive:function(a,c,b,e,f){if(a&&a.domNode){var d=p.getBorderBoxPageCoordsCached(a.domNode);if(d.l>=c&&d.t>=b&&d.l+d.w<=c+e&&d.t+d.h<=b+f)this._context.select(a,!0);else{a=a.getChildren();for(d=0;d<a.length;d++)this._areaSelectRecursive(a[d],c,b,e,f)}}},_getBounds:function(a,c,b,e){var f={};a<=b?(f.l=a,f.w=b-a):(f.l=b,f.w=a-b);c<=e?(f.t=c,f.h=e-c):(f.t=e,
f.h=c-e);return f},_checkFocusXY:function(a,c){for(var b=this._context,e=b.getSelection(),f=0;f<e.length;f++){var d=b._focuses[f].getBounds();if(a>=d.l&&a<=d.l+d.w&&c>=d.t&&c<=d.t+d.h)return e[f]}return null},_selectionHideFocus:function(){for(var a=this._context,c=a.getSelection(),b=0;b<c.length;b++)a._focuses[b].hide()},_selectionShowFocus:function(){for(var a=this._context,c=a.getSelection(),b=0;b<c.length;b++)a._focuses[b].show(c[b],{})}})});
//# sourceMappingURL=SelectTool.js.map