//>>built
define("davinci/ve/palette/PaletteFolder","dojo/_base/declare dijit/_WidgetBase dojo/dom-class dojo/fx davinci/Runtime davinci/ve/metadata".split(" "),function(p,q,k,g,s,r){return p("davinci.ve.palette.PaletteFolder",q,{icon:"",displayName:"",paletteId:"",palette:null,preset:null,presetId:null,presetClassName:null,_type:"",_isOpen:!1,_openSubsection:null,buildRendering:function(){this.palette=dijit.byId(this.paletteId);var d=this.domNode=this.palette.folderTemplate.cloneNode(!0);this.presetClassName&&
k.add(d,this.presetClassName);var c="PaletteFolder__"+this.presetId+"__"+this.section.id;this.subsection&&(c+="__"+this.subsection.id);dojo.attr(d,"selType",c);c=d.firstChild;dojo.attr(c,"tabIndex","0");c.onclick=this.palette.nop;c.firstChild.src=this.iconBase64?this.iconBase64:this.icon;c.appendChild(dojo.doc.createTextNode(this.displayName));d._paletteFolder=this;this._type=this.subsections?"subsection_container":this.subsection?"subsection":"simple";"subsection"==this._type&&k.add(d,"PaletteFolderSubsection");
this._children=[]},postCreate:function(){this.connect(this.domNode,"onmouseover","folderMouseOverHandler");this.connect(this.domNode,"onmouseout","folderMouseOutHandler");this.connect(this.domNode,"onclick","folderClickHandler")},startup:function(){},isFocusable:function(){return!0},focus:function(){dijit.focus(this.domNode)},addChild:function(d){for(var c=this.palette.getChildren(),a=0,e=c.length;a<e;a++)if(c[a]==this)return this.palette.addChild(d,a+1),!0;return!1},_paletteItemGroupInfo:function(d,
c){var a={},e=c,b=d[e],f=b._paletteItemGroup;do{b._paletteGroupSelected&&(a.selectedIndex=e);e++;if(e>=d.length)break;b=d[e]}while("davinci.ve.palette.PaletteItem"==b.declaredClass&&b._paletteItemGroup===f);"number"!=typeof a.selectedIndex&&(a.selectedIndex=c,d[c]._paletteGroupSelected=!0);a.endIndex=e-1;return a},folderClickHandler:function(d){this.showHideFolderContents()},showHideFolderContents:function(d){for(var c=this.palette.getChildren(),a=0,e=c.length;a<e;){var b=c[a];if(b==this){"none"==
this.domNode.style.display&&g.wipeIn({node:this.domNode,duration:100}).play();if("subsection_container"==this._type){this._isOpen="boolean"==typeof d?d:!this._isOpen;for(b=a+1;b<e;b++)if(a=c[b],"davinci.ve.palette.PaletteFolder"==a.declaredClass){if("subsection"!=a._type)break;0==a._children.length?(a.domNode.style.display="none",a.isOpen=!1):this._isOpen?(g.wipeIn({node:a.id,duration:100}).play(),a._isOpen=a==a.subsection_container._openSubsection):(g.wipeOut({node:a.id,duration:100}).play(),a.isOpen=
!1)}else this._isOpen&&a.PaletteFolderSubsection._isOpen?g.wipeIn({node:a.id,duration:100,onEnd:function(a){setTimeout(function(){a.style.height=""},1)}.bind(this,a.domNode)}).play():a.domNode.style.display="none"}else{this._isOpen="boolean"==typeof d?d:!this._isOpen;"subsection"==this._type&&(this.subsection_container._openSubsection=this._isOpen?this:null);for(b=a+1;b<e;){a=c[b];if("davinci.ve.palette.PaletteItem"!=a.declaredClass)break;for(a=this._paletteItemGroupInfo(c,b);b<=a.endIndex;b++){var f=
c[b],h=r.getWidgetDescriptorForType(f.type);if("custom"==h.category)h=!0;else{var k=h&&h.collection,h=!1;if(f.preset&&f.preset.collections)for(var n=f.preset.collections,l=0;l<n.length;l++){var m=n[l];if(m.id&&m.id===k){h=m.show;break}}}b==a.selectedIndex&&h?this._isOpen?g.wipeIn({node:f.id,duration:100,onEnd:function(a){setTimeout(function(){a.style.height=""},1)}.bind(this,f.domNode)}).play():g.wipeOut({node:f.id,duration:100}).play():f.domNode.style.display="none"}}}a=b}else{"davinci.ve.palette.PaletteItem"==
b.declaredClass&&"none"!=b.domNode.style.display&&g.wipeOut({node:b.id,duration:100}).play();if("davinci.ve.palette.PaletteFolder"==b.declaredClass&&("simple"==b._type||"subsection"==b._type))b._isOpen=!1;"davinci.ve.palette.PaletteFolder"==b.declaredClass&&"subsection_container"==b._type&&b!=this.subsection_container&&(b._isOpen=!1);"davinci.ve.palette.PaletteFolder"==b.declaredClass&&("subsection"==b._type&&!b.subsection_container._isOpen&&"none"!=b.domNode.style.display)&&(g.wipeOut({node:b.id,
duration:100}).play(),b._isOpen=!1);a++}}return!1},folderMouseOverHandler:function(d){dojo.removeClass(this.domNode,"dojoyPaletteFolderLow");dojo.addClass(this.domNode,"dojoyPaletteFolderHi")},folderMouseOutHandler:function(d){dojo.removeClass(this.domNode,"dojoyPaletteFolderHi");dojo.addClass(this.domNode,"dojoyPaletteFolderLow")}})});
//# sourceMappingURL=PaletteFolder.js.map