//>>built
define("davinci/ve/palette/PaletteItem","dojo/_base/declare dojo/on dojo/_base/event dojo/query dojo/dom-construct dojo/dom-geometry dijit/focus dijit/_WidgetBase dojo/dom-class dojox/html/entities dijit/popup dijit/Tooltip dijit/TooltipDialog davinci/ve/tools/CreateTool davinci/ui/dnd/DragManager davinci/ve/utils/GeomUtils davinci/ve/metadata dojo/i18n!davinci/ve/nls/common".split(" "),function(z,f,h,q,d,A,r,B,C,v,s,D,w,t,u,x,l,m){return z("davinci.ve.palette.PaletteItem",B,{icon:"",displayName:"",
name:"",paletteId:"",type:"",data:null,tool:"",palette:null,category:"",template:'\x3ca href\x3d"javascript:void(0)"\x3e\x3cspan class\x3d"paletteItemSelectionContainer"\x3e\x3c/span\x3e\x3cspan class\x3d"paletteItemNormalContainer"\x3e\x3cspan class\x3d"paletteItemImageContainer"\x3e\x3cimg class\x3d"paletteItemImage" border\x3d"0"/\x3e\x3c/span\x3e\x3cspan class\x3d"paletteItemLabelContainer"\x3e\x3cspan class\x3d"paletteItemLabel"\x3e\x3c/span\x3e\x3c/span\x3e\x3c/span\x3e\x3c/a\x3e',selectedWidgetTemplate:'\x3cspan class\x3d"paletteItemSelectionContent"\x3e\x3cspan class\x3d"paletteItemSelectedStrip paletteItemSelectedStripV paletteItemSelectedStripL"\x3e\x3c/span\x3e\x3cspan class\x3d"paletteItemSelectedStrip paletteItemSelectedStripV paletteItemSelectedStripR"\x3e\x3c/span\x3e\x3cspan class\x3d"paletteItemSelectedStrip paletteItemSelectedStripH paletteItemSelectedStripT"\x3e\x3c/span\x3e\x3cspan class\x3d"paletteItemSelectedStrip paletteItemSelectedStripH paletteItemSelectedStripB"\x3e\x3c/span\x3e\x3cspan class\x3d"paletteItemSelectedIcon paletteItemSelectedMoreIcon" title\x3d"'+
m.MoreIconTitleString+'"\x3e\x3c/span\x3e\x3cspan class\x3d"paletteItemSelectedIcon paletteItemSelectedHelpIcon" title\x3d"'+m.HelpIconTitleString+'"\x3e\x3c/span\x3e\x3c/span\x3e',preset:null,presetId:null,presetClassName:null,_paletteItemGroup:null,_collectionName:null,_paletteItemMoreConnects:[],_paletteItemHelpConnects:[],buildRendering:function(){this.palette=dijit.byId(this.paletteId);var a=this.domNode=dojo.create("div",{className:"dojoyPaletteCommon dojoyPaletteItem"});a.innerHTML=this.template;
a._paletteItem=this;this.presetClassName&&C.add(a,this.presetClassName);var b=this.type+"__"+this.presetId+"__"+this.PaletteFolderSection.section.id;this.PaletteFolderSubsection&&(b+="__"+this.PaletteFolderSubsection.subsection.id);dojo.attr(a,"selType",b);a=a.firstChild;dojo.attr(a,"tabIndex","0");a.onclick=this.palette.nop;a.querySelector("img").src=this.icon;a=a.querySelector(".paletteItemLabel");a.appendChild(dojo.doc.createTextNode(this.displayName));for(var b=v.encode(a.textContent),c=b.length-
1;0<c;c--)0<="_-".indexOf(b[c])?(b=b.substr(0,c+1)+"\x26#8203;"+b.substr(c+1),a.innerHTML=b):b[c].toLowerCase()!=b[c]&&(b=b.substr(0,c)+"\x26#8203;"+b.substr(c),a.innerHTML=b);this.domNode.componentClassName=this.name;dojo.setSelectable(this.domNode,!1)},postCreate:function(){var a=q(".paletteItemNormalContainer",this.domNode)[0];this.connect(a,"onmouseover","itemMouseOverHandler");this.connect(a,"onmouseout","itemMouseOutHandler");this.connect(this.domNode,"onmousedown","itemMouseDownHandler");this.connect(this.domNode,
"onmouseup","itemMouseUpHandler");this.connect(this.domNode,"onkeydown","itemKeyDownHandler")},startup:function(){},isFocusable:function(){return"none"!=dojo.style(this.domNode,"display")},focus:function(){dijit.focus(this.domNode)},itemMouseOverHandler:function(a){this._mouseover=!0;a=this.domNode;this.palette.selectedItem!=this&&this.raised(a);setTimeout(function(){if(this._mouseover&&(0==this.palette.moreItems.length&&0==this.palette.helpItems.length)&&this._tooltipNode!=this.domNode){this._tooltipNode&&
dijit.hideTooltip(this._tooltipPos);this._tooltipNode=this.domNode;this._tooltipPos=A.position(this.domNode,!0);var a;a='\x3cdiv class\x3d"paletteTooltip"\x3e'+('\x3cdiv class\x3d"paletteTooltipCurrent"\x3e\x3cspan class\x3d"paletteTooltipCurrentWidget"\x3e'+v.encode(this.displayName)+'\x3c/span\x3e \x3cspan class\x3d"paletteTooltipCurrentLibrary"\x3e('+this._collectionName+")\x3c/span\x3e\x3c/div\x3e");var c=this.palette.getPaletteItemsSameGroup(this);if(1<c.length){a+='\x3cdiv class\x3d"paletteTooltipAlternates"\x3e\x3cspan class\x3d"paletteTooltipAlternatesLabel"\x3e'+
m.alternates+': \x3c/span\x3e\x3cspan class\x3d"paletteTooltipAlternatesLibraries"\x3e';for(var d=!1,g=0;g<c.length;g++){var n=c[g];n!=this&&(d&&(a+=", "),a+=n._collectionName,d=!0)}a=a+"\x3c/div\x3e"+('\x3cdiv class\x3d"paletteTooltipNote"\x3e'+m.howToChooseAlternate+"\x3c/div\x3e");a+="\x3c/div\x3e"}dijit.showTooltip(a,this._tooltipPos);setTimeout(function(){dijit.hideTooltip(this._tooltipPos);this._tooltipPos=this._tooltipNode=null}.bind(this),5E3)}}.bind(this),750)},itemMouseOutHandler:function(a){this._mouseover=
!1;this._tooltipPos&&(dijit.hideTooltip(this._tooltipPos),this._tooltipPos=this._tooltipNode=null);a=this.domNode;this.palette.selectedItem==this?this.sunken(a):this.flat(a)},itemMouseDownHandler:function(a){a=this.domNode;this.focus();this.sunken(a);this.palette.selectedItem&&this.palette.selectedItem!=this&&(this.palette.removeSelectionAll(),this.flat(this.palette.selectedItem.domNode),this.palette.selectedItem=null);u.document=this.palette._context.getDocument();if(a=this.palette._context.frameNode){a=
dojo.coords(a);var b=this.palette._context.getContainerNode();u.documentX=a.x-x.getScrollLeft(b);u.documentY=a.y-x.getScrollTop(b)}l.getHelper(this.type,"helper")},itemMouseUpHandler:function(a){a=this.domNode;if(this.palette.selectedItem==this)this.palette.removeSelectionAll(),this.palette.selectedItem.flat(this.palette.selectedItem.domNode),this.palette.selectedItem=null,this.palette.sunkenItem=null,this.palette.flattenAll(),this.palette._context.setActiveTool(null),r.curNode&&(r.curNode==a&&r.curNode.blur)&&
r.curNode.blur();else{this.palette.selectedItem&&this.palette.selectedItem!=this&&(this.palette.removeSelectionAll(),this.flat(this.palette.selectedItem.domNode),this.palette.selectedItem=null);this.palette.selectedItem=this;this.sunken(a);l.getHelper(this.type,"tool").then(function(a){a=new (a||t)(dojo.clone(this.data));this.palette._context.setActiveTool(a)}.bind(this));var b=function(){this.palette._contextMouseUpHandler&&(this.disconnect(this.palette._contextMouseUpHandler),this.palette._contextMouseUpHandler=
null);this.palette._docMouseUpHandler&&(dojo.disconnect(this.palette._docMouseUpHandler),this.palette._docMouseUpHandler=null);this.palette.removeSelectionAll();this.palette.selectedItem=null;this.flat(this.domNode);this.palette._context.dragMoveCleanup()}.bind(this);this.palette._contextMouseUpHandler=this.connect(this.palette._context,"onMouseUp",function(a){b()}.bind(this));setTimeout(function(){this.palette._docMouseUpHandler=dojo.connect(document,"onmouseup",function(a){var d=!1;if(this.palette.selectedItem){var g=
this.palette.selectedItem.domNode;for(a=a.target;a&&"BODY"!=a.tagName;){if(a==g){d=!0;break}a=a.parentNode}}this.palette.selectedItem&&!d&&(b(),this.palette._context.setActiveTool(null))}.bind(this))}.bind(this),0)}},itemKeyDownHandler:function(a){a.keyCode==dojo.keys.ENTER&&(this.palette.selectedItem&&(this.flat(this.palette.selectedItem.domNode),this.palette.selectedItem=null),l.getHelper(this.type,"tool").then(function(a){a=new (a||t)(dojo.clone(this.data));var c=this.palette._context;c.setActiveTool(a);
a.create({target:c.getSelection()[0],position:{x:50,y:50}});c.setActiveTool(null);c.getContainerNode().focus()}),l.getHelper(this.type,"helper"))},flat:function(a){dojo.removeClass(a,"dojoyPaletteItemRaised");dojo.removeClass(a,"dojoyPaletteItemSunken");dojo.addClass(a,"dojoyPaletteItemFlat")},raised:function(a){dojo.removeClass(a,"dojoyPaletteItemFlat");dojo.removeClass(a,"dojoyPaletteItemSunken");dojo.addClass(a,"dojoyPaletteItemRaised");this.palette.raisedItems.push(this)},sunken:function(a){dojo.removeClass(a,
"dojoyPaletteItemFlat");dojo.removeClass(a,"dojoyPaletteItemRaised");dojo.addClass(a,"dojoyPaletteItemSunken");this.palette.sunkenItems.push(this);this._selectionShowing=!0;q(".paletteItemSelectionContainer",this.domNode)[0].innerHTML=this.selectedWidgetTemplate;var b=q(".paletteItemSelectedMoreIcon",a)[0],c=this.palette.getPaletteItemsSameGroup(this);1<c.length?(b.style.display="inline-block",f(b,"mousedown, mouseup",function(a){h.stop(a)}),f(b,"click",function(a){h.stop(a);this._tooltipNode&&(dijit.hideTooltip(this._tooltipPos),
this._tooltipPos=this._tooltipNode=null);if(this._moreShowing)this.paletteItemMoreCloseCleanup();else{a=d.create("div",{className:"paletteItemMoreContent"});var n=d.create("span",{className:"paletteItemMoreCloseBox"},a);d.create("div",{className:"paletteItemAlternatesLabel",innerHTML:m.alternateWidgets},a);this._paletteItemMoreConnects.push(f(n,"mousedown, mouseup",function(a){h.stop(a)}.bind(this)));this._paletteItemMoreConnects.push(f(n,"click",function(a){h.stop(a);this.paletteItemMoreCloseCleanup()}.bind(this)));
for(var n=d.create("div",{className:"paletteItemAlternatesContainer"},a),p=[],k=0;k<c.length;k++){var e=c[k],y=e._collectionName,e=d.create("button",{className:"paletteItemAlternate "+(e._paletteGroupSelected?"paletteItemMoreSelected":"paletteItemMoreUnselected"),innerHTML:y},n);p.push(e);this._paletteItemMoreConnects.push(f(e,"mousedown, mouseup",function(a){h.stop(a)}.bind(this)));this._paletteItemMoreConnects.push(f(e,"click",function(a,b){h.stop(b);for(var d,g=0;g<c.length;g++){var e=c[g];if(e._collectionName==
a){d=e;break}}if(d){for(g=0;g<c.length;g++)e=c[g],e==d?(e._paletteGroupSelected=!0,e.domNode.style.display=this.palette._displayShowValue):(e._paletteGroupSelected=!1,e.domNode.style.display="none");d.sunken(d.domNode);l.getHelper(d.type,"tool").then(function(a){a=new (a||t)(dojo.clone(this.data));this.palette._context.setActiveTool(a)}.bind(d))}this.paletteItemMoreCloseCleanup()}.bind(this,y)))}this._tooltipDialog=new w({className:"paletteItemMorePopup",style:"width: auto; ",content:a,onShow:function(a){if(a=
this._tooltipDialog.domNode.parentNode){var b=parseFloat(a.style.top);isNaN(b)||(a.style.top=b+12+"px")}}.bind(this)});s.open({popup:this._tooltipDialog,around:b,orient:["above-centered"]});this._moreShowing=!0;this.palette.moreItems.push(this)}}.bind(this))):b.style.display="none";var p=q(".paletteItemSelectedHelpIcon",a)[0];f(p,"mousedown, mouseup",function(a){h.stop(a)}.bind(this));f(p,"click",function(a){h.stop(a);this._tooltipNode&&(dijit.hideTooltip(this._tooltipPos),this._tooltipPos=this._tooltipNode=
null);if(this._helpShowing)this.paletteItemHelpCloseCleanup();else{var b=l.getOamDescriptivePropertyForType(this.type,"title"),c=l.getOamDescriptivePropertyForType(this.type,"description");a=d.create("div",{className:"helpInnerContent"});var k=d.create("div",{className:"paletteTooltipCurrent"},a);d.create("span",{className:"paletteTooltipCurrentWidget"},k).textContent=this.name;this._collectionName&&d.create("span",{className:"paletteTooltipCurrentLibrary",innerHTML:" ("+this._collectionName+")"},
k);k={container:"helpInnerContentSummary",title:"helpInnerContentSummaryTitle",content:"helpInnerContentSummaryContent"};this._createHelpSection(b,a,m.summary,k);this._createHelpSection(c,a,m.description,k);b=d.create("div",{className:"paletteItemHelpContent"});c=d.create("span",{className:"paletteItemHelpCloseBox"},b);d.create("div",{className:"paletteItemHelpDescription"},b).appendChild(a);this._paletteItemHelpConnects.push(f(c,"mousedown, mouseup",function(a){h.stop(a)}.bind(this)));this._paletteItemHelpConnects.push(f(c,
"click",function(a){h.stop(a);this.paletteItemHelpCloseCleanup()}.bind(this)));this._tooltipDialog=new w({className:"paletteItemHelpPopup",style:"width: auto; ",content:b,onShow:function(a){if(a=this._tooltipDialog.domNode.parentNode){var b=parseFloat(a.style.top);isNaN(b)||(a.style.top=b-12+"px")}}.bind(this)});s.open({popup:this._tooltipDialog,around:p,orient:["below-centered"]});this._helpShowing=!0;this.palette.helpItems.push(this)}}.bind(this))},_createHelpSection:function(a,b,c,f){a&&a.value&&
(b=d.create("div",{className:f.container},b),d.create("div",{className:f.title,innerHTML:c},b),c=d.create("div",{className:f.content},b),"text/html"==a.type?c.innerHTML=a.value:c.textContent=a.value)},paletteItemMoreCloseCleanup:function(){if(this._moreShowing){for(var a=0;a<this._paletteItemMoreConnects.length;a++)this._paletteItemMoreConnects[a].remove();this._paletteItemMoreConnects=[];this._moreShowing=!1;index=this.palette.moreItems.indexOf(this);0<=index&&this.palette.moreItems.splice(index,
1)}this._tooltipDialog&&(s.close(this._tooltipDialog),this._tooltipDialog.destroyRecursive(),this._tooltipDialog=null)},paletteItemHelpCloseCleanup:function(){if(this._helpShowing){for(var a=0;a<this._paletteItemHelpConnects.length;a++)this._paletteItemHelpConnects[a].remove();this._paletteItemHelpConnects=[];this._helpShowing=!1;index=this.palette.helpItems.indexOf(this);0<=index&&this.palette.helpItems.splice(index,1)}this._tooltipDialog&&(s.close(this._tooltipDialog),this._tooltipDialog.destroyRecursive(),
this._tooltipDialog=null)},updateImgSrc:function(a){this.domNode.querySelector(".paletteItemImage").src=a}})});
//# sourceMappingURL=PaletteItem.js.map