//>>built
define("davinci/ve/palette/Palette","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/on dojo/query dojo/dom-class dojo/Deferred dijit/focus dijit/_WidgetBase davinci/Runtime davinci/Workbench dijit/_KeyNavContainer dijit/form/TextBox dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem davinci/ui/dnd/DragSource davinci/ve/metadata davinci/library ./PaletteFolder ./PaletteItem dojo/i18n!davinci/ve/nls/common davinci/ve/tools/CreateTool davinci/workbench/Preferences".split(" "),function(B,
C,z,M,A,D,E,x,F,y,w,G,N,O,P,Q,H,v,I,R,J,K,L,u){return B("davinci.ve.palette.Palette",[F,G],{descriptors:"",_displayShowValue:"block",_presetClassNamePrefix:"maqPaletteSection_",_presetSections:{},_presetCreated:{},raisedItems:[],sunkenItems:[],moreItems:[],helpItems:[],_userWidgetSection:{id:"$$UserWidgets$$",name:"User Widgets",includes:[]},postMixInProperties:function(){this._resource=K},postCreate:function(){dojo.addClass(this.domNode,"dojoyPalette");this.refresh();z.subscribe("/davinci/ui/addedCustomWidget",
this,"addCustomWidget");z.subscribe("/davinci/preferencesChanged",this,"preferencesChanged")},addCustomWidget:function(a){if(this._loaded&&a&&a.$wm&&a.$wm.widgets&&a.$wm.widgets.length){var d=y.currentEditor.getContext().getCompType();u.getPreferences("davinci.ve.editorPrefs",w.getProject()).showAllWidgets&&(d="mobile"==d?"$ALLMOBILE":"$ALLDESKTOP");var c=a.$wm;a=a.$wm.widgets;for(var b=null,f=0;f<a.length;f++){var e=a[f],k;for(k in this._presetSections){var g=null,l=this._presetSections[k];if(l){for(var h=
0;h<l.length;h++){var m=l[h];if("$$UserWidgets$$"==m.id){g=m;break}}g||(g=dojo.clone(this._userWidgetSection),g.preset=this._presetSections[k],g.presetId=k,g.items=[],l.push(g),this._presetCreated[k]&&(this._generateCssRules([g]),this._createPalette(g),g._created=!0));l="type:"+e.type;if(0>g.includes.indexOf(l)){g.includes.push(l);e.$library=c;e.section=g;e._paletteItemGroup=this._paletteItemGroupCount++;g.items.push(e);l=null;h=this.getChildren();for(m=0;m<h.length;m++){var q=h[m];if("davinci.ve.palette.PaletteFolder"==
q.declaredClass&&q.presetId==k&&"$$UserWidgets$$"==q.section.id){l=q;break}}l&&(l.domNode.style.display="none",g={displayName:e.$library._maqGetString(e.type)||e.$library._maqGetString(e.name)||e.name,description:e.$library._maqGetString(e.type+"_description")||e.$library._maqGetString(e.name+"_description")||e.description||e.type,name:e.name,paletteId:this.id,type:e.type,data:e.data||{name:e.name,type:e.type,properties:e.properties,children:e.children},tool:e.tool,category:"custom",section:g,PaletteFolderSection:l,
PaletteFolderSubsection:null,_paletteItemGroup:e._paletteItemGroup,_paletteGroupSelected:!0},this._setIconProperties(e,g),this._createItem(g,l).domNode.style.display="none",d==k&&(b=l))}}else console.error("Palette.js:addCustomWidget - no sections for comptype\x3d"+k)}}b&&b.showHideFolderContents(!0)}},setContext:function(a){this._context=a;try{this._loadPalette()}catch(d){console.error("_loadPalette:crash "+d)}this._filter();this.updatePaletteVisibility()},refresh:function(){delete this._loaded;
this._presetSections={};this._createFolderTemplate();this._createHeader();if(this._context)try{this._loadPalette()}catch(a){console.error("_loadPalette:crash")}},_loadPalette:function(){if(!this._loaded){var a=v.getLibrary(),d={};I.getUserLibs(w.getProject()).forEach(function(b){var c;a:{c=b.id;b=b.version;for(var f in a)if(a.hasOwnProperty(f)){var e=a[f];if(e.name===c&&e.version===b){b={};b[c]=a[f];c=b;break a}}c=null}c&&dojo.mixin(d,c)});var c={};console.error("load palette");var b=[],f;for(f in d)if(d.hasOwnProperty(f)){var e=
d[f].$wm;e&&dojo.forEach(e.widgets,function(a){"untested"==a.category||a.hidden||b.push(a.type)})}this._paletteItemGroupCount=0;if(this._widgetPalette=y.getSiteConfigData("widgetPalette"))if(f=this._widgetPalette.presets,!f||"object"!=typeof f)console.warning("No presets defined in widgetPalette.json (in siteConfig folder)");else for(var k in f){e=b.concat();this._presetSections[k]=[];var g=f[k],l,h="string"==typeof g.sections?this._widgetPalette.defs?this._widgetPalette.defs[g.sections]:void 0:g.sections;
if(!h||!h.length)console.warning("No sections defined for preset "+k+" in widgetPalette.json (in siteConfig folder)");else{var m=[],q;for(q in c){var n=c[q];n.descriptor&&m.push({name:q,value:n})}m.sort(function(a,b){var c=a.name.split("/").pop().toLowerCase(),d=b.name.split("/").pop().toLowerCase();return c<d?-1:c>d?1:0});for(var n=!1,u,r=0;r<m.length;r++){n||(q=dojo.clone(this._userWidgetSection),h=h.concat(q),n=!0,u=q.includes);var s=m[r].value.descriptor.widgets;for(q=0;q<s.length;q++)u.push("type:"+
s[q].type)}for(m=0;m<h.length;m++){n=dojo.clone("string"==typeof h[m]?this._widgetPalette.defs?this._widgetPalette.defs[h[m]]:void 0:h[m]);n.preset=g;n.presetId=k;if(n.subsections&&n.subsections.length){r=n.subsections;for(s=0;s<r.length;s++){if("string"==typeof r[s]){var t=this._widgetPalette.defs?this._widgetPalette.defs[r[s]]:void 0;t&&(r[s]=dojo.clone(t))}t=r[s];t.includes&&0<=t.includes.indexOf("$$AllOthers$$")&&(l=t);t.preset=g;t.presetId=k;this._createSectionItems(t,g,e)}}else this._createSectionItems(n,
g,e),n.includes&&0<=n.includes.indexOf("$$AllOthers$$")&&(l=n);this._presetSections[k].push(n)}}for(g=0;g<e.length;g++)h=e[g],l&&(h=v.getWidgetDescriptorForType(h),h=dojo.clone(h),this._prepareSectionItem(h,l,this._paletteItemGroupCount),l.items.push(h),this._paletteItemGroupCount++)}else console.error("widgetPalette.json not defined (in siteConfig folder)");this._loaded=!0}},_generateCssRules:function(a){var d=dojo.doc.styleSheets[0];d&&dojo.forEach(a,function(a){a.items&&dojo.forEach(a.items,function(a){var c=
a.iconBase64||this._getIconUri(a.icon,"ve/resources/images/file_obj.gif");a="img.davinci_"+a.type.replace(/[\.\/]/g,"_");c="{background-image: url("+c+")}";dojo.isIE?d.addRule(a,c):d.insertRule(a+c,d.cssRules.length)},this)},this)},_createPaletteItemsForComponent:function(a,d){if(a.items){var c=null;dojo.forEach(a.items,function(b){if(!b.hidden){var f={displayName:b.$library._maqGetString(b.type)||b.$library._maqGetString(b.name)||b.name,description:b.$library._maqGetString(b.type+"_description")||
b.$library._maqGetString(b.name+"_description")||b.description||b.type,name:b.name,paletteId:this.id,type:b.type,data:b.data||{name:b.name,type:b.type,properties:b.properties,children:b.children},category:a.name,section:a,preset:a.preset,presetId:a.presetId,presetClassName:d.presetClassName,PaletteFolderSection:d.PaletteFolderSection,PaletteFolderSubsection:d.PaletteFolderSubsection,_paletteItemGroup:b._paletteItemGroup,_paletteGroupSelected:b._paletteItemGroup!=c,_collectionName:b.$library&&b.$library.collections&&
b.$library.collections[b.collection]&&b.$library.collections[b.collection].name};this._setIconProperties(b,f);this._createItem(f);c=b._paletteItemGroup}},this)}},_createPalette:function(a){var d=a.presetId?this._presetClassNamePrefix+a.presetId:null,c={paletteId:this.id,icon:this._getIconUri(a.icon,"ve/resources/images/fldr_obj.gif"),iconBase64:a.iconBase64,displayName:a.name,section:a,subsections:a.subsections,subsection_container:null,preset:a.preset,presetId:a.presetId,presetClassName:d};this._createFolder(c).then(function(b){if(a.subsections&&
a.subsections.length)for(var c=0;c<a.subsections.length;c++){var e=a.subsections[c],e={paletteId:this.id,icon:this._getIconUri(e.icon,"ve/resources/images/fldr_obj.gif"),iconBase64:e.iconBase64,displayName:e.name,section:a,subsection:e,subsection_container:b,preset:a.preset,presetId:a.presetId,presetClassName:d};this._createFolder(e).then(function(e){b._children.push(e);this._createPaletteItemsForComponent(a.subsections[c],{presetClassName:d,PaletteFolderSection:b,PaletteFolderSubsection:e})}.bind(this))}else this._createPaletteItemsForComponent(a,
{presetClassName:d,PaletteFolderSection:b,PaletteFolderSubsection:null})}.bind(this))},_getIconUri:function(a,d){return a?0==a.indexOf("http")?a:w.location()+a:require.toUrl("davinci/"+d)},_createFolder:function(a){var d=new E;require(["davinci/ve/palette/PaletteFolder"],function(c){c=new c(a);this.addChild(c);d.resolve(c)}.bind(this));return d},_createFolderTemplate:function(){this.folderTemplate=dojo.create("div",{className:"dojoyPaletteCommon dojoyPaletteFolder dojoyPaletteFolderLow ui-widget-header",
innerHTML:'\x3ca href\x3d"javascript:void(0)"\x3e\x3cimg border\x3d"0"/\x3e\x3c/a\x3e'})},_createHeader:function(){},_updateShowAllWidgetsPreference:function(a){var d=w.getProject(),c=u.getPreferences("davinci.ve.editorPrefs",d);c.showAllWidgets=a;u.savePreferences("davinci.ve.editorPrefs",d,c)},_updateShowAllWidgetsMenu:function(a){},_clearFilter:function(){this.filterField&&this.filterField.set("value","");this._filter()},_filter:function(){var a=this.context.getCompType(),d=u.getPreferences("davinci.ve.editorPrefs",
w.getProject());d.showAllWidgets=!0;d.showAllWidgets&&(a="mobile"==a?"$ALLMOBILE":"$ALLDESKTOP");dojo.removeClass(this.domNode,"maqWidgetsFiltered");dojo.removeClass(this.toolbarDiv,"maqWidgetsToolbarFiltered");this.getChildren().forEach(function(c){"dijit.form.TextBox"!=c.declaredClass&&dojo.style(c.domNode,"display","davinci.ve.palette.PaletteFolder"===c.declaredClass&&c.presetId==a&&0<c._children.length&&("simple"==c._type||"subsection_container"==c._type)?"block":"none")})},_hasItem:function(a){for(var d=
this.getChildren(),c=0;c<d.length;c++)if(d[c].type==a)return!0;return!1},_createItem:function(a,d){if("$$UserWidgets$$"!=a.section.id){var c=v.queryDescriptor(a.type,"collection"),b;if(a.preset&&(b=a.preset.collections,!b||!b.length)){console.error("_create item : presetCollections.l\x3d0");return}if(a.preset&&a.preset.exclude){var f="string"==typeof a.preset.exclude?this._widgetPalette.defs?this._widgetPalette.defs[a.preset.exclude]:void 0:a.preset.exclude;if(f&&0<=f.indexOf(a.type)){console.error("_create item : exclude \x3d 1");
return}}f=!1;if(b&&b.length){for(var e=0;e<b.length;e++)if(b[e].id==c&&b[e].show){f=!0;break}if(!f)return}}a.icon=a.iconLarge;c=new J(a);d?d.addChild(c):this.addChild(c);a.PaletteFolderSubsection?(a.PaletteFolderSubsection._children.push(c),c.domNode.style.display=a.PaletteFolderSubsection._isOpen&&c._paletteGroupSelected?this._displayShowValue:"none"):a.PaletteFolderSection&&(a.PaletteFolderSection._children.push(c),c.domNode.style.display=a.PaletteFolderSection._isOpen&&c._paletteGroupSelected?
this._displayShowValue:"none");b=A(".paletteItemImageContainer",c.domNode)[0];b=new H(c.domNode,"component",c,b);b.targetShouldShowCaret=!0;b.returnCloneOnFailure=!1;this.connect(b,"onDragStart",dojo.hitch(this,function(a){this.onDragStart(a)}));this.connect(b,"onDragEnd",dojo.hitch(this,function(a){this.onDragEnd(a)}));return c},_prepareSectionItem:function(a,d,c){var b=v.getLibraryMetadataForType(a.type);a.$library=b;a.section=d;a._paletteItemGroup=c},_createSectionItems:function(a,d,c){a.items=
[];collections=d.collections;d=a.includes;if(!d||!d.length)return console.warning("No includes property for preset "+p+" in widgetPalette.json (in siteConfig folder)"),returnItems;for(var b=0;b<d.length;b++){for(var f=d[b],e=C.isArray(f)?f:[f],f=[],k=0;k<e.length;k++){var g=e[k],l=[];if("type:"===g.substr(0,5)){var h=v.getWidgetDescriptorForType(g.substr(5));h&&l.push(h)}else l=v.getWidgetsWithTag(g);for(g=0;g<l.length;g++)h=l[g],h=dojo.clone(h),this._prepareSectionItem(h,a,this._paletteItemGroupCount),
f.push(h)}e=[];if(collections&&collections.length){for(l=0;l<collections.length;l++){g=collections[l];for(k=0;k<f.length;)h=f[k],h.collection==g.id?(e.push(h),f.splice(k,1)):k++}for(k=0;k<f.length;k++)e.push(f[k])}else e=f;for(k=0;k<e.length;k++)f=e[k],l=c.indexOf(f.type),0<=l&&c.splice(l,1),a.items.push(f);this._paletteItemGroupCount++}},updatePaletteVisibility:function(){this._clearFilter();this._updateShowAllWidgetsMenu();var a=y.currentEditor.getContext().getCompType();this._presetCreated[a]=
!0;dojo.addClass(this.domNode,"paletteLayoutIcons");this._displayShowValue="inline-block";var d=this._presetSections[a];if(d)for(var c=0;c<d.length;c++){var b=d[c];b._created||(this._generateCssRules([b]),this._createPalette(b),b._created=!0)}else console.error("Palette.js - no sections for comptype\x3d"+a);d=this.getChildren();c=0;for(b=d.length;c<b;c++){var f=d[c];f&&(f.domNode&&f.presetId)&&("davinci.ve.palette.PaletteFolder"==f.declaredClass?(f.domNode.style.display=f.presetId==a?0==f._children.length||
"subsection"==f._type?"none":"block":"none","subsubsection_container"==f._type&&(f._openSubsection=null),f._isOpen=!1):f.domNode.style.display="none")}},preferencesChanged:function(){for(var a=u.getPreferences("davinci.ve.editorPrefs",w.getProject()),a=!a.widgetPaletteLayout||"icons"==a.widgetPaletteLayout?"iconLarge":"icon",d=this.getChildren(),c=0;c<d.length;c++){var b=d[c];"davinci.ve.palette.PaletteItem"==b.declaredClass&&b.updateImgSrc(b[a])}this.updatePaletteVisibility()},flattenAll:function(){for(var a=
0;a<this.raisedItems.length;a++)this.raisedItems[a].flat(this.raisedItems[a].domNode);this.raisedItems=[];for(a=0;a<this.sunkenItems.length;a++){var d=this.sunkenItems[a];d._tooltipDialog&&(d.paletteItemMoreCloseCleanup(),d.paletteItemHelpCloseCleanup());d.flat(d.domNode);d._selectionShowing=!1}this.sunkenItems=[]},removeSelectionAll:function(){this.flattenAll();for(var a=A(".paletteItemSelectionContent",this.domNode),d=0;d<a.length;d++){var c=a[d];c&&c.parentNode&&(c.parentNode.innerHTML="")}},getPaletteItemsSameGroup:function(a){for(var d=
[],c=a._paletteItemGroup,b;a&&a._paletteItemGroup;)if(a._paletteItemGroup==c)a=(b=a)&&a.domNode&&a.domNode.previousSibling&&a.domNode.previousSibling._paletteItem;else break;for(a=b;a&&a._paletteItemGroup==c;)d.push(a),a=a&&a.domNode&&a.domNode.nextSibling&&a.domNode.nextSibling._paletteItem;return d},_setIconProperties:function(a,d){d.icon=a.iconBase64||a.icon&&this._getIconUri(a.icon,"ve/resources/images/file_obj.gif")||a.iconLargeBase64||a.iconLarge&&this._getIconUri(a.iconLarge,"ve/resources/images/file_obj.gif")||
this._getIconUri(a.icon,"ve/resources/images/file_obj.gif");d.iconLarge=a.iconLargeBase64||a.iconLarge&&this._getIconUri(a.iconLarge,"ve/resources/images/file_obj.gif")||a.iconBase64||this._getIconUri(a.icon,"ve/resources/images/file_obj.gif")},onDragStart:function(a){this.removeSelectionAll();this.selectedItem=null;var d=a.dragSource.data;v.getHelper(d.type,"tool").then(function(a){a=new (a||L)(dojo.clone(d.data));this._context.setActiveTool(a)}.bind(this));this._context.blockChange(!1);a._dragClone&&
(D.add(a._dragClone,"paletteDragContainer"),dojo.create("div",{className:"maqCandidateParents"},a._dragClone));this._context.setActiveDragDiv(a._dragClone);this._dragKeyDownListener=dojo.connect(document,"onkeydown",dojo.hitch(this,function(a){var b=this._context.getActiveTool();if(b&&b.onKeyDown)b.onKeyDown(a)}));this._dragKeyUpListener=dojo.connect(document,"onkeyup",dojo.hitch(this,function(a){var b=this._context.getActiveTool();if(b&&b.onKeyUp)b.onKeyUp(a)}))},onDragEnd:function(a){this._context.setActiveTool(null);
this._context.setActiveDragDiv(null);dojo.disconnect(this._dragKeyDownListener);dojo.disconnect(this._dragKeyUpListener);x.curNode&&x.curNode.blur&&x.curNode.blur();this.removeSelectionAll();this.selectedItem=null;this.flattenAll()},onDragMove:function(a){},nop:function(){return!1},__dummy__:null})});
//# sourceMappingURL=Palette.js.map