//>>built
define("davinci/ui/dnd/DragSource",["dojo/_base/declare","dojo/fx"],function(e,d){return e("davinci.ui.dnd.DragSource",null,{disabled:!1,dragObject:null,dragClone:null,offsetParent:null,offsetParentCoords:null,parentCoords:null,refNode:null,positioning:null,useCurrentPositioning:!0,targetShouldShowCaret:!1,draggingMousePosition:"TopLeft",data:null,returnCloneOnFailure:!0,constructor:function(a,b,c,d){this.data=c;a=dojo.byId(a);a.dragSource=this;this.domNode=a;this.dragObject=d?d:a;this.refNode=a;
this.type=b;this.offsetParent=dojo.doc.body},onDragDown:function(a){this.useCurrentPositioning&&(this.positioning=dojo.style(this.refNode,"position"));this.storeMouseDownInfo(a);this.initDrag(a)},onDragStart:function(a){this.createDragClone(a);return a._dragClone=this.dragClone},onDragMove:function(a){"TopLeft"==this.draggingMousePosition?(this.dragClone.style.top=a.pageY+4+(a.documentY||0)+"px",this.dragClone.style.left=a.pageX+4+(a.documentX||0)+"px"):"ClickedPosition"==this.draggingMousePosition&&
(this.dragClone.style.top=a.pageY-this.dragOffset.y+(a.documentY||0)+"px",this.dragClone.style.left=a.pageX-this.dragOffset.x+(a.documentX||0)+"px");"none"==this.dragClone.style.display&&(this.dragClone.style.display="")},onDragEnd:function(a){"dropSuccess"==a.dragStatus||!this.returnCloneOnFailure?this.removeClone():"dropFailure"==a.dragStatus?this.returnClone():console.error("DragSource#onDragEnd: internal error: e.dragStatus is not set");this.cleanupDrag()},unregister:function(){this.domNode.dragSource=
null;this.cleanupDrag()},reregister:function(){this.domNode.dragSource=this;this.initDrag()},storeMouseDownInfo:function(a){dojo.isIE?(this.layerX=a.layerX+dojo._getBorderExtents(this.domNode).l,this.layerY=a.layerY+dojo._getBorderExtents(this.domNode).t):(this.layerX=a.layerX-1,this.layerY=a.layerY-1);this.pageX=a.pageX;this.pageY=a.pageY;this.scrollOffset=dojo._docScroll();this.dragStartPosition=dojo.position(this.refNode,!0);this.dragStartCssPosition={y:this.refNode.offsetTop,x:this.refNode.offsetLeft};
this.dragOffset={y:a.pageY-this.dragStartPosition.y,x:a.pageX-this.dragStartPosition.x};this.offsetParentCoords=dojo.position(this.offsetParent,!0);a=dojo.position(this.domNode.parentNode,!0);this.parentCoords={y:a.y-this.offsetParentCoords.y,x:a.x-this.offsetParentCoords.x};this.fixMouseDownInfo&&this.fixMouseDownInfo(this)},initDrag:function(){dojo.isIE&&dojo._event_listener.add(this.domNode,"ondragstart",this.cancelEvent)},cleanupDrag:function(){dojo.isIE&&dojo._event_listener.remove(this.domNode,
"ondragstart",this.cancelEvent)},createDragClone:function(a){this.dragClone=a=a.dragSource.dragHandler&&a.dragSource.dragHandler.createDragClone?a.dragSource.dragHandler.createDragClone():this.dragObject.cloneNode(!0);dojo.style(a,"opacity",0.5);a.style.zIndex=1001E3;var b=dojo.contentBox(this.dragObject);a.style.width=b.w+"px";a.style.height=b.h+"px";a.style.top=this.dragObject.offsetTop+4+"px";a.style.left=this.dragObject.offsetLeft+4+"px";a.style.position="absolute";a.style.clear="both";a.style.display=
"none";this.offsetParent.appendChild(a)},setDragTarget:function(a){this.dragObject=a},cancelEvent:function(a){a.stopPropagation();a.preventDefault()},removeClone:function(){setTimeout(dojo.hitch(this,"removeClone_1"),0)},removeClone_1:function(){this.dragClone.parentNode.removeChild(this.dragClone);this.dragClone=null},returnClone:function(){var a=dojo.position(this.dragClone,!0),b=this.dragStartPosition,c=this;d.slideTo({node:this.dragClone,top:a.y>b.y?b.y-10:b.y+10,left:a.x>b.x?b.x-10:b.x+10,duration:400,
onEnd:function(){d.slideTo({node:c.dragClone,top:b.y,left:b.x,duration:100,onEnd:function(){c.dragClone.parentNode.removeChild(c.dragClone);c.dragClone=null;c.onCloneReturned()}}).play()}}).play()},onCloneReturned:function(){},globalChangeCursor:function(a){var b=dojo.doc.styleSheets[0];if(b)if(a){if(this._showingCursor){if(this._showingCursor==a)return;this.globalChangeCursor(null)}this._showingCursor=a;dojo.isIE?(this._ruleIndex=b.rules.length,b.addRule("*","{cursor:"+a+" ! important;}",b.rules.length),
this._prevCursor=dojo.doc.body.style.cursor,dojo.doc.body.style.cursor=null):(this._ruleIndex=b.cssRules.length,b.insertRule("*{cursor:"+a+" ! important;}",b.cssRules.length))}else this._showingCursor&&(this._showingCursor=null,dojo.isIE?(b.removeRule(this._ruleIndex),dojo.doc.body.style.cursol=null!=this._prevCursor?this._prevCursor:"auto"):b.deleteRule(this._ruleIndex))}})});
//# sourceMappingURL=DragSource.js.map