//>>built
define("davinci/ui/dnd/DragManager",["dojo/_base/declare"],function(g){return(new g("",null,{disabled:!1,currentDragSource:null,currentDropTarget:null,dropAcceptable:!1,dropTargets:null,dragTriggered:!1,currentDomElement:null,_connectors:null,_moveConnector:null,document:null,documentX:0,documentY:0,_ABSOLUTE_THRESHOLD:3,_STATIC_THRESHOLD:40,constructor:function(){this.dropTargets=[];this._connectors=[dojo.connect(dojo.doc,"onkeydown",this,"onKeyDown"),dojo.connect(dojo.doc,"onmouseover",this,"onMouseOver"),
dojo.connect(dojo.doc,"onmouseout",this,"onMouseOut"),dojo.connect(dojo.doc,"onmousedown",this,"onMouseDown"),dojo.connect(dojo.doc,"onmouseup",this,"onMouseUp")]},destroy:function(){dojo.forEach(this._connectors,dojo.disconnect)},onKeyDown:function(a){27==a.keyCode&&this.currentDragSource&&(this.dropAcceptable=!1,this.onMouseUp(a))},onMouseDown:function(a,c){if(!this.disabled&&(!this.dragTriggered&&dojo.mouseButtons.isLeft(a)&&!a.metaKey&&!a.ctrlKey)&&(dojo.isIE&&(a.pageX-=2,a.pageY-=2),!this.dragTriggered)){var b=
this.currentDragSource=c||this.findDragSource(a);if(b){b.onDragDown(a);for(var b=0,d=this.dropTargets.length;b<d;b++){var e=this.dropTargets[b];if(!e.disabled)e.onDragDown(a)}a.preventDefault();this._moveConnectors=[dojo.connect(dojo.doc,"onmousemove",this,"onMouseMove")];this.document&&this.document!=dojo.doc&&(this._moveConnectors.push(dojo.connect(this.document,"onmousemove",this,"onMouseMove")),this._moveConnectors.push(dojo.connect(this.document,"onmouseover",this,"onMouseOver")),this._moveConnectors.push(dojo.connect(this.document,
"onmouseout",this,"onMouseOut")),this._moveConnectors.push(dojo.connect(this.document,"onmouseup",this,"onMouseUp")))}}},onMouseMove:function(a){a.preventDefault();dojo.isIE&&(a.pageX-=2,a.pageY-=2);if(a.target==this.document||a.target.ownerDocument==this.document)a.documentX=this.documentX,a.documentY=this.documentY;var c=a.dragSource=this.currentDragSource;if(!this.dragTriggered){var b=a.pageX-c.pageX,d=a.pageY-c.pageY,b=Math.sqrt(b*b+d*d);if("absolute"==c.positioning){if(b<this._ABSOLUTE_THRESHOLD)return}else if(b<
this._STATIC_THRESHOLD)return;this.dragTriggered=!0;c.onDragStart(a);b=0;for(d=this.dropTargets.length;b<d;b++){var e=this.dropTargets[b];e.disabled||(a.dropTarget=e,e.onDragStart(a))}this.onMouseOver(a)}c.onDragMove(a);(e=this.currentDropTarget)?this.dropAcceptable&&(a.dropTarget=e,e.onDragMove(a,this.dragObjects)):this.dropAcceptable=!1},onMouseOver:function(a){this.currentDomElement=a.target;if(this.dragTriggered){var c=this.currentDragSource;if(c){a.dragSource=c;var b=this.findDropTarget(this.currentDomElement,
c);b&&c.domNode==b.domNode||(b!=this.currentDropTarget&&(this.currentDropTarget&&(a.dropTarget=this.currentDropTarget,this.currentDropTarget.onDragOut(a)),b&&(a.dropTarget=b,this.dropAcceptable=b.onDragOver(a))),this.currentDropTarget=b)}}},onMouseOut:function(a){},onMouseUp:function(a){if(!this.ignoreMouseUp){dojo.forEach(this._moveConnectors,dojo.disconnect);if(this.dragTriggered){for(var c=0,b=this.dropTargets.length;c<b;c++){var d=this.dropTargets[c];d.disabled||(a.dropTarget=d,d.onDragEnd(a))}c=
this.currentDragSource;b=this.currentDropTarget;a.dragSource=c;a.dropTarget=b;if(c&&(b?(b.onDropStart(a),this.dropAcceptable?(d=b.onDrop(a),b.onDragOut(a),void 0!=d&&!a.dragStatus&&(a.dragStatus=d?"dropSuccess":"dropFailure")):(b.onDragOut(a),a.dragStatus="dropFailure")):a.dragStatus="dropFailure",c.onDragEnd(a),b))b.onDropEnd(a)}this._resetStatus()}},_resetStatus:function(){this.currentDragSource=this.currentDropTarget=null;this.dragTriggered=this.dropAcceptable=!1;this.currentDomElement=null},findDragSource:function(a){for(a=
a.target;a&&a!=dojo.doc.body;a=a.parentNode)if(a.dragSource&&!a.dragSource.disabled)return a.dragSource;return null},findDropTarget:function(a,c){for(var b=null,d=a,e=null;null!=d&&d!=dojo.doc.body;d=d.parentNode){var f=d.dropTarget;if(f&&!f.disabled&&f.accepts(c)){b=f;b.nodeUnderMouse=e;break}d.dragSource&&!d.dragSource.disabled&&(e=d)}return b},registerDropTarget:function(a){this.dropTargets.push(a)},unregisterDropTarget:function(a){for(var c=0,b=this.dropTargets.length;c<b;c++)if(this.dropTargets[c]==
a){this.dropTargets.splice(c,1);break}}}))()});
//# sourceMappingURL=DragManager.js.map