//>>built
define("davinci/js/Format",["dojo/_base/declare","davinci/Runtime","davinci/Workbench","davinci/workbench/Preferences"],function(x,y,t,u){var d=function(v,w){function q(a){0!=a&&(k.push("                                                                                                                         ".substring(0,a)),l+=a)}function h(){if(arguments)for(var a=0;a<arguments.length;a++)"string"==typeof arguments[a]?(k.push(arguments[a]),l+=arguments[a].length):q(arguments[a])}function b(a){k.push(a);
l+=a.length}function g(a){0<k.length&&k.push(r);q(e);l=e;a&&b(a)}function m(a,d){g();a.visit(d);a.nosemicolon||b(";")}function p(a,d){"JSBlock"!=a.elementType?(e+=2,g()):b(" ");a.visit(d);"JSBlock"!=a.elementType&&(a.nosemicolon||b(";"),e-=2)}function s(a,b){return a.replace(/[\f]/g,"\\f").replace(/[\b]/g,"\\b").replace(/[\n]/g,"\\n").replace(/[\t]/g,"\\t").replace(/[\r]/g,"\\r")}var f=w||u.getPreferences("davinci.js.format",t.getProject()),e=0,k=[],r="\n",l=0;v.visit({visit:function(a){var k=!0;
if(a.comment){for(var n=a.comment,c=0;c<n.comments.length;c++)0<c&&q(e),"line"==n.comments[c].commentType?h("//",n.comments[c].s,r):"block"==n.comments[c].commentType&&h("/*",n.comments[c].s,"*/",r);q(e)}a.label&&(h(a.label.s,f.labelSpace,":",f.labelSpace),f.breakOnLabel&&h(d.newline,e));switch(a.elementType){case "JSWhile":b("while (");d.visit(a.expr);b(")");p(a.action,d);break;case "JSNameReference":b(a.name);break;case "JSFunction":b("function");null!=a.name&&b(" "+a.name);b(" (");for(c=0;c<a.parms.length;c++)0<
c&&h(",",f.functionParamSpaceing),b(a.parms[c].name);b(")");f.functionNewLine?g("{"):b(" {");e+=f.functionIndent;for(c=0;c<a.children.length;c++)m(a.children[c],d);e-=f.functionIndent;g("}");null!=a.name&&b(r);k=!0;break;case "JSFieldReference":d.visit(a.receiver);b("."+a.name);break;case "JSFunctionCall":d.visit(a.receiver);b("(");for(c=0;c<a.parms.length;c++)0<c&&h(",",f.functionParamSpaceing),d.visit(a.parms[c]);b(")");break;case "JSBinaryOperation":d.visit(a.left);b(a.operator);d.visit(a.right);
break;case "JSLiteral":switch(a.type){case "char":b("'"+s(a.value,"'")+"'");break;case "string":b('"'+s(a.value,'"')+'"');break;case "number":b(a.value);break;default:b(a.type)}break;case "JSParenExpression":b("(");d.visit(a.expression);b(")");break;case "JSAllocationExpression":b("new ");d.visit(a.expression);if(null!=a.arguments){b("(");for(c=0;c<a.arguments.length;c++)0<c&&b(", "),d.visit(a.arguments[c]);b(")")}break;case "JSFunctionExpression":d.visit(a.func);break;case "JSUnaryExpression":b(a.operator);
d.visit(a.expr);break;case "JSObjectLiteral":b("{");n=e;e=l;for(c=0;c<a.children.length;c++)0<c&&g(),d.visit(a.children[c]),c<a.children.length-1&&b(",");e--;0<a.children.length&&g();e=n;b("}");break;case "JSObjectLiteralField":"(string)"==a.nameType?b("'"+a.name+"'"):b(a.name);h(f.objectLitFieldSpace,":",f.objectLitFieldSpace);d.visit(a.initializer);break;case "JSArrayAccess":d.visit(a.array);b("[");d.visit(a.index);b("]");break;case "JSArrayInitializer":b("[");for(c=0;c<a.children.length;c++)0<
c&&b(", "),d.visit(a.children[c]);b("]");break;case "JSPrefixPostfixExpression":a.isPrefix&&b(a.operator);d.visit(a.expr);a.isPrefix||b(a.operator);break;case "JSConditionalExpression":d.visit(a.condition);b(" ? ");d.visit(a.trueValue);b(" : ");d.visit(a.falseValue);break;case "JSVariableDeclaration":b("var ");e+=4;for(c=0;c<a.children.length;c++)0<c&&(b(","),3<a.children.length?g():b(" ")),d.visit(a.children[c]);e-=4;break;case "JSVariableFragment":b(a.name);null!=a.init&&(h(f.varAssignmentSpaceing,
"\x3d",f.varAssignmentSpaceing),d.visit(a.init));break;case "JSBlock":f.blockNewLine&&g();b("{");e+=f.blockIndent;for(c=0;c<a.children.length;c++)m(a.children[c],d);e-=f.blockIndent;g("}");break;case "JSIf":h("if ",f.ifStmtSpacing,"(");d.visit(a.expr);b(")");"JSBlock"!=a.trueStmt.elementType?(e+=2,g(),d.visit(a.trueStmt),a.trueStmt.nosemicolon||b(";"),e-=2):(b(" "),d.visit(a.trueStmt));null!=a.elseStmt&&(g(),h(f.ifStmtSpacing,"else",f.ifStmtSpacing),"JSBlock"!=a.elseStmt.elementType?(e+=2,g(),d.visit(a.elseStmt),
a.elseStmt.nosemicolon||b(";"),e-=2):(b(" "),d.visit(a.elseStmt)));break;case "JSTry":b("try");m(a.stmt,d);a.catchBlock&&(g("catch("),b(a.catchArgument+")"),m(a.catchBlock,d));a.finallyBlock&&(g("finally"),m(a.finallyBlock,d));break;case "JSFor":b("for (");if(null!=a.initializations)for(c=0;c<a.initializations.length;c++)0<c&&h(",",f.forParamSpacing),d.visit(a.initializations[c]);b(";");null!=a.condition&&d.visit(a.condition);b(";");if(null!=a.increments)for(c=0;c<a.increments.length;c++)0<c&&h(",",
f.forParamSpacing),d.visit(a.increments[c]);b(")");p(a.action,d);break;case "JSForIn":b("for (");d.visit(a.iterationVar);b(" in ");d.visit(a.collection);b(")");p(a.action,d);break;case "JSWith":b("with (");d.visit(a.expr);context.indent+=2;b(")");p(a.action,d);break;case "JSDebugger":b("debugger");break;case "JSBranch":b(a.statement);a.targetLabel&&b(" "+a.targetLabel);break;case "JSExit":b(a.statement);a.expr&&b(" "+a.expr);break;case "JSDo":b("do");p(a.action,d);g("while(");d.visit(a.expr);b(")");
break;case "JSSwitch":b("switch (");d.visit(a.expr);b(")");f.blockNewLine?g():b(" ");b("{");e+=f.switchSpacing;for(c=0;c<a.children.length;c++)"JSCase"!=a.children[c].elementType?(e+=f.switchSpacing,m(a.children[c],d),e-=f.switchSpacing):(g(),d.visit(a.children[c]));e-=f.switchSpacing;g("}");break;case "JSCase":a.expr?(b("case "),d.visit(a.expr)):b("default");b(":");break;case "JSFile":for(c=0;c<a.children.length;c++)m(a.children[c],this);k=!0}return k}});return k.join("")};return{format:d}});
//# sourceMappingURL=Format.js.map