//>>built
require({cache:{"url:davinci/review/widgets/templates/Comment.html":'\x3cdiv class\x3d"davinciComment"\x3e\n    \x3cdiv dojoAttachPoint\x3d"mainBody" class\x3d"commentBody"\x3e\n        \x3cdiv class\x3d"commentSubject" dojoAttachPoint\x3d"subjectNode"\x3e\x3c/div\x3e\n        \x3cdiv class\x3d"commentSubtitle"\x3e\n            ${by}\x26nbsp;\x3cspan dojoAttachPoint\x3d"ownerName"\x3e\x3c/span\x3e\n            \x26nbsp;\x3cspan dojoAttachPoint\x3d"createTime"\x3e\x3c/span\x3e\n            \x3cspan class\x3d\'editReplyBlock\'\x3e\n                \x3ca class\x3d"commentLinkButton" dojoAttachPoint\x3d"editButton"\x3e${edit}\x3c/a\x3e\n                \x3cspan class\x3d\'editReplySpace\'\x3e\x3c/span\x3e\n                \x3ca class\x3d"commentLinkButton" dojoAttachPoint\x3d"replyButton"\x3e${reply}\x3c/a\x3e\n            \x3c/span\x3e\n        \x3c/div\x3e\n        \x3cdiv class\x3d"commentContent" dojoAttachPoint\x3d"contentNode"\x3e\x3c/div\x3e\n    \x3c/div\x3e\n    \x3cdiv dojoAttachPoint\x3d"tempForm"\x3e\x3c/div\x3e\n    \x3cdiv dojoAttachPoint\x3d"replyRegion" class\x3d"displayNone"\x3e\n        \x3cdiv class\x3d"commentReplyBar"\x3e\n            \x3cimg class\x3d"dijitTreeExpando dijitTreeExpandoOpen commentLinkButton" src\x3d"app/dojo/resources/blank.gif" style\x3d"vertical-align: middle;" dojoAttachPoint\x3d"imgNode"/\x3e\n            \x3ca class\x3d"commentLinkButton" dojoAttachPoint\x3d"replyCountButton"\x3e\x3c/a\x3e\n        \x3c/div\x3e\n        \x3cdiv class\x3d"commentReplies" dojoAttachPoint\x3d"commentReplies"\x3e\x3c/div\x3e\n    \x3c/div\x3e\n\x3c/div\x3e',
"url:davinci/review/widgets/templates/MailFailureDialogContent.html":"\x3cdiv\x3e\n\x3cdiv class\x3d'mailFailureInfo'\x3e${inviteNotSent}\x3c/div\x3e\n\x3cdiv class\x3d'mailFailureExtraInfo'\x3e${mailFailureMsg}\x3c/div\x3e\n\x3cdiv class\x3d'mailFailureContent'\x3e${htmlContent}\x3c/div\x3e\n\x3c/div\x3e\n"}});
define("davinci/review/widgets/Comment","dojo/_base/declare davinci/XPathUtils davinci/maqetta/AppStates davinci/review/Review davinci/Runtime davinci/Workbench dijit/_WidgetBase dijit/_TemplatedMixin dijit/Menu dijit/MenuItem dijit/form/DropDownButton dojo/date/locale dojo/date/stamp dojo/Deferred dojo/string dojo/i18n!./nls/widgets dojo/text!./templates/Comment.html dojo/text!./templates/MailFailureDialogContent.html".split(" "),function(m,k,n,p,f,q,r,s,z,A,B,t,u,l,v,g,w,x){var y=n.prototype;return m("davinci.review.widgets.Comment",
[r,s],{templateString:w,postMixInProperties:function(){this.inherited(arguments);dojo.mixin(this,g)},VISIBLE_PART_LENGTH:80,postCreate:function(){this._createdPromise=new l;if(this.existed)this._populate(this),this._createdPromise.resolve(this.created);else{var a={id:this.commentId,subject:this.subject,content:this.content,ownerId:this.ownerId,email:this.email,previous:this.previous,next:this.next,pageState:this.pageState,pageStateList:this.pageStateList?dojo.toJson(this.pageStateList):"",viewScene:this.viewScene,
viewSceneList:this.viewSceneList?dojo.toJson(this.viewSceneList):"",designerId:this.designerId,pageName:this.pageName,replyTo:this.replyTo||"root",drawingJson:this.drawingJson};f.currentEditor&&f.currentEditor.getContext().getPreference("zazl")&&(urlParms.zazl=!0);dojo.xhrGet({url:"cmd/addComment",handleAs:"json",content:a,error:dojo.hitch(this,function(a){dojo.publish("/davinci/review/commentAddedError",[this]);var b=a.responseText,b=b.substring(b.indexOf("\x3ctitle\x3e")+7,b.indexOf("\x3c/title\x3e"));
f.handleError(dojo.string.substitute(g.errorAddingCom,[a,b]))})}).then(dojo.hitch(this,function(a){this.created=a.created;this._populate(this);this._createdPromise.resolve(this.created);a.emailResult&&"OK"!==a.emailResult&&(a=v.substitute(x,{htmlContent:a.emailResult,inviteNotSent:g.commentNotSent,mailFailureMsg:g.commentMailFailureMsg}),q.showMessage(g.warning,a))}.bind(this)))}this.comments=[];this.collapsed=!1;this.enabled=!0;this.focused=!1;a=this.color=p.getColor(this.email);this.subjectNode.innerHTML=
this.subject;dojo.style(this.subjectNode,"color",a);var c=f.getUserDisplayName({email:this.email,userId:this.ownerId,userDisplayName:this.displayName});this.ownerName.innerHTML=c;dojo.style(this.ownerName,"color",a);this.contentNode.innerHTML=this.content;this._ajustLengthOfCommentContent(!0);this.isReply()&&dojo.addClass(this.subjectNode,"displayNone");this.connect(this.imgNode,"click","_toggleReplies");this.connect(this.replyCountButton,"click","_toggleReplies");this.connect(this.editButton,"click",
"_editComment");this.connect(this.replyButton,"click","_newReply");this.connect(this.mainBody,"click","focusComment");this.connect(this.mainBody,"dblclick","_editComment");this.closed&&(dojo.style(this.editButton,"display","none"),dojo.style(this.replyButton,"display","none"));f.userName!=this.ownerId&&dojo.style(this.editButton,"display","none")},getCreated:function(){var a=new l;this._createdPromise.then(function(c){a.resolve(c)});return a},refresh:function(){dojo.style(this.editButton,"display",
"inline");dojo.style(this.replyButton,"display","inline");this.closed&&(dojo.style(this.editButton,"display","none"),dojo.style(this.replyButton,"display","none"));f.userName!=this.ownerId&&dojo.style(this.editButton,"display","none")},_populate:function(a){this.createdFormatted=u.fromISOString(a.created);a=this.createTime;var c;var d=this.createdFormatted;c=new Date;var b=d.getTime()-c.getTime();c=0>b?"ago":"later";var e,b=Math.floor(Math.abs(b)/1E3);60>=b?c="just now":604800<b?c=t.format(d,{formatLength:"short",
selector:"date"}):(b=Math.floor(b/60),e=b%60,b=Math.floor(b/60),d=b%24,b=Math.floor(b/24),c=(b?b+" days ":d?d+" hours ":e?e+" mins ":"")+c);a.innerHTML=c},update:function(a){this.subjectNode.innerHTML=this.subject;this.contentNode.innerHTML=this.content;this._ajustLengthOfCommentContent(!0);dojo.xhrGet({url:"cmd/updateComment",handleAs:"json",content:{id:this.commentId,designerId:this.designerId,subject:this.subject,content:this.content,pageState:this.pageState,pageStateList:this.pageStateList?dojo.toJson(this.pageStateList):
"",viewScene:this.viewScene,viewSceneList:this.viewSceneList?dojo.toJson(this.viewSceneList):"",drawingJson:this.drawingJson},error:function(a){var d=a.responseText,d=d.substring(d.indexOf("\x3ctitle\x3e")+7,d.indexOf("\x3c/title\x3e"));f.handleError(dojo.string.substitute(g.errorUpdateCom,[a,d]))}})},_editComment:function(){if(!this.isDisabled)this.onEditComment({commentId:this.commentId})},onEditComment:function(a){},_newReply:function(){if(!this.isDisabled)this.onNewReply({replyTo:this.commentId,
subject:"Re: "+this.subject})},onNewReply:function(a){},isReply:function(){return"root"!=this.replyTo},isPageOwner:function(){return this.designerId==f.userName},appendReply:function(a){this.comments.push(a);a.placeAt(this.commentReplies);dojo.hasClass(this.replyRegion,"displayNone")&&dojo.removeClass(this.replyRegion,"displayNone");a=this.getReplies().length;this.replyCountButton.innerHTML=a+(1==a?" Reply":" Replies")},getReplies:function(){return this.comments},_toggleReplies:function(){this.collapsed?
this.expand():this.collapse()},collapse:function(a){if(a){var c=this.getReplies();dojo.forEach(c,function(c){c.collapse(a)})}this.collapsed||(dojo.removeClass(this.imgNode,"dijitTreeExpandoOpen"),dojo.addClass(this.imgNode,"dijitTreeExpandoClosed"),dojo.addClass(this.commentReplies,"displayNone"));this.collapsed=!0},expand:function(a){if(a){var c=this.getReplies();dojo.forEach(c,function(c){c.expand(a)})}this.collapsed&&(dojo.removeClass(this.imgNode,"dijitTreeExpandoClosed"),dojo.addClass(this.imgNode,
"dijitTreeExpandoOpen"),dojo.removeClass(this.commentReplies,"displayNone"));this.collapsed=!1},focusComment:function(a){this.isDisabled||(this.isFocused&&a&&(a.ctrlKey||a.metaKey)?this.blurComment():(this.onCommentFocus(this,a),dojo.addClass(this.mainBody,"commentFocused"),this.isFocused=!0))},onCommentFocus:function(a){},blurComment:function(a){if(!a)this.onCommentBlur(this);dojo.removeClass(this.mainBody,"commentFocused");this.isFocused=!1},onCommentBlur:function(a){},_ajustLengthOfCommentContent:function(a){var c=
this.content;if(c.length<=this.VISIBLE_PART_LENGTH)a=dojo.query("a",this.contentNode),0<a.length&&this.contentNode.removeChild(a[0]);else{var d=dojo.create("a",{"class":"commentLinkButton",innerHTML:a?g.more:g.commentHide,onclick:dojo.hitch(this,"_ajustLengthOfCommentContent",!a)});c&&(this.contentNode.innerHTML=a?c.substring(0,this.VISIBLE_PART_LENGTH):c,this.contentNode.appendChild(d))}},hide:function(){dojo.style(this.mainBody,"display","none")},show:function(){dojo.style(this.mainBody,"display",
"block");dojo.window.scrollIntoView(this.domNode)},enable:function(){dojo.removeClass(this.domNode,"disabled");dojo.removeClass(this.mainBody,"commentBodyDisabled");dojo.style(this.subjectNode,"color",this.color);dojo.style(this.ownerName,"color",this.color);this.isDisabled=!1},disable:function(){dojo.addClass(this.domNode,"disabled");dojo.removeAttr(this.mainBody,"style");dojo.addClass(this.mainBody,"commentBodyDisabled");dojo.style(this.subjectNode,"color","");dojo.style(this.ownerName,"color",
"");this.isDisabled=!0},getBody:function(){return this.mainBody},setStatesScenes:function(){var a=davinci.Workbench.getOpenEditor(),c=(a=a&&a.getContext?a.getContext():null)?a.rootNode:null;if(c=c&&c.ownerDocument){if(this.pageStateList)for(var d=this.pageStateList.length-1;-0<d;d--){var b=this.pageStateList[d],e=b.id?c.getElementById(b.id):null;!e&&b.xpath&&(e=k.toCssPath(b.xpath),e=c.querySelector(e));e&&y.setState(b.state,e,{updateWhenCurrent:!0})}if(this.viewSceneList&&a.sceneManagers)for(var f in this.viewSceneList)if(d=
a.sceneManagers[f])for(var g=this.viewSceneList[f],h=g.length-1;0<=h;h--)b=g[h],e=b.scId?c.getElementById(b.scId):null,!e&&b.scXpath&&(e=k.toCssPath(b.scXpath),e=c.querySelector(e)),e&&b.sceneId&&d.selectScene({sceneContainerNode:e,sceneId:b.sceneId})}}})});
//# sourceMappingURL=Comment.js.map