//>>built
require({cache:{"url:davinci/review/widgets/templates/CommentForm.html":'\x3cdiv class\x3d"davinciComment davinciComment2"\x3e\n\t\x3cdiv dojoAttachPoint\x3d"toolbarNode"\x3e\x3c/div\x3e\n\t\x3cdiv dojoAttachPoint\x3d"subjectNode" class\x3d"commentSubjectEdit"\x3e\x3c/div\x3e\n\t\x3cdiv dojoAttachPoint\x3d"contentNode" class\x3d"contentNode"\x3e\n\t\x3cspan dojoAttachPoint\x3d"placeHolder" style\x3d"padding:3px 0 0 2px;" class\x3d"dijitPlaceHolder dijitInputField"\x3e${comment}\x3c/span\x3e\n\t\x3c/div\x3e\n\t\x3cdiv class\x3d"submitCancelDiv"\x3e\n\t\t\x3cdiv dojoAttachPoint\x3d"submitNode"\x3e\x3c/div\x3e\n\t\t\x3ca dojoAttachPoint\x3d"cancelNode" class\x3d"commentLinkButton" class\x3d"cancelLink"\x3e${buttonCancel}\x3c/a\x3e\n\t\x3c/div\x3e\n\x3c/div\x3e\n'}});
define("davinci/review/widgets/CommentForm","dojo/_base/declare dijit/_Widget dijit/_Templated dijit/form/TextBox dijit/form/SimpleTextarea dijit/Menu dijit/MenuItem dijit/form/Button dijit/form/DropDownButton dojo/i18n!./nls/widgets davinci/Runtime dojo/text!./templates/CommentForm.html".split(" "),function(d,e,f,g,h,n,p,k,q,b,l,m){return d("davinci.review.widgets.CommentForm",[e,f],{templateString:m,postMixInProperties:function(){this.inherited(arguments);this.comment=b.comment;this.buttonCancel=
b.buttonCancel},postCreate:function(){this.subject=new g({placeHolder:b.subjectPlaceHolder,style:"width: 100%"},this.subjectNode);this.content=new h({rows:4,style:"width: 100%; margin: 2px 0px 2px 0px;font-family:Verdana, Arial, Helvetica, sans-serif;font-size:100%;"},dojo.create("div"));this.contentNode.appendChild(this.content.domNode);new k({label:b.submit,onClick:dojo.hitch(this,"_submit")},this.submitNode);this.replyTo="root";this.connect(this.cancelNode,"click","hide");this.connect(this.content,
"onFocus","hidePlaceHolder");this.connect(this.content,"onBlur","showPlaceHolder");this.connect(this.placeHolder,"click",function(){this.hidePlaceHolder();this.content.focus()});var a=this._getActions(),c=dojo.create("span",{style:{display:"inline-block"}},this.toolbarNode),a=this._toolbar=davinci.Workbench._createToolBar("toolbarPath",c,a,this);dojo.style(a.domNode,{display:"inline-block"});dojo.subscribe("/davinci/review/drawing/selectshape",this,function(a,c){this._updateToolbarEnablement()}.bind(this));
dojo.subscribe("/davinci/review/drawing/deselectshape",this,function(a,c){this._updateToolbarEnablement()}.bind(this))},_updateToolbarEnablement:function(){var a=this._toolbar.getChildren();dojo.forEach(a,function(a){var b=a._maqAction;b&&(b.action&&b.action.isEnabled)&&(b=b.action.isEnabled(),a.set("disabled",!b))})},_getActions:function(){var a=[];l.getExtensions("davinci.annotationActions",function(b){a.push(b.editorContribution);return!0});return a},hide:function(){this.isShowing=!1;this.onHide();
dojo.style(this.domNode,"display","none");this.reset();dojo.publish("/davinci/review/view/closeComment",[])},onHide:function(){},show:function(){this.isShowing=!0;this.onShow();dojo.style(this.domNode,"display","block");dojo.window.scrollIntoView(this.domNode);dojo.publish("/davinci/review/view/openComment",[]);this._updateToolbarEnablement()},onShow:function(){},_submit:function(){var a=this.subject.get("value"),b=this.content.get("value");this[this._update?"onUpdate":"onSubmit"]({subject:a,content:b})},
onSubmit:function(a){},onUpdate:function(a){},reset:function(){dojo.style(this.subject.domNode,"display","block");this.placeHolder.innerHTML=b.comment;this.showPlaceHolder();this.subject.set("value","");this.content.set("value","");this.replyTo="root";this.placeAt(this.parentNode,"first");this.isShowing=this._update=!1;this.editFrom=null},showPlaceHolder:function(){""==this.content.get("value")&&dojo.removeClass(this.placeHolder,"davinciReviewHide")},hidePlaceHolder:function(){dojo.addClass(this.placeHolder,
"davinciReviewHide")},setReplyMode:function(){dojo.style(this.subject.domNode,"display","none");this.placeHolder.innerHTML=b.commentReply},setEditMode:function(){this._update=!0},moveTo:function(a){this.parentNode||(this.parentNode=a);this.placeAt(a)}})});
//# sourceMappingURL=CommentForm.js.map