//>>built
define("davinci/html/CSSParser","dojo/_base/declare davinci/html/CSSSelector davinci/html/CSSCombinedSelector davinci/html/CSSRule davinci/html/CSSProperty davinci/html/CSSAtRule davinci/html/CSSImport davinci/model/parser/Tokenizer davinci/model/Comment".split(" "),function(F,G,H,I,J,K,L,C,M){var e=null,z=function(){function e(r,b,n){return function(e){return!r||/^\}/.test(e)?n:b?n+2*indentUnit:n+indentUnit}}var s=function(){function e(f,g){var d=f.next();if("@"==d)return f.nextWhileMatches(/[a-zA-Z0-9_-]/),
"css-at";if("/"==d&&f.equals("*"))return g(b),null;if("\x3c"==d&&f.equals("!"))return g(n),null;if("\x3d"==d)return"css-compare";if(f.equals("\x3d")&&("~"==d||"|"==d))return f.next(),"css-compare";if('"'==d||"'"==d)return g(l(d)),null;if("#"==d)return f.nextWhileMatches(/[\w-]/),"css-hash";if("!"==d)return f.nextWhileMatches(/[ \t]/),f.nextWhileMatches(/\w/),"css-important";if(/\d/.test(d))return f.nextWhileMatches(/[\w.%]/),"css-unit";if(/[,.+>*\/]/.test(d))return"css-select-op";if(/[;{}:\[\]]/.test(d))return"css-punctuation";
f.nextWhileMatches(/[\w\\\-_]/);return"css-identifier"}function b(b,g){for(var d=!1;!b.endOfLine();){var a=b.next();if(d&&"/"==a){g(e);break}d="*"==a}return"css-comment"}function n(b,g){for(var d=0;!b.endOfLine();){var a=b.next();if(2<=d&&"\x3e"==a){g(e);break}d="-"==a?d+1:0}return"css-comment"}function l(b){return function(g,d){for(var a=!1;!g.endOfLine();){var c=g.next();if(c==b&&!a)break;a=!a&&"\\"==c}a||d(e);return"css-string"}}return function(b,g){return C.tokenizer(b,g||e)}}();return{make:function(r,
b){b=b||0;var n=s(r),l=!1,f=!1,g=!1,d={next:function(){var a=n.next(),c=a.style,d=a.content;"css-hash"==c&&(c=a.style=f?"css-colorcode":"css-identifier");"css-identifier"==c&&(f?a.style="css-value":!l&&!g&&(a.style="css-selector"));"\n"==d&&(a.indentation=e(l,f,b));"{"==d&&"@media"==g?g=!1:"{"==d?l=!0:"}"==d?l=f=g=!1:";"==d?f=g=!1:l&&"css-comment"!=c&&"whitespace"!=c?f=!0:!l&&"css-at"==c&&(g=d);return a},copy:function(){var a=l,b=f,e=n.state;return function(g){n=s(g,e);l=a;f=b;return d}}};return d},
electricChars:"}"}}();z.parse=function(w,s){function r(a){D.push(a)}function b(){var b;a=d.next();for(var c=!1;"css-comment"==a.style||"whitespace"==a.style;){if("css-comment"==a.style||c)e||(e=new M),b=a.content,0===a.content.indexOf("/*")&&(b=b.substring(2),c=!0,e.addComment("block",void 0,void 0,"")),-1<b.lastIndexOf("*/")&&b.lastIndexOf("*/")==b.length-2&&(b=b.substring(0,b.length-2),c=!1),e.appendComment(b);a=d.next()}return a}function n(){c=new G;c.startOffset=a.offset;c.parent=m;q?(q.selectors.push(c),
c.parent=q):m.selectors.push(c)}function l(){var b=c;b.endOffset=a.offset-1;q||(q=new H,q.parent=m,q.selectors.push(b),c.startOffset=b.startOffset,m.selectors[m.selectors.length-1]=q);n();q.combiners.push(x);x=" "}var f,g;"string"==typeof w?f=C.stringStream({next:function(){if(1==++this.count)return w;throw StopIteration;},count:0,text:w}):(f=w,g=!0);var d=z.make(f),a,c,q,x=" ",D=[],E=[],m,t;try{do switch(b(),a.style){case "css-selector":case "css-select-op":if(g&&"\x3c"==a.content)throw f.push("\x3c"),
StopIteration;m=new I;E.push(m);m.startOffset=a.offset;s&&s.addChild(m,void 0,!0);t=!1;q=void 0;x=" ";n();a:for(;;){switch(a.style){case "css-select-op":switch(a.content){case ",":q=void 0;n();break;case ".":t&&l();b();c.cls=c.cls?c.cls+"."+a.content:a.content;t=a.value.length>a.content.length;break;case "*":(c.element||c.cls)&&l();c.element="*";break;case "+":case "\x3e":x=a.content,l()}break;case "css-selector":"css-identifier"==a.type?((c.element||c.cls||t)&&l(),c.element=a.content):"css-hash"==
a.type&&((c.id||t)&&l(),c.id=a.content.substring(1));t=a.value.length>a.content.length;break;case "css-punctuation":if("{"==a.content)break a;else if(":"==a.content)b(),":"==a.content?(b(),c.pseudoElement=a.content):(c.pseudoRule=a.content,t=!0);else if("["==a.content&&(b(),c.attribute={name:a.content},b(),"\x3d"===a.content||"~\x3d"===a.content||"|\x3d"===a.content))c.attribute.type=a.content,b(),c.attribute.value=a.content.substring(1,a.content.length-1),b()}b()}e&&(m.comment=e,e=null);for(c.endOffset=
a.offset-1;"}"!=b().content;){var N=a.offset,u=a.content,p=!1;"css-hash"==a.type?(b(),"css-identifier"==a.type?u+=a.content:p=!0):"css-identifier"!=a.type&&("*"!=a.content?r("expecting identifier around "+c.getText()+"{ "+k.name+": "+propery.value):(b(),u+=a.content));var k=new J;k.startOffset=N;k.parent=m;e&&(k.comment=e,e=null);m.properties.push(k);m.addChild(k,void 0,!0);k.name=u;p||":"!=b().content&&r("expecting ':' "+c.getText()+"{ "+k.name+": "+propery.value);b();k.value=a.value;if("url"==k.value){for(;")"!=
b().content;)k.value+=a.value;k.value+=a.value}for(;";"!=b().content&&"}"!=a.content;)k.value+=a.value;e&&(k.postComment=e,e=null);k.endOffset=a.offset-1;if("}"==a.content)break}e&&(k.postComment=e,e=null);m.endOffset=a.offset;break;case "css-at":var v=a.content.substring(1),h="import"==v?new L:new K;h.startOffset=a.offset;s&&s.addChild(h,void 0,!0);if("import"==v)p=h,b(),"url"==a.content&&(p.isURL=!0,b(),b()),p.url=a.content.substring(1,a.content.length-1),p.isURL&&b(),b();else if(0<=v.indexOf("keyframes")){var y=
p="",A=!1,B="\t\t";b();p=a.content;"."==p&&(b(),p+=a.content);b();h.value=a.content+"\n";b();if(0<=a.content.indexOf("from")||0<=a.content.indexOf("to")||0<=a.content.indexOf("%"))a:for(;;){h.value+="\t"+a.content+" ";b();for(h.value+=a.content+"\n";"}"!=b().content;){A&&(B="\t\t",A=!1);if(";"==a.content)y="\n",A=!0;else if(":"==a.content||")"==a.content)y=" ";h.value+=B+a.content+y;B=y=""}h.value+="\t"+a.content+"\n";b();if("}"==a.content)break a}else r("inside keyframes decl expecting from/to blocks or nn% blocks");
h.value+=a.content;h.name=v+" "+p}else{h.name=v;for(h.value="";";"!=b().content;)h.value+=a.content}h.endOffset=a.offset}while(1)}catch(F){e&&m&&(m.postComment=e,e=null)}return{errors:D,model:E}};return z});
//# sourceMappingURL=CSSParser.js.map