//>>built
define("davinci/html/HTMLFile","dojo/_base/declare davinci/html/HTMLItem davinci/html/HTMLParser davinci/html/CSSSelector davinci/html/HTMLElement davinci/html/CSSImport davinci/html/CSSFile davinci/model/Model davinci/model/Path".split(" "),function(k,l,h,m,n,p,s,q,r){return k("davinci.html.HTMLFile",l,{constructor:function(a){this.url=this.fileName=a;this.elementType="HTMLFile";this._loadedCSS={};this._styleElem=null},save:function(a){var b,c=system.resource.findResource(this.fileName);this.getText();
c?(b=this.getText(),b=c.setContents(b,a)):console.error("couldnt find file in resources : "+this.fileName);return b},getText:function(a){a=a||{};a.indent=0;for(var b="",c=0;c<this.children.length;c++){var f=this.children[c],b=b+f.getText(a);"HTMLComment"==f.elementType&&(b+=this._addWS(f._fmLine,f._fmIndent))}return b},getDocumentElement:function(a){for(a=0;a<this.children.length;a++)if("html"==this.children[a].tag)return this.children[a]},findElement:function(a){var b=this.getDocumentElement();if(b)return b.findElement(a)},
getMatchingRules:function(a,b){var c={visit:function(b){if("CSSFile"==b.elementType){var c=[];b=b.getMatchingRules(a,[],c);for(var e=0;e<b.length;e++)for(var g=0;g<this.matchLevels.length;g++)if(c[e]>this.matchLevels[g]){this.matchLevels.splice(g,0,c[e]);this.rules.splice(g,0,b[e]);break}0==this.rules.length&&(this.rules=b,this.matchLevels=c);return!0}return!1},matchLevels:[],rules:[]};this.visit(c);return b?{rules:c.rules,matchLevels:c.matchLevels}:c.rules},getRule:function(a){if(!a)return[];var b=
m.parseSelectors(a);a={visit:function(a){return"CSSFile"==a.elementType?(a=a.getRule(b),this.rules=this.rules.concat(a||[]),!0):!1},rules:[]};this.visit(a);return a.rules},setText:function(a,b){this.visit({visit:function(a){"CSSImport"==a.elementType&&a.close()}});this.children=[];this._styleElem=null;var c=h.parse(a||"",this),f="";!b&&0==c.errors.length&&(f=this.getText(),this.children=[],c=h.parse(f,this));this.endOffset=c.endOffset;this.errors=c.errors;var d=this;b||this.visit({visit:function(a){"CSSImport"==
a.elementType&&!a.cssFile&&(a.load(!0),dojo.connect(a.cssFile,"onChange",null,dojo.hitch(d,"onChange")))}});this.onChange()},hasStyleSheet:function(a){for(var b=this.find({elementType:"CSSImport"}),c=0;c<b.length;c++)if(b[c].url==a)return!0;return!1},addStyleSheet:function(a,b,c,f,d){var e=new r(this.url||this.fileName),e=e.getParentPath().append(a),e=e.toString();c||(this._loadedCSS[e]=require("davinci/model/Factory").getModel({url:e,includeImports:!0,loader:d}));b&&this._loadedCSS[e].setText(b);
this.onChange();this._styleElem||(b=this.find({elementType:"HTMLElement",tag:"head"},!0),d=b.getChildElement("style"),d||(d=new n("style"),b.addChild(d)),this._styleElem=d);b=new p;b.parent=this;b.url=a;f?this._styleElem.insertBefore(b,f):this._styleElem.addChild(b);c||b.load(!0)},close:function(){this.visit({visit:function(a){"CSSImport"==a.elementType&&a.close()}});require("davinci/model/Factory").closeModel(this)},getLabel:function(){return"\x3c\x3e"},getID:function(){return this.fileName},updatePositions:function(a,
b){(new q(this)).updatePositions(this,a,b);this.visit({visit:function(c){if(c.endOffset<a)return!0;"HTMLElement"==c.elementType&&c.startTagOffset>a&&(c.startTagOffset+=b)}})},mapPositions:function(a){var b=this.getText();a=a.getText();b=b.indexOf(a);a=b+a.lastIndexOf("\x3e")+1;return{startOffset:b,endOffset:a}},reportPositions:function(){this.visit({visit:function(a){}})},evaluate:function(a){if("/"!==a.charAt(0))console.error("invalid XPath string");else{var b=this;a.substr(1).split("/").forEach(function(a){a=
a.match(this._RE_XPATH);var f=a[1];a=a[2];var d;d=b.children.filter(function(a){return a.tag===f});!a&&1<d.length?console.error("invalid XPath string; no index specified for multiple elements"):b=a?d[a-1]:d[0]},this);return b}},_RE_XPATH:/(\w+)(?:\[(\d+)\])?/})});
//# sourceMappingURL=HTMLFile.js.map