//>>built
define("davinci/html/HTMLParser","dojo/_base/declare davinci/html/HTMLText davinci/html/HTMLElement davinci/html/HTMLAttribute davinci/html/HTMLComment davinci/html/PHPBlock davinci/model/parser/Tokenizer davinci/html/CSSParser".split(" "),function(O,H,I,J,C,K,F,L){var N=function(){var t={autoSelfClosers:{br:!0,img:!0,hr:!0,link:!0,input:!0,meta:!0,col:!0,frame:!0,base:!0,area:!0},doNotIndent:{pre:!0,"!cdata":!0}},y={autoSelfClosers:{},doNotIndent:{"!cdata":!0}},w=t,x=!1,z=function(){function k(a,
c){var b=a.next();if("\x3c"==b){if(a.equals("!"))return a.next(),a.equals("[")?a.lookAhead("[CDATA[",!0)?(c(m("xml-cdata","]]\x3e")),null):"xml-text":a.lookAhead("--",!0)?(c(m("xml-comment","--\x3e")),null):a.lookAhead("DOCTYPE",!0)?(a.nextWhileMatches(/[\w\._\-]/),c(m("xml-doctype","\x3e")),"xml-doctype"):"xml-text";if(a.equals("?")){a.next();if(a.lookAhead("php",!0,!1,!0))return c(p("php-block","?\x3e")),null;a.nextWhileMatches(/[\w\._\-]/);c(m("xml-processing","?\x3e"));return"xml-processing"}a.equals("/")&&
a.next();c(v);return"xml-punctuation"}if("\x26"==b){for(;!a.endOfLine()&&";"!=a.next(););return"xml-entity"}a.nextWhileMatches(/[^&<\n]/);return"xml-text"}function v(a,c){var b=a.next();if("\x3e"==b)return c(k),"xml-punctuation";if(/[?\/]/.test(b)&&a.equals("\x3e"))return a.next(),c(k),"xml-punctuation";if("\x3d"==b)return"xml-punctuation";if(/[\'\"]/.test(b))return c(e(b)),null;a.nextWhileMatches(/[^\s\u00a0=<>\"\'\/?]/);return"xml-name"}function e(a){return function(c,b){for(;!c.endOfLine();)if(c.next()==
a){b(v);break}return"xml-attribute"}}function m(a,c){return function(b,d){for(;!b.endOfLine();){if(b.lookAhead(c,!0)){d(k);break}b.next()}return a}}function p(a,c){return function(b,d){for(var e=!1;!b.endOfLine();){if(b.lookAhead(c,!0)){e=!0;d(k);break}b.next()}if(!e&&b.endOfLine())b.next();else{for(;b.lookAheadRegex(/^[\ \t]/,!0););b.endOfLine()&&b.next()}return a}}return function(a,c){return F.tokenizer(a,c||k)}}();return{make:function(k){function v(a){for(var b=a.length-1;0<=b;b--)A.push(a[b])}
function e(){v(arguments);D=!0}function m(){v(arguments);D=!1}function p(){h.style+=" xml-error"}function a(a){return function(b,c){c==a?e():(p(),e(arguments.callee))}}function c(a,b){var c=w.doNotIndent.hasOwnProperty(a)||n&&n.noIndent;n={prev:n,name:a,indent:B,startOfLine:b,noIndent:c}}function b(a){return function(b,c){var f=a;if(f&&f.noIndent)return c;if(x&&/<!\[CDATA\[/.test(b))return 0;f&&/^<\//.test(b)&&(f=f.prev);for(;f&&!f.startOfLine;)f=f.prev;return f?f.indent+indentUnit:0}}function d(){return m(u,
d)}function u(b,d){"\x3c"==d?e(r,t,q(1==f)):"\x3c/"==d?e(l,a("\x3e")):("xml-cdata"==b?((!n||"!cdata"!=n.name)&&c("!cdata"),/\]\]>$/.test(d)&&(n=n.prev)):C.hasOwnProperty(b)||p(),e())}function r(a,b){"xml-name"==a?(E=b.toLowerCase(),h.style="xml-tagname",e()):(E=null,m())}function l(a,b){"xml-name"==a&&(h.style="xml-tagname",n&&b.toLowerCase()==n.name?n=n.prev:p());e()}function q(a){return function(b,f){"/\x3e"==f||"\x3e"==f&&w.autoSelfClosers.hasOwnProperty(E)?e():"\x3e"==f?(c(E,a),e()):(p(),e(arguments.callee))}}
function t(a){"xml-name"==a?(h.style="xml-attname",e(y,t)):m()}function y(a,b){"\x3d"==b?e(g):"\x3e"==b||"/\x3e"==b?m(q):m()}function g(a){"xml-attribute"==a?e(g):m()}var s=z(k),h,A=[d],f=0,B=0,E=null,n=null,D,C={"xml-text":!0,"xml-entity":!0,"xml-comment":!0,"xml-processing":!0,"xml-doctype":!0,"php-block":!0};return{indentation:function(){return B},next:function(){h=s.next();"whitespace"==h.style&&0==f?B=h.value.length:f++;"\n"==h.content&&(B=f=0,h.indentation=b(n));if("whitespace"==h.style||"xml-comment"==
h.type||"php-block"==h.type)return h;for(;;)if(D=!1,A.pop()(h.style,h.content),D)return h},copy:function(){var a=A.concat([]),b=s.state,c=n,d=this;return function(e){A=a.concat([]);f=B=0;n=c;s=z(e,b);return d}}}},electricChars:"/",configure:function(k){null!=k.useHTMLKludges&&(w=k.useHTMLKludges?t:y);k.alignCDATA&&(x=k.alignCDATA)}}}();return{parse:function(t,y){function w(a,c){d=new H;d.wasParsed=!0;d.startOffset=c;b[b.length-1].addChild(d,void 0,!0);d.value=a}function x(a){a.content!=a.value&&w(a.value.substring(a.content.length),
a.offset+a.value.length)}function z(a,b){var c=a.split("\n"),d=c[c.length-1].length;b.children.length?(lastElement=b.children[b.children.length-1],lastElement._fmLine=c.length-1,lastElement._fmIndent=d):(b._fmChildLine=c.length-1,b._fmChildIndent=d)}function k(){if(null!=d&&!d.value.match(/\S/)){var a=b[b.length-1];a.children.pop();z(d.value,a)}d=null}function v(){var a=b[b.length-1];m.nextWhileMatches(/[\s\u00a0]/);var c=m.get();null!=d?(d.value+=c,k()):z(c,a);L.parse(m,a)}function e(b){for(a=p.next();b&&
"whitespace"==a.style;)a=p.next();return a}var m=F.stringStream({next:function(){if(1==++this.count)return t;throw StopIteration;},count:0,text:t}),p=N.make(m),a,c=[],b=[];b.push(y);var d,u,r;try{do switch(a=p.next(),a.style){case "xml-punctuation":k();if("\x3c"==a.content){var l=new I;l.wasParsed=!0;l.startOffset=a.offset;b[b.length-1].addChild(l,void 0,!0);e(!0);for("xml-tagname"==a.style?l.tag=a.content:c.push("expecting tag name");"xml-attname"==(a=e(!0)).style;){var q=new J;q.wasParsed=!0;l.attributes.push(q);
q.name=a.content;q.startOffset=a.offset;e(!0);if("\x3d"==a.content)if(a=p.next(),"xml-attribute"==a.style){var G=a.content;q.setValue(G.substring(1,G.length-1))}else c.push("expecting attribute value");else q.noValue=!0,q.setValue(!0);q.endOffset=a.offset-1;if(q.noValue&&"xml-attname"!=a.style)break}"xml-punctuation"!=a.style?c.push("expecting \x3e"):(l.startTagOffset=a.offset,"\x3e"==a.content?b.push(l):(l.noEndTag=!0,l=b[b.length-1]),x(a));"style"==l.tag&&v()}else if("\x3c/"==a.value){var M=l;a=
p.next();"script"==l.tag&&(l.script=l.getElementText());b.pop();l=b[b.length-1];a=p.next();M.endOffset=a.offset;x(a)}r=null;break;case "xml-text":case "whitespace":case "xml-entity":u?u.value+=a.value:r?r.value+=a.value:d?d.value+=a.value:w(a.value,a.offset);r=null;break;case "xml-comment":k();var g=new C;g.wasParsed=!0;g.startOffset=a.offset;g.value=a.content.substring(4,a.content.length-3);g.endOffset=a.offset+a.content.length;b[b.length-1].addChild(g,void 0,!0);r=null;break;case "php-block":k();
var s=new K;s.wasParsed=!0;s.startOffset=a.offset;s.value=a.content;s.endOffset=a.offset+a.content.length;b[b.length-1].addChild(s,void 0,!0);r=s;break;case "xml-doctype":u||(k(),g=new C,g.wasParsed=!0,g.startOffset=a.offset,g.value=a.value.substring(2),b[b.length-1].addChild(g,void 0,!0),g.isProcessingInstruction=!0,a=p.next());var h=a.content.length-1;"\x3e"==a.content.charAt(a.content.length-1)?(g.endOffset=a.offset+a.content.length,g.value+=a.content.substring(0,h),x(a),u=void 0):(u=g,g.value+=
a.content);r=null}while(1)}catch(A){}return{errors:c,endOffset:a?a.offset:0}}}});
//# sourceMappingURL=HTMLParser.js.map