//>>built
define("davinci/html/HTMLElement",["dojo/_base/declare","davinci/html/HTMLItem","davinci/html/HTMLText","davinci/html/HTMLComment","davinci/html/HTMLAttribute"],function(n,f,p,q,r){return n("davinci.html.HTMLElement",f,{constructor:function(b){this.elementType="HTMLElement";this.attributes=[];this.tag=b||"";this._fmChildIndent=this._fmChildLine=0},add:function(b){this.statements||(this.statements=[]);this.statements.push(b);this.onChange()},getText:function(b){b=b||{};var a;b.indent+=2;a="\x3c"+this.tag;
for(var c=0;c<this.attributes.length;c++){var e=this.attributes[c].getText(b);0<e.length&&(a=a+" "+e)}if(this.noEndTag)a+="/\x3e";else{a=a+"\x3e"+this._addWS(this._fmChildLine,this._fmChildIndent);if(this.statements)for(c=0;c<this.statements.length;c++)a+=this.statements[c].printStatement(b,this.statements[c]);else if(this.script)a+=this.script;else if(0<this.children.length){e="style"==this.tag;for(c=0;c<this.children.length;c++)if(a+=this.children[c].getText(b),e){var k=this._fmChildLine,d=this._fmChildIndent||
0;c+1==this.children.length&&(k=this._fmLine,d=this._fmIndent);a+=this._addWS(k,d)}}a=a+"\x3c/"+this.tag+"\x3e"}b.indent-=2;return a+=this._addWS(this._fmLine,this._fmIndent)},_formatModel:function(b,a,c){function e(a,b,e){d+=h+a;b?(b._fmChildLine=1,b._fmChildIndent=c.indent):(e._fmLine=1,e._fmIndent=c.indent)}function k(a,b){a.startOffset=d;a.wasParsed=!0;d+=a.tag.length+2;for(var c=0;c<a.attributes.length;c++){a.attributes[c].startOffset=d;var g=a.attributes[c].getText(b);0<g.length&&(d+=1+g.length);
a.attributes[c].endOffset=d-1}a.noEndTag&&d++;a.startTagOffset=d;g="";if(a.statements)for(c=0;c<a.statements.length;c++)g+=a.statements[c].printStatement(b,a.statements[c]);else a.script&&(g=a.script);if(g)d+=g.length;else if(0<a.children.length){var h;davinci.html._noFormatElements[a.tag]||(b.indent+=2,e(b.indent,a),h=!0);for(var f,c=0;c<a.children.length;c++){g=a.children[c];switch(g.elementType){case "HTMLElement":f&&("HTMLText"!=f.elementType&&!davinci.html._noFormatElements[g.tag])&&e(b.indent,
null,f);k(g,b);break;case "HTMLText":g.startOffset=d;d+=g.value.length;break;case "HTMLComment":g.startOffset=d;d+=g.value.length;d++;g.isProcessingInstruction&&(d+=2);break;default:debugger}f=g}h&&(b.indent-=2);f&&"HTMLText"!=f.elementType&&e(b.indent,null,f)}d+=a.tag.length+3;a.endOffset=d-1}var d=0,h=1;void 0==a&&(a=this.children.length);var l,f;!this.children.length||0==a?(l=this,d=this.startTagOffset+1):(f=this.children[a-1],d=f.endOffset+1);var m=d;davinci.html._noFormatElements[b.tag]||(e(c.indent,
l,f),b._fmLine=1,b._fmIndent=a<this.children.length?c.indent:c.indent-2);k(b,c);return d>m?d-m:0},getElementText:function(b){b=b||{};var a="";if(0<this.children.length)for(var c=0;c<this.children.length;c++)"HTMLComment"!=this.children[c].elementType&&(a+=this.children[c].getText(b));else{if(this.script)return this.script;if(this.statements)for(c=0;c<this.statements.length;c++)a+=this.statements[c].printStatement(b,this.statements[c])}return a},getChildElements:function(b,a,c){c=c||[];for(var e=0;e<
this.children.length;e++)this.children[e].tag==b&&c.push(this.children[e]),a&&"HTMLElement"==this.children[e].elementType&&this.children[e].getChildElements(b,a,c);return c},getChildElement:function(b){for(var a=0;a<this.children.length;a++)if(this.children[a].tag==b)return this.children[a]},hasAttribute:function(b){for(var a=0;a<this.attributes.length;a++)if(this.attributes[a].name==b)return!0;return!1},getAttribute:function(b){if(b=this._getAttribute(b))return b.value},_getAttribute:function(b){for(var a=
0;a<this.attributes.length;a++)if(this.attributes[a].name==b)return this.attributes[a]},addText:function(b){this.addChild(new p(b));this.onChange()},addComment:function(b){this.addChild(new q(b));this.onChange()},getLabel:function(){return"\x3c"+this.tag+"\x3e"},addAttribute:function(b,a,c){if("textContent"==b)this.children=[],this.addText(a);else{var e,f=0<this.attributes.length?this.attributes[this.attributes.length-1].endOffset+1:this.startTagOffset-(this.noEndTag?2:1),d=this._getAttribute(b),
h;d?e=a.length-d.value.length:(d=new r,h=!0,e=b.length+a.length+4,d.startOffset=f,d.endOffset=f+e-1);d.name=b;d.setValue(a);d.noPersist=c;this.wasParsed&&(!c&&0<e)&&this.getHTMLFile().updatePositions(f,e);h&&this.attributes.push(d);this.onChange()}},removeAttribute:function(b){this.attributes.every(function(a,c,e){return a.name===b?(e.splice(c,1),c=this.getHTMLFile(),!a.noPersist&&c&&(e=a.getText(),c.updatePositions(a.startOffest,0-(e.length+1))),!1):!0},this);this.onChange()},setAttribute:function(b,
a){this.removeAttribute(b);this.addAttribute(b,a)},getUniqueID:function(b){if(!this.getAttribute("id")){var a=this.getHTMLFile();a.uniqueIDs||(a.uniqueIDs={});a=a.uniqueIDs.hasOwnProperty(this.tag)?++a.uniqueIDs[this.tag]:a.uniqueIDs[this.tag]=0;this.addAttribute("id",this.tag+"_"+a,b)}},findElement:function(b){var a=this.getAttribute("id");if(b==a)return this;for(a=0;a<this.children.length;a++)if("HTMLElement"==this.children[a].elementType){var c=this.children[a].findElement(b);if(c)return c}},insertBefore:function(b,
a){var c=dojo.indexOf(this.children,a);0>c&&(c=void 0);this.addChild(b,c);this.onChange()},addChild:function(b,a,c){if(!c&&this.wasParsed)if("HTMLElement"==b.elementType){var e=this._getIndent(),k;a<this.children.length&&"HTMLElement"==this.children[a].elementType?k=this.children[a]._getIndent():this.children.length?dojo.forEach(this.children,function(a){"HTMLElement"==a.elementType&&(k=a._getIndent())}):k=e+1;e=this._formatModel(b,a,{indent:k});this.getHTMLFile().updatePositions(b.startOffset,e)}else if("HTMLText"==
b.elementType||"CSS"==b.elementType.substring(0,3)){var e=b.getText(),d=this.children.length?this.children[this.children.length-1].endOffset:this.startTagOffset,h=e.length;0<h&&("HTMLText"!=b.elementType&&(h+=this._fmChildIndent+1),this.getHTMLFile().updatePositions(d+1,h));b.startOffset=d+1;b.endOffset=b.startOffset+e.length-1}f.prototype.addChild.apply(this,arguments)},removeChild:function(b){var a=dojo.indexOf(this.children,b);if(0<=a){var c=1+b.endOffset-b.startOffset;if("HTMLElement"==b.elementType)if(1==
this.children.length)c+=1*this._fmChildLine+this._fmChildIndent,this._fmChildIndent-=2;else{if(0<a&&"HTMLElement"==this.children[a-1].elementType)var e=this.children[a-1],c=c+(1*e._fmLine+e._fmIndent);a+1==this.children.length&&"HTMLElement"==this.children[a-1].elementType&&(this.children[a-1]._fmChildIndent-=2)}0<c&&this.wasParsed&&this.getHTMLFile().updatePositions(b.startOffset,0-c)}f.prototype.removeChild.apply(this,arguments)},_textModify:function(b,a){var c=b.length-a.length;0!=c&&this.wasParsed&&
this.getHTMLFile().updatePositions(this.startOffset,c)},setScript:function(b){this._textModify(b,this.script);this.script=b},_previous:function(){var b=dojo.indexOf(this.parent.children,this);if(0<b)return this.parent.children[b-1]},_getIndent:function(){var b=this._previous();return b?" HTMLText"==b.elementType?(b=b.value.split("\n"),b[b.length-1].length):b._fmIndent:this.parent._fmChildIndent},visit:function(b){if(!b.visit(this)){for(var a=0;a<this.attributes.length;a++)this.attributes[a].visit(b);
for(a=0;a<this.children.length;a++)this.children[a].visit(b)}b.endVisit&&b.endVisit(this)},setText:function(b){this.script="";var a=this.parent;this.errors=require("davinci/html/HTMLParser").parse(b,this).errors;dojo.mixin(this,this.children[0]);this.parent=a;this.visit({visit:function(a){delete a.wasParsed},rules:[]});this.onChange()}})});
//# sourceMappingURL=HTMLElement.js.map