//>>built
define("davinci/ve/commands/AppStateCommand","dojo/_base/declare dojo/_base/lang dojo/topic davinci/XPathUtils davinci/html/HtmlFileXPathAdapter davinci/ve/States".split(" "),function(p,h,l,m,n,d){return p("davinci.ve.commands.AppStateCommand",null,{name:"AppStateCommand",_actions:["add","remove","modify","reorder"],constructor:function(b){if(b){this._params=h.mixin({},b);var c=b.stateContainerNode;c&&c._dvWidget&&(this._params.stateContainerId=c.id,this._params.stateContainerXpath=m.getXPath(c._dvWidget._srcElement,
n));"reorder"==this._params.action&&(c=this._getStateContainerNode(),!c||!b.newStatesList.length?this._params=null:(this._oldStatesList=d.getStates(c),this._oldStatesList.shift()))}},_validParams:function(){return this._params&&0<=this._actions.indexOf(this._params.action)&&this._params.stateContainerNode&&this._params.stateContainerId&&this._params.stateContainerXpath&&this._params.context},_getStateContainerNode:function(){var b,c=this._params.context;if(!c)return b;var a=c.getDocument();if(!a)return b;
var d=this._params.stateContainerXpath;b=a.getElementById(this._params.stateContainerId);b||(c=c.model.evaluate(d))&&(b=a.getElementById(c.getAttribute("id")));return b},execute:function(){if(this._validParams()){var b=this._params.action,c=this._params.state,a=this._getStateContainerNode();a&&("add"==b?(d.add(a,c),this._setStateAndFocus(a)):"remove"==b?(this._stateIndex=a._maqAppStates&&a._maqAppStates.states&&a._maqAppStates.states.indexOf(c),this._preservedNodesId=[],this._preservedNodesXpath=
[],this._preservedStateValues=[],this._preserveStateFromNodeRecursive(a,c),d.remove(a,c),this._setStateAndFocus(a)):"modify"==b?(this._params.newState&&(this._traverseRenameState(this._params.state,this._params.newState),l.publish("/davinci/states/state/renamed",{node:a,oldName:this._params.state,newName:this._params.newState,stateContainerNode:a})),"string"==typeof this._params.initialState&&(this._oldInitialState=d.getInitial(a),b="undefined"==this._params.initialState?void 0:this._params.initialState,
this._params.newState&&b==this._params.state&&(b=this._params.newState),d.setState(b,a,{initial:b,updateWhenCurrent:!0})),this._setStateAndFocus(a)):"reorder"==b&&(a&&a._maqAppStates&&a._dvWidget)&&(a._maqAppStates.states=this._params.newStatesList,b=d.stringifyWithQuotes(a._maqAppStates),a.setAttribute(d.APPSTATES_ATTRIBUTE,b),srcElement=a._dvWidget._srcElement,srcElement.setAttribute(d.APPSTATES_ATTRIBUTE,b),l.publish("/davinci/states/statesReordered",[a,this._params.newStatesList])))}},undo:function(){if(this._validParams()){var b=
this._params.action,c=this._params.state,a=this._getStateContainerNode();a&&("add"==b?(d.remove(a,c),this._setStateAndFocus(a)):"remove"==b?(d.add(a,c,{index:this._stateIndex}),this._restoreState(c),d.setState(c,a,{focus:!0}),this._setStateAndFocus(a)):"modify"==b?("string"==typeof this._params.initialState&&d.setState(this._oldInitialState,a,{initial:this._oldInitialState,updateWhenCurrent:!0}),this._params.newState&&this._traverseRenameState(this._params.newState,this._params.state),this._setStateAndFocus(a)):
"reorder"==b&&(a&&a._maqAppStates&&a._dvWidget)&&(a._maqAppStates.states=this._oldStatesList,b=d.stringifyWithQuotes(a._maqAppStates),a.setAttribute(d.APPSTATES_ATTRIBUTE,b),srcElement=a._dvWidget._srcElement,srcElement.setAttribute(d.APPSTATES_ATTRIBUTE,b),l.publish("/davinci/states/statesReordered",[a,this._params.newStatesList])))}},_setStateAndFocus:function(b){var c=d.getState(b);d.setState(c,b,{focus:c,updateWhenCurrent:!0})},_preserveStateFromNodeRecursive:function(b,c){var a=b._dvWidget;if(b&&
a&&c){this._preserveStateFromNode(b,c);for(var a=a.getChildren(),d=0;d<a.length;d++)this._preserveStateFromNodeRecursive(a[d].domNode,c)}},_preserveStateFromNode:function(b,c){b&&(b._maqDeltas&&b._maqDeltas[c]&&b._dvWidget&&b._dvWidget._srcElement)&&(this._preservedNodesId.push(b.id),this._preservedNodesXpath.push(m.getXPath(b._dvWidget._srcElement,n)),this._preservedStateValues.push(h.clone(b._maqDeltas[c])))},_restoreState:function(b){var c=this._params.context;if(c&&this._preservedNodesId){var a=
c.getDocument();if(a)for(var f=0;f<this._preservedNodesId.length;f++){var g=this._preservedNodesXpath[f],e=a.getElementById(this._preservedNodesId[f]);e||(g=c.model.evaluate(g))&&(e=a.getElementById(g.getAttribute("id")));e&&(e._maqDeltas||(e._maqDeltas={}),e._maqDeltas[b]=h.clone(this._preservedStateValues[f]),d._updateSrcState(e))}}},_traverseRenameState:function(b,c){var a=this._getStateContainerNode();if(a&&(d.rename(a,{oldName:b,newName:c}),a=a._dvWidget&&a._dvWidget._srcElement)){var f=null,
g=!1,e=/^(.*davinci.states.setState\s*\(\s*)('[^']*'|"[^"]*")([^\)]*\).*)$/,h=/^(['"])(.*)(['"])$/;a.visit({visit:dojo.hitch(this,function(a){if("HTMLElement"==a.elementType)f=a;else if("HTMLAttribute"==a.elementType){var d=a.name;if(d&&"on"==d.substr(0,2).toLowerCase()&&(a=a.value.match(e))){var k=a[2].match(h);k&&k[2]==b&&(f.setAttribute(d,a[1]+k[1]+c+k[3]+a[3]),g=!0)}}})});g&&(a=this._params&&this._params.context&&this._params.context.editor)&&a._visualChanged()}}})});
//# sourceMappingURL=AppStateCommand.js.map