//>>built
define("davinci/ve/commands/ChangeThemeCommand","dojo/_base/declare dojo/_base/lang dojo/query davinci/Theme davinci/Workbench davinci/library davinci/html/CSSImport davinci/html/HTMLElement davinci/html/HTMLText preview/silhouetteiframe davinci/model/Factory".split(" "),function(n,q,r,h,l,m,s,t,w,u,v){return n("davinci.ve.commands.ChangeThemeCommand",null,{name:"changeTheme",constructor:function(b,c){this._newTheme=b;this._context=c;this._oldTheme=h.getThemeSet(this._context);this._oldTheme||(this._oldTheme=
h.dojoThemeSets.themeSets[0])},execute:function(){this._changeTheme(this._newTheme,this._oldTheme)},undo:function(){this._changeTheme(this._oldTheme,this._newTheme)},_changeTheme:function(b,c){c.desktopTheme?this.removeThemeSet(c):this.removeTheme(c);b.desktopTheme?this.addThemeSet(b):this.addTheme(b);var a=this._context,d=a.editor,g=a.getModel().getText();d.setContent(d.fileName,g);a.widgetAddedOrDeleted(!0);a._configDojoxMobile();d=a.getMobileDevice()||"none";"none"!=d&&(d=u.themeMap[d+".svg"]);
(a=q.getObject("dojox.mobile",!0,a.getGlobal()))&&a.loadDeviceTheme&&a.loadDeviceTheme(d);window.setTimeout(function(){this._context.resizeAllWidgets()}.bind(this),50)},removeTheme:function(b){var c=h.getHelper(b);if(c&&c.removeTheme)c.removeTheme(this._context,b);else{var a=this._context.getModel().getDocumentElement(),c=a.getChildElement("head"),a=a.getChildElement("body"),d=dojo.clone(this._context.getHeader()),g=b.files;b.conditionalFiles&&(g=g.concat(b.conditionalFiles));for(var f=0;f<g.length;f++)for(var l=
g[f],p=0;p<d.styleSheets.length;p++)if(-1<d.styleSheets[p].indexOf(l)){var e=a.getAttribute("class");e&&(e=e.replace(b.className,""),d.bodyClasses=e,a.removeAttribute("class"),0<e.length&&a.addAttribute("class",e,!1));this._context.setHeader(d);for(var e=c.find({elementType:"CSSImport"}),k=0;k<e.length;k++)if(-1<e[k].url.indexOf(l)){var m=e[k].url,n=this._context.getDocument();e[k].url="x";e[k].parent.removeChild(e[k]);e[k].close();r('link[href\x3d"'+m+'"]',n).orphan();this._context.theme=null;break}}}},
addTheme:function(b){var c=h.getHelper(b);if(c&&c.addTheme)c.addTheme(this._context,b);else{var a=this._context.getModel().getDocumentElement(),c=a.getChildElement("head"),d=a.getChildElement("body"),g=dojo.clone(this._context.getHeader()),a=this._context.getFullResourcePath(),a=(new davinci.model.Path(b.getFile().parent.getPath())).append(b.files[0]).relativeTo(a,!0).toString();g.styleSheets[g.styleSheets.length]=a;var f=d.getAttribute("class");f||(f=" ");f=f+" "+b.className;f=f.trim();g.bodyClasses=
f;d.removeAttribute("class");d.addAttribute("class",f,!1);this._context.setHeader(g);d=c.getChildElement("style");d||(d=new t("style"),c.addChild(d));c=new s;c.url=a;a=v.getModel({url:h.getBase()+"/"+c.url,includeImports:!0});c.cssFile=a;d.addChild(c,0);this._context.theme=b}},removeThemeSet:function(b){var c=m.getThemes(l.getProject(),this.workspaceOnly);if(b.desktopTheme)for(var a=0;a<c.length;a++)c[a].name===b.desktopTheme&&this.removeTheme(c[a]);b.mobileTheme&&!h.themeSetEquals(b.mobileTheme,
h.dojoMobileDefault)&&(this._context.close(),this._dojoxMobileRemoveTheme(this._context))},addThemeSet:function(b){var c=m.getThemes(l.getProject(),this.workspaceOnly);if(b.desktopTheme)for(var a=0;a<c.length;a++)c[a].name===b.desktopTheme&&this.addTheme(c[a]);b.mobileTheme&&this._dojoxMobileAddTheme(this._context,b.mobileTheme)},_dojoxMobileRemoveTheme:function(b){b._updateDojoConfig({themeMap:null,mblLoadCompatPattern:null,mblThemeFiles:null})},_dojoxMobileAddTheme:function(b,c,a){h.getThemeLocation().toString().replace(/\//g,
"\\/");b._updateDojoConfig({themeMap:h.getDojoxMobileThemeMap(b,c),mblLoadCompatPattern:"''",mblThemeFiles:[]})}})});
//# sourceMappingURL=ChangeThemeCommand.js.map