//>>built
define("davinci/ve/commands/ModifyCommand",["dojo/_base/declare","davinci/ve/commands/_hierarchyCommand","../widget","../utils/ImageUtils","../States"],function(k,l,g,m,h){return k("davinci.ve.commands.ModifyCommand",[l],{name:"modify",constructor:function(a,b,e,c,d){this._oldId=a?a.id:void 0;this._properties=b=b||{};this._children=e||"string"==typeof e?e:b._children;this._context=c||a.getContext();this._scripts=d;delete this._properties._children},setContext:function(a){this._context=a},add:function(a){a&&
a._oldId==this._oldId&&(a._properties&&dojo.mixin(this._properties,a._properties),a._children&&(this._children=a._children))},execute:function(){if(this._oldId&&this._properties){var a=g.byId(this._oldId),b=this._context;if(a){this._oldData=a.getData();this._oldData.context=b;this._newData={type:this._oldData.type,properties:dojo.mixin({},this._oldData.properties,this._properties),children:this._children||"string"==typeof this._children?this._children:this._oldData.children,scripts:dojo.mixin({},
this._oldData.scripts,this._scripts),maqAppStates:this._oldData.maqAppStates,maqDeltas:this._oldData.maqDeltas,context:b};for(var e in this._newData.properties)"$MAQ_MODIFYCOMMAND_DELETE_PROPERTY$"===this._newData.properties[e]&&delete this._newData.properties[e];if(this._doRefreshFromSource(a))a.setProperties(this._newData.properties,!0),setTimeout(function(){b.visualEditor.refresh()},0);else{b&&b.detach(a);(!this._oldData.properties.isTempID||this._properties.id)&&delete this._newData.properties.isTempID;
e=a.getParent();var c=null,d=e.indexOf(a);e.removeChild(a);a.destroyWidget();if(c=g.createWidget(this._newData)){"IMG"===c.domNode.tagName&&m.ImageUpdateFocus(c,b);e.addChild(c,d);this._newId=c.id;b&&(b.attach(c),c.startup(),c.renderWidget(),b.widgetAddedOrDeleted(),this._oldId!=this._newId&&b.widgetChanged(b.WIDGET_ID_CHANGED,c,this._oldId),b.widgetChanged(b.WIDGET_MODIFIED,c));this.newWidget=c;dojo.publish("/davinci/ui/widget/replaced",[c,a]);h.resetState(c.domNode);var f;if(a=this._isRefreshParentOnPropChange(c))if("string"==
typeof a)for(f=e;f&&f.domNode&&f.type!=a&&"BODY"!=f.domNode.tagName;){if(!f.domNode||"BODY"==f.domNode.tagName){f=null;break}f=f.getParent()}else f=e;(a=this._isRefreshOnDescendantChange(c))&&(f=a);f&&(new davinci.ve.commands.ModifyCommand(f,null,null,e._edit_context)).execute();dojo.publish("/davinci/ui/widgetPropertiesChanged",[[c]])}}}}},_doRefreshFromSource:function(a){var b=this._properties,e,c,d=!1;for(e in b)if(b.hasOwnProperty(e)&&(c=a.metadata.property[e])&&c.refreshFromSource){d=!0;break}return d},
_isRefreshParentOnPropChange:function(a){return davinci.ve.metadata.queryDescriptor(a.type,"refreshParentOnPropChange")},undo:function(){if(this._newId&&this._oldData){var a=g.byId(this._newId);if(a){var b=a.getParent();if(b){var e=b.indexOf(a);if(!(0>e)){var c=b.getContext();c&&c.detach(a);b.removeChild(a);a.destroyWidget();if(newWidget=g.createWidget(this._oldData)){this._oldData=newWidget.getData();this._oldData.context=this._context;b.addChild(newWidget,e);c&&(c.attach(newWidget),newWidget.startup(),
newWidget.renderWidget(),c.widgetAddedOrDeleted(),c.widgetChanged(c.WIDGET_MODIFIED,newWidget));dojo.publish("/davinci/ui/widget/replaced",[newWidget,a]);h.resetState(newWidget.domNode);var d;if(this._isRefreshParentOnPropChange(a))if("string"==typeof refreshParent)for(d=b;d&&d.domNode&&d.type!=refreshParent&&"BODY"!=d.domNode.tagName;){if(!d.domNode||"BODY"==d.domNode.tagName){d=null;break}d=d.getParent()}else d=b;(a=this._isRefreshOnDescendantChange(newWidget))&&(d=a);d&&(new davinci.ve.commands.ModifyCommand(d,
null,null,b._edit_context)).execute();dojo.publish("/davinci/ui/widgetPropertiesChanged",[[newWidget]])}}}}}}})});
//# sourceMappingURL=ModifyCommand.js.map