//>>built
define("davinci/ve/_Widget","dojo/_base/declare ./metadata ../html/CSSModel dojox/html/entities davinci/ve/utils/StyleArray davinci/ve/utils/GeomUtils".split(" "),function(k,g,l,m,n,h){var p=function(a,b,c){if(a==b)return!0;if(!a||!b||a.length!=b.length)return!1;for(var d=0;d<a.length;d++)if(c){if(!c(a[d],b[d]))return!1}else if(a[d]!=b[d])return!1;return!0};return k("davinci.ve._Widget",null,{isWidget:!0,acceptsHTMLChildren:!1,_skipAttrs:"id style class dir lang _children".split(" "),constructor:function(a,
b,c,d){this.domNode=b;this.id=b.id;b._dvWidget=this;this._params=dojo.mixin({},a);this.type=c;this.metadata=d},postscript:function(){var a;if(this.domNode){var b=this.domNode.ownerDocument;b.body._edit_context?a=b.body._edit_context:b.body._dvWidget&&b.body._dvWidget._edit_context&&(a=b.body._dvWidget._edit_context)}this.id&&a&&(a.widgetHash[this.id]=this);this.buildRendering();this.postCreate()},buildRendering:function(){},postCreate:function(){},getObjectType:function(){},getContext:function(){return this._edit_context},
getChildren:function(a){var b=this.getHelper();return b&&b.getChildren?b.getChildren(this,a):this._getChildren(a)},indexOf:function(a){var b=this.getHelper();return b&&b.indexOf?b.indexOf(this,a):dojo.indexOf(this.getChildren(),a)},_getChildren:function(a){var b=this.getContainerNode(),c=[];b&&dojo.forEach(b.children,function(b){a?c.push(require("davinci/ve/widget").getWidget(b)):(b=b._dvWidget)&&c.push(b)});return c},getContainerNode:function(){var a=this.getHelper();return a&&a.getContainerNode?
a.getContainerNode(this):"NONE"!==g.getAllowedChild(this.type)[0]?this._getContainerNode():null},_getContainerNode:function(){return this.domNode},getMetadata:function(){this.metadata||(this.metadata=g.query(this));return this.metadata},getHelper:function(){this._edit_helper||(this._edit_helper=require("davinci/ve/widget").getWidgetHelper(this.type));return this._edit_helper},attr:function(a,b){var c=this._attr.apply(this,arguments);if(1<arguments.length)b=this._stringValue(a,b),this._srcElement.addAttribute(a,
b);else return c},_attr:function(a,b){},indexOf:function(a){var b=this.getHelper();return b&&b.indexOf?b.indexOf(this,a):dojo.indexOf(this.getChildren(),a)},getStyleNode:function(){return this.styleNode||this.domNode},addChild:function(a,b){if(this.getContainerNode()){if(void 0===b||null===b||-1===b)this._srcElement.addChild(a._srcElement);else{var c=this.getChildren();b<c.length?this._srcElement.insertBefore(a._srcElement,c[b]._srcElement):this._srcElement.addChild(a._srcElement)}(c=this.getHelper())&&
c.addChild?c.addChild(this,a,b):this._addChildToDom.apply(this,arguments)}},_addChildToDom:function(a,b){var c=a.domNode,d=this.getContainerNode();if(void 0===b||null===b||-1===b)d.appendChild(c);else{var e=this.getChildren();b<e.length?d.insertBefore(c,e[b].domNode):d.appendChild(c)}},getParent:function(){return require("davinci/ve/widget").getEnclosingWidget(this.domNode.parentNode)||this.domNode.parentNode},getObjectId:function(a){a=a||this;var b=a._edit_object_id;if(b)return b;if(a.domNode)return a.domNode.getAttribute("jsId")},
addClass:function(a){var b=this.getClassNames(),b=b?b.split(/\s+/):[];-1===b.indexOf(a)&&(b.push(a),this._srcElement.setAttribute("class",b.join(" ")),dojo.addClass(this.domNode,a))},getId:function(){if(!this.id){if(!this.domNode.id||!this.type)return;var a=this.domNode.id,b=(this.isHtmlWidget?this.getTagName():this.type).replace(/\./g,"_")+"_";if(a.length>b.length&&a.substring(0,b.length)==b)return}return this._srcElement&&this._srcElement._getAttribute("id")&&this._srcElement._getAttribute("id").noPersist?
void 0:this.id},setMarginBox:function(a){var b=this.getStyleNode();b&&(dojo.marginBox(b,a),this._updateSrcStyle())},getMarginBox:function(){var a=this.domNode,b=null,b=(b=this.getHelper())&&b.getMarginBoxPageCoords?b.getMarginBoxPageCoords(this):h.getMarginBoxPageCoords(a);b.l-=h.getScrollLeft(a);b.t-=h.getScrollTop(a);b.x=b.l;b.y=b.t;return b},getStyle:function(a){a=this.getStyleValues(a);return!a?"":this._styleText(a)},_sortStyleValues:function(a){a=dojo.clone(a);for(var b=l.shorthand,c=0,d=0;d<
b.length;d++){var e;a:{e=b[d][0];for(var f=0;f<a.length;f++)if(a[f]&&a[f].hasOwnProperty(e)){e=f;break a}e=-1}-1<e&&(f=a[e],a.splice(e,1),a.splice(c,0,f),c++)}return a},_styleText:function(a){var b="";if(dojo.isArray(a)){a=davinci.ve.states.normalizeArray("style",this.domNode,d,a);for(var c=0;c<a.length;c++)for(var d in a[c])value=a[c][d],void 0!==value&&(""!=value&&null!=value)&&(b+=d+": "+a[c][d]+"; ")}else for(d in a)value=davinci.ve.states.normalize("style",this.domNode,d,a[d]),void 0!==value&&
(""!=value&&null!=value)&&(b+=d+": "+a[d]+"; ");return b.trim()},getChildrenData:function(a){a=a||{identify:!0};var b=this.getHelper();return b&&b.getChildrenData?b.getChildrenData.apply(b,[this,a]):this._getChildrenData(a)},_getChildrenData:function(a){return this.getChildren().map(function(b){return b.getData(a)})},getClassNames:function(){return this._srcElement.getAttribute("class")||""},_getData:function(a){var b={type:this.type,properties:{}},c=require("davinci/ve/widget");if(a.identify){this._srcElement||
(this._srcElement=c._createSrcElement(this.domNode));var d=this._srcElement._getAttribute("id");d&&d.noPersist&&(b.properties.isTempID=!0);b.properties.id=this.id}!1!==a.preserveTagName&&this.id&&(b.tagName=this._srcElement.tag);d=g.query(this,"property");this.domNode&&this.domNode.parentNode&&(c=c.getEnclosingWidget(this.domNode.parentNode),(c=g.query(c,"childProperties"))&&(d=d?dojo.mixin({},d,c):c));if(d)for(var e in d)if(-1===this._skipAttrs.indexOf(e.toLowerCase())){var c=d[e],f=this.getPropertyValue(e);
if(f&&f.length)"array"==c.datatype?p(f,c.defaultValue)||(b.properties[e]=f):f!=c.defaultValue&&(b.properties[e]=f);else if(("boolean"==c.datatype||"number"==c.datatype)&&f!=c.defaultValue)b.properties[e]=f;else if(c.datatype&&(0==c.datatype.indexOf("dijit")||"object"==c.datatype&&c.isData))b.properties[e]=f}b.properties.style=this.getStyle(a);(e=this.getClassNames(a))&&(b.properties["class"]=e);b.children=this.getChildrenData(a);return b},getData:function(a){a=a||{identify:!0,preserveStates:!0};var b=
this.getHelper();a=b&&b.getData?b.getData.apply(b,[this,a]):this._getData(a);a.maqAppStates=dojo.clone(this.domNode._maqAppStates);a.maqDeltas=dojo.clone(this.domNode._maqDeltas);a.properties||(a.properties={});if(this.properties)for(var c in this.properties)c in a.properties||(a.properties[c]=this.properties[c]);c=this._srcElement;for(var b=c.attributes,d=0;d<b.length;d++){var e=b[d];"on"==e.name.substr(0,2).toLowerCase()?a.properties[e.name]=e.value:"a"==c.tag.toLowerCase()&&"href"==e.name.toLowerCase()&&
(a.properties[e.name]=e.value)}return a},getPropertyValue:function(a){if("id"===a)return this.getId();if("jsId"===a)return this.getObjectId();var b=this.getHelper();return b&&b.getPropertyValue?b.getPropertyValue(this,a):this._getPropertyValue(a)},_getPropertyValue:function(a){return this.domNode.getAttribute(a)},getTagName:function(){return this.domNode.nodeName.toLowerCase()},getStyleValues:function(){function a(a){for(var b=d.length-1;0<=b;b--)void 0!==d[b][a]&&d.splice(b,1)}var b=this.getStyleNode().style,
c=this._srcElement.getAttribute("style"),d=require("davinci/ve/widget").parseStyleValues(c),c=this.getParent();b&&(c&&c.dijitWidget&&c.dijitWidget.addChild&&!c.acceptsHTMLChildren)&&(a("position"),a("left"),a("top"));return d},getStyleValuesAllStates:function(){var a=this.getStyleValues(),b={undefined:a},c=this.domNode._maqDeltas;if(c)for(var d in c)c[d].style&&(b[d]="undefined"==d?n.mergeStyleArrays(a,c[d].style):c[d].style);return b},_updateSrcStyle:function(){var a=this.getStyle();a.length?this._srcElement.addAttribute("style",
a):this._srcElement.removeAttribute("style")},_getStyleString:function(a){if(!a)return"";a=this._sortStyleValues(a);return this._styleText(a)},setStyleValuesCanvas:function(a){if(a){a=this._getStyleString(a);var b=this.getStyleNode();dojo.attr(b,"style",a);this.dijitWidget&&(this.dijitWidget.style=a)}},setStyleValuesModel:function(a){a=this._getStyleString(a);0<a.length?this._srcElement.addAttribute("style",a):this._srcElement.removeAttribute("style")},setStyleValuesAllStates:function(a){this.domNode._maqDeltas=
void 0;if(a)for(var b in a){var c=a[b];"undefined"===b&&(b=void 0);davinci.ve.states.setStyle(this.domNode,b,c,!0)}},isLayout:function(){return!1},resize:function(){},refresh:function(){var a=this.getParent();a.dijitWidget?a.refresh():this.resize&&this.resize()},removeChild:function(a){this._srcElement.removeChild(a._srcElement);var b=this.getHelper();b&&b.removeChild?b.removeChild(this,a):this._removeChildFromDom.apply(this,arguments)},_removeChildFromDom:function(a){(a=a.domNode)&&a.parentNode&&
a.parentNode.removeChild(a)},setProperties:function(a,b){this.properties||(this.properties={});b=b||!1;a.id&&(this._srcElement.addAttribute("id",a.id,a.isTempID),delete a.id,delete a.isTempID);a.isTempID&&delete a.isTempID;for(var c in a){var d=a[c];d||"boolean"==typeof d||"number"==typeof d?(d=this._stringValue(c,d),b||(this.properties[c]=d),this._srcElement.addAttribute(c,d)):(delete this.properties[c],this._srcElement.removeAttribute(c))}},startup:function(){},renderWidget:function(){},destroyWidget:function(a){(a=
this.getHelper())&&a.destroy?a.destroy(this):this.dijitWidget?this.dijitWidget.destroyRecursive():dojo.forEach(this.getChildren(),function(a){a.destroyWidget()})},selectChild:function(a){},attach:function(){var a=this.getHelper();a&&a.create&&a.create(this,this._srcElement)},_stringValue:function(a,b){var c=this.getMetadata(),c=c.property&&c.property[a];if(!c)return b;if("object"==c.datatype)if(b.getObjectId)b=b.getObjectId();else{if(c=b._edit_object_id)return c;if(b.domNode)return b.domNode.getAttribute("jsId")}else if("json"==
c.datatype){var c=(c=this.getContext())&&c.getDojo()||dojo,d=this.getHelper();d&&d.checkValue&&(b=d.checkValue(b));c.isObject(b)&&(b=c.toJson(b))}else if("string"==c.datatype)switch(c.format){case "date":case "time":isFinite(b)&&(b=dojo.date.stamp.toISOString(b,{selector:c.format}));break;default:b=m.encode(b)}return b}})});
//# sourceMappingURL=_Widget.js.map