//>>built
define("davinci/ve/ChooseParent","dojo/_base/declare davinci/Runtime ./widget ./_Widget ./metadata davinci/ve/utils/GeomUtils".split(" "),function(u,v,n,w,t,p){return u("davinci.ve.ChooseParent",null,{constructor:function(a){this._context=a.context},getAllowedTargetWidget:function(a,b,d,h){var e=n.getEnclosingWidget,c=[],f=[];b=b.length?b:[b];var g=this;b.forEach(function(a){f.push({type:a.type,allowedParent:t.getAllowedParent(a.type),classList:g.getClassList(a.type)})});do{b=a instanceof w?a.type:
a._dvWidget.type;var l=this.getClassList(b);this.isAllowed(f,a,b,l,h)&&c.push(a);a=e(a)}while(a&&d);return c},isAllowed:function(a,b,d,h,e){function c(a,b){return b.some(function(b){return-1!==a.indexOf(b)})}var f=t.getAllowedChild(d);"html.body"===d&&(f=["ANY"]);return a.every(function(a){var b="NONE"!==f[0]&&("ANY"===f[0]||c(f,a.classList)),m="ANY"===a.allowedParent[0]||c(a.allowedParent,h),k=n.getWidgetHelper(a.type);return k&&k.isAllowed?k.isAllowed({childType:a.type,childClassList:a.classList,
parentType:d,parentClassList:h,absolute:e.absolute,isAllowedChild:b,isAllowedParent:m}):b&&m})},getClassList:function(a){var b=t.queryDescriptor(a,"class");return b?(b=b.split(/\s+/),b.push(a),b):[a]},dragUpdateCandidateParents:function(a){var b=a.widgetType,d=a.showCandidateParents,h=a.doCursor,e=a.absolute,c=a.currentParent;a=this._XYParent;this._proposedParentWidget||(this._proposedParentWidget=this._getDefaultParent(b,a,e,c));(d||h)&&this.highlightNewWidgetParent(this._proposedParentWidget);var b=
this._context,e=b.getActiveDragDiv(),f;e&&(e=dojo.query(".maqCandidateParents",e),1==e.length&&(f=e[0]));if(f)if(d){d=!0;if(this._lastProposedParentWidget!=this._proposedParentWidget)d=!1;else if("undefined"==typeof this._lastAllowedParentList||null===this._lastAllowedParentList)d=!1;else if(this._lastAllowedParentList.length!=a.length)d=!1;else for(c=0;c<a.length;c++)if(this._lastAllowedParentList[c]!=a[c]){d=!1;break}this._lastProposedParentWidget=this._proposedParentWidget;if(!d)if(d=dojo.i18n.getLocalization("davinci.ve",
"ve"),f.innerHTML="","undefined"==typeof a||null===a)this._lastAllowedParentList=null,c=0;else{this._lastAllowedParentList=a.slice();var c=a.length,g=dojo.create("div",{className:"maqCandidateParentsHeader"},f),e=dojo.create("div",{className:"maqCandidateParentsList"},f);f=dojo.create("div",{className:"maqCandidateParentsHelp"},f);if(0===c)g.innerHTML=d.noValidParents;else if(1==c)g.innerHTML=d.willBeChildOf,dojo.create("div",{className:"maqCandidateListItem maqCandidateCurrent",innerHTML:n.getLabel(a[0])},
e);else{g.innerHTML=d.candidateParents;for(var g="\x3ctable\x3e",c=a.length-1,l=1;0<=c;c--,l++){var m="maqCandidateListItem";a[c]==this._proposedParentWidget&&(m+=" maqCandidateCurrent");g+='\x3ctr class\x3d"'+m+'"\x3e\x3ctd class\x3d"maqCandidateCheckedColumn"\x3e\x26rarr;\x3c/td\x3e\x3ctd class\x3d"maqCandidateNumberColumn"\x3e'+l+'\x3c/td\x3e\x3ctd class\x3d"maqCandidateParentColumn"\x3e'+n.getLabel(a[c])+"\x3c/td\x3e\x3c/tr\x3e"}e.innerHTML=g+"\x3c/table\x3e";f.innerHTML=d.toChangePress}}}else f.innerHTML=
"",this._lastAllowedParentList=null;if(h){for(var k,c=0;c<this._XYParent.length;c++)if(this._XYParent[c]===this._proposedParentWidget){k=c;break}if(void 0!==k){if(!this._cursorSpan&&(this._cursorSpan=dojo.create("span",{className:"editCursor"}),h=b.getGlobal()))this._timer=h.setInterval(function(a,b){var g=v.currentEditor;(g.getContext&&g.getContext())!==b?this.cleanup():dojo.toggleClass(a,"editCursorBlink")}.bind(this),400,this._cursorSpan,b);h=this._XYParent[k].domNode;a=(a=this._XYRefChild[k])?
a.domNode:null;k=this._XYRefAfter[k];a?(k?a.nextSibling&&a.nextSibling._dvWidget?(b=p.getBorderBoxPageCoordsCached(a.nextSibling),k=b.l):(b=p.getBorderBoxPageCoordsCached(a),k=b.l+b.w):(b=p.getBorderBoxPageCoordsCached(a),k=b.l),a=b.t,b=b.h):(b=p.getBorderBoxPageCoordsCached(h),k=b.l,a=b.t,b=16);f=this._cursorSpan.style;f.height=b+"px";f.left=k+"px";f.top=a+"px";h.ownerDocument.body.appendChild(this._cursorSpan)}}},_getDefaultParent:function(a,b,d,h){var e;b&&(a=n.getWidgetHelper(a),e=1<b.length&&
a&&a.chooseParent?a.chooseParent(b):0===b.length?null:d&&h?h:b[b.length-1]);return e},cleanup:function(){this._cursorSpan&&(this._cursorSpan.parentNode.removeChild(this._cursorSpan),this._cursorSpan=null);if(this._timer){var a=this._context.getGlobal();a&&(a.clearInterval(this._timer),this._timer=null)}this.highlightNewWidgetParent(null);this._lastAllowedParentList=null},highlightNewWidgetParent:function(a){if(a!=this.newWidgetParent&&(this.newWidgetParent&&(this.newWidgetParent.domNode.style.outline=
""),this.newWidgetParent=a))a.domNode.style.outline="1px solid rgba(165,42,42,.7)"},getProposedParentWidget:function(){var a=null;if(this._XYParent){var b=this._XYParent.indexOf(this._proposedParentWidget);0<=b&&(a={},a.parent=this._XYParent[b],a.refChild=this._XYRefChild[b],a.refAfter=this._XYRefAfter[b])}return a},setProposedParentWidget:function(a){this._proposedParentWidget=a},getProposedParentsList:function(){return this._XYParent},findParentsXYBeforeTraversal:function(a){a=a.position;this._XYParent=
[];this._XYRefChild=[];this._XYRefAfter=[];"undefined"==typeof this.findParentsXYLastPosition&&(this.findParentsXYLastPosition={});var b=this.findParentsXYLastPosition;if(a.x===b.x&&a.y===b.y)return!1;b.x=a.x;b.y=a.y;return!0},findParentsXY:function(a){var b=a.data,d=a.widget,h=a.absolute,e=a.position;a=a.beforeAfter;var c=e.x,e=e.y,f=d.getHelper();marginBoxPageCoords=f&&f.getMarginBoxPageCoords?f.getMarginBoxPageCoords(d):p.getMarginBoxPageCoordsCached(d.domNode);var g=marginBoxPageCoords.l,l=marginBoxPageCoords.t,
f=marginBoxPageCoords.w,m=marginBoxPageCoords.h,k;if(c>=g&&(c<=g+f&&e>=l&&e<=l+m)&&1===this.getAllowedTargetWidget(d,b,!1,{absolute:h}).length)if(!0===h)this._XYParent.push(d),this._XYRefChild.push(null),this._XYRefAfter.push(!0);else{for(var h=d.getChildren(),n=[],b=0;b<h.length;b++)f=h[b],g=f.domNode,l=p.getBorderBoxPageCoordsCached(g),f=g.offsetWidth,m=g.offsetHeight,g=l.l,l=l.t,k=g+f,m=l+m,n.push({l:g,t:l,r:k,b:m,c:g+f/2});for(var q,r,s,b=0;b<n.length;b++){g=n[b];f=h[b];if(c>=g.l&&c<=g.r&&e>=
g.t&&e<=g.b){q=f;r=c>=g.c?!0:!1;break}0===b?(q=f,r=e>g.b||c>=g.c?!0:!1,s=g.b):(e>=g.t||e>=s)&&c>=g.l?(q=f,r=e>g.b||c>=g.c?!0:!1):e>=s&&e>=g.b&&(q=f,r=!0);g.b>s&&(s=g.b)}this._XYParent.push(d);this._XYRefChild.push(q);this._XYRefAfter.push("after"===a?!0:"before"===a?!1:r)}},findParentsXYAfterTraversal:function(a){var b=a.widgets,d=a.currentParent,h=a.eventTarget.ownerDocument.body._dvWidget;if(a.absolute&&d&&d!=h){var e=!1;this._XYParent.forEach(function(a){a==d&&(e=!0)});e||(this._XYParent.push(d),
this._XYRefChild.push(b[0]),this._XYRefAfter.push(!0))}this.findParentsXYLastPosition={};for(a=0;a<this._XYRefAfter.length-1;a++)this._XYRefAfter[a]=!0},findParentsXYCleanup:function(a){this.findParentsXYLastPosition={}},parentListDivCreate:function(a){var b=a.widgetType,d=a.absolute,h=a.doCursor,e=a.beforeAfter,c=a.currentParent;a=this._context;if(b){var f=a.getDocument();this._oldActiveElement=document.activeElement;f.defaultView.focus();this._keyDownHandler=dojo.connect(f,"onkeydown",dojo.hitch(this,
function(a,b){this.onKeyDown(b,a[0],a[1],a[2],a[3],a[4])},[b,d,h,e,c]));this._keyUpHandler=dojo.connect(f,"onkeyup",dojo.hitch(this,function(a,b){this.onKeyUp(b,a[0],a[1],a[2],a[3],a[4])},[b,d,h,e,c]));b=this._parentListDiv=dojo.create("div",{className:"maqParentListDiv"},document.body);a.setActiveDragDiv(b);dojo.create("div",{className:"maqCandidateParents"},b);return b}},parentListDivGet:function(){return this._parentListDiv},parentListDivDelete:function(){var a=this._context,b=this._parentListDiv;
b&&(this._oldActiveElement&&(this._oldActiveElement.focus(),this._oldActiveElement=null),dojo.disconnect(this._keyDownHandler),dojo.disconnect(this._keyUpHandler),this._keyDownHandler=this._keyUpHandler=null,b.parentNode.removeChild(b),a.setActiveDragDiv(null),this._parentListDiv=null)},_keyEventDoUpdate:function(a,b,d,h,e){var c=this._context.getPreference("showPossibleParents");this.dragUpdateCandidateParents({widgetType:a,showCandidateParents:!c&&this._spaceKeyDown||c&&!this._spaceKeyDown,doCursor:d,
beforeAfter:h,absolute:b,currentParent:e})},onKeyDown:function(a,b,d,h,e,c){dojo.stopEvent(a);a.keyCode==dojo.keys.SPACE?this._spaceKeyDown=!0:this._processKeyDown(a.keyCode);this._keyEventDoUpdate(b,d,h,e,c)},onKeyUp:function(a,b,d,h,e,c){dojo.stopEvent(a);a.keyCode==dojo.keys.SPACE&&(this._spaceKeyDown=!1);this._keyEventDoUpdate(b,d,h,e,c)},_processKeyDown:function(a){if(49<=a&&57>=a){var b=this.getProposedParentsList();1<b.length&&(a=b.length-(a-48),0<=a&&this.setProposedParentWidget(b[a]))}},
isSpaceKeyDown:function(){return this._spaceKeyDown}})});
//# sourceMappingURL=ChooseParent.js.map