//>>built
define("davinci/ve/Focus","require dojo/_base/declare dojo/query dijit/_WidgetBase dojo/dnd/Mover ../Runtime ./metadata ./States ./utils/GeomUtils".split(" "),function(y,q,z,r,s,m,n,p,f){return q(r,{nobSize:11,frameSize:6,postCreate:function(){dojo.addClass(this.domNode,"maqFocus");dojo.style(this.domNode,{position:"absolute",display:"none"});this._stdChrome=dojo.create("div",{"class":"editFocusStdChrome"},this.domNode);this._frames=[];for(var a=0;4>a;a++){var b=dojo.create("div",{"class":"editFocusFrame"},
this._stdChrome);this._frames.push(b);this.connect(b,"onmousedown","onMouseDown")}dojo.addClass(this._frames[0],"editFocusFrameLEFT");dojo.addClass(this._frames[1],"editFocusFrameRIGHT");dojo.addClass(this._frames[2],"editFocusFrameTOP");dojo.addClass(this._frames[3],"editFocusFrameBOTTOM");this._nobs=[];for(a=0;8>a;a++)b=dojo.create("div",{"class":"editFocusNob"},this._stdChrome),this._nobs.push(b),this.connect(b,"onmousedown","onMouseDown");this._frameIndex=this._nobIndex=-1;this._custom=dojo.create("div",
{"class":"editFocusCustom"},this.domNode)},resize:function(a,b){b&&(this._selectedWidget=b);this._moverCurrent=dojo.mixin({},a);this._moverCurrentConstrained=dojo.mixin({},this._moverCurrent);this._updateFocusChrome(this._moverCurrent,!0);this._contexDiv&&(this._contexDiv.style.left=a.w+10+"px",this._updateSubwidgetList());this._box=a},getBounds:function(){return this._moverCurrent},show:function(a,b){var c=b&&b.inline;if(a){this._custom.innerHTML="";var d=n.queryDescriptor(a.type,"showStandardSelectionChrome");
this._stdChrome.style.display=!1===d?"none":"block";this.domNode.style.display="block";this._selectedWidget=a;var d=a.getHelper(),e=!0;if(d&&d.onShowSelection)d.onShowSelection({widget:a,customDiv:this._custom});c&&(this.showInline(a),e=!1);e&&delete this._inline}},showInline:function(a){this._selectedWidget=a;var b=this._context,c=this;n.getSmartInput(a.type).then(function(d){if(d)if(c._inline=d,d.useParent){if(d=a.getParent())b.deselect(a),b.select(d),b.getFocus(d).showInline(d)}else d.show&&d.show(a.id)})},
inlineEditActive:function(){return this._inline&&this._inline.inlineEditActive?this._inline.inlineEditActive():!1},hide:function(a){var b=(a=this._selectedWidget)?a.getHelper():void 0;if(b&&b.onHideSelection)b.onHideSelection({widget:a,customDiv:this._custom});this.domNode.style.display="none";this._displayedWidget=this._selectedWidget=null;this._inline&&(this._inline.hide(),delete this._inline)},allow:function(a){if(a){this._op=a;var b={},c=this._selectedWidget.getHelper();c&&c.resizeAllowWhich?
(c.resizeAllowWhich(this._selectedWidget,b),this._resizeLeft=b.resizeLeft,this._resizeRight=b.resizeRight,this._resizeTop=b.resizeTop,this._resizeBottom=b.resizeBottom):(this._resizeLeft=this._resizeRight=a.resizeWidth,this._resizeTop=this._resizeBottom=a.resizeHeight);b.left=this._resizeLeft&&!this._resizeTop&&!this._resizeBottom?"block":"none";b.right=this._resizeRight&&!this._resizeTop&&!this._resizeBottom?"block":"none";b.top=this._resizeTop&&!this._resizeLeft&&!this._resizeRight?"block":"none";
b.bottom=this._resizeBottom&&!this._resizeLeft&&!this._resizeRight?"block":"none";b.left_top=this._resizeLeft&&this._resizeTop?"block":"none";b.left_bottom=this._resizeLeft&&this._resizeBottom?"block":"none";b.right_top=this._resizeRight&&this._resizeTop?"block":"none";b.right_bottom=this._resizeRight&&this._resizeBottom?"block":"none";this._nobs[0].style.display=b.left;this._nobs[1].style.display=b.right;this._nobs[2].style.display=b.top;this._nobs[3].style.display=b.bottom;this._nobs[4].style.display=
b.left_top;this._nobs[5].style.display=b.left_bottom;this._nobs[6].style.display=b.right_top;this._nobs[7].style.display=b.right_bottom;this._nobs[0].style.cursor=this._frames[0].style.cursor=this._resizeLeft?"w-resize":"auto";this._nobs[1].style.cursor=this._frames[1].style.cursor=this._resizeRight?"e-resize":"auto";this._nobs[2].style.cursor=this._frames[2].style.cursor=this._resizeTop?"n-resize":"auto";this._nobs[3].style.cursor=this._frames[3].style.cursor=this._resizeBottom?"s-resize":"auto";
this._nobs[4].style.cursor="none"!=b.left_top?"nw-resize":"auto";this._nobs[5].style.cursor="none"!=b.left_bottom?"sw-resize":"auto";this._nobs[6].style.cursor="none"!=b.right_top?"ne-resize":"auto";this._nobs[7].style.cursor="none"!=b.right_bottom?"se-resize":"auto"}},_updateFocusChrome:function(a,b){var c,d,e,A,h=this.nobSize+1,t=this.frameSize+1,k=dojo.byId("focusContainer");if(k){var k=f.getBorderBoxPageCoords(k),g=this._context.getParentIframe(),l=f.getBorderBoxPageCoords(g);a.l+=l.l;a.t+=l.t;
if(g)if(g.contentDocument)if(g.contentDocument.body){g=g.contentDocument.body;a.l-=f.getScrollLeft(g);a.t-=f.getScrollTop(g);this.domNode.style.left=a.l-k.l+"px";this.domNode.style.top=a.t-k.t+"px";var g=k=-11,l=a.w,u=a.h,m=a.w,n=a.h,p=-6,q=-6,r=a.w,s=a.h,v=a.w+4+4,w=a.h+4+4,x=this.domNode&&this.domNode.ownerDocument,y=x&&x.body;this._frames[0].style.left=this._frames[2].style.left=this._frames[3].style.left=p+"px";this._frames[0].style.top=this._frames[2].style.top=this._frames[1].style.top=q+"px";
this._frames[0].style.height=w+"px";this._frames[1].style.height=w+"px";this._frames[1].style.left=r+"px";this._frames[2].style.width=v+"px";this._frames[3].style.top=s+"px";this._frames[3].style.width=v+"px";t=Math.round(m/2-this.nobSize/2);h=Math.round(n/2-this.nobSize/2);this._nobs[0].style.left=this._nobs[4].style.left=this._nobs[5].style.left=k+"px";this._nobs[2].style.top=this._nobs[4].style.top=this._nobs[6].style.top=g+"px";this._nobs[0].style.top=h+"px";this._nobs[1].style.left=l+"px";this._nobs[1].style.top=
h+"px";this._nobs[2].style.left=t+"px";this._nobs[3].style.left=t+"px";this._nobs[3].style.top=u+"px";this._nobs[5].style.top=u+"px";this._nobs[6].style.left=l+"px";this._nobs[7].style.left=l+"px";this._nobs[7].style.top=u+"px";this.domNode.style.opacity=0.95;setTimeout(function(){this.domNode.style.opacity=1}.bind(this),1)}else console.error("have no body");else console.error("have no contentDocument");else console.error("have no parent iframe")}},onMouseDown:function(a){this._removeKeyHandlers();
if(this._selectedWidget&&this._selectedWidget.domNode&&!(2===a.button||a.ctrlKey)&&"davinci.ve.tools.SelectTool"==this._context._activeTool.declaredClass){this._shiftKey=a.shiftKey;this._sKey=!1;this._nobIndex=dojo.indexOf(this._nobs,a.target);this._frameIndex=dojo.indexOf(this._frames,a.target);var b=a.pageX-400,c=a.pageY-400,d=null,e=this._selectedWidget.getHelper(),d=e&&e.getMarginBoxPageCoords?e.getMarginBoxPageCoords(this._selectedWidget):f.getMarginBoxPageCoords(this._selectedWidget.domNode),
e=f.getBorderBoxPageCoords(this._context.getParentIframe());this._moverStart={moverLeft:b,moverTop:c,l:d.l+e.l,t:d.t+e.t,w:d.w,h:d.h};d=document.body;this._moverCurrent=dojo.mixin({},this._moverStart);this._moverDragDiv=dojo.create("div",{className:"focusDragDiv",style:"position:absolute;left:"+b+"px;top:"+c+"px;width:800px;height:800px"},d);this._mover=new s(this._moverDragDiv,a,this);dojo.stopEvent(a);this._mouseDownInfo={widget:this._selectedWidget,pageX:a.pageX+e.l,pageY:a.pageY+e.t,dateValue:Date.now()};
this._moverMouseDownEvent=a;this._moverMouseUpEvent=null;this._moverMouseUpHandler=dojo.connect(this._moverDragDiv,"onmouseup",dojo.hitch(this,function(a){this.onMouseUp(a)}));a=this._context.getDocument();(b=document.getElementById("maqetta_project_select"))&&b.focus();a.defaultView.focus();this._keyDownHandler=dojo.connect(a,"onkeydown",dojo.hitch(this,function(a){this.onKeyDown(a)}));this._keyUpHandler=dojo.connect(a,"onkeyup",dojo.hitch(this,function(a){this.onKeyUp(a)}))}},onMove:function(a,
b,c){this._mouseDownInfo=null;this._moverDragDiv&&(this._moverDragDiv.style.left=b.l+"px",this._moverDragDiv.style.top=b.t+"px");if(!(0===this._frameIndex&&!this._resizeLeft||1===this._frameIndex&&!this._resizeRight||2===this._frameIndex&&!this._resizeTop||3===this._frameIndex&&!this._resizeBottom)){a=this._moverStart;c=b.l-a.moverLeft;b=b.t-a.moverTop;if(0===this._frameIndex||4===this._nobIndex||0===this._nobIndex||5===this._nobIndex)this._moverCurrent.l=a.l+c,this._moverCurrent.w=a.w-c;else if(1===
this._frameIndex||6===this._nobIndex||1===this._nobIndex||7===this._nobIndex)this._moverCurrent.w=a.w+c;if(2===this._frameIndex||4===this._nobIndex||2===this._nobIndex||6===this._nobIndex)this._moverCurrent.t=a.t+b,this._moverCurrent.h=a.h-b;else if(3===this._frameIndex||5===this._nobIndex||3===this._nobIndex||7===this._nobIndex)this._moverCurrent.h=a.h+b;b=this._moverCurrent.w;a=this._moverCurrent.h;c=!1;if(this._selectedWidget&&"IMG"===this._selectedWidget.domNode.nodeName){var d=this._selectedWidget.domNode,
e=d.naturalWidth,d=d.naturalHeight;"number"==typeof d&&(0<d&&"number"==typeof e&&0<e)&&(c=e/d,b<c*a?b=a*c:a=b/c,c=!0)}c||(0===this._frameIndex||0===this._nobIndex||1===this._frameIndex||1===this._nobIndex?a=b:2===this._frameIndex||2===this._nobIndex||3===this._frameIndex||3===this._nobIndex?b=a:b>a?a=b:b=a);this._moverCurrentConstrained={l:this._moverCurrent.l,t:this._moverCurrent.t,w:b,h:a};if(0===this._frameIndex||0===this._nobIndex||1===this._frameIndex||1===this._nobIndex)this._moverCurrentConstrained.t-=
(this._moverCurrentConstrained.h-this._moverCurrent.h)/2;if(2===this._frameIndex||2===this._nobIndex||3===this._frameIndex||3===this._nobIndex)this._moverCurrentConstrained.l-=(this._moverCurrentConstrained.w-this._moverCurrent.w)/2;b=dojo.mixin({},this._shiftKey?this._moverCurrentConstrained:this._moverCurrent);a=f.getBorderBoxPageCoords(this._context.getParentIframe());b.l-=a.l;b.t-=a.t;this._updateFocusChrome(b,!1)}},onFirstMove:function(a){},onMoveStart:function(a){},_moverDoneCleanup:function(){var a=
this._context,b=a._chooseParent;this._lastEventTarget=null;this._removeKeyHandlers();a.dragMoveCleanup();b.parentListDivDelete();this._mover=void 0;this._frameIndex=this._nobIndex=-1},onMoveStop:function(a){if(this._moverDragDiv&&((a=this._moverDragDiv.parentNode)&&a.removeChild(this._moverDragDiv),this._moverDragDiv=null,this._moverCurrent.l!=this._moverStart.l||this._moverCurrent.t!=this._moverStart.t||this._moverCurrent.w!=this._moverStart.w||this._moverCurrent.h!=this._moverStart.h)){a=void 0;
if(this._selectedWidget&&this._selectedWidget.domNode)if(this._sKey)for(var b=p.getStatesListCurrent(this._selectedWidget.domNode),c=0;c<b.length;c++){if(b[c]){a=b[c];break}}else a=p.propertyDefinedForAnyCurrentState(this._selectedWidget.domNode,["width","height"]);b=this._shiftKey?this._moverCurrentConstrained:this._moverCurrent;b.w==this._moverStart.w&&delete b.w;b.h==this._moverStart.h&&delete b.h;"number"!=typeof b.l&&(b.l=this._moverStart.l);"number"!=typeof b.t&&(b.t=this._moverStart.t);b.l==
this._moverStart.l&&b.t==this._moverStart.t&&(delete b.l,delete b.t);b=dojo.mixin({},b);b.hasOwnProperty("l")&&(c=f.getBorderBoxPageCoords(this._context.getParentIframe()),b.l-=c.l,b.t-=c.t);this.onExtentChange(this,this._moverStart,b,a)}this._moverDoneCleanup();a=this._moverMouseUpEvent||this._moverMouseDownEvent;this._moverMouseUpEvent=this._moverMouseDownEvent=null;if(a&&a.target){b=Date.now();this._mouseDownInfo=null;if(this._lastMouseUp&&10>=Math.abs(a.pageX-this._lastMouseUp.pageX)&&10>=Math.abs(a.pageY-
this._lastMouseUp.pageY)&&750>=b-this._lastMouseUp.dateValue)this.onDblClick(a);this._lastMouseUp={pageX:a.pageX,pageY:a.pageY,dateValue:b};dojo.stopEvent(a)}},onMouseUp:function(a){this._moverMouseUpEvent=a},onDblClick:function(a){this.showInline(this._selectedWidget);a.stopPropagation()},onKeyDown:function(a){a&&this._moverDragDiv?(dojo.stopEvent(a),a.keyCode==dojo.keys.SHIFT?(this._shiftKey=!0,this._updateFocusChrome(this._shiftKey?this._moverCurrentConstrained:this._moverCurrent,!1)):83==a.keyCode&&
(this._sKey=!0)):this._removeKeyHandlers()},onKeyUp:function(a){a&&this._moverDragDiv?(dojo.stopEvent(a),a.keyCode==dojo.keys.SHIFT?(this._shiftKey=!1,this._updateFocusChrome(this._shiftKey?this._moverCurrentConstrained:this._moverCurrent,!1)):83==a.keyCode&&(this._sKey=!1)):this._removeKeyHandlers()},_removeKeyHandlers:function(){this._keyDownHandler&&(dojo.disconnect(this._keyDownHandler),this._keyDownHandler=null);this._keyUpHandler&&(dojo.disconnect(this._keyUpHandler),this._keyUpHandler=null)},
onExtentChange:function(a,b,c,d){},isFocusNode:function(a){return dojo.hasClass(a,"focusDragDiv")||dojo.hasClass(a,"editFocusNob")||dojo.hasClass(a,"editFocusFrame")||dojo.hasClass(a,"maqFocus")||dojo.hasClass(a,"editFocusStdChrome")},showContext:function(a,b){"davinci.ve.themeEditor.ThemeEditor"==this._context.editor.declaredClass&&(this._contexDiv||(this._context=a,this._createContextPopUp()),this._contexDiv.style.display="block")},hideContext:function(){"davinci.ve.themeEditor.ThemeEditor"==this._context.editor.declaredClass&&
this._contexDiv&&(this._contexDiv.style.display="none")},_createContextPopUp:function(){var a=dojo.doc.createElement("div");a.id="ieb";this._contexDiv=a;this.domNode.appendChild(a)},_createSubwidgetList:function(){var a=this._context._selectedWidget;if(a){var b=this._context.getThemeMeta().metadata,c=b.getWidgetType(a),b=(b=b.getMetadata(c))?b.subwidgets:null;this._displayedWidget=a;if(b){c=this._contexDiv;c.innerHTML="\x3cspan\x3e\x3c/span\x3e";c.style.position="absolute";c.style.left=this._box.w+
10+"px";c.className="themeSubwidgetMenu";dojo.connect(c,"onmousedown",this,"stopPropagation");c.style.display="none";this._contexDiv=c;this.domNode.appendChild(c);var d=this._contexDiv.firstElementChild,e=this._context.theme.name+"_subwidgetmenu";(c=dijit.byId(e))&&c.destroyRecursive(!1);var f=this._context.getDijit(),c=new f.Menu({id:e},d),d=!1;a.subwidget||(d=!0);d=new f.CheckedMenuItem({label:"WidgetOuterContainer",id:this._context.theme.name+"_WidgetOuterContainer",checked:d,onClick:dojo.hitch(this,
"_subwidgetSelected",this._context.theme.name+"_WidgetOuterContainer")});d.domNode.children[0].children[0].setAttribute("src",d.domNode.children[0].children[0].src);c.addChild(d);this._currentItem=d;for(var h in b)d=a.subwidget===h,b=new f.CheckedMenuItem({label:h,id:this._context.theme.name+"_"+h,checked:d,onClick:dojo.hitch(this,"_subwidgetSelected",this._context.theme.name+"_"+h)}),b.domNode.children[0].children[0].setAttribute("src",b.domNode.children[0].children[0].src),c.addChild(b),d&&(this._currentItem=
b);c.startup();this._cm=c;this._updateSubwidgetListForState();this._connections=[];this._connections.push(dojo.subscribe("/davinci/ui/subwidgetSelectionChanged",dojo.hitch(this,this._subwidgetSelectedChange)));this._connections.push(dojo.subscribe("/davinci/states/state/changed",dojo.hitch(this,this._updateSubwidgetListForState)))}else this._contexDiv.innerHTML=""}},stopPropagation:function(a){a.stopPropagation()},_subwidgetSelected:function(a,b){b.stopPropagation();var c=this._context.getDijit(),
d=c.byId(a);d.checked?(this._currentItem&&d!=this._currentItem&&this._currentItem.set("checked",!1),this._currentItem=d,c=this._currentItem.label):((this._currentItem=c.byId(this._context.theme.name+"_WidgetOuterContainer"))&&this._currentItem.set("checked",!0),c=null);b.currentTarget.id===this._context.theme.name+"_WidgetOuterContainer"&&(c=null);dojo.publish("/davinci/ui/subwidgetSelectionChanged",[{subwidget:c,origin:this.declaredClass}])},_subwidgetSelectedChange:function(a){var b=this._context.getDijit();
a.origin!==this.declaredClass&&(this._currentItem&&this._currentItem.set("checked",!1),(this._currentItem=a.subwidget?b.byId(this._context.theme.name+"_"+a.subwidget):b.byId(this._context.theme.name+"_WidgetOuterContainer"))&&this._currentItem.set("checked",!0))},_updateSubwidgetListForState:function(){if(this._context.editor==m.currentEditor)if(this._context._selectedWidget&&this._displayedWidget===this._context._selectedWidget&&this._cm){var a=m.currentEditor,b=a._theme;this._cm.getChildren().forEach(function(c){var d=
c.label;"WidgetOuterContainer"===d&&(d=null);c.setDisabled(!b.isStateValid(this._displayedWidget,a._currentState,d))},this)}else this._clearList(),this._createSubwidgetList()},_updateSubwidgetList:function(){this._displayedWidget!==this._context._selectedWidget&&(this._clearList(),this._createSubwidgetList())},_clearList:function(){if(this._cm){this._cm.destroyRecursive(!1);for(delete this._cm;connection=this._connections.pop();)dojo.unsubscribe(connection)}this._currentItem=null},dojoStyle:function(a,
b,c){if(a&&(a.ownerDocument&&a.ownerDocument.defaultView)&&a.ownerDocument.defaultView.getComputedStyle(a))return dojo.style.apply(dojo,arguments)}})});
//# sourceMappingURL=Focus.js.map