//>>built
define("davinci/ve/metadata","require dojo/Deferred dojo/promise/all dojo/_base/lang dojo/_base/connect ../library ../model/Path ../repositoryinfo xide/types xide/utils".split(" "),function(m,y,N,s,O,t,u,z,F,P){function A(a,b){a=a||{};for(var c=1,d=arguments.length;c<d;c++){var e=arguments[c],f,k;for(f in e)e.hasOwnProperty(f)&&(k=e[f],!(f in a)||"object"!==typeof k&&a[f]!==k?a[f]=k:A(a[f],k))}return a}function Q(a,b,c){l[a.name]=a;b=new u(b);var d=a.overlays,e;for(e in d)d.hasOwnProperty(e)&&("oam"===
e||"maqetta"===e)&&A(a,d[e]);delete a.overlays;a.__metadataModuleId="maq-metadata-"+a.name;d=new u(location.href);d.path=d.path.substring(0,d.path.lastIndexOf("/"));d.path=P.removeURLParameter(d.path,"theme");d.path=""+c;e=[{name:a.__metadataModuleId,location:c+b}];e[0].location=e[0].location.replace("index.php","");e[0].location=e[0].location.replace("?debug\x3dtrue","");e[0].location=e[0].location.replace("\x26isDesktop\x3dtrue","");e[0].location=e[0].location.replace("maqetta.html","");e[0].location=
e[0].location.replace("maqettar.html","");e[0].location=e[0].location.replace("index.html","");e[0].location=e[0].location.replace("xui.php","");e[0].location=e[0].location.replace("xui.php?debug\x3dtrue","");"dojo"!=a.name&&(a.__libraryModuleId=a.name,e.push({name:a.__libraryModuleId,location:d.append("app/static/lib/"+a.name+"/"+a.version).toString()}));m=m({packages:e});var f;if(s.exists("scripts.widget_metadata",a))if("string"==typeof a.scripts.widget_metadata){var k=b.append(a.scripts.widget_metadata);
f=dojo.xhrGet({url:c+k.toString()+(0<z.revision.length?"?"+z.revision:""),handleAs:"json"}).then(function(b){if(b){var d=k.getParentPath();return B(a.name,b,d,d,c)}})}else f=B(a.name,a.scripts.widget_metadata,b,c);if(s.exists("scripts.callbacks",a)){var g=new y;m([a.scripts.callbacks],function(b){a.$callbacks=b;g.resolve()});G.push(g)}return f}function B(a,b,c,d){function e(a,b,c){"undefined"==typeof a.$providedTags[b]&&(a.$providedTags[b]=[]);a.$providedTags[b].push(c)}a||console.error("parseLibraryDescriptor: missing 'libName' arg");
var f=l[a];b.$descriptorFolderPath=c.toString();b.$moduleFolderPath=d.toString();if(f)if(f.$widgets){b.widgets.forEach(function(a){f.$wm.widgets.push(a)});for(var k in b.categories)f.$wm.categories.hasOwnProperty(k)||(f.$wm.categories[k]=b.categories[k])}else if(f.$wm)for(d=0;d<b.widgets.length;d++){k=!1;for(var g=0;!k&&g<f.$wm.widgets.length;g++)f.$wm.widgets[g].type==b.widgets[d].type&&(k=!0);k||f.$wm.widgets.push(b.widgets[d])}else f.$wm||(f.$wm=b);else l[a]={$wm:b,name:b.name,version:b.version},
b.__metadataModuleId&&(l[a].__metadataModuleId=b.__metadataModuleId),f=l[a];var h=f.$wm;h.$providedTypes=h.$providedTypes||{};h.$providedTags=h.$providedTags||{};h.widgets.forEach(function(a){h.$providedTypes[a.type]=a;if("string"==typeof a.tags)e(h,a.tags,a);else if(a.tags&&a.tags.length)for(var b=0;b<a.tags.length;b++)e(h,a.tags[b],a);a.icon&&!a.iconLocal&&(a.icon=c.append(a.icon).toString());a.iconLarge&&!a.iconLargeLocal&&(a.iconLarge=c.append(a.iconLarge).toString());a.widgetClass=h.categories[a.category].widgetClass});
dojo.mixin(h,{_maqGetString:R});if(h.extend)for(var p in h.extend)h.extend.hasOwnProperty(p)&&(l[p]&&l[p].$wm?H(l[p].$wm,[h.extend[p]]):(b=v[p]||[],b.push(h.extend[p]),v[p]=b));v[a]&&H(h,v[a]);return f}function H(a,b){var c=a.$providedTypes;b.forEach(function(a){for(var b in a)if(a.hasOwnProperty(b)){var f=a[b],k=c[b];f.mixin&&s.mixin(k,f.mixin);if(f.concat)for(var g in f.concat)if(f.concat.hasOwnProperty(g)){var h=f.concat[g];if(k[g]){var l=k,n=g;var m=k[g];"string"===typeof m?h=m+","+h:m instanceof
Array?h=m.concat(h):(console.error('Unhandled type for "concat()"'),h=void 0);l[n]=h}else k[g]=h}}})}function n(a){if(a)for(var b in l)if(l.hasOwnProperty(b)){var c=l[b];if(c.$wm&&c.$wm.$providedTypes[a])return c}return null}function R(a){I||(I=!0);return null}function J(a){if(a){if(w.hasOwnProperty(a))return w[a];var b=n(a),c;b&&(c=b.$wm.$descriptorFolderPath);if(!c)return null;var b=b.$wm,d=null,e=C.getResourceManager().getVariable(F.RESOURCE_VARIABLES.APP_URL);b.localPath?(c=a.replace(/\./g,"/").split("/"),
c.shift(),c=c.join("/"),c=[b.$moduleFolderPath,"/",c,"_oam.json"].join(""),e=system.resource.findResource(c).getContentSync(),d=dojo.fromJson(e)):(c=[c,"/",a.replace(/\./g,"/"),"_oam.json"].join(""),c=e+"/lib/metadata/"+c,dojo.xhrGet({url:c,handleAs:"json",sync:!0}).then(function(a){d=a}));if(!d)return console.error("ERROR: Could not load metadata for type: "+a),null;d.$ownproperty=dojo.mixin({},d.property);d.property=dojo.mixin({},S,d.property);d.$src=c;w[a]=d;A(d,b.$providedTypes[a].metadata);return d}}
function K(a,b){if(!b)return a;dojo.every(b.split("."),function(b){if(void 0===a[b])return a=void 0,!1;a=a[b];return!0});return a}function L(a,b){var c=q.queryDescriptor(b,"allowed"+a);c||(c="Parent"===a?"ANY":"NONE");return c.split(/\s*,\s*/)}function M(a,b){var c=q.queryDescriptor(a,b);if(!c)return null;var d=n(a);return D(d,c)}function D(a,b){return!a||!b?null:"string"===typeof b&&"./"===b.substr(0,2)?(new u(a.__metadataModuleId)).append(b).toString():b}var q,E,C,l={},w={},x={},G=[],v={},S={id:{datatype:"string",
hidden:!0},lang:{datatype:"string",hidden:!0},dir:{datatype:"string",hidden:!0},"class":{datatype:"string",hidden:!0},style:{datatype:"string",hidden:!0},title:{datatype:"string",hidden:!0}};dojo.subscribe("/davinci/ui/libraryChanged/start",function(){l={};w={};x={};q.init().then(function(){dojo.publish("/davinci/ui/libraryChanged")})});var I=!1;q={prefix:"",init:function(a,b){C=a;var c=[];E=m("../Workbench");C.getResourceManager().getVariable(F.RESOURCE_VARIABLES.APP_URL);t.getUserLibs(E.getProject()).forEach(function(a){var e=
a.metaRoot;(e=e.replace("app/metadata/",""))&&c.push(dojo.xhrGet({url:b+e+"/package.json?"+z.revision,handleAs:"json"}).then(function(a){return Q(a,e,b)}))});return N(c)},parseMetaData:function(a,b,c,d){return B(a,b,c,d)},getLibrary:function(a){return a?l[a]:l},getLibraryActions:function(a,b){var c=[],d;for(d in l)if(l.hasOwnProperty(d)){var e=l[d];if(e.$wm){var f=e.$wm["davinci.actionSets"];f&&dojo.forEach(f,function(d){if(d.id==a&&(!b||d.targetID===b))d=dojo.clone(d.actions),dojo.forEach(d,function(a){if(a.action){var b=
D(e,a.action);a.action=b}a.menu&&a.menu.forEach(function(a){if(a.action){var b=D(e,a.action);a.action=b}});c.push(a)})})}}return c},loadThemeMeta:function(a){for(var b=a.find({elementType:"HTMLElement",tag:"style"}),c=[],d,e=0;e<b.length;e++)for(var f=0;f<b[e].children.length;f++)"CSSImport"==b[e].children[f].elementType&&c.push(b[e].children[f]);new u(a.fileName);e=t.getThemes(E.getProject());b={};for(f=0;f<e.length;f++)if(e[f].files)for(var k=0;k<e[f].files.length;k++)b[e[f].files[k]]=e[f];for(f=
0;f<c.length;f++){var e=c[f].url,g;for(g in b)if(-1<g.indexOf("claro")&&(d=g),-1<e.indexOf(g))return{themeUrl:e,themeMetaCache:t.getThemeMetadata(b[g]),theme:b[g]}}if(f=q._loadThemeMetaDojoxMobile(a,b))return f;if(d){for(var h,f=0;f<c.length;f++)if((g=c[f].url.match(/\/([^\/]*)\.css$/))&&2==g.length)if(g=g[1],c[f].url.match(RegExp("themes/"+g+"/"+g+".css$"))){h=g;break}if(h)return g=a.getDocumentElement(),a=g.getChildElement("head"),g=g.getChildElement("body"),(e=g.getAttribute("class"))&&g.setAttribute("class",
e.replace(RegExp("\\b"+h+"\\b","g"),"claro")),a=a.getChildElements("style"),dojo.forEach(a,function(a){dojo.forEach(a.children,function(a){"CSSImport"==a.elementType&&(a.url=a.url.replace(RegExp("/"+h,"g"),"/claro"))})}),e=c[f].url.replace(RegExp("/"+h,"g"),"/claro"),c={themeUrl:e,themeMetaCache:t.getThemeMetadata(b[d]),theme:b[d]},c.themeMetaCache.usingSubstituteTheme={oldThemeName:h,newThemeName:"claro"},c}},_loadThemeMetaDojoxMobile:function(a,b){for(var c=a.find({elementType:"HTMLElement",tag:"script"}),
d=0;d<c.length;d++){var e=c[d].getElementText();if(e.length){var f=e.indexOf("dojoxMobile.themeMap");if(0<f){var f=e.indexOf("\x3d",f),k=e.indexOf(";",f);if(k>f){var e=dojo.fromJson(e.substring(f+1,k))[0][2][0],g;for(g in b)if(-1<e.indexOf(g))return{themeUrl:e,themeMetaCache:t.getThemeMetadata(b[g]),theme:b[g]}}}}}},getLibraryForType:function(a){return n(a)},getLibraryMetadataForType:function(a){return(a=n(a))?a.$wm:null},getWidgetDescriptorForType:function(a){var b=n(a);a=b?b.$wm.$providedTypes[a]:
void 0;return a},getOamDescriptivePropertyForType:function(a,b){var c=J(a);return c&&c[b]?(c=c[b],"string"==typeof c?{type:"text/plain",value:c}:"string"==typeof c.value?{type:c.type?c.type:"text/plain",value:c.value}:null):null},getWidgetsWithTag:function(a){var b=[];if(a)for(var c in l)if(l.hasOwnProperty(c)){var d=l[c];d.$wm&&d.$wm.$providedTags[a]&&(b=b.concat(d.$wm.$providedTags[a]))}return b},getLibraryBase:function(a){if(a=n(a))return a.$wm.$descriptorFolderPath},invokeCallback:function(a,
b,c){var d=a;"string"===typeof a&&(d=n(type));if(d&&d.$callbacks&&(a=d.$callbacks[b]))return a.apply(d.$callbacks,c)},query:function(a,b){if(a){var c,d;a.declaredClass?(a.metadata&&(d=a.metadata),c=a.type):c=a;if(!d){d=J(c);if(!d)return;a.declaredClass&&(a.metadata=d)}return K(d,b)}},queryDescriptorByName:function(a,b,c){b=n(b);var d;if(b){b=b.$wm.widgets;for(var e=0;e<b.length;e++)if(b[e].name==a){d=b[e];break}}return this._queryDescriptor(d,c)},queryDescriptor:function(a,b){var c=n(a),d;c&&(d=c.$wm.$providedTypes[a]);
return this._queryDescriptor(d,b)},_queryDescriptor:function(a,b){if(a&&"object"===typeof a){var c=K(a,b);"resizable"===b&&(c||(c="both"));return c}},getAllowedParent:function(a){return L("Parent",a)},getAllowedChild:function(a){return L("Child",a)},getHelper:function(a,b){var c=new y,d=a+":"+b;if(d in x)return c.resolve(x[d]),c;var e=M(a,b);e?m([e],function(a){c.resolve(a);x[d]=a}):c.resolve();return c},getSmartInput:function(a){var b=new y;if(a in r)b.resolve(r[a]);else{var c=M(a,"inlineEdit");
c?"string"===typeof c?m([c],function(c){b.resolve(r[a]=new c)}):"[object Array]"===Object.prototype.toString.call(c.property)?m(["davinci/ve/input/MultiFieldSmartInput"],function(d){d=new d;s.mixin(d,c);b.resolve(r[a]=d)}):m(["davinci/ve/input/SmartInput"],function(d){d=new d;s.mixin(d,c);b.resolve(r[a]=d)}):b.resolve(null)}return b},getDeferreds:function(){return G}};var r={};O.subscribe("/davinci/ui/libraryChanged/start",function(){r={}});return dojo.setObject("davinci.ve.metadata",q)});
//# sourceMappingURL=metadata.js.map