//>>built
define("davinci/ve/PageEditor","require dojo/_base/declare ../ui/ModelEditor dijit/layout/BorderContainer dijit/layout/ContentPane dojo/dnd/Moveable ../Runtime ../commands/CommandStack ../html/ui/HTMLEditor ../model/Path ./VisualEditor ./VisualEditorOutline ./widget ./States ../XPathUtils ../html/HtmlFileXPathAdapter ./utils/GeomUtils dojox/widget/Toaster davinci/model/Factory".split(" "),function(f,h,k,l,g,m,u,n,v,w,p,q,r,x,y,z,d,s,A){return h("davinci.ve.PageEditor",k,{_latestSourceMode:"source",
_latestLayoutMode:"flow",item:null,delegate:null,constructor:function(a,b,c,t){this._bc=new l({},a);this.item=c;this.domNode=this._bc.domNode;this._commandStack=new n(this);this.savePoint=0;this._designCP=new g({"class":"designCP",region:"center",style:"padding:0px;"});this._bc.addChild(this._designCP);this.currentEditor=this.visualEditor=new p(this._designCP.domNode,this);this.currentEditor._commandStack=this._commandStack;try{this._srcCP=new g({region:"bottom",splitter:!0,style:"height:50%;padding:0px;"});
var f=this._srcCP.resize;this._srcCP.resize=function(a,b){dojo.marginBox(this.domNode,b);f.apply(this,arguments);e.editor&&e.editor.getTextView()&&e.editor.getTextView().resize()};var e=null,e=this.htmlEditor=t(this._srcCP.domNode);this.model=e.model;this._displayMode="design";this._bc.startup();this._bc.resize();this._connect(this.visualEditor,"onContentChange","_visualChanged");this.subscribe("/davinci/ui/styleValuesChange",this._stylePropertiesChange);this.subscribe("/davinci/ui/widgetSelected",
this._widgetSelectionChange);this.subscribe("/davinci/ui/selectionChanged",this._modelSelectionChange);this.subscribe("/davinci/ui/editorSelected",this._editorSelected.bind(this));this.subscribe("/davinci/ui/context/loaded",this._contextLoaded.bind(this));this.subscribe("/davinci/ui/deviceChanged",this._deviceChanged.bind(this))}catch(d){this.visualEditor._connectCallback(d),console.error("page editor crash : "+d)}},setRootElement:function(a){this._rootElement=a},supports:function(a){return a.match(/^palette|properties|style|states|inline-style|MultiPropTarget|propsect_common|propsect_widgetSpecific|propsect_events|propsect_layout|propsect_paddingMargins|propsect_background|propsect_border|propsect_fontsAndText|propsect_shapesSVG$/)},
focus:function(){},_editorSelected:function(a){var b=this.getContext();if(b){if(this==a.oldEditor&&b.hideFocusAll(),a.editor&&(a.editor.editorContainer&&("davinci.ve.PageEditor"==a.editor.declaredClass||"davinci.ve.themeEditor.ThemeEditor"==a.editor.declaredClass))&&this==a.editor)a=b.getFlowLayout()?"flow":"absolute",this._updateLayoutDropDownButton(a),b.clearCachedWidgetBounds()}else console.error("_editorSelected : have no context!")},_contextLoaded:function(){},_deviceChanged:function(){if(m.currentEditor==
this&&this.editorContainer){var a=this.getContext();a&&a.updateFocusAll&&setTimeout(function(){a.updateFocusAll()},1E3)}},_updateLayoutDropDownButton:function(a){(a=dojo.query(".maqLayoutDropDownButton"))&&a[0]&&dijit.byNode(a[0])},_selectLayout:function(a){this._latestLayoutMode=a;f(["davinci/actions/SelectLayoutAction"],function(b){(new b)._changeLayoutCommand(a)});this._updateLayoutDropDownButton(a)},selectLayoutFlow:function(){this._selectLayout("flow")},selectLayoutAbsolute:function(){this._selectLayout("absolute")},
getDisplayMode:function(){return this._displayMode},getSourceDisplayMode:function(){return this._latestSourceMode},_switchDisplayModeSource:function(a){this._latestSourceMode=a;this.switchDisplayMode(a)},switchDisplayModeSource:function(){this._switchDisplayModeSource("source")},switchDisplayModeSplitVertical:function(){this._switchDisplayModeSource("splitVertical")},switchDisplayModeSplitHorizontal:function(){this._switchDisplayModeSource("splitHorizontal")},switchDisplayModeSourceLatest:function(){this.switchDisplayMode(this._latestSourceMode)},
switchDisplayModeDesign:function(){this.switchDisplayMode("design")},switchDisplayMode:function(a){var b=this.getContext();"design"!=this._displayMode&&(this._bc.removeChild(this._srcCP),this.htmlEditor.setVisible(!1));this._designCP.set("region","center");delete this._designCP.domNode.style.width;delete this._srcCP.domNode.style.width;switch(a){case "source":this._designCP.set("region","left");this._designCP.domNode.style.width=0;this._srcCP.set("region","center");break;case "splitVertical":this._designCP.domNode.style.width=
"50%";this._srcCP.set("region","right");this._srcCP.domNode.style.width="50%";this._bc.set("design","sidebar");break;case "splitHorizontal":this._designCP.domNode.style.height="50%",this._srcCP.set("region","bottom"),this._srcCP.domNode.style.height="50%",this._bc.set("design","headline")}"design"!=a&&(this._bc.addChild(this._srcCP),this.htmlEditor.setVisible(!0));this._displayMode=a;this._bc.layout();this.editorContainer&&this.editorContainer.updateToolbars();dojo.publish("/davinci/ui/repositionFocusContainer",
[]);"source"==a?b.hideFocusAll():(b.clearCachedWidgetBounds(),b.updateFocusAll())},_modelSelectionChange:function(a){if(!("source"==this._displayMode||f("davinci/Runtime").currentEditor!==this))if(this._selectionCssRules=null,a.length&&(a=a[0].model)&&"HTMLElement"==a.elementType)if((a=a.getAttribute("id"))&&"source"!=this._displayMode){a=r.byId(a,this.visualEditor.context.getDocument());var b=d.getMarginBoxPageCoords(a.domNode);this.getContext().getGlobal().scroll(b.l,b.t);this.visualEditor.context.select(a)}},
_widgetSelectionChange:function(a){if(this.visualEditor.context&&(!a||!(a.length&&a[0]._edit_context!=this.visualEditor.context)))(a=this.visualEditor.context.getSelection())&&a.length&&"design"!=this._displayMode&&this.htmlEditor.selectModel([{model:a[0]._srcElement}])},_stylePropertiesChange:function(a){this.visualEditor._stylePropertiesChange(a)},_setDirty:function(){this.setDirty(!0)},setDirty:function(a){if(this.isDirty=a)this.lastModifiedTime=Date.now();this.editorContainer&&this.editorContainer.setDirty(a)},
_visualChanged:function(a){a||this._setDirty();this.htmlEditor.setValue(this.model.getText(),!0)},_srcChanged:function(){dojo.withDoc(window.document,function(){this.htmlEditor.isTyping&&(this.visualEditor.skipSave=!0);var a=this.visualEditor.context,b=a&&this._getStatesScenes(a);this.visualEditor.setContent(this.fileName,this.htmlEditor.model);this.editorContainer.updateToolbars();dojo.publish("/davinci/ui/context/pagerebuilt",[a]);b&&this._setStatesScenes(a,b);delete this.visualEditor.skipSave;
this._setDirty()},this)},_getStatesScenes:function(a){return[]},_setStatesScenes:function(a,b){},getContext:function(){return this.visualEditor.context},getOutline:function(){this.outline||(this.outline=new q(this));return this.outline},getPropertiesView:function(){return this.currentEditor.getPropertiesView()},setContent:function(a,b,c){this.fileName=a;this.htmlEditor.setContent(a,b);this.visualEditor.setContent(a,this.htmlEditor.model,c);this._connect(this.htmlEditor.model,"onChange","_themeChange")},
_themeChange:function(a){a&&"CSSRule"===a.elementType&&(this.setDirty(!0),this.visualEditor.context.hotModifyCssRule(a))},getDefaultContent:function(){this._isNewFile=!0;return this.visualEditor.getDefaultContent()},selectModel:function(a,b){if(!(this.publishingSelect||b&&this!=b)){var c=a&&a[0];c&&(c.elementType?this.htmlEditor.selectModel(a):c.model&&c.model.isWidget&&this.visualEditor.context.select(c.model,c.add))}},save:function(a){if(this.delegate&&this.delegate.save){var b=this.visualEditor.context.getModel(),
c=b.getText();this.delegate.save(this,this.visualEditor,b,c)}else"undefined"==typeof hasToaster&&(new s({position:"br-left",duration:4E3,messageTopic:"/davinci/resource/saveError"}),hasToaster=!0),this.savePoint=this._commandStack.getUndoCount(),(b=this.visualEditor.save(a))&&b.then&&b.then(function(b){this.isDirty=a;this.editorContainer&&this.editorContainer.domNode&&this.editorContainer.setDirty(a)}.bind(this),function(a){})},removeWorkingCopy:function(){},previewInBrowser:function(){this.visualEditor.previewInBrowser()},
destroy:function(){this.inherited(arguments);this.visualEditor.destroy();this.htmlEditor.destroy()},getText:function(){return this.htmlEditor.getText()},onResize:function(){for(var a=this.getContext(),b=a.getSelection(),c=0;c<b.length;c++)a.select(b[c],0!=c)},handleKeyEvent:function(a){},getDisplayMode:function(){return this._displayMode},getFocusContainerBounds:function(){if("source"==this._displayMode)return{l:0,t:0,w:0,h:0};var a=d.getBorderBoxPageCoords(this._designCP.domNode);a.l-=8;a.t-=8;"none"==
(this.visualEditor&&this.visualEditor.getDevice?this.visualEditor.getDevice():"none")?(a.w+="splitVertical"==this._displayMode?8:16,a.h+="splitHorizontal"==this._displayMode?8:16):(a.w+=8,a.h+=8);return a},getCommandStack:function(){return this.getContext().getCommandStack()}})});
//# sourceMappingURL=PageEditor.js.map