//>>built
define("davinci/ve/Snap",["davinci/ve/utils/GeomUtils"],function(p){dojo.getObject("davinci.ve.Snap",!0);return davinci.ve.Snap={updateSnapLinesBeforeTraversal:function(b,f){b._snapX=null;b._snapY=null;if(b._lastSnapBox&&b._lastSnapBox.l==f.l&&b._lastSnapBox.t==f.t&&b._lastSnapBox.w==f.w&&b._lastSnapBox.h==f.h)return!1;snapBox={l:f.l,t:f.t,w:f.w,h:f.h,c:f.l+f.w/2,r:f.l+f.w,m:f.t+f.h/2,b:f.t+f.h};b._lastSnapBox=snapBox;return!0},findSnapOpportunities:function(b,f,c,d,e){function h(a,d,c,e){e<q&&(b._snapX=
{type:a,typeRefObj:a,typeCurrObj:d,x:c,widget:f,delta:e},q=e,b._snapXLast=b._snapX)}function k(a,d,c,e){e<r&&(b._snapY={type:a,typeRefObj:a,typeCurrObj:d,y:c,widget:f,delta:e},r=e,b._snapYLast=b._snapY)}c=b._lastSnapBox;var m=f.domNode;if("BODY"!=m.tagName){var g=null,a=f.getHelper(),g=a&&a.getMarginBoxPageCoords?a.getMarginBoxPageCoords(f):p.getMarginBoxPageCoordsCached(m);g.x=g.l;g.y=g.t;var q=b._snapX?b._snapX.delta:6,r=b._snapY?b._snapY.delta:6,m={snapRect:{l:g.x,c:g.x+g.w/2,r:g.x+g.w,t:g.y,m:g.y+
g.h/2,b:g.y+g.h}};a&&a.getSnapInfo&&(m=a.getSnapInfo(f,m));var a=m.snapRect,l;if(a){if(d){d=b._snapXLast&&b._snapXLast.widget===f?Infinity:75;g=Math.abs(a.t-c.t);l=Math.abs(a.t-c.b);var n=Math.abs(a.b-c.t),s=Math.abs(a.b-c.b);if(g<=d||l<=d||n<=d||s<=d)d=Math.abs(a.l-c.l),g=Math.abs(a.c-c.c),l=Math.abs(a.r-c.r),h("left","left",a.l,d),h("center","center",a.c,g),h("right","right",a.r,l),h("left","center",a.c,Math.abs(a.c-c.l)),h("left","right",a.r,Math.abs(a.r-c.l)),h("right","left",a.l,Math.abs(a.l-
c.r)),h("right","center",a.c,Math.abs(a.c-c.r)),h("center","left",a.l,Math.abs(a.l-c.c)),h("center","right",a.r,Math.abs(a.r-c.c))}if(e&&(e=b._snapYLast&&b._snapYLast.widget===f?Infinity:75,d=Math.abs(a.l-c.l),g=Math.abs(a.l-c.r),l=Math.abs(a.r-c.l),n=Math.abs(a.r-c.r),d<=e||g<=e||l<=e||n<=e))d=Math.abs(a.t-c.t),g=Math.abs(a.m-c.m),l=Math.abs(a.b-c.b),k("top","top",a.t,d),k("middle","middle",a.m,g),k("bottom","bottom",a.b,l),k("top","middle",a.m,Math.abs(a.m-c.t)),k("top","bottom",a.b,Math.abs(a.b-
c.t)),k("bottom","top",a.t,Math.abs(a.t-c.b)),k("bottom","middle",a.m,Math.abs(a.m-c.b)),k("middle","top",a.t,Math.abs(a.t-c.m)),k("middle","bottom",a.b,Math.abs(a.b-c.m))}if(m=m.snapPoints)for(a=0;a<m.length;a++)e=m[a],d=Math.abs(e.x-c.l),g=Math.abs(e.x-c.c),l=Math.abs(e.x-c.r),h("point",e.x,d),h("point",e.x,g),h("point",e.x,l),d=Math.abs(e.y-c.t),g=Math.abs(e.y-c.m),l=Math.abs(e.y-c.b),k("point",e.y,d),k("point",e.y,g),k("point",e.y,l)}},updateSnapLinesAfterTraversal:function(b){function f(b,c,
a,e){a.style.display="block";e.style.display="block";d=(b=c.getHelper())&&b.getMarginBoxPageCoords?b.getMarginBoxPageCoords(c):p.getMarginBoxPageCoordsCached(c.domNode);d.x=d.l;d.y=d.t;d.r=d.x+d.w;d.b=d.y+d.h;d.c=d.x+d.w/2;d.m=d.y+d.h/2;a.style.left=d.x+"px";a.style.top=d.y+"px";a.style.width=d.w+"px";a.style.height=d.h+"px";a.style.backgroundColor="rgba(255,0,255,.05)"}var c=b.getContainerNode();b._snapLinesDiv||(b._snapLinesDiv=dojo.create("div",{"class":"snaplines",style:"position:absolute;top:0px;left:0px;z-index:1000001;pointer-events:none;"},
c),b._snapLinesDivWidgetX=dojo.create("div",{"class":"snaplinesWidgetX",style:"position:absolute;pointer-events:none;"},b._snapLinesDiv),b._snapLinesDivAlignX=dojo.create("div",{"class":"snaplinesAlignX",style:"position:absolute;pointer-events:none;"},b._snapLinesDiv),b._snapLinesDivWidgetY=dojo.create("div",{"class":"snaplinesWidgetY",style:"position:absolute;pointer-events:none;"},b._snapLinesDiv),b._snapLinesDivAlignY=dojo.create("div",{"class":"snaplinesAlignY",style:"position:absolute;pointer-events:none;"},
b._snapLinesDiv));b._snapLinesDiv.style.display="block";var d,c=b._snapLinesDivAlignX.style,e=b._snapLinesDivWidgetX.style;if(b._snapX){e=b._snapX;f(b,e.widget,b._snapLinesDivWidgetX,b._snapLinesDivAlignX);var h,k;d.y<snapBox.t?(h=d.y,k=snapBox.t-d.y):(h=snapBox.t,k=d.y-snapBox.t);c.left="point"==e.typeCurrObj?b._snapX.x+"px":"left"==e.typeCurrObj?d.x+"px":"center"==e.typeCurrObj?d.c+"px":d.r+"px";c.top=h+"px";c.width="1px";c.height=k+"px";c.backgroundColor="rgba(255,0,255,.75)"}else c.display="none",
e.display="none";c=b._snapLinesDivAlignY.style;e=b._snapLinesDivWidgetY.style;b._snapY?(e=b._snapY,f(b,e.widget,b._snapLinesDivWidgetY,b._snapLinesDivAlignY),d.x<snapBox.l?(b=d.x,h=snapBox.l-d.x):(b=snapBox.l,h=d.x-snapBox.l),c.top="point"==e.type?e.y+"px":"top"==e.typeCurrObj?d.y+"px":"middle"==e.typeCurrObj?d.m+"px":d.b+"px",c.left=b+"px",c.height="1px",c.width=h+"px",c.backgroundColor="rgba(255,0,255,.75)"):(c.display="none",e.display="none")},clearSnapLines:function(b){b._snapLinesDiv&&(b._snapLinesDiv.style.display=
"none");b._snapX=b._snapY=null}}});
//# sourceMappingURL=Snap.js.map