//>>built
"undefined"===typeof davinci&&(davinci={});davinci.AppStatesDontInitialize=!0;
define("davinci/ve/States","dojo/_base/declare dojo/_base/connect dojo/query dojo/dom-class dojo/dom-style dojo/_base/window dijit/registry davinci/Runtime davinci/Workbench davinci/maqetta/AppStates ./utils/GeomUtils ./commands/EventCommand ./commands/StyleCommand davinci/ve/utils/StyleArray davinci/workbench/Preferences dojo/i18n!davinci/ve/nls/ve".split(" "),function(r,A,p,k,t,u,s,n,B,y,q,z,C,D,v,w){var x=document;r=r(y,{_update:function(a,b){n.currentEditor&&"davinci.ve.PageEditor"==n.currentEditor.declaredClass&&
a&&(a._dvWidget&&(a._maqAppStates||!a._maqDeltas))&&this._refresh(a._dvWidget)},_refresh:function(a){var b=a.getParent();b.dijitWidget?this._refresh(b):a&&a.resize&&a.resize()},_updateEvents:function(a,b,c){if(a&&a._dvWidget){a=a._dvWidget;var e=["onclick","onmouseover","onmouseout","onfocus","onblur"],d,f;for(f in e){var g=e[f],h=a&&a.properties&&a.properties[g];if("string"==typeof h&&0<=h.indexOf("davinci.states.setState")){var l=h,h=h.replace("'"+b+"'","'"+c+"'");h!==l&&(d=d||{},d[g]=h)}}if(b=
this.getContext())d=new z(a,d),b.getCommandStack().execute(d)}},normalize:function(a,b,c,e){switch(a){case "style":var d=this.getStatesListCurrent(b);for(a=0;a<d.length;a++)d[a]="Normal";if(b=this.getStyle(b,d,c))for(a=0;a<b.length;a++)b[a][c]&&(e=b[a][c])}return e},normalizeArray:function(a,b,c,e){e=dojo.clone(e);switch(a){case "style":var d=this.getStatesListCurrent(b);for(a=0;a<d.length;a++)d[a]="Normal";if(b=this.getStyle(b,d,c)){for(a=0;a<b.length;a++){c=b[a];for(var f in c)for(c=e.length-1;0<=
c;c--){var d=e[c],g;for(g in d)if(g==f){e.splice(c,1);break}}}e=e.concat(b)}}return e},getEditor:function(){return n.currentEditor},getContext:function(){var a=this.getEditor();return a&&(a.getContext&&a.getContext()||a.context)},getDocument:function(){var a=this.getContext();return a&&a.getDocument&&a.getDocument()},resetState:function(a){if(a){var b=this.getStateContainersForNode(a);a=this.getFocus(a.ownerDocument.body);for(var c=0;c<b.length;c++){var e=b[c],d=this.getState(e);this.setState(d,e,
{focus:a&&e==a.stateContainerNode&&d==a.state,updateWhenCurrent:!0,silent:!1})}}},_updateSrcState:function(a,b){var c=a&&a._dvWidget;if(c){var e=c._srcElement.getAttribute(davinci.states.APPSTATES_ATTRIBUTE),d=c._srcElement.getAttribute(davinci.states.DELTAS_ATTRIBUTE);if(c&&c._srcElement){var f=this.serialize(a);f.maqAppStates&&f.maqAppStates.trim();f.maqAppStates?c._srcElement.addAttribute(davinci.states.APPSTATES_ATTRIBUTE,f.maqAppStates):c._srcElement.removeAttribute(davinci.states.APPSTATES_ATTRIBUTE);
f.maqDeltas&&f.maqDeltas.trim();f.maqDeltas?c._srcElement.addAttribute(davinci.states.DELTAS_ATTRIBUTE,f.maqDeltas):c._srcElement.removeAttribute(davinci.states.DELTAS_ATTRIBUTE);f=c._srcElement.getAttribute(davinci.states.APPSTATES_ATTRIBUTE);c=c._srcElement.getAttribute(davinci.states.DELTAS_ATTRIBUTE);if(e!==f||d!==c)(e=this.getEditor())&&e._visualChanged&&e._visualChanged(b)}}},_removeStateFromNodeRecursive:function(a,b){var c=a._dvWidget;if(a&&c&&b){this._removeStateFromNode(a,b);for(var c=c.getChildren(),
e=0;e<c.length;e++)this._removeStateFromNodeRecursive(c[e].domNode,b)}},_removeStateFromNode:function(a,b){if(a&&a._maqDeltas&&a._maqDeltas[b]){delete a._maqDeltas[b];var c=!1,e;for(e in a._maqDeltas)if("undefined"!==e){c=!0;break}c||delete a._maqDeltas;this._updateSrcState(a)}},removeUnusedStates:function(a){if(a){a=a.getAllWidgets();for(var b=0;b<a.length;b++){var c=a[b].domNode;if("BODY"!==c.tagName&&c&&c._maqDeltas){var e=this.getAllStatesForNode(c),d;for(d in c._maqDeltas)"undefined"!==d&&0>
e.indexOf(d)&&this._removeStateFromNode(c,d)}}}},_getStateIndex:function(a){return!a||"Normal"==a||"undefined"==a?"undefined":a},getCurrentStateIndex:function(){return this._getStateIndex(this.getState())},getApplyToStateIndex:function(a){var b=this.getState();return this._getStateIndex("current"===a&&b&&"Normal"!=b&&"undefined"!=b?b:void 0)},getEffectiveDisplayValue:function(a,b,c,e){a=b?b.domNode:null;b="none";var d=c||"undefined";if(e&&"string"==typeof e[d]&&"$MAQ_DELETE_PROPERTY$"!=e[d])b=e[d];
else if(a){var f=!1;if(a._maqDeltas&&!(e&&"$MAQ_DELETE_PROPERTY$"==e[d])){var g=a._maqDeltas[c]&&a._maqDeltas[c].style;if(g)for(c=0;c<g.length;c++){var h=g[c],l;for(l in h)"display"==l&&(b=h[l],f=!0)}}if(!f){if(e&&"string"==typeof e.undefined)b=e.undefined;else{e=a._maqDeltas&&a._maqDeltas.undefined&&a._maqDeltas.undefined.style;d=!1;if(e)for(c=0;c<e.length;c++)for(l in h=e[c],h)"display"==l&&(b=h[l],d=!0);d||(b=t.get(a,"display"))}d="undefined"}if(0==a.offsetLeft&&0==a.offsetTop&&0==a.offsetWidth&&
0==a.offsetHeight)b="none";else for(;a&&"BODY"!=a.tagName.toUpperCase();){if(a&&(a.ownerDocument&&a.ownerDocument.defaultView)&&"none"==t.get(a,"display")){b="none";break}a=a.parentNode}}else b="none";return{effectiveDisplayValue:b,effectiveState:d}},propertyDefinedForAnyCurrentState:function(a,b){var c,e=a._maqDeltas;if(e){var d=this.getStateContainersForNode(a),f=d.length-1;a:for(;0<=f;f--){var g=this.getState(d[f]),h=!g||g==this.NORMAL?"undefined":g;if(h=e[h]&&e[h].style)for(var l=0;l<h.length;l++)for(var k=
h[l],m=0;m<b.length;m++)if(k.hasOwnProperty(b[m])){c=g;break a}}}return c},_customStateActive:function(a){return!a?!1:this.getState(a.rootNode)},updateStateIcons:function(a){a&&(a.editor&&!(a.editor!=n.currentEditor||"davinci.ve.PageEditor"!=a.editor.declaredClass))&&u.withDoc(x,function(){var b=p(".manageStatesButton")[0],c=s.byNode(b),b=p(".manageStatesIcon")[0];c&&b&&(this.manageStatesActive(a)?(k.remove(b,"manageStatesIconDisabled"),c.set("disabled",!1)):(k.add(b,"manageStatesIconDisabled"),c.set("disabled",
!0)));var c=v.getPreferences("davinci.ve.editorPrefs",davinci.Workbench.getProject()).newWidgetsCurrentState,b=p(".newWidgetsCurrentStateButton")[0],e=s.byNode(b),b=p(".newWidgetsCurrentStateIcon")[0];e&&b&&(this.newWidgetsCurrentStateActive(a)?k.remove(b,"newWidgetsCurrentStateIconDisabled"):k.add(b,"newWidgetsCurrentStateIconDisabled"),c?(k.remove(b,"newWidgetsCurrentStateIconOff"),k.add(b,"newWidgetsCurrentStateIconOn"),e.set("title",w.NewWidgetsCurrentStateTitleCurrentState)):(k.remove(b,"newWidgetsCurrentStateIconOn"),
k.add(b,"newWidgetsCurrentStateIconOff"),e.set("title",w.NewWidgetsCurrentStateTitleBackground)))}.bind(this))},manageStatesActive:function(a){return a&&a.getSelection().length},newWidgetsCurrentStateActive:function(a){return this._customStateActive(a)},highlightBaseWidgetsActive:function(a){return this._customStateActive(a)},updateHighlightsBaseStateWidgets:function(a){setTimeout(function(){!a||!a.editor||a.editor!=n.currentEditor||"davinci.ve.PageEditor"!=a.editor.declaredClass?console.error("states : invalid editor!"):
u.withDoc(x,function(){var b=v.getPreferences("davinci.ve.editorPrefs",davinci.Workbench.getProject()).highlightBaseWidgets,c=this.highlightBaseWidgetsActive(a),e=p(".highlightBaseWidgetsButton")[0];if(e){var e=s.byNode(e),d=p(".highlightBaseWidgetsIcon")[0];e&&d&&(c?k.remove(d,"highlightBaseWidgetsIconDisabled"):k.add(d,"highlightBaseWidgetsIconDisabled"),b?(k.add(d,"highlightBaseWidgetsIconOn"),k.remove(d,"highlightBaseWidgetsIconOff")):(k.add(d,"highlightBaseWidgetsIconOff"),k.remove(d,"highlightBaseWidgetsIconOn")))}e=
this.getState(a.rootNode);if(c=dojo.byId("focusContainer")){for(var f=p(".maqBaseStateShiningThrough",c),g=0;g<f.length;g++)d=f[g],d.parentNode.removeChild(d);if(e&&b){d=a.getAllWidgets();b=[];for(g=0;g<d.length;g++)if(f=d[g],!f.domNode||!(f.domNode.tagName&&"BODY"==f.domNode.tagName.toUpperCase())){var h=this.getEffectiveDisplayValue(a,f,e),l=h.effectiveState;"none"!=h.effectiveDisplayValue&&"undefined"==l&&b.push(f)}for(var e=a.getDocument(),d=q.getBorderBoxPageCoords(c),g=a.getParentIframe(),f=
q.getBorderBoxPageCoords(g),g=f.l-d.l,f=f.t-d.t,d=e.body,h=q.getScrollLeft(d),l=q.getScrollTop(d),n=0;n<b.length;n++)if(d=b[n].domNode){var m=q.getBorderBoxPageCoords(d);m.l+=g-h;m.t+=f-l;d=e.createElement("div");d.className="maqBaseStateShiningThrough";d.style.left=m.l+"px";d.style.top=m.t+"px";d.style.width=m.w+"px";d.style.height=m.h+"px";c.appendChild(d)}}}}.bind(this))}.bind(this),10)},initialize:function(){this.subscribed=!0}});davinci.ve.states=new r;davinci.ve.states.initialize();return davinci.ve.states});
//# sourceMappingURL=States.js.map