//>>built
require({cache:{"url:davinci/ve/template.html":'\x3c!DOCTYPE html\x3e\n\x3chtml\x3e\n\x3chead\x3e\n\x3cmeta charset\x3d"utf-8" /\x3e\n\x3cmeta http-equiv\x3d"X-UA-Compatible" content\x3d"IE\x3dedge" /\x3e\n\x3ctitle\x3eUntitled\x3c/title\x3e\n\x3c/head\x3e\n\x3cbody\x3e\n\x3c/body\x3e\n\x3c/html\x3e\n'}});
define("davinci/ve/VisualEditor","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/dom-class dojo/dom-construct dojo/promise/all dojo/text!./template.html ../Runtime ../Workbench ../model/Path ./metadata ./Context preview/silhouetteiframe preview/loadIndicator ../workbench/Preferences ./widget ../XPathUtils ../html/HtmlFileXPathAdapter ./utils/GeomUtils".split(" "),function(m,x,y,n,f,k,p,g,e,q,r,s,t,u,z,h,v,w,l){return m("davinci.ve.VisualEditor",null,{deviceName:"none",_orientation:"portrait",
_subscriptions:[],constructor:function(a,b){this._pageEditor=b;this.contentPane=dijit.getEnclosingWidget(a);this.loadingDiv=f.create("div",{className:"loading",innerHTML:dojo.replace("\x3ctable\x3e\x3ctr\x3e\x3ctd\x3e\x3cspan\x3e\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;\x3c/span\x3e\x26nbsp;{0}\x3c/td\x3e\x3c/tr\x3e\x3c/table\x3e",["Loading..."])},this.contentPane.domNode.parentNode,"first");n.add(this.contentPane.domNode,"fullPane");var c=f.create("div",{className:"silhouette_div_container"},
this.contentPane.domNode);f.create("span",{className:"silhouetteiframe_object_container"},c);this.silhouetteiframe=new t({rootNode:c,margin:20});var d=this;this.contentPane.connect(this.contentPane,"resize",function(a){var b=dojo.query(".designCP iframe",this._pageEditor.domNode)[0];b&&(b.contentDocument&&b.contentDocument.body)&&(d._resizeBody(b.contentDocument.body,a),setTimeout(function(){var a=d.getContext();a.clearCachedWidgetBounds();a.updateFocusAll();d._registerScrollHandlers()},100))}.bind(this));
this._pageEditor.deferreds=k(r.getDeferreds());this._subscriptions.push(dojo.subscribe("/davinci/ui/editorSelected",this._editorSelected.bind(this)));this._subscriptions.push(dojo.subscribe("/davinci/ui/context/loaded",this._contextLoaded.bind(this)))},getDevice:function(){return this.deviceName},setDevice:function(a,b){this.deviceName=a;var c=this.getContext();c.setMobileMeta(a);b||c.setMobileTheme(a);this.silhouetteiframe.setSVGFilename("none"==a?null:"app/preview/images/"+a+".svg");c.clearCachedWidgetBounds();
dojo.publish("/davinci/ui/deviceChanged",[a]);dojo.publish("/davinci/ui/repositionFocusContainer",[])},toggleOrientation:function(){"none"!=this.deviceName&&this.setOrientation("landscape"==this._orientation?"portrait":"landscape");this.getContext().clearCachedWidgetBounds()},getOrientation:function(a){return this._orientation},setOrientation:function(a){if("none"!=this.deviceName&&this._orientation!=a){this._orientation=a;a=e.getOpenEditor();a.editorContainer&&a.editorContainer.updateToolbars&&a.editorContainer.updateToolbars();
var b=this.getContext();b.setMobileOrientation(this._orientation);this.silhouetteiframe.setOrientation(this._orientation);a._visualChanged();setTimeout(function(){b.clearCachedWidgetBounds();b.updateFocusAll()},100)}},_objectPropertiesChange:function(a){if(this.isActiveEditor()){var b=this.getContext(),c=a.command;b.getCommandStack().execute(a.compoundCommand||c);c._newId?(a=h.byId(c._newId,b.getDocument()),b.select(a)):(c=b.getSelection(),a=c.length?c[c.length-1]:void 0,1<c.length&&b.select(a));
this._srcChanged()}},isActiveEditor:function(){var a=g.currentEditor;return a&&"davinci.ve.PageEditor"==a.declaredClass&&a.visualEditor==this},_stylePropertiesChange:function(a){if(this.isActiveEditor()){var b=this.getContext().getCommandForStyleChange(a);b&&(this.getContext().getCommandStack().execute(b),b._newId&&(b=h.byId(b._newId,context.getDocument()),this.context.select(b)),this._srcChanged(),dojo.publish("/davinci/ui/widgetValuesChanged",[a]))}},_srcChanged:function(){this.isDirty=!0},getContext:function(){return this.context},
getTemplate:function(){return p},destroy:function(){this._handles&&(this._focusPopup&&this._focusPopup.destroyRecursive(),delete this._focusPopup,this.context.destroy(),this._handles.forEach(dojo.disconnect),this._iframeScrollHandler&&(dojo.disconnect(this._iframeScrollHandler),delete this._iframeScrollHandler),this._designCPScrollHandler&&(dojo.disconnect(this._designCPScrollHandler),delete this._designCPScrollHandler),this._subscriptions.forEach(dojo.unsubscribe),this._subscriptions=[])},setContent:function(a,
b,c){this._onloadMessages=[];this._setContent(a,b,c)},saveAs:function(a,b,c){this._setContent(a,c)},_setContent:function(a,b,c){this._setContentRaw(a,b,c)},_setContentRaw:function(a,b,c){this.fileName=a;this.basePath=new q(a);if(this.initialSet)this.context.setSource(b,this.context._restoreStates,this.context);else{var d=g.getUserWorkspaceUrl();0==a.indexOf("./")&&(a=a.substring(2,a.length));a=d+a;a=d;this._handles=[];d=dojo.query(".silhouette_div_container",this.contentPane.domNode)[0];this.context=
new s({editor:this._pageEditor,visualEditor:this,containerNode:d,model:b,baseURL:a,iframeattrs:{"class":"silhouetteiframe_iframe"}});this.context._commandStack=this._commandStack;this._commandStack._context=this.context;try{this._handles.push(dojo.connect(this.context,"activate",this,this.update))}catch(e){debugger}this._handles.push(dojo.connect(this.context,"onContentChange",this,this.onContentChange));this._handles.push(dojo.connect(this.context,"onSelectionChange",this,this.onContentChange));
this.title=dojo.doc.title;this.context._setSource(b,this._connectCallback,this,c);this.context.getFlowLayout();this.initialSet=!0}},_connectCallback:function(a){try{if(a instanceof Error)throw a;var b=this.context,c;this.savePoint=0;try{b.activate()}catch(d){console.error("crash in context activation! : "+d)}c=e.createPopup({partID:"davinci.ve.visualEditor",domNode:b.getContainerNode(),keysDomNode:b.getDocument(),context:b});if(!b.getDocument().createElement)debugger;c&&(c.adjustPosition=function(a){var c=
dojo.position(b.frameNode);dojo.withDoc(b.getDocument(),function(){var a=dojo.docScroll();c.x-=a.x;c.y-=a.y});return c});this._focusPopup=e.createPopup({partID:"davinci.ve.visualEditor",domNode:b.getFocusContainer(),keysDomNode:b.getDocument(),context:b});b.getTopWidgets().forEach(function(a){a.resize&&a.resize()});b.anyDojoxMobileWidgets=void 0;dojo.publish("/davinci/ui/context/pagebuilt",[b])}catch(f){a=f}finally{a.errorMessage?this.loadingDiv.innerHTML=a.errorMessage||"(unknown)":a instanceof Error?
(this.loadingDiv.parentNode&&this.loadingDiv.parentNode.removeChild(this.loadingDiv),delete this.loadingDiv,console.error("error! ",a),dojo.publish("/davinci/ui/context/pagebuilt",[b])):(this.loadingDiv.parentNode&&this.loadingDiv.parentNode.removeChild(this.loadingDiv),delete this.loadingDiv)}},getSelectedWidget:function(){var a=this.getContext(),b=a.getSelection(),c=b.length?b[b.length-1]:void 0;1<b.length&&a.select(c);return c},getSelectedSubWidget:function(){return this._selectedSubWidget},save:function(a){if(this.context){var b=
[],c=this.context.getModel();c.getText();c.setDirty(!0);c.visit({visit:function(c){("HTMLFile"==c.elementType||"CSSFile"==c.elementType)&&c.isDirty()&&b.push(c.save(a));return!1}});b=b.concat(this.getContext().saveDynamicCssFiles(this.context.cssFiles,a));b.length?this.savePromise=k(b):delete this.savePromise;return this.savePromise}},removeWorkingCopy:function(){},getDefaultContent:function(){return this.getTemplate()},previewInBrowser:function(){var a=this.deviceName,b=e.getOpenEditor().resourceFile.getURL(),
c=[];"none"!=a&&(c=["preview\x3d1","device\x3d"+encodeURIComponent(a),"file\x3d"+encodeURIComponent(b)],b=e.location(),b+="/maqetta/preview.html?","landscape"==this._orientation&&c.push("orientation\x3d"+this._orientation));this.context.getPreference("zazl")&&c.push("zazl\x3dtrue");c.length&&(b+="?"+c.join("\x26"));a=function(){var a=window.open(b,"preview_"+b);u(a,g.location()+require.toUrl("dojox/image/resources/images/loading.gif"),"gray")};this.savePromise?this.savePromise.then(a):a()},refresh:function(){var a=
this.context,b=v.getXPath(a.getSelection()[0]._srcElement,w);a.setSource(a.model);var b=a.model.evaluate(b).getAttribute("id"),c=h.byId(b,a.getDocument());setTimeout(function(){a.select(c)},0)},_contextLoaded:function(a){a==this.getContext()&&this._registerScrollHandlers()},_editorSelected:function(a){var b=this.getContext(),b=b?b.getFocusContainer():null;a.oldEditor==this._pageEditor&&b&&this._focusPopup&&this._focusPopup.unBindDomNode(b);a.editor==this._pageEditor&&(this._registerScrollHandlers(),
b&&this._focusPopup&&this._focusPopup.bindDomNode(b));if(b=document.getElementById("visualEditorBorder"))b.style.display=!a.editor||"davinci.ve.PageEditor"!=a.editor.declaredClass?"none":"block"},_resizeBody:function(a,b){var c=l.getScrollLeft(a),d=l.getScrollTop(a);a.style.width=0<c?b.w+c+"px":"100%";a.style.height=0<d?b.h+d+"px":"100%"},_scrollHandler:function(a){if((a=dojo.query(".designCP iframe",this._pageEditor.domNode)[0])&&a.contentDocument&&a.contentDocument.body)this._resizeBody(a.contentDocument.body,
{w:dojo.style(this.contentPane.domNode,"width"),h:dojo.style(this.contentPane.domNode,"height")}),setTimeout(function(){var a=this.getContext();a.clearCachedWidgetBounds();a.updateFocusAll()}.bind(this),100)},_registerScrollHandlers:function(){if(!this._iframeScrollHandler){var a=dojo.query(".designCP iframe",this._pageEditor.domNode)[0];a&&(a.contentDocument&&a.contentDocument.body)&&(this._iframeScrollHandler=dojo.connect(a.contentDocument.body.ownerDocument,"onscroll",this,this._scrollHandler))}if(!this._designCPScrollHandler&&
(a=dojo.query(".designCP",this._pageEditor.domNode)[0]))this._designCPScrollHandler=dojo.connect(a,"onscroll",this,this._scrollHandler)}})});
//# sourceMappingURL=VisualEditor.js.map