//>>built
define("davinci/ve/VisualEditorOutline","dojo/_base/declare dojo/_base/connect ./commands/ReparentCommand ./commands/StyleCommand ./widget ./States dijit/tree/dndSource ../Runtime".split(" "),function(h,f,m,n,g,k,q,l){var p=h(null,{toggleMode:!0,betweenThreshold:4,showRoot:!0,dndController:"dijit.tree.dndSource",constructor:function(a){this._context=a;this._handles=[];this._connect("activate","_rebuild");this._connect("widgetChanged","_widgetChanged")},getRoot:function(a,b){a(this._context.rootWidget||
{id:"myapp",label:"application"})},getLabel:function(a){if("myapp"==a.id)return this._context.model.fileName;a=this._getWidget(a);if(a.isWidget)return label=g.getLabel(a);var b=a.type;if(b){var c=this.useRichTextLabel?"\x26lt;":"\x3c",d=this.useRichTextLabel?"\x26gt;":"\x3e";label=0===b.indexOf("html.")?c+b.substring(5)+d:0===b.indexOf("OpenAjax.")?c+b.substring(9)+d:0<b.indexOf(".")?b.substring(b.lastIndexOf(".")+1):a.label||b;if(a=g.byId(a.id,this._context.getDocument()))(a=a.getId())&&(label+=
" id\x3d"+a);return label}},_getChildren:function(a){this._context.rootWidget||console.error("editor context has no root widget yet!");return!this._context.rootWidget||"state"==a.type||"html.stickynote"==a.type||"html.richtext"==a.type?[]:("myapp"==a.id||a===this._context.rootNode?this._context.getTopWidgets():this._getWidget(a).getChildren()).filter(function(a){return a&&a.getContext&&a.getContext()&&!a.internal&&a._srcElement}).map(this._buildItem)},mayHaveChildren:function(a){return(a=this._getWidget(a))&&
a.type&&0===a.type.indexOf("OpenAjax.")?!1:0<this._getChildren(a).length},getIdentity:function(a){return a.id},getChildren:function(a,b,c){b(this._getChildren(a))},put:function(a,b){var c=this._getWidget(a),d=c.getParent();this.onChildrenChange(d,this._getChildren(d));return this.getIdentity(c)},add:function(a,b){(b=b||{}).overwrite=!1;return this.put(a,b)},remove:function(a){this.onDelete(a)},newItem:function(a,b){},pasteItem:function(a,b,c,d,e,f){a&&(c&&b)&&(c="myapp"==c.id?this._context.rootWidget:
this._getWidget(c),b="myapp"==b.id?this._context.rootWidget:this._getWidget(b),a=this._getWidget(a),b==c&&!d&&dojo.indexOf(b.getChildren(),a)<e&&e++,a=new m(a,c,e),this._context.getCommandStack().execute(a))},checkItemAcceptance:function(a,b,c){switch(c){case "before":case "after":return!0;default:return a=dijit.getEnclosingWidget(a).item,a=this.tree.model._getWidget(a),a.getContainerNode&&a.getContainerNode()||"myapp"==a.id}},onChildrenChange:function(a,b){},_rebuild:function(){if(!this._skipRefresh){var a=
this._context.rootNode;if(a)this.onChildrenChange(this._buildItem(a),this._getChildren(a))}},_widgetChanged:function(a,b,c){try{a===this._context.WIDGET_ADDED?this.add(b):a===this._context.WIDGET_REMOVED?this.remove(b):a===this._context.WIDGET_MODIFIED?(this.onChange(b),this.onChildrenChange(b,this._getChildren(b))):a===this._context.WIDGET_REPARENTED?(this.remove(b),this.put(b,{overwrite:!0,parent:c[1]})):a===this._context.WIDGET_ID_CHANGED&&(this.remove({id:c}),this.add(b))}catch(d){console.error("VisualEditorOutline._widgetChanged: e \x3d "+
d)}},toggle:function(a,b,c){a=this._getWidget(a);var d=a.getHelper(),e=!0;d&&d.onToggleVisibility&&(e=d.onToggleVisibility(a,b));return e?(this._toggle(a,b,c),!0):!1},_toggle:function(a,b,c){b=!b?"":"none";var d;if(c=k.getFocus(a.domNode.ownerDocument.body))d=c.state;else{c=k.getStatesListCurrent(a.domNode);for(var e=0;e<c.length;e++)if(c[e]){d=c[e];break}}a=new n(a,[{display:b}],d);this._context.getCommandStack().execute(a)},shouldShowElement:function(a,b){return"toggleNode"==a?"states"!=b.type&&
"myapp"!=b.id:!0},_getToggledItemsAttr:function(){var a=[],b;for(b in this.toggledItems)a.push(b);return a},isToggleOn:function(a){a=this._getWidget(a);var b=a.getHelper();return b&&b.isToggleOn?b.isToggleOn(a):"none"===a.domNode.style.display},_getWidget:function(a){return g.byId(a.id)},_buildItem:function(a){if(a)return{id:a.id,type:a.type}},_connect:function(a,b){this._handles.push(f.connect(this._context,a,this,b))},destroy:function(){this._handles.forEach(f.disconnect)}});return h("davinci.ve.VisualEditorOutline",
null,{toolbarID:"davinci.ve.outline",_outlineMode:"design",constructor:function(a){this._editor=a;this._context=a.visualEditor.context;this._handles=[];this._connect("onSelectionChange","onSelectionChange");this._connect("deselect","deselect");this._widgetModel=new p(this._context);f.subscribe("/maqetta/appstates/state/changed/end",this,function(a){if("davinci.themeEditor.ThemeEditor"!==("undefined"!==typeof davinci&&l.currentEditor&&l.currentEditor.declaredClass)&&this._tree&&(a=a&&a.node&&a.node._dvWidget))for(a=
a.getChildren();a.length;){var c=a.shift();c&&(this._tree.toggleNode(c,"none"===c.domNode.style.display),a=a.concat(c.getChildren()))}})},getActionsID:function(){if("design"===this._outlineMode)return"davinci.ve.VisualEditorOutline"},_connect:function(a,b){this._handles.push(f.connect(this._context,a,this,b))},switchDisplayMode:function(a){this._outlineMode=a;this._outlineView.createTree()},getModel:function(){switch(this._outlineMode){case "design":this._model=this._widgetModel;break;case "source":this._model=
this._srcModel}return this._model},getSelectedItem:function(){return this._tree&&this._tree._getSelectedItemAttr()},onSelectionChange:function(a,b){"design"==this._outlineMode&&(a=a||this._context.getSelection())&&this._tree.selectNode(a,b)},deselect:function(){this._tree.deselectAll()},getIconClass:function(a,b){if("design"===this._outlineMode){var c=a.type;return c?"davinciOutlineTreeIcon davinci_"+c.replace(/\./g,"_"):b?"dijitFolderOpened":"dijitFolderClosed"}}})});
//# sourceMappingURL=VisualEditorOutline.js.map