//>>built
define("davinci/ve/widget","davinci/html/HTMLElement ../Runtime ./metadata dojo/Deferred ./DijitWidget ./GenericWidget ./HTMLWidget ./ObjectWidget dojo/window".split(" "),function(s,n,q,z,t,u,v,w,r){var x={},y=function(a,b,c){for(var d=0;d<c.children.length;d++){var f=b.childNodes[d],e=c.children[d];f&&1==f.nodeType&&"HTMLElement"==e.elementType&&(f.id=a.getUniqueID(e),y(a,f,e))}},m={_dojo:function(a){a=(a=a?a.ownerDocument||a:dojo.doc)||dojo.doc;return r.get(a).dojo||dojo},_dijit:function(a){return r.get(a?
a.ownerDocument||a:dojo.doc).dijit||dijit},parseStyleValues:function(a){var b=[];a&&dojo.forEach(a.split(";"),function(a){var d=a.indexOf(":");if(0<d){var f=a.substring(0,d).trim();a=a.substring(d+1).trim();d={};d[f]=a;b.push(d)}});return b},retrieveStyleProperty:function(a,b,c){var d=c;a&&dojo.some(a,function(a){if(a.hasOwnProperty(b))return d=a[b],!0});return d},setStyleProperty:function(a,b,c){var d=!1;a&&dojo.some(a,function(a){if(a.hasOwnProperty(b))return a[b]=c,d=!0});if(!d){var f={};f[b]=
c;a.push(f)}},getStyleString:function(a){var b="";dojo.forEach(a,function(a){for(var d in a)a[d]&&(b=b+d+":"+a[d]+";")});return b},getEnclosingWidget:function(a){var b=m.getEnclosingWidgetForRichText(a);if(b)return b;for(;a;){if(a._dvWidget)return a._dvWidget;a=a.parentNode||a.domNode&&a.domNode.parentNode}},getEnclosingWidgetForRichText:function(a){if(a&&a._dvWidget)return"html.stickynote"===a._dvWidget.type||"html.richtext"===a._dvWidget.type?a._dvWidget:a.parentNode?m.getEnclosingWidgetForRichText(a.parentNode):
null},getUniqueObjectId:function(a,b){if(a){for(var c=a.substring((a.lastIndexOf("/")||a.lastIndexOf("."))+1),d=1,f=c+"_"+d++,e=m._dojo(b);e.getObject(f)||e.byId(f);)f=c+"_"+d++;return f}},_remove_prefix:function(a){for(var b=a,c="dijit/form/ dijit/layout/ dijit/ dojox/mobile/ html. html/ OpenAjax. OpenAjax/".split(" "),d=0;d<c.length;d++)if(0==a.indexOf(c[d])){b=a.substr(c[d].length);"html."==c[d]&&(b="\x26lt;"+b+"\x26gt;");break}return b},_getWidgetNameText:function(a){a="\x3cspan class\x3d'propertiesTitleWidgetName'\x3e"+
this._remove_prefix(a);return a+"\x3c/span\x3e "},_getWidgetClassText:function(a,b){var c="\x3cspan class\x3d'propertiesTitleClassName'\x3e";a&&(c+="#"+a);b&&(c+="."+b.replace(/\s+/g,"."));return c+"\x3c/span\x3e "},getLabelForNode:function(a){var b=a.getAttribute("data-dojo-type")||a.getAttribute("dojoType");b||(b=a.tagName.toLowerCase());b=b.replace(/\./g,"/");b=this._getWidgetNameText(b);a.id&&(b+=this._getWidgetClassText(a.id));return b},getLabel:function(a){var b=this._getWidgetNameText(a.type),
c,d=m.getWidgetHelper(a.type);d&&d.getWidgetText&&(c=d.getWidgetText(a));var f=a.domNode;switch(a.type.replace(/\//g,".")){case "dijit.form.ComboBox":case "dijit.form.Button":c=a.attr("label");break;case "dijit.layout.ContentPane":c=a.attr("title");break;case "html.label":c=f.innerHTML;break;case "html.img":c=f.alt,c||(c=f.title)}c&&(b+="\x3cspan class\x3d'propertiesTitleWidgetText'\x3e"+c+"\x3c/span\x3e ");d&&d.getWidgetDescriptor&&(b+=" \x3cspan class\x3d'propertiesTitleWidgetDescriptor'\x3e"+d.getWidgetDescriptor(a)+
"\x3c/span\x3e ");var e=a._srcElement;c=a.getId();e=(e=e&&e.getAttribute("class"))&&e.trim();if(c||e)b+=this._getWidgetClassText(c,e);d&&d.getWidgetTextExtra&&(b+=d.getWidgetTextExtra(a));"html.img"==a.type&&(b+="\x3cspan\x3e"+f.src.substr(f.src.lastIndexOf("/")+1)+"\x3c/span\x3e");return b},byId:function(a,b){var c=dojo.byId(a,b&&b.body?b:void 0);if(c){if(c._dvWidget)return c._dvWidget;c=m.getEnclosingWidget(c);if(c.id==a)return c}if(n.currentEditor&&n.currentEditor.currentEditor&&n.currentEditor.currentEditor.context)return n.currentEditor.currentEditor.context.widgetHash[a]},
byNode:function(a){if(a._dvWidget)return a._dvWidget},createWidget:function(a){if(a&&a.type){var b=dojo.mixin({},a);b.properties&&(b.properties=dojo.mixin({},a.properties));a=b.type;var c,d,f=q.query(a);if(f&&(b.properties&&("content"in b.properties&&!b.properties.content&&delete b.properties.content,b.properties.theme&&(d=b.properties.theme.themeName)),c=q.queryDescriptor(a,"widgetClass"),"object"==c?(c=w,f.attributes=f.attributes||{},f.attributes.dojoType=a):c="html"==c?v:"dijit"==c?t:u,c)){var e=
f.content.trim().replace(/\s+/g," ");r.get(dojo.doc);var k=r.get(dojo.doc).dojo._toDom(e);if(11===k.nodeType){for(var h=0,p=null,e=k.childNodes,n=0;n<e.length&&!(8!==e[n].nodeType&&(h++,p=e[n],1<h));n++);if(1<h){console.error("ERROR: complex widget content not supported");return}k=p}var l=new s(k.tagName.toLowerCase());if(k.hasAttributes()){e=k.attributes;for(h=e.length-1;0<=h;--h)l.addAttribute(e[h].name,e[h].value)}k.innerHTML&&l.addText(k.innerHTML);e=q.queryDescriptor(a,"requiresId");h=q.queryDescriptor(a,
"name");e=e&&h.match(/^[A-Za-z]\w*$/)?h:void 0;k.id=b.properties&&b.properties.id||b.context.getUniqueID(l,e);if(e=b.children)dojo.isString(e)?(k.innerHTML=e,k.nodeName.toLowerCase(),h=l._getAttribute("id"),l.addText(e),e=l.getText(b.context),l.children=[],l.setText(e),h&&l.addAttribute(h.name,h.value,h.noPersist),y(b.context,k,l)):dojo.forEach(e,function(a){if(a)if(dojo.isString(a))7<a.length&&"\x3c!--"==a.substring(0,4)&&"--\x3e"==a.substring(a.length-3)?(k.appendChild(dojo.doc.createComment(a.substring(4,
a.length-3))),l.addComment(a.substring(4,a.length-3))):(k.appendChild(dojo.doc.createTextNode(a)),l.addText(a));else if(a.context=b.context,a=m.createWidget(a))k.appendChild(a.domNode),l.addChild(a._srcElement)});(e=m.getWidgetHelper(a))&&e.preProcessData&&(b=e.preProcessData(b));var e={},h={},g;for(g in b.properties)p=b.properties[g],null!=p&&("on"!=g.substr(0,2).toLowerCase()&&!("a"==l.tag.toLowerCase()&&"href"==g.toLowerCase())?e[g]=p:h[g]=p);g=new c(e,k,a,f,l,a);g._srcElement=l;g.chart&&(b.properties&&
b.properties.theme)&&(g.chart.theme.themeName=d);b.scripts&&(g.scripts=b.scripts);b.context&&(g._edit_context=b.context);b.properties&&(g.setProperties(e),g.setProperties(h,!0));if(b.maqAppStates||b.maqDeltas)b.maqAppStates&&(g.domNode._maqAppStates=dojo.clone(b.maqAppStates)),b.maqDeltas&&(g.domNode._maqDeltas=dojo.clone(b.maqDeltas)),d=davinci.states.serialize(g.domNode),d.maqAppStates&&g._srcElement.addAttribute(davinci.states.APPSTATES_ATTRIBUTE,d.maqAppStates),d.maqDeltas&&g._srcElement.addAttribute(davinci.states.DELTAS_ATTRIBUTE,
d.maqDeltas);(e=m.getWidgetHelper(a))&&e.cleanSrcElement&&e.cleanSrcElement(g._srcElement);e&&e.postCreateWidget&&e.postCreateWidget(g);return g}}},_createSrcElement:function(a){var b=new s(a.tagName.toLowerCase());if(a.hasAttributes()){a=a.attributes;for(var c=a.length-1;0<=c;--c)b.addAttribute(a[c].name,a[c].value)}return b},getWidgetHelper:function(a){return x[a]},requireWidgetHelper:function(a){var b=new z;q.getHelper(a,"helper").then(function(c){c?b.resolve(x[a]=new c):b.resolve()});return b},
getWidget:function(a){if(a&&1==a.nodeType){var b=m.byNode(a);if(!b){if(a){for(var b={properties:{}},c=0;c<a.attributes.length;c++){var d=a.attributes[c];if(d.specified&&d.nodeValue){var f=d.nodeName.toLowerCase();if(!("id"==f||"widgetid"==f||"style"==f)&&"_"!=f.charAt(0)){if((d=d.nodeValue)&&"class"==f)if(d=d.replace("HtmlWidget","").trim(),!d)continue;b.properties[f]=d}}}"script"==a.tagName.toLowerCase()&&(b.children=a.innerHTML||void 0)}else b=void 0;c=a.getAttribute("dvwidget");if(a.hasAttribute("widgetid")||
a.hasAttribute("data-dojo-type")||a.hasAttribute("dojotype"))c=m._dijit(a).byNode(a),f=a.getAttribute("data-dojo-type")||a.getAttribute("dojotype"),b=c?new t(b,a,c,null,null,f):new w(b,a);else if(c)b=new u(b,a,c);else{if("svg"==a.nodeName)return;b=new v(b,a)}}return b}}};dojo.setObject("davinci.ve.widget",m);return m});
//# sourceMappingURL=widget.js.map