//>>built
define("davinci/workbench/EditorContainer","require dojo/_base/declare dojo/_base/connect ./_ToolbaredContainer ../Runtime ../ve/metadata ../ve/utils/GeomUtils dojo/Deferred dojo/i18n!./nls/workbench".split(" "),function(l,s,t,u,f,v,y,m,w){var q={},r={};return s(u,{constructor:function(a){},postCreate:function(){this.subscribe("/davinci/ui/editorSelected",function(a){a.editor==this.editor&&this.updateToolbars()});this.subscribe("/davinci/ui/widgetSelected",this.updateToolbars);this.subscribe("/davinci/workbench/ready",
this.updateToolbars)},layout:function(){this.titleBarDiv.style.display="none";this.toolbarDiv.style.display="none";this.inherited(arguments)},resize:function(){this.inherited(arguments);this.editor&&(this.editor.editor&&this.editor.editor.getTextView)&&this.editor.editor.getTextView().resize()},setEditor:function(a,c,b,n,k,e,h){var g=new m;this.editorExtension=a;l([a.editorClass],function(p){try{var d=this.editor=new p(this.containerNode,c,h),x=function(){d.setRootElement&&d.setRootElement(k);this.containerNode=
d.domNode||this.containerNode;"string"==typeof a.editorClassName&&dojo.addClass(this.domNode,a.editorClassName);d.editorID=a.id;d.isDirty=!d.isReadOnly&&this.isDirty;this._createToolbar(a.editorClass);b||(b=d.getDefaultContent(),d.isDirty=!d.isReadOnly&&n.isNew,d.lastModifiedTime=Date.now());b||(b="");d.resourceFile=n;d.fileName=c;if(davinci.Workbench._state.activeEditor==c)d.setContent(c,b,e),this._setupKeyboardHandler(d);else var p=dojo.subscribe("editors_container-selectChild",this,function(a){d==
a.editor&&(dojo.unsubscribe(p),d.setContent(c,b),this._setupKeyboardHandler(d))});d.editorContainer=this;this.setDirty(d.isDirty)}.bind(this);(d.deferreds||(new m).resolve()).then(function(){return!0===b?n.getContent().then(function(a){b=a}):(new m).resolve()}).then(function(){x();g.resolve(d)},function(a){g.reject(a)})}catch(f){g.reject(f)}}.bind(this));return g},setDirty:function(a){var c=this._getTitle();this.lastModifiedTime=Date.now();this.isDirty=a;l("../Workbench").editorTabs.setTitle(this,
c)},_getTitle:function(){return this.attr("title")},save:function(a){this.editor.save(a);this.setDirty(a)},_close:function(a,c){dojo.publish("/davinci/ui/EditorClosing",[{editor:a}]);var b=!0;c&&(a&&a.isDirty)&&((b=a.getOnUnloadWarningMessage())||(b=dojo.string.substitute(w.fileHasUnsavedChanges,[this._getTitle()])),b=confirm(b));b&&(this._isClosing=!0,a.removeWorkingCopy?a.removeWorkingCopy():a.getFileEditors?a.getFileEditors().forEach(function(a){a.isReadOnly||a.resourceFile.removeWorkingCopy()}):
a.resourceFile&&a.resourceFile.removeWorkingCopy());return b},onClose:function(){return this._close(this.editor,!this._skipDirtyCheck)},forceClose:function(a,c){this._close(a,c);var b=this.getParent();b&&(b.removeChild(this),this.destroyRecursive())},_getViewActions:function(){var a=this.editorExtension.id,c=[];f.getExtensions("davinci.editorActions",function(b){if(a==b.editorContribution.targetID)return c.push(b.editorContribution),!0});0==c.length&&f.getExtension("davinci.defaultEditorActions",
function(a){c.push(a.editorContribution);return!0});var b=v.getLibraryActions("davinci.editorActions",a),c=dojo.clone(c);0<c.length&&b.length&&dojo.forEach(b,function(a){var b=l("../Workbench");a.action&&b._loadActionClass(a);if(a.menu)for(var e=0;e<a.menu.length;e++){var h=a.menu[0];h.action&&b._loadActionClass(h)}c[0].actions.push(a)});return c},_getViewContext:function(){return this.editor},_setupKeyboardHandler:function(a){var c=function(a){this.keyBindings||(this.keyBindings=[]);this.keyBindings.push(a)}.bind(this);
this._getViewActions().forEach(function(a){a.actions.forEach(function(a){a.keyBinding&&c({keyBinding:a.keyBinding,action:a});a.menu&&a.menu.forEach(function(a){a.keyBinding&&c({keyBinding:a.keyBinding,action:a})},this)},this)},this);t.connect(a,"handleKeyEvent",this,"_handleKeyDown")},_handleKeyDown:function(a,c){!this._handleKey(a,c)&&!c&&f.handleKeyEvent(a)},_handleKey:function(a,c){if(!this.keyBindings)return!1;var b=this.keyBindings.some(function(b){if((!c||b.keyBinding.allowGlobal)&&f.isKeyEqualToEvent(b.keyBinding,
a))return l("../Workbench")._runAction(b.action,this.editor,b.action.id),!0},this);b&&dojo.stopEvent(a);return b},destroy:function(){this.inherited(arguments);this.editor&&this.editor.destroy();delete this.editor},_updateToolbar:function(a){function c(a,c){var b=!0;a&&a.action&&a.action[c]?b=a.action[c]():a&&a[c]&&(b=a[c]());return b}function b(a,b){c(b,"shouldShow")?dojo.removeClass(a.domNode,"maqHidden"):dojo.addClass(a.domNode,"maqHidden")}function f(a,b){var e=c(b,"isEnabled");a.set("disabled",
!e)}if(a&&this.editor&&this.editor.getContext&&this.editor.getContext()){a=a.getChildren();for(var k=0;k<a.length;k++){var e=a[k];b(e,e._maqAction);f(e,e._maqAction);c(e._maqAction,"updateStyling");if(e=e.dropDown)for(var e=e.getChildren(),h=0;h<e.length;h++){var g=e[h];b(g,g._maqAction);f(g,g._maqAction);c(g._maqAction,"updateStyling")}}}},updateToolbars:function(){if(this.editor==f.currentEditor){var a=this.getToolbarDiv();a&&(a.innerHTML="");var c=this.toolbarCreated(this.editorExtension.editorClass);
a&&(c&&c.domNode)&&a.appendChild(c.domNode);a=(a=dojo.query("#davinci_toolbar_container .dijitToolbar")[0])?dijit.byNode(a):null;this._updateToolbar(a)}},_createToolbar:function(a){!this.toolbarCreated(a)&&!q[a]&&(q[a]=!0,this.inherited(arguments))},getToolbarDiv:function(){return dojo.byId("davinci_toolbar_container")},toolbarCreated:function(a,c){1<arguments.length&&(r[a]=c);return r[a]}})});
//# sourceMappingURL=EditorContainer.js.map