//>>built
define("davinci/workbench/Explorer","dojo/_base/declare dojo/dom-class dojo/dom-construct davinci/workbench/ViewPart davinci/Workbench davinci/Runtime dijit/registry dijit/form/Button dijit/form/DropDownButton dijit/DropDownMenu dijit/MenuItem dijit/MenuSeparator dijit/Tree dojo/mouse system/resource davinci/ui/dnd/DragSource davinci/ui/Resource davinci/ui/widgets/TransformTreeMixin davinci/ui/widgets/ProjectToolbar davinci/ui/NewProjectTemplate davinci/ui/ManageProjectTemplates davinci/ui/Rename davinci/ui/Download davinci/ui/DownloadSelected davinci/ui/UserLibraries dojo/i18n!davinci/ve/nls/common dojo/i18n!davinci/ui/nls/ui".split(" "),
function(n,g,m,r,f,p,q,s,t,u,h,v,w,x,k,y,C,D,E,z,A,B,F,G,H,I,e){return n("davinci.workbench.Explorer",r,{toolbarID:"workbench.Explorer",getActionsID:function(){return"davinci.workbench.Explorer"},postCreate:function(){this.inherited(arguments);g.add(this.toolbarDiv,"ExplorerToolbar");var b=p.getExtensions("davinci.dnd",function(d){return dojo.some(d.parts,function(d){return"davinci.ui.navigator"==d})&&d.dragSource}),c=system.resource,a=this.tree=new (n(w,{_createTreeNode:function(d){var a=this.inherited(arguments);
b&&d.item&&b.forEach(function(b){if(b.dragSource(d.item)){var c=new y(a.domNode,"component",a);c.targetShouldShowCaret=!0;c.returnCloneOnFailure=!1;require([b.dragHandler],function(a){c.dragHandler=new a(d.item);this.connect(c,"initDrag",function(a){c.dragHandler.initDrag&&c.dragHandler.initDrag(a)});this.connect(c,"onDragStart",function(a){c.dragHandler.dragStart(a)});this.connect(c,"onDragEnd",function(a){c.dragHandler.dragEnd(a)})}.bind(this))}},this);return a}}))({showRoot:!1,persist:!1,cookieName:"maqExplorer",
model:c,id:"resourceTree",labelAttr:"name",childrenAttrs:"children",getIconClass:davinci.ui.Resource.getResourceIcon,getRowClass:davinci.ui.Resource.getResourceClass,transforms:[system.resource.alphabeticalSort],isMultiSelect:!0});dojo.style(a.domNode,{width:"100%","overflow-x":"hidden",position:"absolute",bottom:0,top:"7px"});a.dndController.onMouseDown=dojo.hitch(null,function(d,b){if(x.isRight(b)){var c=dijit.getEnclosingWidget(b.target);-1===this.tree.get("selectedItems").indexOf(c.item)&&this.tree.set("selectedItems",
[c.item])}c=dojo.stopEvent;dojo.stopEvent=function(){};try{d.call(a.dndController,b)}finally{dojo.stopEvent=c}},a.dndController.onMouseDown);c=dojo.doc.createElement("div");c.appendChild(a.domNode);this.setContent(c);this.attachToolbar();a.startup();dojo.connect(a,"onDblClick",dojo.hitch(this,this._dblClick));a.watch("selectedItems",dojo.hitch(this,function(a,b,c){a=dojo.map(c,function(a){return{resource:a}});this._updateToolbarIcons(a);this.publish("/davinci/ui/selectionChanged",[a,this])}));f.createPopup({partID:"davinci.ui.navigator",
domNode:this.tree.domNode,openCallback:function(b){if((b=dijit.getEnclosingWidget(b.target))&&b.item){var c=a.get("selectedNodes");-1==dojo.indexOf(c,b)&&a.set("selectedNodes",[b])}}});(c=f.getActionSets("davinci.ui.navigator").clonedActionSets)&&dojo.forEach(c[0].actions,dojo.hitch(this,function(a){a.keyBinding&&(this.keyBindings||(this.keyBindings=[]),this.keyBindings.push({keyBinding:a.keyBinding,action:a}))}));dojo.connect(a.domNode,"onkeypress",this,"_onKeyPress")},attachToolbar:function(){this.inherited(arguments);
var b=dojo.doc.createElement("div");b.className="explorerHeaderProjectDiv";var c=dojo.doc.createElement("table");c.className="explorerHeaderProjectTable";b.appendChild(c);var a=dojo.doc.createElement("tr");c.appendChild(a);c=m.create("td",{"class":"explorerHeaderProjectCol0",innerHTML:e.projectColon});a.appendChild(c);var d=m.create("td",{"class":"explorerHeaderProjectCol1"});a.appendChild(d);c=m.create("td",{"class":"explorerHeaderProjectCol2"});a.appendChild(c);a=new davinci.ui.widgets.ProjectToolbar({});
d.appendChild(a.domNode);this.toolbarDiv.insertBefore(b,this.toolbarDiv.children[0]);dojo.connect(a,"onChange",function(){f.loadProject(this.value)});b=new s({"class":"ExplorerNewProjectButton",iconClass:"ExplorerNewProjectIcon",title:e.createProject,showLabel:!1,onClick:function(){require(["davinci/ui/Resource"],function(a){a.newProject()})}.bind(this)});c.appendChild(b.domNode);b=new u({style:"display: none;"});b.addChild(new h({id:"ExplorerCreateProject",label:e.createProjectMenuItem,iconClass:"",
onClick:function(){require(["davinci/ui/Resource"],function(a){a.newProject()})}.bind(this)}));b.addChild(new h({id:"ExplorerDeleteProject",label:e.deleteProjectMenuItem,iconClass:"",onClick:function(){this._deleteProject()}.bind(this)}));b.addChild(new h({id:"ExplorerRenameProject",label:e.renameProjectMenuItem,iconClass:"",onClick:function(){this._renameProject()}.bind(this)}));b.addChild(new v);b.addChild(new h({id:"ExplorerSaveAsProjectTemplate",label:e.saveAsProjectTemplateMenuItem,iconClass:"",
onClick:function(){var a=new z({});f.showModal(a,e.saveAsProjectTemplate,{width:"330px"},null,!0)}.bind(this)}));b.addChild(new h({id:"ExplorerManageProjectTemplates",label:e.manageProjectTemplatesMenuItem,iconClass:"",onClick:function(){var a=new A({});f.showModal(a,e.manageProjectTemplates,{},null,!0,function(){a.onShow.call(a)})}.bind(this)}));b=new t({"class":"ExplorerDropDownButton",iconClass:"ExplorerDropDownIcon",title:e.ProjectMenu,showLabel:!1,dropDown:b});c.appendChild(b.domNode)},_updateToolbarIcons:function(b){for(var c=
!1,a=0;a<b.length;a++){var d=b[a].resource;if(!d)return;d.readOnly()&&(c=!0)}a=document.querySelector(".FilesToolbarDeleteFile");a=q.byNode(a);d=document.querySelector(".FilesToolbarDeleteFileIcon");a&&d&&(c||0==b.length?(g.add(d,"FilesToolbarDeleteFileIconDisabled"),a.set("disabled",!0)):(g.remove(d,"FilesToolbarDeleteFileIconDisabled"),a.set("disabled",!1)));a=document.querySelector(".FilesToolbarRenameFile");a=q.byNode(a);d=document.querySelector(".FilesToolbarRenameFileIcon");a&&d&&(c||1!=b.length?
(g.add(d,"FilesToolbarRenameFileIconDisabled"),a.set("disabled",!0)):(g.remove(d,"FilesToolbarRenameFileIconDisabled"),a.set("disabled",!1)))},_deleteProject:function(){var b=null;k.listProjects(function(a){b=a.map(function(a){return a.name})}.bind(this));if(!b||2>b.length)alert(e.deleteOnlyProjectError);else{for(var c=null,a=f.getProject(),d=!1,l=0;l<b.length;l++)if(b[l]==a){if(d=!0,c)break}else if(c=b[l],d)break;d=dojo.string.substitute(e.areYouSureDeleteProject,[a]);d+="\n\n"+e.NoteOperationNotUndoable+
"\n";confirm(d)&&k.findResource(a).deleteResource().then(function(){f.loadProject(c)})}},_renameProject:function(){var b=f.getProject(),c=null;k.listProjects(function(a){c=a.map(function(a){return a.name})}.bind(this));var a=new B({value:b,invalid:c});f.showModal(a,e.renameProjectDialogTitle,{height:110,width:200},function(){if(!a.get("cancel")){var c=a.get("value");if(c==b)return;k.findResource(b).rename(c).then(function(){f.loadProject(c)})}return!0})},destroy:function(){this.inherited(arguments)},
_dblClick:function(b){"File"==b.elementType&&f.openEditor({fileName:b,content:b.getText(),isDirty:b.isDirty()})},_onKeyPress:function(b){var c=dojo.some(this.keyBindings,dojo.hitch(this,function(a){if(p.isKeyEqualToEvent(a.keyBinding,b))return davinci.Workbench._runAction(a.action),!0}));c&&dojo.stopEvent(b);return c}})});
//# sourceMappingURL=Explorer.js.map