//>>built
require({cache:{"url:davinci/workbench/templates/Preferences.html":"\x3cdiv style\x3d'width:100%; height: 100%'\x3e\n\t\x3cdiv class\x3d\"dijitDialogPaneContentArea\"\x3e\n\t\t\x3cdiv dojoType\x3d'dijit.layout.BorderContainer' dojoAttachPoint\x3d\"borderContainer\" style\x3d'width:100%; height: 100%' gutters\x3d'false' liveSplitters\x3d'true' id\x3d'preferencesContainer'\x3e\n\t\t\t\x3cdiv dojoType\x3d'dijit.layout.ContentPane' id\x3d'pref.TreePane' splitter\x3d'true' region\x3d'leading' style\x3d'width: 200px;' minSize\x3d'100' maxSize\x3d'300'\x3e\x3c/div\x3e\n\t\t\t\x3cdiv dojoType\x3d'dijit.layout.ContentPane' region\x3d'center' id\x3d'pref.RightPane'\x3e\x3c/div\x3e\n\t\t\x3c/div\x3e\n\t\x3c/div\x3e\n\t\x3cdiv class\x3d\"dijitDialogPaneActionBar\"\x3e\n\t\t\x3c!-- FIXME: we don't have logic to yet implement restoreDefaults() yet. See #627\n\t\t\x3cbutton dojoType\x3ddijit.form.Button type\x3d\"button\" onclick\x3d\"davinci.workbench.Preferences.restoreDefaults();\"\x3e\x3c/button\x3e--\x3e\n\t\t\x3cbutton dojoType\x3d\"dijit.form.Button\" type\x3d\"button\" onclick\x3d\"davinci.workbench.Preferences.save();\" class\x3d\"maqPrimaryButton\" type\x3d\"submit\"\x3e${commonStrings.buttonSave}\x3c/button\x3e\n\t\t\x3cbutton dojoType\x3d\"dijit.form.Button\" type\x3d\"button\" onclick\x3d\"davinci.workbench.Preferences.finish();\" class\x3d\"maqSecondaryButton\"\x3e${commonStrings.buttonCancel}\x3c/button\x3e\n\t\x3c/div\x3e\n\x3c/div\x3e\n\n\n"}});
define("davinci/workbench/Preferences","dojo/_base/declare dojo/_base/xhr dojo/_base/lang dojo/topic dojo/dom ../Runtime dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/registry davinci/ui/Dialog dijit/Tree dijit/tree/ForestStoreModel dojo/data/ItemFileReadStore dojo/i18n!./nls/workbench dojo/i18n!dijit/nls/common dojo/text!./templates/Preferences.html dijit/form/Button".split(" "),function(l,z,m,A,n,h,p,q,r,g,s,t,u,v,k,w,x){var y=l([p,q,r],{templateString:x,commonStrings:w,
resize:function(){this.borderContainer.resize()}}),c={_allPrefs:{},savePreferences:function(b,a,c){},_loadExtensions:function(){c._extensions||(c._extensions=h.getExtensions("davinci.preferences"))},showPreferencePage:function(){c._loadExtensions();var b=c.getPrefJson();if(b.items)for(var a=b.items.length-1;0<=a;a--){var d=b.items[a];d.hide&&b.items.splice(a,1)}if(!b||1>b.length)alert(k.noUserPref);else{this.dialog=s.showModal(new y({}),k.preferences,{width:650,height:350});var d=new v({data:b,jsId:"prefTreeDataStore"}),
a=new u({jsId:"fileModel",labelAttr:"name",store:d,rootId:"root"}),f=["root"];if(b=b.items){do d=b[0],f.push(d.id),b=d.children;while(b)}var e=g.byId("prefTree");e||(e=new t({model:a,id:"prefTree",persist:!1,query:"{type:'directory'}",label:"Preferences",labelAttr:"name",showRoot:!1,childrenAttrs:"children",openOnClick:!0,autoExpand:!0}));e.onClick=function(a){c.setPaneContent(a)};n.byId("pref.TreePane").appendChild(e.domNode);e.startup();e.onLoadDeferred.then(function(){e.set("paths",[f]).then(function(){e.focusNode(e.selectedNode);
c.setPaneContent(e.selectedItem)})})}},getPrefJson:function(){var b=c._extensions;if(!b)return[];for(var a=[],d=0;d<b.length;d++)b[d]._index=d,b[d].category?(a[b[d].category]||(a[b[d].category]=[]),a[b[d].category].push(b[d])):(a.root||(a.root=[]),a.root.push(b[d]));return{identifier:"id",items:a.root.map(function(b){return{id:b.id,name:b.name,hide:b.hide,index:b._index,children:c._getPrefJsonChildren(b.id,a)}})}},_getPrefJsonChildren:function(b,a){var d=a[b];if(!d)return[];for(var f=[],e=0;e<d.length;e++)f[e]=
{id:d[e].id,name:d[e].name,index:d[e]._index},a[d[e].id]&&(f[e].children=c._getPrefJsonChildren(d[e].id,a));return f},setPaneContent:function(b){var a;delete c._currentPane;var d=c._extensions[b.index[0]],f=c.getPreferences(d.id,davinci.Workbench.getProject());d.pane?require([d.pane],function(a){a=new a;c._currentPane=a;c._currentPane._extension=d;c._currentPane.setPreferences(f);g.byId("pref.RightPane").setContent(a.domNode)}):a=d.pageContent?document.createTextNode(d.pageContent):document.createTextNode("");
a&&g.byId("pref.RightPane").setContent(a)},_save:function(b){if(c._currentPane){var a=c._currentPane.getPreferences(),d=c._currentPane._extension.id,f=davinci.Workbench.getProject();c.savePreferences(d,f,a);c._currentPane.save&&c._currentPane.save(a)}for(a=0;a<b.length;a++){try{b[a].save&&b[a].save()}catch(e){}b[a].children&&0<b[a].children.length&&c._save(b[a].children)}},save:function(){c._save(c._extensions);c.finish()},finish:function(){c._extensions=null;c._currentPane=null;this.dialog.destroyRecursive(!1);
this.dialog=null},getPreferences:function(b,a){c._allPrefs[a]||(c._allPrefs[a]={});return{version:"1.7",specVersion:"0.8",snap:!0,helper:"maq-metadata-dojo/dojox/mobile/ThemeHelper",themeSets:[{_COMMENT_:"Defines site-specific default theme sets",desktopTheme:"claro",mobileTheme:[{device:"Android",theme:"android"},{device:"BlackBerry",theme:"blackberry"},{device:"iPad",theme:"ipad"},{device:"iPhone",theme:"iphone"},{device:"other",theme:"iphone"}],name:"site_dojo_default"}]}},getDefaultPreferences:function(b){c._loadExtensions();
for(var a=0;a<c._extensions.length;a++)if(c._extensions[a].id==b)return"string"===typeof c._extensions[a].defaultValues?h.serverJSONRequest({url:c._extensions[a].defaultValues,handleAs:"json",sync:!0}).defaultValues:c._extensions[a].defaultValues}};return m.setObject("davinci.workbench.Preferences",c)});
//# sourceMappingURL=Preferences.js.map