//>>built
define("davinci/review/view/CommentExplorerView","dojo/_base/declare davinci/Runtime davinci/review/model/ReviewTreeModel davinci/Workbench davinci/workbench/ViewPart dijit/Tree dojo/date/stamp dojo/date/locale davinci/review/actions/CloseVersionAction davinci/review/actions/EditVersionAction davinci/review/actions/OpenVersionAction dijit/Toolbar dijit/ToolbarSeparator dijit/form/Button dijit/form/TextBox dojo/i18n!./nls/view dojo/i18n!../widgets/nls/widgets davinci/ui/widgets/TransformTreeMixin".split(" "),
function(h,f,s,l,t,u,v,n,w,x,y,z,B,m,A,g,k){var q=function(a,c){if("ReviewVersion"==a.elementType){if(a.isDraft)return"draft-open";if(a.closed)return c?"reviewFolder-open-disabled":"reviewFolder-closed-disabled";if(!a.closed)return c?"reviewFolder-open":"reviewFolder-closed"}if("ReviewFile"==a.elementType){if(a.parent.closed)return"disabledReviewFileIcon";var b,d=a.getExtension(),e=f.getExtension("davinci.fileType",function(a){return a.extension==d});e&&(b=e.iconClass);return b||"dijitLeaf"}return"dijitLeaf"};
getLabelClass=function(a,c){var b="dijitTreeLabel";"ReviewVersion"==a.elementType&&(b=a.designerId==f.userName?"reviewOwnedByUserLabel":"reviewOwnedByOtherLabel");return b};var r=function(){return[function(a){return a.sort(function(a,b){return a.timeStamp>b.timeStamp?-1:a.timeStamp<b.timeStamp?1:0})}]};h=h(t,{postCreate:function(){this.inherited(arguments);var a=new s;this.model=a;var c=r();c.push(function(a){return a.filter(this.commentingFilter.filterItem,this)}.bind(this));this.tree=new u({id:"reviewCommentExplorerViewTree",
persist:!1,showRoot:!1,model:a,labelAttr:"name",childrenAttrs:"children",getIconClass:dojo.hitch(this,this._getIconClass),getLabelClass:dojo.hitch(this,this._getLabelClass),transforms:c,isMultiSelect:!0});this.setContent(this.tree);this.attachToolbar();this.tree.startup();dojo.connect(this.tree,"onDblClick",dojo.hitch(this,this._dblClick));dojo.connect(this.tree,"onClick",dojo.hitch(this,this._click));dojo.connect(this.tree,"_onNodeMouseEnter",dojo.hitch(this,this._over));dojo.connect(this.tree,"_onNodeMouseLeave",
dojo.hitch(this,this._leave));dojo.connect(this.tree,"_setSelectedNodesAttr",function(){this._publishSelectionChanges()}.bind(this));this.subscribe("/davinci/review/selectionChanged","_updateActionBar");this.subscribe("/davinci/review/resourceChanged",function(a,c,e){e&&e.timeStamp&&davinci.review.model.resource.root.findVersion(e.timeStamp).then(function(a){a?this.tree.set("selectedItem",a):this.tree.set("selectedItems",[]);this._publishSelectionChanges();this.tree.rootNode.expand()}.bind(this))});
l.createPopup({partID:"davinci.review.reviewNavigator",context:this,domNode:this.tree.domNode,openCallback:function(a){(a=dijit.getEnclosingWidget(a.target))&&a.item&&this.tree.set("path",this._buildTreePath(a.item))}.bind(this)});(a=l.getActionSets("davinci.review.reviewNavigator").clonedActionSets)&&1==a.length&&dojo.forEach(a[0].actions,dojo.hitch(this,function(a){a.keyBinding&&(this.keyBindings||(this.keyBindings=[]),this.keyBindings.push({keyBinding:a.keyBinding,action:a}))}));dojo.connect(this.tree.domNode,
"onkeypress",this,"_onKeyPress");this.infoCardContent=dojo.cache("davinci","review/widgets/templates/InfoCard.html",'\x3cdiv class\x3d"detail_title"\x3e${detail_title}\x3c/div\x3e\n\x3cdiv\x3e\n\t\x3cdiv class\x3d"detail_div"\x3e\x3cspan\x3e${your_role}:\x3c/span\x3e\x3cspan class\x3d"detail_role"\x3e${detail_role}\x3c/span\x3e\x3cspan\x3e${due_by}:\x3c/span\x3e\x3cspan class\x3d"${detail_dueDate_class}"\x3e${detail_dueDate}\x3c/span\x3e\x3c/div\x3e\n\t\x3cdiv class\x3d"detail_div"\x3e\x3cspan\x3e${created_by}:\x3c/span\x3e\x3cspan class\x3d"detail_creator"\x3e${detail_creator}\x3c/div\x3e\n\t\x3cdiv class\x3d"detail_div"\x3e\x3cspan\x3e${creation_date}:\x3c/span\x3e\x3cspan class\x3d"detail_creationDate"\x3e${detail_creationDate}\x3c/div\x3e\n\x3c/div\x3e\n\x3cdiv class\x3d"detail_div"\x3e\x3cstrong\x3e${artifacts_in_rev}\x3c/strong\x3e\x3c/div\x3e\n${detail_files}\n\x3cdiv class\x3d"detail_div"\x3e\x3cstrong\x3e${reviewers}\x3c/strong\x3e\x3c/div\x3e\n${detail_reviewers}');
dijit._masterTT||(dijit._masterTT=new dijit._MasterTooltip);this.connect(dijit._masterTT.domNode,"mouseover",function(){this._deleteDelTimer()});this.connect(dijit._masterTT.domNode,"mouseleave",function(){this._lastAnchorNode&&this._leave()});dojo.subscribe("/davinci/ui/editorSelected",function(a){if((a=a.editor)&&"davinci.review.CommentReviewEditor"===a.editorID){a=a.resourceFile;var c=a.parent;dojo.forEach(this.model.root.children,function(a){a!=c&&(a=this.tree.getNodesByItem(a),0<a.length&&(a=
a[0],a.isExpanded&&this.tree._collapseNode(a)))}.bind(this));this.tree.set("path",this._buildTreePath(a))}}.bind(this))},_buildTreePath:function(a){for(var c=[];a;a=a.parent)c.unshift(a);return c},_updateActionBar:function(a,c){if(c!=this||!a||!a.length)this.closeBtn.set("disabled",!0),this.editBtn.set("disabled",!0);else{var b="ReviewFile"==a[0].resource.elementType?a[0].resource.parent:a[0].resource;f.reviewers=b.reviewers||[];var d=b.designerId==f.userName,e="ReviewVersion"==b.elementType,p=b.isDraft;
this.closeBtn.set("disabled",!d||!e||b.closed||p);this.openBtn.set("disabled",!d||!e||!b.closedManual||p);this.editBtn.set("disabled",!d||!e)}},getTopAdditions:function(){var a=new z({},dojo.create("div")),c=new m({id:a.get("id")+".Close",showLabel:!1,label:g.closeVersion,disabled:!0,iconClass:"viewActionIcon closeVersionIcon",onClick:dojo.hitch(this,"_closeVersion")});this.closeBtn=c;var b=new m({id:a.get("id")+".Open",showLabel:!1,label:g.openVersion,disabled:!0,iconClass:"viewActionIcon openVersionIcon",
onClick:dojo.hitch(this,"_openVersion")});this.openBtn=b;var d=new m({id:a.get("id")+".Edit",showLabel:!1,label:g.editVersion,disabled:!0,iconClass:"viewActionIcon editVersionIcon",onClick:dojo.hitch(this,"_editVersion")});this.editBtn=d;var e=new A({id:"reviewExplorerFilter",placeHolder:g.filter,onKeyUp:dojo.hitch(this,this._filter)});a.addChild(c);a.addChild(b);a.addChild(new dijit.ToolbarSeparator);a.addChild(d);dojo.place(dojo.create("br"),a.domNode);a.addChild(e);dojo.addClass(a.domNode,"davinciCommentExplorer");
return a.domNode},_closeVersion:function(){(new w).run(this)},_openVersion:function(){(new y).run(this)},_editVersion:function(){(new x).run(this)},_filter:function(a){a=dijit.byId("reviewExplorerFilter").get("value");this.commentingFilter.filterString=a;dojo.forEach(this.model.root.children,dojo.hitch(this,function(a){a.getChildren(function(b){this.model.onChildrenChange(a,b)}.bind(this))}))},commentingFilter:{filterString:"",filterItem:function(a){var c=this.commentingFilter.filterString;return c?
"ReviewFile"==a.elementType?0<=a.name.toLowerCase().indexOf(c.toLowerCase()):!0:!0}},destroy:function(){this.inherited(arguments)},_dblClick:function(a){if(a.isDraft||a.parent.isDraft){if(a.designerId==f.userName||a.parent.designerId==f.userName)this._openPublishWizard(a.isDraft?a:a.parent)}else"ReviewFile"==a.elementType&&l.openEditor({fileName:a,content:a.getText()})},_click:function(a){this._publishSelectionChanges()},_publishSelectionChanges:function(){var a=this.getSelection();this.publish("/davinci/review/selectionChanged",
[a,this])},getSelection:function(){return dojo.map(this.tree.get("selectedItems"),function(a){return{resource:a}})},_over:function(a){if("ReviewVersion"==a.item.elementType&&!this._showTimer){var c=a.item,b={};b.detail_title=c.name;b.your_role=k.yourRole;b.due_by=k.dueBy;b.created_by=k.createdBy;b.creation_date=k.creationDate;b.artifacts_in_rev=k.artifactsInRev;b.reviewers=k.reviewers;b.detail_role=c.designerId==f.userName?g.designer:g.reviewer;b.detail_dueDate="infinite"==c.dueDate?g.infinite:n.format(c.dueDate,
{selector:"date",formatLength:"long"});var d=f.getUserDisplayNamePlusEmail({email:c.designerEmail,userDisplayName:c.designerDisplayName,userId:c.designerId});b.detail_creator=d;d=c.timeStamp.match(/^(\d{4})(\d{2})(\d{2})\T(\d{2})(\d{2})(\d{2})\Z$/);d=v.fromISOString(d?dojo.replace("{1}-{2}-{3}T{4}:{5}:{6}Z",d):c.timeStamp);b.detail_creationDate=n.format(d,{formatLength:"medium"});b.detail_files="";c.getChildren(function(d){dojo.forEach(d,function(a){a=a.getLabel();b.detail_files+="\x3cdiv\x3e\x3cspan\x3e"+
a.substr(0,a.length-4)+"\x3c/span\x3e\x3cspan class\x3d'dijitTreeIcon reviewFileIcon detail_file'\x3e\x3c/span\x3e\x3c/div\x3e"});b.detail_reviewers="";dojo.forEach(c.reviewers,function(a){if(a.email!=c.designerEmail){var d="\x3cdiv\x3e"+a.email+"\x3c/div\x3e";""!=a.displayName&&a.email!=a.displayName&&(d="\x3cdiv\x3e"+a.displayName+" \x26lt;"+a.email+"\x26gt;\x3c/div\x3e");b.detail_reviewers+=d}});c.closed?b.detail_dueDate_class="closed":b.detail_dueDate_class="notClosed";this._showTimer=setTimeout(dojo.hitch(this,
function(){this._deleteDelTimer();dijit.showTooltip(dojo.string.substitute(this.infoCardContent,b),a.rowNode);this._lastAnchorNode=a;delete this._showTimer;this._createDelTimer(15E3)}),1E3)}.bind(this))}},_leave:function(a){this._deleteDelTimer();this._showTimer&&(clearTimeout(this._showTimer),delete this._showTimer);this._lastAnchorNode&&this._createDelTimer(1E3)},_createDelTimer:function(a){this._delTimer=setTimeout(dojo.hitch(this,function(){this._hideTooltip();delete this._delTimer}),a)},_deleteDelTimer:function(){this._delTimer&&
(clearTimeout(this._delTimer),delete this._delTimer)},_hideTooltip:function(){this._lastAnchorNode&&(dijit.hideTooltip(this._lastAnchorNode.rowNode),this._lastAnchorNode=null)},_openPublishWizard:function(a){(new davinci.review.actions.PublishAction(a)).run()},_getIconClass:function(a,c){return q(a,c)},_getLabelClass:function(a,c){return getLabelClass(a,c)},_onKeyPress:function(a){var c=dojo.some(this.keyBindings,dojo.hitch(this,function(b){if(f.isKeyEqualToEvent(b.keyBinding,a))return davinci.Workbench._runAction(b.action,
this,b.action.id),!0}));c&&dojo.stopEvent(a);return c}});h.getIconClass=q;h.getLabelClass=getLabelClass;h.getSortTransforms=r;return h});
//# sourceMappingURL=CommentExplorerView.js.map