//>>built
define("davinci/review/view/CommentView","dojo/_base/declare davinci/Workbench davinci/Runtime davinci/maqetta/AppStates davinci/review/Review davinci/workbench/ViewPart davinci/review/widgets/Comment davinci/review/widgets/CommentForm dijit/form/Button dijit/form/TextBox dijit/form/DropDownButton dijit/Toolbar dijit/ToolbarSeparator dijit/CheckedMenuItem dijit/MenuSeparator dijit/Dialog dijit/Menu dojo/fx dojo/i18n!./nls/view dojo/i18n!davinci/workbench/nls/workbench".split(" "),function(p,q,f,r,
s,t,l,u,g,v,w,x,y,m,z,A,B,C,h,D){var k=r.prototype,n=function(){for(var a="",c=1;32>=c;c++){var b=Math.floor(16*Math.random()).toString(16),a=a+b;if(8==c||12==c||16==c||20==c)a+="-"}return a};return p("davinci.review.view.CommentView",t,{interval:33554432,id:0,postCreate:function(){this.inherited(arguments);this._cached={};this._cached.indices={};this.comments=[];this.commentIndices={root:this};this._commentConns=[];this.container=new dijit.layout.ContentPane;this.commentReplies=this.container.domNode;
dojo.attr(this.commentReplies,"tabindex","0");this.setContent(this.container);this.attachToolbar();this._initCommentForm();this.connect(this.commentReplies,"keydown",function(a){var c=this,b=function(a){c.commentIsActive(a)?a.enable():a.disable();a=a.getReplies();0<a.length&&dojo.forEach(a,b)};this._currentPage&&(a.keyCode==dojo.keys.CTRL||a.keyCode==dojo.keys.META)&&0<this._cached[this._currentPage].focusedComments.length&&dojo.forEach(this.comments,b)});this.connect(this.commentReplies,"keyup",
function(a){if(a.keyCode==dojo.keys.CTRL||a.keyCode==dojo.keys.META){var c=function(a){a.enable();a=a.getReplies();0<a.length&&dojo.forEach(a,c)};dojo.forEach(this.comments,c)}});this.connect(this.commentReplies,"click",function(a){a.target===this.commentReplies&&this._blurAllComments()});dojo.subscribe("/davinci/review/view/canvasFocused",this,function(){this._blurAllComments()});dojo.subscribe("/davinci/review/resourceChanged",this,function(a,c,b){!("open"!=c&&"closed"!=c)&&this._currentPage&&(this._currentPage.split("/")[2]==
b.timeStamp&&(this._versionClosed="closed"==c),dijit.byId("davinciReviewToolbar.Add").set("disabled",this._versionClosed),dijit.byId("davinciReviewToolbar.Reviewers").set("disabled",!1),dojo.publish(this._currentPage+"/davinci/review/drawing/addShape",["[]",!0]),this._destroyCommentWidgets(),this._render(),this._cached[this._currentPage].viewScene||this._getCurrentScene(),this._cached[this._currentPage].viewSceneList||this._context.getCurrentScenes(),dojo.publish(this._currentPage+"/davinci/review/drawing/filter",
[{},[]]))});dojo.subscribe("/davinci/review/context/loaded",this,function(a,c){a._commentView=this;this._context=a;var b=dojo.window.get(a.containerNode.ownerDocument);this._loadCommentData(a.resourceFile.parent.designerId,c);q.getOpenEditor()===a.containerEditor&&(this._currentPage=c,this._cached[this._currentPage].context=a,this._destroyCommentWidgets(),setTimeout(function(){this._render();this._updateToolbar({editor:a});this._reviewFilterChanged();this._context.getCurrentStates();this._getCurrentScene();
this._context.getCurrentScenes();dojo.publish(this._currentPage+"/davinci/review/drawing/filter",[{},[]])}.bind(this),100));b&&b.require&&b.require("dojo/_base/connect").subscribe("/maqetta/appstates/state/changed",this,function(a){f.currentEditor&&"davinci.review.CommentReviewEditor"==f.currentEditor.editorID&&(this._cached&&this._currentPage&&this._cached[this._currentPage])&&(this._cached[this._currentPage].pageState=a.newState||"Normal",this._cached[this._currentPage].pageStateList=this._context.getCurrentStates(),
this._cached[this._currentPage].viewScene=this._getCurrentScene().s,this._cached[this._currentPage].viewSceneList=this._context.getCurrentScenes(),dojo.publish(this._currentPage+"/davinci/review/drawing/filter",[{},[]]))});this.updateStatesScenes()});dojo.subscribe("/davinci/ui/editorSelected",this,function(a){var c=this._editor=a.editor;if(a.oldEditor&&a.oldEditor.basePath)if(this._commentForm.isShowing){var b={commentId:this._commentForm.commentId,replyTo:this._commentForm.replyTo,subject:this._commentForm.subject.get("value"),
content:this._commentForm.content.get("value").replace(/\n/g,"\x3cbr/\x3e"),editFrom:this._commentForm.editFrom};this._setPendingEditComment(a.oldEditor,b)}else this._setPendingEditComment(a.oldEditor,null);if(c&&c.basePath&&(this._currentPage=c.basePath.path,this._commentForm.hide(),this._destroyCommentWidgets(),this._updateToolbar(a),this._render(),(a=this._cached[this._currentPage]&&this._cached[this._currentPage].focusedComments)&&dojo.forEach(a,dojo.hitch(this,function(a){this.commentIndices[a].focusComment({ctrlKey:!0,
metaKey:!0,silent:!0})})),this._cached[this._currentPage]&&this._cached[this._currentPage].editComment)){a=this._commentForm;b=this._cached[this._currentPage].editComment;a.reset();a.commentId=b.commentId;a.subject.set("value",b.subject);a.content.set("value",b.content.replace(/<br\/>/g,"\n"));b.content&&a.hidePlaceHolder();var d;if("root"!==b.replyTo){a.setReplyMode();a.replyTo=b.replyTo;d=this.commentIndices[b.replyTo];a.moveTo(d.tempForm);for(var e=d;e&&e.expand;)e.expand(),e=this.commentIndices[e.replyTo];
dojo.window.scrollIntoView(d.domNode)}b.editFrom&&(a.setEditMode(),d=this.commentIndices[b.editFrom],d.hide(),a.moveTo(d.tempForm),dojo.window.scrollIntoView(d.domNode));a.show()}!c||"davinci.review.CommentReviewEditor"!=c.editorID?(this._resetCommentView(),this._currentPage=null):this._versionClosed=c.resourceFile.parent.closed});dojo.subscribe("/davinci/review/drawing/annotationSelected",this,function(a,c){var b=this.commentIndices[a],d=this._cached[this._currentPage].focusedComments;if(b&&!b.isFocused||
1<d.length){for(d=this.commentIndices[b.replyTo];d&&d.expand;)d.expand(),d=this.commentIndices[d.replyTo];dojo.window.scrollIntoView(b.domNode);b.focusComment();this._flash(b.getBody())}else b&&b.blurComment()});dojo.subscribe("/davinci/review/commentAddedError",this,this._onErrorCreateNewComment)},_getCurrentScene:function(){var a=this._context.sceneManagers,c,b;for(b in a){var d=a[b];if(d.getCurrentScene&&(c=d.getCurrentScene()))break}return{sm:d,s:c}},_setPendingEditComment:function(a,c){var b=
null;"string"===typeof a?b=a:a.basePath&&a.basePath.path&&(b=a.basePath.path);if(b&&(b=this._cached[b]))b.editComment=c},_resetCommentView:function(){dijit.byId("davinciReviewToolbar.Add").set("disabled",!0);dijit.byId("davinciReviewToolbar.Reviewers").set("disabled",!0);this._commentForm.hide();this._destroyCommentWidgets()},_initCommentForm:function(){var a=this._commentForm=new u({onSubmit:dojo.hitch(this,"_onCreateNewComment"),onUpdate:dojo.hitch(this,"_onUpdateComment"),onShow:dojo.hitch(this,
"_onCommentFormShown")});this.connect(a.cancelNode,"click","_onCommentFormCancel");a.moveTo(this.container.domNode);a.hide()},_onCommentFormShown:function(){},_onErrorCreateNewComment:function(a){for(var c=this._cached[this._currentPage],b,d=0;d<c.length;d++)c[d]&&c[d].id==a.commentId&&(b=d),c[d]._hasPopulate=!1;b&&c.splice(b,1);delete this._cached.indices[a.commentId];this._destroyCommentWidgets();dojo.publish(this._currentPage+"/davinci/review/drawing/addShape",["[]",!0]);this._render()},_onCreateNewComment:function(a){var c=
this._commentForm,b=this._cached[this._currentPage]||[];dojo.publish(this._currentPage+"/davinci/review/drawing/getShapesInEditing",[this,{state:this._cached[this._currentPage].pageState,stateList:this._cached[this._currentPage].pageStateList,scene:this._cached[this._currentPage].viewScene||this._getCurrentScene().s,sceneList:this._cached[this._currentPage].viewSceneList||this._context.getCurrentScenes()}]);a=new l({commentId:c.commentId,subject:a.subject,content:a.content,designerId:this._getDesignerId(),
pageName:this._currentPage,pageState:this._cached[this._currentPage].pageState,pageStateList:this._cached[this._currentPage].pageStateList,viewScene:this._cached[this._currentPage].viewScene||this._getCurrentScene().s,viewSceneList:this._cached[this._currentPage].viewSceneList||this._context.getCurrentScenes(),ownerId:f.userName,email:f.userEmail,displayName:f.getUserDisplayName(),replyTo:c.replyTo,drawingJson:this.drawingJson});this._commentConns.push(dojo.connect(a,"onNewReply",this,"_onNewReply"),
dojo.connect(a,"onEditComment",this,"_onEditComment"),dojo.connect(a,"onCommentFocus",this,"_onCommentFocus"),dojo.connect(a,"onCommentBlur",this,"_onCommentBlur"));this.commentIndices[a.commentId]=a;c.hide();c=this.commentIndices[a.replyTo];c.appendReply(a);c.expand&&c.expand();dojo.window.scrollIntoView(a.domNode);a.focusComment();this._flash(a.getBody());var d={id:a.commentId,subject:a.subject,content:a.content,pageName:a.pageName,pageState:a.pageState,pageStateList:a.pageStateList,viewScene:a.viewScene,
viewSceneList:a.viewSceneList,ownerId:a.ownerId,email:a.email,displayName:a.displayName,depth:a.depth,replyTo:a.replyTo,drawingJson:a.drawingJson};b.push(d);this._cached.indices[d.id]=d;a.getCreated().then(function(a){d.created=a})},_onUpdateComment:function(a){var c=this._commentForm,b=this.commentIndices[c.commentId];dojo.publish(this._currentPage+"/davinci/review/drawing/getShapesInEditing",[this,{state:this._cached[this._currentPage].pageState,stateList:this._cached[this._currentPage].pageStateList,
scene:this._cached[this._currentPage].viewScene||this._getCurrentScene().s,sceneList:this._cached[this._currentPage].viewSceneList||this._context.getCurrentScenes()}]);b.subject=a.subject;b.content=a.content;b.pageState=this._cached[this._currentPage].pageState;b.pageStateList=this._cached[this._currentPage].pageStateList;b.viewScene=this._cached[this._currentPage].viewScene||this._getCurrentScene().s;b.viewSceneList=this._cached[this._currentPage].viewSceneList||this._context.getCurrentScenes();
b.drawingJson=this.drawingJson;c.hide();b.update();b.show();this._flash(b.getBody());a=this._cached.indices[b.commentId];a.subject=b.subject;a.content=b.content;a.pageState=b.pageState;a.pageStateList=b.pageStateList;a.viewScene=b.viewScene;a.viewSceneList=b.viewSceneList;a.drawingJson=b.drawingJson},_loadCommentData:function(a,c){this._cached[c]=f.serverJSONRequest({url:"cmd/getComments",sync:!0,content:{ownerId:a,pageName:c}}).sort(function(a,b){return a.created>b.created?1:a.created<b.created?
-1:0});for(var b=0;b<this._cached[c].length;b++){var d=this._cached[c][b];d.pageStateList=d.hasOwnProperty("pageStateList")&&d.pageStateList?dojo.fromJson(d.pageStateList):[];d.viewSceneList=d.hasOwnProperty("viewSceneList")&&d.viewSceneList?dojo.fromJson(d.viewSceneList):[]}this._cached[c].pageState="Normal";this._cached[c].pageStateList=this._context.getCurrentStates();this._cached[c].viewSceneList=this._context.getCurrentScenes();this._cached[c].focusedComments=[]},_destroyCommentWidgets:function(){dojo.forEach(this.comments,
function(a){a.destroyRecursive()});this.comments=[];dojo.forEach(this._commentConns,dojo.disconnect);this._commentConns=[]},_render:function(){dojo.forEach(this._cached[this._currentPage],function(a,c){var b=new l({commentId:a.id,subject:a.subject,content:a.content,designerId:a.designerId,pageName:this._currentPage,pageState:a.pageState,pageStateList:a.pageStateList,viewScene:a.viewScene,viewSceneList:a.viewSceneList,ownerId:a.ownerId,email:a.email,displayName:a.displayName,created:a.created,parent:this,
existed:!0,replyTo:a.replyTo,drawingJson:a.drawingJson,closed:this._versionClosed});this._cached.indices[a.id]=a;this.commentIndices[b.commentId]=b;this.commentIndices[b.replyTo].appendReply(b);this._commentConns.push(dojo.connect(b,"onNewReply",this,"_onNewReply"),dojo.connect(b,"onEditComment",this,"_onEditComment"),dojo.connect(b,"onCommentFocus",this,"_onCommentFocus"),dojo.connect(b,"onCommentBlur",this,"_onCommentBlur"));0===c&&dojo.style(b.domNode,"borderTop","none");a._hasPopulate||(b.drawingJson=
b.drawingJson.replace(/\"colorAlias\":\"[\S+]\"/,'"colorAlias":"'+b.email+'"'),dojo.publish(this._currentPage+"/davinci/review/drawing/addShape",[b.drawingJson]),a._hasPopulate=!0)},this);dojo.forEach(this.comments,function(a){a.collapse(!0)})},_onEditComment:function(a){var c=this._commentForm,b=this.commentIndices[a.commentId];b.ownerId==f.userName&&(c.isShowing&&this._onCommentFormCancel(),c.reset(),c.commentId=a.commentId,c.subject.set("value",b.subject),c.content.set("value",b.content.replace(/<br\/>/g,
"\n")),b.content&&c.hidePlaceHolder(),c.setEditMode(),b.isReply()&&c.setReplyMode(),c.replyTo=b.replyTo,b.hide(),c.moveTo(b.tempForm),c.editFrom=a.commentId,c.show(),dojo.publish(this._currentPage+"/davinci/review/drawing/enableEditing",[f.userEmail,c.commentId,{pageState:b.pageState,pageStateList:b.pageStateList,viewScene:b.viewScene,viewSceneList:b.viewSceneList}]))},_onNewReply:function(a){var c=this._commentForm;c.isShowing&&this._onCommentFormCancel();c.reset();c.commentId=n();c.setReplyMode();
c.replyTo=a.replyTo;c.subject.set("value",a.subject);c.moveTo(this.commentIndices[a.replyTo].tempForm);c.show();dojo.publish(this._currentPage+"/davinci/review/drawing/enableEditing",[f.userEmail,c.commentId,{pageState:this._cached[this._currentPage].pageState,pageStateList:this._cached[this._currentPage].pageStateList,viewScene:this._cached[this._currentPage].viewScene,viewSceneList:this._cached[this._currentPage].viewSceneList}])},_onCommentFocus:function(a,c){var b=this._cached[this._currentPage].focusedComments;
if(!c||!c.ctrlKey&&!c.metaKey){dojo.forEach(b,function(a){this.commentIndices[a].blurComment(!0)},this);b.length=0;b.push(a.commentId);var d=this.commentIndices[a.commentId];d.setStatesScenes()}else if((c.ctrlKey||c.metaKey)&&!dojo.some(b,function(b){return b==a.commentId}))b.push(a.commentId),d=this.commentIndices[a.commentId],d.setStatesScenes();if(!c||!c.silent)this._editor&&(d=(d=this._editor.getContext())&&d.rootNode&&d.rootNode.ownerDocument&&d.rootNode.ownerDocument.defaultView&&d.rootNode.ownerDocument.defaultView.davinci&&
d.rootNode.ownerDocument.defaultView.davinci.states)&&d.setState(a.pageState),(d=this._getCurrentScene())&&(d.sm&&d.sm.selectScene&&a.viewScene)&&d.sm.selectScene({sceneId:a.viewScene}),this.publish(this._currentPage+"/davinci/review/drawing/filter",[{},b])},_onCommentBlur:function(a){for(var c=this._cached[this._currentPage].focusedComments,b=0;b<c.length;b++)c[b]==a.commentId&&(b==c.length-1?c.pop():c[b]=c.pop());a=this._cached[this._currentPage].viewScene||this._getCurrentScene().s;this.publish(this._currentPage+
"/davinci/review/drawing/filter",[{},c]);this.publish(this._currentPage+"/davinci/review/drawing/filter",[{pageState:this._cached[this._currentPage].pageState,viewScene:a},c])},_onCommentFormCancel:function(){dojo.publish(this._currentPage+"/davinci/review/drawing/cancelEditing",[]);var a=this._cached[this._currentPage].focusedComments;0<a.length&&this.commentIndices[a[0]].show();dojo.publish(this._currentPage+"/davinci/review/drawing/filter",[{},a])},_updateToolbar:function(a){dijit.byId("davinciReviewToolbar.Add").set("disabled",
this._versionClosed);dijit.byId("davinciReviewToolbar.Reviewers").set("disabled",!1);if((a=a.editor)&&a.resourceFile){var c=a.resourceFile.parent,b=c.reviewers;dojo.forEach(this._cached[this._currentPage],function(a){!dojo.some(b,function(b){return b.email==a.email})&&f.userName!=c.name&&b.push({name:a.ownerId,email:a.email})});a=this.reviewerList.getChildren();for(var d=2;d<a.length;d++)a[d].destroy();f.reviewers=b;dojo.forEach(b,dojo.hitch(this,function(a,b){if(a.email){var c=f.getUserDisplayName({email:a.email,
userId:a.name,userDisplayName:a.displayName}),c=new m({label:"\x3cdiv class\x3d'davinciReviewToolbarReviewersColor' style\x3d'background-color:"+s.getColor(a.email)+";'\x3e\x3c/div\x3e\x3cspan\x3e"+c+"\x3c/span\x3e",onChange:dojo.hitch(this,function(){this._reviewFilterChanged();this._reviewersBtn.openDropDown()}),checked:!0,reviewer:a,title:a.email});this.reviewerList.addChild(c);if(this._cached[this._currentPage]&&this._cached[this._currentPage].shownColors){var d=dojo.some(this._cached[this._currentPage].shownColors,
function(b){return b==a.email?!0:!1});c.set("checked",d)}}}));this._reviewFilterChanged()}},getTopAdditions:function(){this.category="content";var a=new v({id:"filterText",placeHolder:h.filter});dojo.connect(a.domNode,"onkeyup",this,function(a){this._filter();dojo.stopEvent(a)});var c=new x({id:"davinciReviewToolbar"},dojo.create("div")),b=new g({id:c.get("id")+".Add",showLabel:!1,disabled:!0,iconClass:"davinciReviewToolbarAdd",title:h.addComment,onClick:dojo.hitch(this,"_showCommentForm")}),d=new B({});
d.addChild(new m({label:h.allReviewers,checked:!0,onChange:dojo.hitch(this,function(a){for(var b=d.getChildren(),c=2;c<b.length;c++)b[c].set("checked",a);this._reviewFilterChanged();this._reviewersBtn.openDropDown()})}));d.addChild(new z);var e=this._reviewersBtn=new w({id:c.get("id")+".Reviewers",showLabel:!1,disabled:!0,iconClass:"davinciReviewToolbarReviewers",title:h.showReviewer,dropDown:d});this.reviewerList=d;c.addChild(b);c.addChild(new y);c.addChild(e);dojo.place(dojo.create("br"),c.domNode);
c.addChild(a);return c.domNode},_reviewFilterChanged:function(){for(var a=[],c=this.reviewerList.getChildren(),b=2;b<c.length;b++)c[b].checked&&a.push(c[b].reviewer.email);c[0].set("checked",a.length==c.length-2);this._cached[this._currentPage]&&(this._cached[this._currentPage].shownColors=a);dojo.publish(this._currentPage+"/davinci/review/drawing/setShownColorAliases",[a])},_createEditButton:function(){this.editButton?this.editButton.domNode.style.display="block":(this.editButton=new g({label:"",
iconClass:"editButtonIcon",disabled:!0,onClick:dojo.hitch(this,"")}),this.container.domNode.appendChild(this.editButton.domNode))},_createViewSwitch:function(){this.switchWrapper=dojo.create("div",{style:{"float":"right"}});var a=new g({label:null,iconClass:"collapseViewActive",onClick:dojo.hitch(this,"collapseAll")}),c=new g({label:null,iconClass:"expandViewActive",onClick:dojo.hitch(this,"expandAll")});this.switchWrapper.appendChild(a.domNode);this.switchWrapper.appendChild(c.domNode);this.container.domNode.appendChild(this.switchWrapper)},
_showCommentForm:function(){var a=this._commentForm;a.isShowing&&this._onCommentFormCancel();a.reset();a.commentId=n();a.show();dojo.publish(this._currentPage+"/davinci/review/drawing/enableEditing",[f.userEmail,a.commentId,{pageState:this._cached[this._currentPage].pageState,pageStateList:this._cached[this._currentPage].pageStateList,viewScene:this._cached[this._currentPage].viewScene,viewSceneList:this._cached[this._currentPage].viewSceneList}])},_filter:function(){var a=dijit.byId("filterText").get("displayedValue");
dojo.query(".davinciComment",this.container.domNode).removeClass("davinciReviewHide davinciReviewShow").forEach(function(c){var b=dijit.getEnclosingWidget(c),d=!0;if(d=0<=b.subjectNode.innerHTML.toLowerCase().indexOf(a.toLowerCase())||0<=b.contentNode.innerHTML.toLowerCase().indexOf(a.toLowerCase())||b.ownerName&&0<=b.ownerName.innerHTML.toLowerCase().indexOf(a.toLowerCase()))for(dojo.addClass(c,"davinciReviewShow");"root"!==b.replyTo;)b=this.commentIndices[b.replyTo],dojo.addClass(b.domNode,"davinciReviewShow"),
dojo.removeClass(b.domNode,"davinciReviewHide");else dojo.addClass(c,"davinciReviewHide")},this)},expandAll:function(){dojo.query(".repliesCount",this.container.domNode).removeClass("davinciReviewShow").addClass("davinciReviewHide");dojo.query(".currentScope",this.container.domNode).addClass("davinciReviewShow").removeClass("davinciReviewHide")},isPageOwner:function(){return this._getDesignerId()==f.userName},_getDesignerId:function(){var a=null,c=this._cached[this._currentPage].context;c&&(a=c.resourceFile.parent.designerId);
return a},popupWarning:function(a){var c=dijit.byId("warningDialog");c||(c=new A({id:"warningDialog",title:"",style:"width: 300px"},dojo.create("p",{innerHTML:a})));c.show()},getReplies:function(){return this.comments},appendReply:function(a){this.comments.push(a);1==this.comments.length&&dojo.style(a.domNode,"borderTop","none");a.placeAt(this.container.domNode)},_blurAllComments:function(){var a=this._cached[this._currentPage].focusedComments,c=[];a&&(dojo.forEach(a,function(a){(a=this.commentIndices[a])&&
c.push(a)},this),dojo.forEach(c,function(a){a.blurComment()},this))},_flash:function(a){a&&(this._originalBkColor||(this._originalBkColor=dojo.style(a,"backgroundColor")),C.chain([dojo.animateProperty({node:a,duration:250,properties:{backgroundColor:{start:this._originalBkColor,end:"#fef7d9"}}}),dojo.animateProperty({node:a,duration:250,properties:{backgroundColor:{start:"#fef7d9",end:this._originalBkColor}}})]).play())},updateStatesScenes:function(){var a=k.getFocus(this._context.rootNode);this._cached[this._currentPage].pageState=
a?a.state:void 0;this._cached[this._currentPage].pageStateList=this._context.getCurrentStates();this._cached[this._currentPage].viewScene=this._getCurrentScene().s;this._cached[this._currentPage].viewSceneList=this._context.getCurrentScenes();dojo.publish(this._currentPage+"/davinci/review/drawing/filter",[{},this._cached[this._currentPage].focusedComments])},commentIsActive:function(a){var c=this._cached[this._currentPage];this._context.getDocument();var b,d,e;for(b=0;b<c.pageStateList.length;b++){d=
c.pageStateList[b];var f=!d.state?k.NORMAL:d.state;e=a.pageStateList[b];var g=!e.state?k.NORMAL:e.state;if(d&&e&&(e.id&&e.id===d.id||e.xpath&&e.xpath===d.xpath)&&g!==f)return!1}for(var h in c.viewSceneList)if(f=c.viewSceneList[h],g=a.viewSceneList[h],f&&g)for(b=0;b<f.length;b++)if(d=f[b],e=g[b],d&&e&&(e.scId&&e.scId===d.scId||e.scXpath&&e.scXpath===d.scXpath)&&(e.sceneId&&e.sceneId!==d.sceneId||e.sceneXpath&&e.sceneXpath!==d.sceneXpath))return!1;return!0}})});
//# sourceMappingURL=CommentView.js.map