//>>built
require({cache:{"url:davinci/ui/widgets/templates/NewHTMLFileOptions.html":'\x3cdiv class\x3d"nhfo_outer2" dojoAttachPoint\x3d"nhfo_outer2"\x3e\t\t\x3c!--  nhfo \x3d NewHTMLFileOptions --\x3e\n\t\x3cdiv class\x3d"nhfo_outer1"\x3e\n\t\t\x3cdiv class\x3d"nhfo_details"\x3e\n\t\t\t\x3ctable\x3e\n\t\t\t\t\x3ctr class\x3d"nhfo_dv" dojoAttachPoint\x3d"deviceLabel"\x3e\t\x3c!--  dv \x3d Device --\x3e\n\t\t\t\t\t\x3ctd class\x3d\'nhfo_label\'\x3e\n\t\t\t\t\t\t\x3clabel dojoAttachPoint\x3d"deviceLabel"\x3e\x3c/label\x3e\n\t\t\t\t\t\t\x3cselect dojoType\x3d"dijit.form.Select" dojoAttachPoint\x3d"deviceSelect"\x3e\n\t\t\t\t\t\t\t\x3c!--  values added dynamically --\x3e\n\t\t\t\t\t\t\x3c/select\x3e\n\t\t\t\t\t\x3c/td\x3e\n\t\t\t\t\x3c/tr\x3e\n\t\t\t\x3c/table\x3e\n\t\t\x3c/div\x3e\n\t\x3c/div\x3e\n\x3c/div\x3e\n'}});
define("davinci/ui/widgets/NewHTMLFileOptions","dojo/_base/declare dijit/_Templated dijit/_Widget davinci/library system/resource davinci/workbench/Preferences davinci/Runtime davinci/Workbench dijit/Menu dijit/MenuItem davinci/model/Path dijit/Tooltip dijit/form/DropDownButton dojo/i18n!davinci/ui/nls/ui dojo/i18n!dijit/nls/common dojo/text!./templates/NewHTMLFileOptions.html dijit/form/Button davinci/ui/widgets/ThemeSetSelection davinci/Theme dijit/form/TextBox dijit/form/RadioButton".split(" "),
function(n,p,q,x,y,z,r,l,A,B,C,s,D,t,E,u,v,w,k){return n("davinci.ui.widgets.NewHTMLFileOptions",[q,p],{widgetsInTemplate:!0,templateString:u,device:null,themeSet:null,dialogSpecificClassOptions:null,standardDevices:[{type:"mobile",value:"android_340x480",device:"android_340x480",layout:"flow"},{type:"mobile",value:"android_480x800",device:"android_480x800",layout:"flow"},{type:"mobile",value:"androidtablet",device:"androidtablet",layout:"flow"},{type:"mobile",value:"blackberry",device:"blackberry",
layout:"flow"},{type:"mobile",value:"ipad",device:"ipad",layout:"flow"},{type:"mobile",value:"iphone",device:"iphone",layout:"flow"}],postCreate:function(){function b(){m.ctTooltip&&m.ctTooltip.close&&m.ctTooltip.close()}this.inherited(arguments);var c=this.dialogSpecificClassOptions,a=c?c.showDevices:!1,c=c?c.showThemeSetsButton:!1,e=this.langObj=t;this.deviceLabel.innerHTML=e.nhfoDevice;a||(this.nhfo_outer2.style.display="none");var d;if(a=l.workbenchStateCustomPropGet("nhfo"))d=l.getActiveProject(),
d=a[d];a=r.getDefaultThemeSet();if((this._selectedThemeSet=d?d.themeSet:a)&&this._selectedThemeSet.name!=k.none_themeset_name){a=this._selectedThemeSet.name;this._selectedThemeSet=dojo.clone(k.none_themeset);var f=k.getThemeSets(l.getProject());if(f)for(var g=0;g<f.themeSets.length;g++)if(f.themeSets[g].name===a){this._selectedThemeSet=dojo.clone(f.themeSets[g]);break}}_updateWithLastDialogValue=function(a,b,c,e){for(var d=0;d<b.length;d++)if(b[d].value==c)return a.attr("value",c),!0;a.attr("value",
e);return!1};a=[];for(f=0;f<this.standardDevices.length;f++){var h=this.standardDevices[f];"separator"==h.type?a.push({type:h.type}):("mobile"==h.type?h=g=h.value:(g=h.value,h=e["nhfoDVMenu_"+g]),a.push({value:g,label:h}))}this.deviceSelect.addOption(a);var m=this;this.connect(this.deviceSelect,"onFocus",dojo.hitch(this,function(){b()}));this.connect(this.deviceSelect.dropDown,"onOpen",dojo.hitch(this,function(){b()}));this.connect(this.deviceSelect.dropDown,"onClose",dojo.hitch(this,function(){b()}));
_updateWithLastDialogValue(this.deviceSelect,a,d?d.device:void 0,"iphone");this.connect(this.deviceSelect,"onChange",dojo.hitch(this,function(){this._update_comp_type()}));this._update_comp_type();c&&(c=document.createElement("input"),this.dialogSpecificButtonsSpan.appendChild(c),this.themeButton=new v({label:this.langObj.nhfoThemeButtonLabel,title:this.langObj.nhfoThemeButtonTitle},c),this.connect(this.themeButton,"onClick",dojo.hitch(this,function(a){this._themeSelectionDialog=new w({newFile:!0});
this._themeSelectionDialog.buildRendering();this.connect(this._themeSelectionDialog,"onOk",dojo.hitch(this,function(a){this._selectedThemeSet=this._themeSelectionDialog._selectedThemeSet;this._updateThemesAndThemeSets()}))})))},startup:function(){var b=this.deviceLabel,c=this.deviceSelect,a=0,e;do a++,e="device"+a;while(dojo.byId(e));b.id=e;this.ctTooltip=new s({connectId:[e,c.id],position:["below","below"],label:this.langObj.nhfoDeviceTooltip})},_update_comp_type:function(){"desktop"==this._currentDeviceObject("_update_comp_type").device&&
(delete this._selectedTheme,delete this._selectedThemeSet)},getOptions:function(){var b=this._currentDeviceObject("getOptions");return{device:b.value,device:b.device,layout:b.layout,theme:this._selectedTheme?this._selectedTheme:b.theme,themeSet:this._selectedThemeSet}},_updateThemesAndThemeSets:function(b){b=this._selectedThemeSet.name;if(b==k.none_themeset_name){var c=this._currentDeviceObject("_updateThemesAndThemeSets").device;if("desktop"==c)b=this._selectedThemeSet.desktopTheme;else for(var a=
0;a<this._selectedThemeSet.mobileTheme.length;a++)if(-1<c.toLowerCase().indexOf(this._selectedThemeSet.mobileTheme[a].device.toLowerCase())){b=this._selectedThemeSet.mobileTheme[a].theme;break}}this._selectedTheme=b},_currentDeviceObject:function(b){for(var c=this.deviceSelect.attr("value"),a=!1,e=0;e<this.standardDevices.length;e++){var d=this.standardDevices[e];if(d.value==c){a=!0;break}}a||(console.error("NewHTMLFileOptions. "+b+": invalid device\x3d"+c),d=this.standardDevices[0]);return d}})});
//# sourceMappingURL=NewHTMLFileOptions.js.map